unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Existing_Member__c.field-meta.xml
<CustomField>
    <fullName>Existing_Member__c</fullName>
    <label>Existing Member?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Send_Application_Confirmation_Email__c.field-meta.xml
<CustomField>
    <fullName>Send_Application_Confirmation_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Application Confirmation Email</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Cows_Housing__c/Cows_Housing__c.object-meta.xml
<CustomObject>
    <label>Cows Housing</label>
    <nameField>
        <displayFormat>CH-{0000}</displayFormat>
        <label>Cows Housing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cows Housings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Cows_Housing__c/fields/WOADairy__c.field-meta.xml
<CustomField>
    <fullName>WOADairy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WOADairy</label>
    <referenceTo>WOADairy__c</referenceTo>
    <relationshipLabel>Cows Housings</relationshipLabel>
    <relationshipName>Cows_Housings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Cows_Housing__c/recordTypes/Dry.recordType-meta.xml
<RecordType>
    <fullName>Dry</fullName>
    <active>true</active>
    <label>Dry</label>
</RecordType>

unpackaged/main/default/objects/Lameness_Prevalence__c/Lameness_Prevalence__c.object-meta.xml
<CustomObject>
    <label>Lameness Prevalence</label>
    <nameField>
        <displayFormat>LP-{0000}</displayFormat>
        <label>Lameness prevalence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lameness Prevalences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Lameness_Prevalence__c/fields/WOADairy__c.field-meta.xml
<CustomField>
    <fullName>WOADairy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WOADairy</label>
    <referenceTo>WOADairy__c</referenceTo>
    <relationshipLabel>Lameness Prevalences</relationshipLabel>
    <relationshipName>Lameness_Prevalences</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Mobility_Scoring__c/Mobility_Scoring__c.object-meta.xml
<CustomObject>
    <label>Mobility Scoring</label>
    <nameField>
        <displayFormat>MS-{0000}</displayFormat>
        <label>Mobility Scoring Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mobility Scorings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Mobility_Scoring__c/fields/WOADairy__c.field-meta.xml
<CustomField>
    <fullName>WOADairy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WOADairy</label>
    <referenceTo>WOADairy__c</referenceTo>
    <relationshipLabel>Mobility Scorings</relationshipLabel>
    <relationshipName>Mobility_Scorings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Standard_Price__c.field-meta.xml
<CustomField>
    <fullName>Standard_Price__c</fullName>
    <label>Standard Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/WOA__c/WOA__c.object-meta.xml
<CustomObject>
    <label>WOA</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>WOA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WOAs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/WOA__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>WOAs</relationshipLabel>
    <relationshipName>WOAs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/WOA__c/fields/Species_Type__c.field-meta.xml
<CustomField>
    <fullName>Species_Type__c</fullName>
    <label>Species Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dairy Cattle</fullName>
            </value>
            <value>
                <fullName>Laying Hen</fullName>
            </value>
            <value>
                <fullName>Pigs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WOADairy__c/WOADairy__c.object-meta.xml
<CustomObject>
    <label>WOADairy</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>WOADairyID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WOAs Dairy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/WOADairy__c/fields/WOA__c.field-meta.xml
<CustomField>
    <fullName>WOA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WOA</label>
    <referenceTo>WOA__c</referenceTo>
    <relationshipLabel>WOAs Dairy</relationshipLabel>
    <relationshipName>WOAs_Dairy</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/WOADairyControllerTest.cls
@isTest
public class WOADairyControllerTest {
@testSetup
    static void loadData(){
         FObject joinFee = new FObject('Product2', 1);
        joinFee.setDefinition('Name','static value(Joining Fee)');
        joinFee.setDefinition('ProductCode','static value(JOINFEE)');
        joinFee.setDefinition('IsActive','static value(true)');
        joinFee.setDefinition('Standard_Price__c','static value(28.80)');
        joinFee.insertRecords(true);
        // Create revisitFee product
        FObject revisitFee = new FObject('Product2', 1);
        revisitFee.setDefinition('Name','static value(Revisit)');
        revisitFee.setDefinition('ProductCode','static value(REVISIT)');
        revisitFee.setDefinition('IsActive','static value(true)');
        revisitFee.setDefinition('Standard_Price__c','static value(114.24)');
        revisitFee.insertRecords(true);

        // Create Application
        FObject application = DataFactory.getDefNewApplications();
        application.setDefinition('Existing_Member__c', 'static value(No)');
        application.insertRecords(true);

        // do assertions
        List<Account> insertedAccounts = FObject.getInsertedRecords('Account');
        List<Contact> insertedCon = FObject.getInsertedRecords('Contact');
        List<Application__c> insertedApp = FObject.getInsertedRecords('Application__c');
        
        Application__c app = insertedApp[0];
        app.Send_Application_Confirmation_Email__c = true;
        update app;
        List<WOA__c> woaList = new List<WOA__c>{
            new WOA__c(Application__c=app.Id,Species_Type__c='Dairy Cattle')
        };
        insert woaList;
        WOADairy__c woaDairy = new WOADairy__c(WOA__c = woaList[0].Id);
        insert woaDairy;
        Id RecordtypeId = Schema.SObjectType.Cows_Housing__c.getRecordTypeInfosByName().get('Dry').getRecordTypeId();

        List<Cows_Housing__c> cows = new List<Cows_Housing__c>{
            new Cows_Housing__c(WOADairy__c =woaDairy.Id,RecordTypeId=RecordtypeId ),
                new Cows_Housing__c(WOADairy__c =woaDairy.Id,RecordTypeId=RecordtypeId )
        };
            insert cows;
        List<Mobility_Scoring__c> mobilityScoring = new List<Mobility_Scoring__c>{
            new Mobility_Scoring__c(WOADairy__c =woaDairy.Id ),
                new Mobility_Scoring__c(WOADairy__c =woaDairy.Id )
        };
            insert mobilityScoring;
        List<Lameness_Prevalence__c> lamenessPrevalence = new List<Lameness_Prevalence__c>{
            new Lameness_Prevalence__c(WOADairy__c =woaDairy.Id ),
                new Lameness_Prevalence__c(WOADairy__c =woaDairy.Id )
        };
            insert lamenessPrevalence;
    }
    @isTest
    static void testMethod1(){
        WOADairy__c woaDairy = [SELECT Id,WOA__c FROM WOADairy__c LIMIT 1];
        WOADairyController.getWOADairy(woaDairy.WOA__c);
        String cowHousing = WOADairyController.getCowHousing(woaDairy.Id, 'Dry');
        String lamenessPrevalence = WOADairyController.getLamenessPrevalence(woaDairy.Id);
        STring mobilityScoring = WOADairyController.getMobilityScoring(woaDairy.Id);
        List<Cows_Housing__c> cowHousingList = (List<Cows_Housing__c>)JSON.deserialize(cowHousing, List<Cows_Housing__c>.class);
        system.Assert(cowHousingList.size() ==2);
        List<Mobility_Scoring__c> mobilityScoringList = (List<Mobility_Scoring__c>)JSON.deserialize(mobilityScoring, List<Mobility_Scoring__c>.class);
        system.Assert(mobilityScoringList.size() ==2);
        WOADairyController.saveWOADairy(woaDairy, cowHousing, new List<String>{cowHousingList[0].Id}, mobilityScoring, new List<String>{mobilityScoringList[0].Id}, lamenessPrevalence);
        cowHousingList = [SELECT ID FROM Cows_Housing__c WHERE WOADairy__c=:woaDairy.Id];
        system.Assert(cowHousingList.size() ==1);
        mobilityScoringList = [SELECT ID FROM Mobility_Scoring__c WHERE WOADairy__c=:woaDairy.Id];
        system.Assert(mobilityScoringList.size() ==1);
        
    }
}