unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Existing_Member__c.field-meta.xml
<CustomField>
    <fullName>Existing_Member__c</fullName>
    <label>Existing Member?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Send_Application_Confirmation_Email__c.field-meta.xml
<CustomField>
    <fullName>Send_Application_Confirmation_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Application Confirmation Email</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Standard_Price__c.field-meta.xml
<CustomField>
    <fullName>Standard_Price__c</fullName>
    <label>Standard Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/WOA__c/WOA__c.object-meta.xml
<CustomObject>
    <label>WOA</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>WOA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WOAs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/WOA__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>WOAs</relationshipLabel>
    <relationshipName>WOAs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/WOA__c/fields/IsCompleted__c.field-meta.xml
<CustomField>
    <fullName>IsCompleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Submitted</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/WOA__c/fields/Species_Type__c.field-meta.xml
<CustomField>
    <fullName>Species_Type__c</fullName>
    <label>Species Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dairy Cattle</fullName>
            </value>
            <value>
                <fullName>Laying Hen</fullName>
            </value>
            <value>
                <fullName>Pigs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/WOAEditControllerTest.cls
@isTest
public class WOAEditControllerTest {
@testSetup
    static void loadData(){
         FObject joinFee = new FObject('Product2', 1);
        joinFee.setDefinition('Name','static value(Joining Fee)');
        joinFee.setDefinition('ProductCode','static value(JOINFEE)');
        joinFee.setDefinition('IsActive','static value(true)');
        joinFee.setDefinition('Standard_Price__c','static value(28.80)');
        joinFee.insertRecords(true);
        // Create revisitFee product
        FObject revisitFee = new FObject('Product2', 1);
        revisitFee.setDefinition('Name','static value(Revisit)');
        revisitFee.setDefinition('ProductCode','static value(REVISIT)');
        revisitFee.setDefinition('IsActive','static value(true)');
        revisitFee.setDefinition('Standard_Price__c','static value(114.24)');
        revisitFee.insertRecords(true);

        // Create Application
        FObject application = DataFactory.getDefNewApplications();
        application.setDefinition('Existing_Member__c', 'static value(No)');
        application.insertRecords(true);

        // do assertions
        List<Account> insertedAccounts = FObject.getInsertedRecords('Account');
        List<Contact> insertedCon = FObject.getInsertedRecords('Contact');
        List<Application__c> insertedApp = FObject.getInsertedRecords('Application__c');
        
        Application__c app = insertedApp[0];
        app.Send_Application_Confirmation_Email__c = true;
        update app;
        List<WOA__c> woaList = new List<WOA__c>{
            new WOA__c(Application__c=app.Id,Species_Type__c='Dairy Cattle'),
            new WOA__c(Application__c=app.Id,Species_Type__c='Laying Hen'),
            new WOA__c(Application__c=app.Id,Species_Type__c='Pigs')
        };
        insert woaList;
    }
    @isTest
    static void testMethod1(){
        List<WOA__c> woaList = [SELECT Id,Application__c,Species_Type__c FROM WOA__c];
        WOAEditController.getAssessors();
        WOA__c woa = WOAEditController.getWOASummaryRecord(woaList[0].Id);
        system.Assert(woa.Name != null);
        woa.IsCompleted__c = true;
        WOAEditController.saveWOASummary(woa);
        woa = [SELECT Id,Application__c,IsCompleted__c FROM WOA__c WHERE Id=:woa.Id];
        system.Assert(woa.IsCompleted__c);
    }
}