unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Existing_Member__c.field-meta.xml
<CustomField>
    <fullName>Existing_Member__c</fullName>
    <label>Existing Member?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/asp04__Payment__c/asp04__Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PAY-{000000000}</displayFormat>
        <label>Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/asp04__Payment__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/asp04__Payment__c/fields/asp04__Amount__c.field-meta.xml
<CustomField>
    <fullName>asp04__Amount__c</fullName>
    <inlineHelpText>The monetary value of the payment</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/asp04__Payment__c/fields/asp04__Payment_Route_Selected__c.field-meta.xml
<CustomField>
    <fullName>asp04__Payment_Route_Selected__c</fullName>
    <inlineHelpText>The payment route that was selected by the customer when they made the payment.</inlineHelpText>
    <label>Payment Route Selected</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>asp04__Payment_Route_Options</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/asp04__Payment__c/fields/asp04__Payment_Stage__c.field-meta.xml
<CustomField>
    <fullName>asp04__Payment_Stage__c</fullName>
    <label>Payment Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting submission</fullName>
                <default>true</default>
                <label>Awaiting submission</label>
            </value>
            <value>
                <fullName>Submitted for collection</fullName>
            </value>
            <value>
                <fullName>Collected from customer</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/asp04__Payment_Route_Options.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Card</fullName>
    </customValue>
    <customValue>
        <fullName>Direct Debit</fullName>
    </customValue>
    <customValue>
        <fullName>eCheck</fullName>
    </customValue>
    <customValue>
        <fullName>PayPal</fullName>
    </customValue>
    <description>Valid payment routes</description>
    <masterLabel>Payment Route Options</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/PaymentTest.cls
@isTest
public class PaymentTest {
    @isTest
    public static void PaymentTest() {
        // Create Application
        FObject application = DataFactory.getDefNewApplications();
        application.setDefinition('Existing_Member__c', 'static value(No)');
        application.insertRecords(true);

        List<Account> insertedAccounts = FObject.getInsertedRecords('Account');
        List<Contact> insertedCon = FObject.getInsertedRecords('Contact');
        List<Application__c> insertedApp = FObject.getInsertedRecords('Application__c');
        System.debug('Acc Size => ' + insertedAccounts.size());
        System.debug('Con Size => ' + insertedCon.size());
        System.debug('App Size => ' + insertedApp.size());
        System.assert(insertedAccounts.size() == 2);
        System.assert(insertedCon.size() == 1);
        System.assert(insertedApp.size() == 1);

        asp04__Payment__c payment = new asp04__Payment__c();
        payment.Application__c = insertedApp[0].Id;
        payment.asp04__Amount__c = 1000;
        payment.asp04__Payment_Route_Selected__c = 'Card';
        payment.asp04__Payment_Stage__c = 'Awaiting submission';
        insert payment;
        payment.asp04__Payment_Stage__c = 'Collected from customer';
        update payment;
    }
}