unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Amount_Ex_VAT__c.field-meta.xml
<CustomField>
    <fullName>Amount_Ex_VAT__c</fullName>
    <label>Amount (excluding VAT)</label>
    <summarizedField>Application_Line_Item__c.Subtotal__c</summarizedField>
    <summaryForeignKey>Application_Line_Item__c.Application__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Total_Amount_Inc_VAT__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Inc_VAT__c</fullName>
    <formula>IF(
(Amount_Ex_VAT__c  +  VAT__c)- (FLOOR(Amount_Ex_VAT__c  +  VAT__c)) &gt;= 0.1,
(Amount_Ex_VAT__c  +  VAT__c),
FLOOR(Amount_Ex_VAT__c  +  VAT__c)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount Inc VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <formula>IF( Head_Office__r.BillingCountry = &#39;United Kingdom&#39;,
				Amount_Ex_VAT__c * 0.2,
			0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>If Head Office billing country is the United Kingdom, then the VAT is 20%. Otherwise, VAT is 0%.</inlineHelpText>
    <label>VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Application_Line_Item__c/Application_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Application Line Item</label>
    <nameField>
        <displayFormat>APL-{0000}</displayFormat>
        <label>Application Line Item Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application_Line_Item__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Application_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Application_Line_Item__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>List Price Ex Vat</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Application_Line_Item__c/fields/Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Subtotal__c</fullName>
    <formula>List_Price__c  *  Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subtotal</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/FindAppLineItems.cls
public class FindAppLineItems {
	public Id appId {get; set;}
    public Boolean hasInvoiceLine {get;set;}
    public List<Application_Line_Item__c> getLineItems(){
        List<Application_Line_Item__c> lineItems;
        if(appId != null){
            lineItems = [SELECT Id, Application__c, Product_Name__c, Subtotal__c, Quantity__c, Number_of_Animals__c, List_Price__c, Line_Description__c FROM Application_Line_Item__c WHERE Application__c =:appId];
            if(lineItems.size() != 0){
                hasInvoiceLine = true;
            }
        }
        return lineItems;
    }
    public decimal getNetAmount(){
        Application__c app = [SELECT Id, Amount_Ex_VAT__c FROM Application__c WHERE Id=:appId];
        return app.Amount_Ex_VAT__c;
        
    }
    public decimal getVatAmount(){
        Application__c app = [SELECT Id, VAT__c FROM Application__c WHERE Id=:appId];
        return app.VAT__c;
    }
    public decimal getTotalAmount(){
        Application__c app = [SELECT Id, Total_Amount_Inc_VAT__c FROM Application__c WHERE Id=:appId];
        return app.Total_Amount_Inc_VAT__c.setscale(2,RoundingMode.DOWN);
    }
    
}