unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Applicant_Contact__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Application_Type__c</fullName>
    <label>Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Existing_Member__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Revisit</fullName>
            </value>
            <value>
                <fullName>Levy</fullName>
            </value>
            <value>
                <fullName>Merchandise</fullName>
            </value>
            <value>
                <fullName>Promotion/Partnership</fullName>
            </value>
            <value>
                <fullName>Consultancy</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Bulk_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Renewal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bulk Renewal</label>
    <referenceTo>Bulk_Renewal__c</referenceTo>
    <relationshipLabel>Renewal Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Custom_Invoice_Message__c.field-meta.xml
<CustomField>
    <fullName>Custom_Invoice_Message__c</fullName>
    <label>Custom Invoice Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Head_Office__c.field-meta.xml
<CustomField>
    <fullName>Head_Office__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Head Office</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Head Office</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Pricebook_Id__c.field-meta.xml
<CustomField>
    <fullName>Pricebook_Id__c</fullName>
    <label>Pricebook Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Sage_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sage_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sage Invoice</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Send_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Send_Invoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Invoice</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>ApplicationSite</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Site_Name__c.field-meta.xml
<CustomField>
    <fullName>Site_Name__c</fullName>
    <formula>Site__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application_Line_Item__c/Application_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Application Line Item</label>
    <nameField>
        <displayFormat>APL-{0000}</displayFormat>
        <label>Application Line Item Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application_Line_Item__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Application_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Application_Line_Item__c/fields/Application_Unit__c.field-meta.xml
<CustomField>
    <fullName>Application_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application Unit</label>
    <referenceTo>Application_Unit__c</referenceTo>
    <relationshipLabel>Application Line Items</relationshipLabel>
    <relationshipName>Application_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application_Line_Item__c/fields/Item_Description__c.field-meta.xml
<CustomField>
    <fullName>Item_Description__c</fullName>
    <formula>Product__r.Description</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Item Description</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application_Line_Item__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>List Price Ex Vat</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Application_Line_Item__c/fields/List_Price_Inc_Vat__c.field-meta.xml
<CustomField>
    <fullName>List_Price_Inc_Vat__c</fullName>
    <label>List Price Inc Vat</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Application_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Application Line Items</relationshipLabel>
    <relationshipName>Application_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application_Line_Item__c/fields/Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Subtotal__c</fullName>
    <formula>List_Price__c  *  Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subtotal</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/Application_Unit__c.object-meta.xml
<CustomObject>
    <label>Application Unit</label>
    <nameField>
        <displayFormat>APUN-{00}</displayFormat>
        <label>APP Unit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application_Unit__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Application Units</relationshipLabel>
    <relationshipName>ApplicationUnits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/fields/Number_of_Animals__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Animals__c</fullName>
    <formula>Unit__r.Number_of_Animals__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Animals</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Bulk_Renewal__c/Bulk_Renewal__c.object-meta.xml
<CustomObject>
    <description>Object to record the renewal applications created from bulk renewing.</description>
    <label>Bulk Renewal</label>
    <nameField>
        <displayFormat>BR{000000}</displayFormat>
        <label>Bulk Renewal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bulk Renewals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bulk_Renewal__c/fields/Custom_Invoice_Message__c.field-meta.xml
<CustomField>
    <fullName>Custom_Invoice_Message__c</fullName>
    <label>Custom Invoice Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Bulk_Renewal__c/fields/Head_Office__c.field-meta.xml
<CustomField>
    <fullName>Head_Office__c</fullName>
    <label>Head Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bulk Renewals</relationshipLabel>
    <relationshipName>Bulk_Renewals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Bulk_Renewal__c/fields/Sage_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sage_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sage Invoice</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bulk Renewals</relationshipLabel>
    <relationshipName>Bulk_Renewals</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Roles__c.field-meta.xml
<CustomField>
    <fullName>Roles__c</fullName>
    <label>Roles</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administration Contact</fullName>
            </value>
            <value>
                <fullName>Agricultural/Technical Contact</fullName>
            </value>
            <value>
                <fullName>Artwork Contact</fullName>
            </value>
            <value>
                <fullName>Assessments Contact</fullName>
            </value>
            <value>
                <fullName>Certification Contact</fullName>
            </value>
            <value>
                <fullName>Compliance Contact</fullName>
            </value>
            <value>
                <fullName>Membership Fee Contact</fullName>
            </value>
            <value>
                <fullName>Licence Fee Contact</fullName>
            </value>
            <value>
                <fullName>Traceability Contact</fullName>
            </value>
            <value>
                <fullName>Payments Contact</fullName>
            </value>
            <value>
                <fullName>Partnerships Commercial Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Invoices &amp; Credit Notes</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Bulk_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Renewal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bulk Renewal</label>
    <referenceTo>Bulk_Renewal__c</referenceTo>
    <relationshipLabel>Sage Invoices</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beef</fullName>
            </value>
            <value>
                <fullName>Chicken</fullName>
            </value>
            <value>
                <fullName>Dairy</fullName>
            </value>
            <value>
                <fullName>Eggs</fullName>
            </value>
            <value>
                <fullName>Lamb</fullName>
            </value>
            <value>
                <fullName>Pork</fullName>
            </value>
            <value>
                <fullName>Salmon</fullName>
            </value>
            <value>
                <fullName>Salmon &amp; Trout</fullName>
            </value>
            <value>
                <fullName>Trout</fullName>
            </value>
            <value>
                <fullName>Turkey</fullName>
            </value>
            <value>
                <fullName>Veal</fullName>
            </value>
            <value>
                <fullName>Value Added</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The site this line item applies to.</description>
    <inlineHelpText>The site this line item applies to.</inlineHelpText>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/SendInvoiceController.cls
public with sharing class SendInvoiceController {
    //public class InvoiceException extends Exception {}
    @AuraEnabled
    public static string getContacts(String recordId){
        try {
            Application__c application = [
                SELECT Id,Head_Office__c FROM Application__c WHERE Id=:recordId
            ];
            List<Contact> contacts = [
                SELECT Id,Name,Email From Contact WHERE AccountId=:application.Head_Office__c AND Roles__c includes ('Invoice Contact')
            ];
            return JSON.serialize(contacts);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static string updateApplication(String recordId,String message){
        try {
            Application__c application = [
                SELECT Id,Name,Payment_Due_Date__c,Invoice_Date__c,Bulk_Renewal__c ,CreatedDate,Site__c,
                Site_Name__c,Application_Type__c,Head_Office__c,Pricebook_Id__c,Applicant_Contact__c,
                Sage_Invoice__c
                FROM Application__c WHERE Id=:recordId
            ];
            application.Send_Invoice__c = true ;
            application.Custom_Invoice_Message__c = message;
            application.Invoice_Date__c = system.today();
            if(application.Payment_Due_Date__c == null){
                application.Payment_Due_Date__c = system.today().addDays(14);
            }
            //update application;
            List<Application_Line_Item__c> lineItemsForApplications = [
                SELECT Id, Product__c, Product__r.Name, Application__c, Application_Unit__c, 
                Item_Description__c, List_Price__c, List_Price_Inc_Vat__c, Quantity__c,
                 Subtotal__c, Number_of_Animals__c, Line_Description__c 
                 FROM   Application_Line_Item__c WHERE Application__c =:recordId
            ];            
            //application.Payment_Due_Date__c != null && application.Invoice_Date__c != null && 
            if(application.Bulk_Renewal__c == null){ 
                if(application.Sage_Invoice__c == null){
                    Id orderEntryRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('OrderEntry').getRecordTypeId();
                    String appCreatedDate = application.CreatedDate.format('dd/MM/yyyy');
                    Opportunity invoiceOpp = new Opportunity();
                    invoiceOpp.Name = application.Site_Name__c + ' ' + application.Application_Type__c + ' ' + appCreatedDate;
                    invoiceOpp.CloseDate = Date.today();
                    invoiceOpp.AccountId = application.Head_Office__c;
                    invoiceOpp.StageName = 'Prospecting';
                    invoiceOpp.Pricebook2Id = application.Pricebook_Id__c;
                    invoiceOpp.Application__c = application.Id;
                    invoiceOpp.ia_crm__Intacct_Transaction__c = 'Sales Invoice';
                    invoiceOpp.RecordTypeId = orderEntryRecordTypeId;
                    invoiceOpp.Intacct_Application__c = application.Name;
                    if(application.Applicant_Contact__c != null){
                        invoiceOpp.ia_crm__Bill_to__c = application.Applicant_Contact__c;
                    }
                    
                    insert invoiceOpp;
                    application.Sage_Invoice__c = invoiceOpp.Id;
                    TriggerHandler.bypass('ApplicationTriggerHandler');
                    update application;
                    TriggerHandler.clearBypass('ApplicationTriggerHandler');
                    List<OpportunityLineItem> oppProdToInsert = new List<OpportunityLineItem>();
                    for(Application_Line_Item__c item : lineItemsForApplications){
                        OpportunityLineItem oppItem = new OpportunityLineItem(
                            OpportunityId = invoiceOpp.Id,
                            Site__c = application.Site__c,
                            Product2Id = item.Product__c,
                            Quantity = item.Quantity__c,
                            UnitPrice = item.List_Price__c,
                            Description = item.Line_Description__c
                        );
                        oppProdToInsert.add(oppItem);
                    }
                    if(oppProdToInsert.size() > 0){
                        insert oppProdToInsert;
                        invoiceOpp.StageName = 'Closed Won';
                        invoiceOpp.ia_crm__Sync_With_Intacct__c = true;
                        update invoiceOpp;
                    }
                }
            }
            return JSON.serialize(application);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static string sendMultipleInvoices(List<String> contactId,String message,String recordId){
        try {
            Application__c application = [
                SELECT Id,Name,Payment_Due_Date__c,Invoice_Date__c,Bulk_Renewal__c ,CreatedDate,Site__c,
                Site_Name__c,Application_Type__c,Head_Office__c,Pricebook_Id__c,Applicant_Contact__c,
                Sage_Invoice__c
                FROM Application__c WHERE Id=:recordId
            ];
            
            if(application.Bulk_Renewal__c == null && application.Sage_Invoice__c != null){ 
                sendEmail(application.Id,contactId);
            }
            return JSON.serialize(application);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    public static void sendEmail(String applicationId,List<String> contactIds){
        EmailTemplate emailTemplate = [SELECT ID FROM EmailTemplate WHERE Name = 'Application Invoice Email'];
        OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = 'help@rspcaassured.org.uk'];
        Application__c app = [SELECT Id,Name,Applicant_Contact__c,Custom_Invoice_Message__c,Alternative_Invoice_Sender_Email__c,Accounts_Email__c,Membership_Number__c,Payment_Reference__c FROM Application__c WHERE Id=:applicationId];
        system.debug('message:::'+app.Custom_Invoice_Message__c);
        PageReference reportPage = new PageReference('/apex/InvoicePDF');
        reportPage.getParameters().put('id', app.Id);
        
        Blob reportPdf;
        if(!Test.isRunningTest()){
          reportPdf = reportPage.getContentAsPDF();
        }else{
            reportPdf = Blob.valueOf('Test');
        }
        
        ContentVersion cv = new ContentVersion();
        cv.VersionData = reportPdf;
        cv.Title = app.Name;
        cv.PathOnClient = app.Name+'.pdf';
        cv.Description = app.Name;
        cv.isMajorVersion = true;
        insert cv;
        Messaging.SingleEmailMessage[] messages = new List<Messaging.SingleEmailMessage>();
        for(String contactId:contactIds){
            Messaging.SingleEmailMessage message = Messaging.renderStoredEmailTemplate(emailTemplate.Id, contactId, app.Id);
            message.setEntityAttachments(new list<Id> {cv.Id});
            if(app.Alternative_Invoice_Sender_Email__c != null){
                message.setReplyTo(app.Alternative_Invoice_Sender_Email__c);
                message.setSenderDisplayName(app.Alternative_Invoice_Sender_Email__c);
            }else{
                message.setReplyTo('help@rspcaassured.org.uk');
                message.setOrgWideEmailAddressId(owea.get(0).Id);
            }
            message.setSubject('Invoice For membership number: '+app.Membership_Number__c);
            message.setUseSignature(false);
            message.setBccSender(false);
            message.setSaveAsActivity(true);   
            if(app.Accounts_Email__c != null){
                message.toAddresses = new String[] {app.Accounts_Email__c};
            }
            system.debug('toAddresses '+message.toAddresses);
            messages.add(message);
        }
        Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
        app.InvoiceSent__c = true;
        TriggerHandler.bypass('ApplicationTriggerHandler');
        update app;
        TriggerHandler.clearBypass('ApplicationTriggerHandler');
    }
}