unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Existing_Member__c.field-meta.xml
<CustomField>
    <fullName>Existing_Member__c</fullName>
    <label>Existing Member?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Send_Application_Confirmation_Email__c.field-meta.xml
<CustomField>
    <fullName>Send_Application_Confirmation_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Application Confirmation Email</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lameness_Prevalence__c/Lameness_Prevalence__c.object-meta.xml
<CustomObject>
    <label>Lameness Prevalence</label>
    <nameField>
        <displayFormat>LP-{0000}</displayFormat>
        <label>Lameness prevalence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lameness Prevalences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Lameness_Prevalence__c/fields/Percentage_Of_Score_2_cows__c.field-meta.xml
<CustomField>
    <fullName>Percentage_Of_Score_2_cows__c</fullName>
    <label>% Of Score 2 cows</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Lameness_Prevalence__c/fields/Percentage_Of_Score_3_cows__c.field-meta.xml
<CustomField>
    <fullName>Percentage_Of_Score_3_cows__c</fullName>
    <label>% Of Score 3 cows</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Lameness_Prevalence__c/fields/WOADairy__c.field-meta.xml
<CustomField>
    <fullName>WOADairy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WOADairy</label>
    <referenceTo>WOADairy__c</referenceTo>
    <relationshipLabel>Lameness Prevalences</relationshipLabel>
    <relationshipName>Lameness_Prevalences</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WOA__c/WOA__c.object-meta.xml
<CustomObject>
    <label>WOA</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>WOA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WOAs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/WOA__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>WOAs</relationshipLabel>
    <relationshipName>WOAs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/WOA__c/fields/Species_Type__c.field-meta.xml
<CustomField>
    <fullName>Species_Type__c</fullName>
    <label>Species Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dairy Cattle</fullName>
            </value>
            <value>
                <fullName>Laying Hen</fullName>
            </value>
            <value>
                <fullName>Pigs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WOADairy__c/WOADairy__c.object-meta.xml
<CustomObject>
    <label>WOADairy</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>WOADairyID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WOAs Dairy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/WOADairy__c/fields/Average_Percentage_Of_Score_2_cows__c.field-meta.xml
<CustomField>
    <fullName>Average_Percentage_Of_Score_2_cows__c</fullName>
    <label>Average % Of Score 2 cows</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/WOADairy__c/fields/Average_Percentage_Of_Score_3_cows__c.field-meta.xml
<CustomField>
    <fullName>Average_Percentage_Of_Score_3_cows__c</fullName>
    <label>Average % Of Score 3 cows</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/WOADairy__c/fields/WOA__c.field-meta.xml
<CustomField>
    <fullName>WOA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WOA</label>
    <referenceTo>WOA__c</referenceTo>
    <relationshipLabel>WOAs Dairy</relationshipLabel>
    <relationshipName>WOAs_Dairy</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/BatchToUpdateLamenessPrevalenceTest.cls
@isTest
public class BatchToUpdateLamenessPrevalenceTest {
	@testSetup
    static void loadData(){
        // Create Application
        FObject application = DataFactory.getDefNewApplications();
        application.setDefinition('Existing_Member__c', 'static value(No)');
        application.insertRecords(true);

        // do assertions
        List<Account> insertedAccounts = FObject.getInsertedRecords('Account');
        List<Contact> insertedCon = FObject.getInsertedRecords('Contact');
        List<Application__c> insertedApp = FObject.getInsertedRecords('Application__c');
        
        Application__c app = insertedApp[0];
        app.Send_Application_Confirmation_Email__c = true;
        update app;
        List<WOA__c> woaList = new List<WOA__c>{
            new WOA__c(Application__c=app.Id,Species_Type__c='Dairy Cattle')
        };
        insert woaList;
        WOADairy__c woaDairy = new WOADairy__c(WOA__c = woaList[0].Id);
        insert woaDairy;
        List<Lameness_Prevalence__c> lamenessPrevalence = new List<Lameness_Prevalence__c>{
            new Lameness_Prevalence__c(WOADairy__c =woaDairy.Id ,Percentage_Of_Score_2_cows__c=1, Percentage_Of_Score_3_cows__c=1),
                new Lameness_Prevalence__c(WOADairy__c =woaDairy.Id ,Percentage_Of_Score_2_cows__c=2, Percentage_Of_Score_3_cows__c=2),
                                new Lameness_Prevalence__c(WOADairy__c =woaDairy.Id )

        };
        insert lamenessPrevalence;
    }
    @isTest
    static void testMethod1(){
        Test.startTest();
        Database.executeBatch(new BatchToUpdateLamenessPrevalenceScore());
        Test.stopTest();
        List<WOADairy__c> woaDairys = [SELECT ID, Average_Percentage_Of_Score_2_cows__c, Average_Percentage_Of_Score_3_cows__c FROM WOADairy__c];
        system.assert(woaDairys[0].Average_Percentage_Of_Score_2_cows__c == 1.5);
        system.assert(woaDairys[0].Average_Percentage_Of_Score_2_cows__c == 1.5);
    }
}