unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Applicant_Contact__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Application_Type__c</fullName>
    <label>Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Existing_Member__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Revisit</fullName>
            </value>
            <value>
                <fullName>Levy</fullName>
            </value>
            <value>
                <fullName>Merchandise</fullName>
            </value>
            <value>
                <fullName>Promotion/Partnership</fullName>
            </value>
            <value>
                <fullName>Consultancy</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Existing_Member__c.field-meta.xml
<CustomField>
    <fullName>Existing_Member__c</fullName>
    <label>Existing Member?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Head_Office__c.field-meta.xml
<CustomField>
    <fullName>Head_Office__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Head Office</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Head Office</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Pricebook_Id__c.field-meta.xml
<CustomField>
    <fullName>Pricebook_Id__c</fullName>
    <label>Pricebook Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Site_Name__c.field-meta.xml
<CustomField>
    <fullName>Site_Name__c</fullName>
    <formula>Site__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application_Line_Item__c/Application_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Application Line Item</label>
    <nameField>
        <displayFormat>APL-{0000}</displayFormat>
        <label>Application Line Item Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application_Line_Item__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Application_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Application_Line_Item__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>List Price Ex Vat</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Application_Line_Item__c/fields/List_Price_Inc_Vat__c.field-meta.xml
<CustomField>
    <fullName>List_Price_Inc_Vat__c</fullName>
    <label>List Price Inc Vat</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Application_Line_Item__c/fields/Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Subtotal__c</fullName>
    <formula>List_Price__c  *  Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subtotal</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Standard_Price__c.field-meta.xml
<CustomField>
    <fullName>Standard_Price__c</fullName>
    <label>Standard Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/CreateCreditNoteControllerTest.cls
@isTest
public class CreateCreditNoteControllerTest {

    @testSetup static void setup() {
       // Create joinFee product
       FObject joinFee = new FObject('Product2', 1);
       joinFee.setDefinition('Name','static value(Joining Fee)');
       joinFee.setDefinition('ProductCode','static value(JOINFEE)');
       joinFee.setDefinition('IsActive','static value(true)');
       joinFee.setDefinition('Standard_Price__c','static value(28.80)');
       joinFee.insertRecords(true);
       
       // Create revisitFee product
       FObject revisitFee = new FObject('Product2', 1);
       revisitFee.setDefinition('Name','static value(Revisit)');
       revisitFee.setDefinition('ProductCode','static value(REVISIT)');
       revisitFee.setDefinition('IsActive','static value(true)');
       revisitFee.setDefinition('Standard_Price__c','static value(114.24)');
       revisitFee.insertRecords(true);

       // Create Application
       FObject application = DataFactory.getDefNewApplications();
       application.setDefinition('Existing_Member__c', 'static value(No)');
       application.insertRecords(true);
    }

    @isTest
    static void getApplication(){
        // get application record
        List<Application__c> appList = [SELECT Id FROM Application__c];

        // run controller method
        Test.startTest();
        CreateCreditNoteController.getApplication(appList[0].Id);
        Test.stopTest();
    }

    @isTest
    static void getCreditLines(){
        // get application record
        List<Application__c> appList = [SELECT Id FROM Application__c];
        List<Application_Line_Item__c> appLineItems = [SELECT Id, Application__c, Product_Name__c, Quantity__c,List_Price__c, List_Price_Inc_Vat__c, Subtotal__c FROM Application_Line_Item__c];
        List<String> appLineIds = new List<String>();
        for(Application_Line_Item__c ali : appLineItems){
            appLineIds.add(ali.Id);
        }

        // run controller method
        Test.startTest();
        CreateCreditNoteController.getCreditLines(appLineIds);
        Test.stopTest();
    }
    /*
    @isTest
    static void createCreditNote(){
        // get application record
        List<Application__c> appList = [SELECT Id, Site_Name__c, Application_Type__c,Pricebook_Id__c, Applicant_Contact__c, Head_Office__c, Head_Office__r.BillingCountry FROM Application__c];
        List<Application_Line_Item__c> appLineItems = [SELECT Id, Application__c, Product_Name__c, Quantity__c,List_Price__c, List_Price_Inc_Vat__c, Subtotal__c FROM Application_Line_Item__c];
        List<String> appLineIds = new List<String>();
        for(Application_Line_Item__c ali : appLineItems){
            appLineIds.add(ali.Id);
        }

        // Get credit note line wrapper
        List<CreateCreditNoteController.CreditNoteLineWrapper> creditNoteLinesWrapper = CreateCreditNoteController.getCreditLines(appLineIds);

        // run controller method
        Test.startTest();
        CreateCreditNoteController.createCreditNote(appList[0], creditNoteLinesWrapper, 'Cancellation', 'ponumber', 'orderdetails');
        Test.stopTest();
    }*/
}