unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Site__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/Application_Unit__c.object-meta.xml
<CustomObject>
    <label>Application Unit</label>
    <nameField>
        <displayFormat>APUN-{00}</displayFormat>
        <label>APP Unit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application_Unit__c/fields/Animals__c.field-meta.xml
<CustomField>
    <fullName>Animals__c</fullName>
    <formula>TEXT( Unit__r.Animals__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Animals</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Application Units</relationshipLabel>
    <relationshipName>ApplicationUnits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Assessment_Checklist_Question__c/Assessment_Checklist_Question__c.object-meta.xml
<CustomObject>
    <label>Assessment Checklist Question</label>
    <nameField>
        <displayFormat>CLQ-{00000}</displayFormat>
        <label>Checklist Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Checklist Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Assessment_Checklist_Question__c/fields/Assessment_Checklist_Section__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Checklist_Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment Checklist Section</label>
    <referenceTo>Assessment_Checklist_Section__c</referenceTo>
    <relationshipLabel>Assessment Checklist Questions</relationshipLabel>
    <relationshipName>Assessment_Checklist_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Assessment_Checklist_Question__c/fields/Comments_Action__c.field-meta.xml
<CustomField>
    <fullName>Comments_Action__c</fullName>
    <label>Comments/Action</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Assessment_Checklist_Question__c/fields/Guidance_Notes__c.field-meta.xml
<CustomField>
    <fullName>Guidance_Notes__c</fullName>
    <label>Guidance Notes</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Assessment_Checklist_Question__c/fields/Section_Order__c.field-meta.xml
<CustomField>
    <fullName>Section_Order__c</fullName>
    <label>Section Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Assessment_Checklist_Question__c/fields/Standard__c.field-meta.xml
<CustomField>
    <fullName>Standard__c</fullName>
    <label>Standard</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Assessment_Checklist_Question__c/fields/Standard_Order__c.field-meta.xml
<CustomField>
    <fullName>Standard_Order__c</fullName>
    <label>Standard Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Assessment_Checklist_Question__c/fields/Subsection__c.field-meta.xml
<CustomField>
    <fullName>Subsection__c</fullName>
    <label>Subsection</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Assessment_Checklist_Section__c/Assessment_Checklist_Section__c.object-meta.xml
<CustomObject>
    <label>Assessment Checklist Section</label>
    <nameField>
        <displayFormat>ACS-{0000}</displayFormat>
        <label>Assessment Checklist Section Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Checklist Section</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Assessment_Checklist_Section__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <label>Assessment</label>
    <referenceTo>Assessments__c</referenceTo>
    <relationshipLabel>Assessment Checklist Section</relationshipLabel>
    <relationshipName>Assessment_Checklist_Section</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Assessment_Checklist_Section__c/fields/Checklist_Section_Name__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Section_Name__c</fullName>
    <label>Checklist Section Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Assessment_Checklist_Section__c/fields/Checklist_Section_Order__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Section_Order__c</fullName>
    <label>Checklist Section Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Assessments__c/Assessments__c.object-meta.xml
<CustomObject>
    <label>Assessment Checklist</label>
    <nameField>
        <displayFormat>AC-{000000}</displayFormat>
        <label>Checklist No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Checklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Assessments__c/fields/Animals__c.field-meta.xml
<CustomField>
    <fullName>Animals__c</fullName>
    <label>Animals</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Animals</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Assessments__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipName>Assessments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Assessments__c/fields/Checklist_Type__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Type__c</fullName>
    <label>Checklist Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Checklist_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Assessments__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Assessment_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Checklist_Template__c/Checklist_Template__c.object-meta.xml
<CustomObject>
    <label>Checklist Template</label>
    <nameField>
        <label>Checklist Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklist Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Checklist_Template__c/fields/Species__c.field-meta.xml
<CustomField>
    <fullName>Species__c</fullName>
    <label>Species</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Animals</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Checklist_Template__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Checklist_Template__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard Checklist</fullName>
            </value>
            <value>
                <fullName>Welfare Outcome Checklist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Checklist_Template_Section__c/Checklist_Template_Section__c.object-meta.xml
<CustomObject>
    <label>Checklist Template Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklist Template Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Checklist_Template_Section__c/fields/Checklist_Template__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Template__c</fullName>
    <label>Checklist Template</label>
    <referenceTo>Checklist_Template__c</referenceTo>
    <relationshipLabel>Checklist Template Sections</relationshipLabel>
    <relationshipName>Checklist_Template_Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Checklist_Template_Section__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>Controls the order the sections appear in the mobile app.</description>
    <inlineHelpText>Controls the order the sections appear in the mobile app.</inlineHelpText>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Checklist_Template_Standard__c/Checklist_Template_Standard__c.object-meta.xml
<CustomObject>
    <label>Checklist Template Standard</label>
    <nameField>
        <label>Standard Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklist Template Standards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Checklist_Template_Standard__c/fields/Checklist_Template__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Template__c</fullName>
    <label>Checklist Template</label>
    <referenceTo>Checklist_Template__c</referenceTo>
    <relationshipName>Checklist_Standards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Checklist_Template_Standard__c/fields/Checklist_Template_Section__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Template_Section__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Checklist Template Section</label>
    <referenceTo>Checklist_Template_Section__c</referenceTo>
    <relationshipName>Checklist_Standards</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Checklist_Template_Standard__c/fields/Checklist_Template_Subsection__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Template_Subsection__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Checklist Template Subsection</label>
    <referenceTo>Checklist_Template_Subsection__c</referenceTo>
    <relationshipName>Checklist_Standards</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Checklist_Template_Standard__c/fields/ContentVersion_URL__c.field-meta.xml
<CustomField>
    <fullName>ContentVersion_URL__c</fullName>
    <label>ContentVersion URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Checklist_Template_Standard__c/fields/Default_Comments_Action__c.field-meta.xml
<CustomField>
    <fullName>Default_Comments_Action__c</fullName>
    <label>Default Comments/Action</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Checklist_Template_Standard__c/fields/Default_Compliant_Value__c.field-meta.xml
<CustomField>
    <fullName>Default_Compliant_Value__c</fullName>
    <label>Default Compliant Value</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Compliant_Value_set</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Checklist_Template_Standard__c/fields/Guidance_Notes__c.field-meta.xml
<CustomField>
    <fullName>Guidance_Notes__c</fullName>
    <label>Guidance Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Checklist_Template_Subsection__c/Checklist_Template_Subsection__c.object-meta.xml
<CustomObject>
    <label>Checklist Template Subsection</label>
    <nameField>
        <label>Subsection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklist Template Subsections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Checklist_Template_Subsection__c/fields/Checklist_Template_Section__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Template_Section__c</fullName>
    <label>Checklist Template Section</label>
    <referenceTo>Checklist_Template_Section__c</referenceTo>
    <relationshipLabel>Checklist Template Subsections</relationshipLabel>
    <relationshipName>Checklist_Template_Subsections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Checklist_Template_Subsection__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>The order the subsections appear in the mobile app.</description>
    <inlineHelpText>The order the subsections appear in the mobile app.</inlineHelpText>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/globalValueSets/Animals.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Beef Cattle</fullName>
    </customValue>
    <customValue>
        <fullName>Chickens</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy Cattle</fullName>
    </customValue>
    <customValue>
        <fullName>Ducklings</fullName>
    </customValue>
    <customValue>
        <fullName>Ducks</fullName>
    </customValue>
    <customValue>
        <fullName>Laying Hen Chicks</fullName>
    </customValue>
    <customValue>
        <fullName>Laying Hens</fullName>
    </customValue>
    <customValue>
        <fullName>Lumpfish</fullName>
    </customValue>
    <customValue>
        <fullName>Meat Chicken Chicks</fullName>
    </customValue>
    <customValue>
        <fullName>Pigs</fullName>
    </customValue>
    <customValue>
        <fullName>Pullets</fullName>
    </customValue>
    <customValue>
        <fullName>Salmon</fullName>
    </customValue>
    <customValue>
        <fullName>Sheep</fullName>
    </customValue>
    <customValue>
        <fullName>Trout</fullName>
    </customValue>
    <customValue>
        <fullName>Turkey Poults</fullName>
    </customValue>
    <customValue>
        <fullName>Turkeys</fullName>
    </customValue>
    <customValue>
        <fullName>Veal Calves</fullName>
    </customValue>
    <customValue>
        <fullName>Wrasse</fullName>
    </customValue>
    <customValue>
        <fullName>List</fullName>
    </customValue>
    <masterLabel>Animals</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Assessment_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <masterLabel>Assessment Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Checklist_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Welfare Standard Checklist</fullName>
    </customValue>
    <customValue>
        <fullName>Welfare Outcome Assessment Checklist</fullName>
    </customValue>
    <masterLabel>Checklist Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Compliant_Value_set.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <masterLabel>Compliant Value-set</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/NewAssessmentChecklistController.cls
public class NewAssessmentChecklistController {
   	
    @AuraEnabled
    public static List<Checklist_Template__c> getChecklistTemplates(String appId){
        // Query Application Units on this application
        List<Application_Unit__c> appUnitList = [SELECT Id, Application__c, Animals__c FROM Application_Unit__c WHERE Application__c =:appId AND Animals__c != null];
        
        // Use a set to store the animals in a unique list
        Set<String> animalSet = new Set<String>();
        for(Application_Unit__c au : appUnitList ){
            animalSet.add(au.Animals__c);
        }
        
        List<Checklist_Template__c> templates = [SELECT Id, Name, Species__c FROM Checklist_Template__c WHERE Status__c = 'Active' AND Species__c IN :animalSet ];
        
        if(templates.size() > 0){
            return templates;
        }else{
            return null;
        }
        
    }
    
    @AuraEnabled
    public static void createAssessmentChecklist(String appId, List<String> checklistIds){
        if(checklistIds != null & checklistIds.size() > 0 && appId != null){
            // Query the Checklist Template
            Map<Id, Checklist_Template__c> checklistTemplateMap = new Map<Id, Checklist_Template__c>([SELECT Id, Name, Species__c, Type__c FROM Checklist_Template__c WHERE Id IN:checklistIds]);
            
			// Query the checklist template standards            
            List<Checklist_Template_Standard__c> templateStandards = [SELECT Id,Name , Checklist_Template__c, Checklist_Template_Section__c ,Checklist_Template_Section__r.Name, Checklist_Template_Section__r.Order__c, Checklist_Template_Subsection__c, Checklist_Template_Subsection__r.Name, Checklist_Template_Subsection__r.Order__c, Standard_Order__c, ContentVersion_URL__c , Default_Compliant_Value__c ,Default_Comments_Action__c , Guidance_Notes__c , Summary__c   FROM Checklist_Template_Standard__c WHERE Checklist_Template__c IN:checklistIds];
            Map<Id, List<Checklist_Template_Standard__c>> templateIdToStandards = new Map<Id, List<Checklist_Template_Standard__c>>();
            
            // Map the checklist template standards to its template parent object id
            for(Checklist_Template_Standard__c cts : templateStandards){
                if(templateIdToStandards.containsKey(cts.Checklist_Template__c)){
                    List<Checklist_Template_Standard__c> lst = templateIdToStandards.get(cts.Checklist_Template__c);
                    lst.add(cts);
                    templateIdToStandards.put(cts.Checklist_Template__c, lst);
                }else{
                    templateIdToStandards.put(cts.Checklist_Template__c,  new List<Checklist_Template_Standard__c>{cts} ) ;
                }                    
            }
            
            // Map of Assessments to create
            Map<Id, Assessments__c> checklistIdToAssessmentList = new Map<Id, Assessments__c>();
             // Iterate through all checklist ids
            for(String checkId : checklistIds){
                if(templateIdToStandards.containsKey(checkId) && checklistTemplateMap.containsKey(checkId)){
                    // Get the checklist template to populate values in the assessment
                    Checklist_Template__c template = checklistTemplateMap.get(checkId);
                    Assessments__c  ass = new Assessments__c();
                    ass.Application__c = appId;
                    if(template.Type__c == 'Standard Checklist'){
                        ass.Checklist_Type__c = 'Welfare Standard Checklist';
                    }else if(template.Type__c == 'Welfare Outcome Checklist'){
                        ass.Checklist_Type__c = 'Welfare Outcome Assessment Checklist';
                    }
                    ass.Animals__c = template.Species__c;
                    checklistIdToAssessmentList.put(checkId, ass);
                }
            }
            // Insert Assessments
            if(!checklistIdToAssessmentList.values().isEmpty()){
                insert checklistIdToAssessmentList.values();
            }
            
            // Map of Checklist Section Id to Assessment Section 
            Map<Id, Assessment_Checklist_Section__c> templateSectionIdToAssessmentSection = new Map<Id, Assessment_Checklist_Section__c>();
            // Iterate through all checklist ids
            for(String checkId : checklistIds){
                if(checklistIdToAssessmentList.containsKey(checkId)){
                    Assessments__c  ass = checklistIdToAssessmentList.get(checkId);
                     // Get the checklist template standard from the checklist template using the id to iterate over and create the assessment sections 
                    List<Checklist_Template_Standard__c> lst = templateIdToStandards.get(checkId);
                    for(Checklist_Template_Standard__c cts : lst){
                        if(!templateSectionIdToAssessmentSection.containsKey(cts.Checklist_Template_Section__c)){
                            templateSectionIdToAssessmentSection.put(
                                cts.Checklist_Template_Section__c,
                                new Assessment_Checklist_Section__c(
                                    Assessment__c = ass.Id, 
                                    Checklist_Section_Name__c = cts.Checklist_Template_Section__r.Name, 
                                    Checklist_Section_Order__c = cts.Checklist_Template_Section__r.Order__c
                                )
                            );
                        }
                    }
                }
            }
            // Insert Assessment Sections
            if(!templateSectionIdToAssessmentSection.values().isEmpty()){
                insert templateSectionIdToAssessmentSection.values();
            }
            
			// List of Assessment Checklist Questions to create            
            List<Assessment_Checklist_Question__c> acqList = new List<Assessment_Checklist_Question__c>();
            // Iterate through all checklist ids
            for(String checkId : checklistIds){
                if(checklistIdToAssessmentList.containsKey(checkId)){
                    Assessments__c  ass = checklistIdToAssessmentList.get(checkId);
                    // Get the checklist template standard from the checklist template using the id to iterate over and create the assessment questions 
                    List<Checklist_Template_Standard__c> lst = templateIdToStandards.get(checkId);
                    for(Checklist_Template_Standard__c cts : lst){                        
                        Assessment_Checklist_Question__c acq = new Assessment_Checklist_Question__c();
                        acq.Assessment_Checklist__c = ass.Id;
                        acq.Compliant__c = cts.Default_Compliant_Value__c;
                        acq.ContentVersion_URL__c  = cts.ContentVersion_URL__c;
                        acq.Guidance_Notes__c = cts.Guidance_Notes__c;
                        acq.Standard__c  = cts.Name;
                        
                        if(templateSectionIdToAssessmentSection.containsKey(cts.Checklist_Template_Section__c)){
                            // If Asessment Checklist Section already exists, then link the Asessment Checklist Question to the section and populate the values
                            Assessment_Checklist_Section__c acs = templateSectionIdToAssessmentSection.get(cts.Checklist_Template_Section__c);
                            acq.Assessment_Checklist_Section__c = acs.Id;
                            acq.Section__c = acs.Checklist_Section_Name__c;
                            acq.Section_Order__c = acs.Checklist_Section_Order__c;
                        }
                        acq.Subsection__c = cts.Checklist_Template_Subsection__r.Name;
                        acq.Subsection_Order__c = cts.Checklist_Template_Subsection__r.Order__c;
                        acq.Summary__c = cts.Summary__c;
                        acq.Standard_Order__c = cts.Standard_Order__c;
                        acq.Comments_Action__c = cts.Default_Comments_Action__c;
                        acqList.add(acq);
                    }
                }
            }
            
            if(!acqList.isEmpty()){
                insert acqList;
            }
        }
    }
    
}