unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Existing_Member__c.field-meta.xml
<CustomField>
    <fullName>Existing_Member__c</fullName>
    <label>Existing Member?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Send_Application_Confirmation_Email__c.field-meta.xml
<CustomField>
    <fullName>Send_Application_Confirmation_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Application Confirmation Email</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Standard_Price__c.field-meta.xml
<CustomField>
    <fullName>Standard_Price__c</fullName>
    <label>Standard Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/WOA__c/WOA__c.object-meta.xml
<CustomObject>
    <label>WOA</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>WOA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WOAs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/WOA__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>WOAs</relationshipLabel>
    <relationshipName>WOAs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/WOA__c/fields/Species_Type__c.field-meta.xml
<CustomField>
    <fullName>Species_Type__c</fullName>
    <label>Species Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dairy Cattle</fullName>
            </value>
            <value>
                <fullName>Laying Hen</fullName>
            </value>
            <value>
                <fullName>Pigs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WOAHens__c/WOAHens__c.object-meta.xml
<CustomObject>
    <label>WOAHens</label>
    <nameField>
        <displayFormat>WH-{0000}</displayFormat>
        <label>WOAHens ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WOAHens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/WOAHens__c/fields/WOA__c.field-meta.xml
<CustomField>
    <fullName>WOA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WOA</label>
    <referenceTo>WOA__c</referenceTo>
    <relationshipLabel>WOAHens</relationshipLabel>
    <relationshipName>WOAHens</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/WOAHenControllerTest.cls
@isTest
public class WOAHenControllerTest {
@testSetup
    static void loadData(){
         FObject joinFee = new FObject('Product2', 1);
        joinFee.setDefinition('Name','static value(Joining Fee)');
        joinFee.setDefinition('ProductCode','static value(JOINFEE)');
        joinFee.setDefinition('IsActive','static value(true)');
        joinFee.setDefinition('Standard_Price__c','static value(28.80)');
        joinFee.insertRecords(true);
        // Create revisitFee product
        FObject revisitFee = new FObject('Product2', 1);
        revisitFee.setDefinition('Name','static value(Revisit)');
        revisitFee.setDefinition('ProductCode','static value(REVISIT)');
        revisitFee.setDefinition('IsActive','static value(true)');
        revisitFee.setDefinition('Standard_Price__c','static value(114.24)');
        revisitFee.insertRecords(true);

        // Create Application
        FObject application = DataFactory.getDefNewApplications();
        application.setDefinition('Existing_Member__c', 'static value(No)');
        application.insertRecords(true);

        // do assertions
        List<Account> insertedAccounts = FObject.getInsertedRecords('Account');
        List<Contact> insertedCon = FObject.getInsertedRecords('Contact');
        List<Application__c> insertedApp = FObject.getInsertedRecords('Application__c');
        
        Application__c app = insertedApp[0];
        app.Send_Application_Confirmation_Email__c = true;
        update app;
        List<WOA__c> woaList = new List<WOA__c>{
            new WOA__c(Application__c=app.Id,Species_Type__c='Laying Hen')
        };
        insert woaList;
        WOAHens__c woaHens = new WOAHens__c(WOA__c = woaList[0].Id);
        insert woaHens;
    }
    @isTest
    static void testMethod1(){
        WOAHens__c woaHens = [SELECT ID,WOA__C,Comments__c FROM WOAHens__c LIMIT 1];
        woaHens = WOAHenController.getWOAHens(woaHens.WOA__c);
        system.Assert(String.isBlank(woaHens.Comments__c));
        woaHens.Comments__c = 'xxxxx';
        WOAHenController.saveWOAHens(woaHens);
        woaHens = [SELECT ID,WOA__C,Comments__c FROM WOAHens__c LIMIT 1];
        system.Assert(String.isNotBlank(woaHens.Comments__c));

    }
}