unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Function: member services select an assessor; system then automatically emails them.</description>
    <inlineHelpText>This field must be populated in order to mark an Additional Visit as complete.</inlineHelpText>
    <label>Allocated Assessor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>You can only select an assessor user to be allocated for this application.</errorMessage>
        <filterItems>
            <field>User.Assessor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>User.Contract_Assessor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Renewal_Stage__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Stage__c</fullName>
    <description>Stage for renewal application. This stage is used in renewal record type.</description>
    <label>Renewal Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Allocation</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>Stage field for new applications for new site, update, or transfers. This field is used for the application record type.</description>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Application</fullName>
                <default>true</default>
                <label>Application</label>
            </value>
            <value>
                <fullName>Allocation</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Schedule</fullName>
            </value>
            <value>
                <fullName>Visit</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/recordTypes/Applications.recordType-meta.xml
<RecordType>
    <fullName>Applications</fullName>
    <active>true</active>
    <description>For new applications.</description>
    <label>Applications</label>
</RecordType>

unpackaged/main/default/objects/Application__c/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <description>For renewal applications</description>
    <label>Renewal</label>
</RecordType>

unpackaged/main/default/objects/Application_Unit__c/Application_Unit__c.object-meta.xml
<CustomObject>
    <label>Application Unit</label>
    <nameField>
        <displayFormat>APUN-{00}</displayFormat>
        <label>APP Unit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application_Unit__c/fields/Animals__c.field-meta.xml
<CustomField>
    <fullName>Animals__c</fullName>
    <formula>TEXT( Unit__r.Animals__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Animals</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Application Units</relationshipLabel>
    <relationshipName>ApplicationUnits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <formula>TEXT(Unit__r.Business__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WOA__c/WOA__c.object-meta.xml
<CustomObject>
    <label>WOA</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>WOA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WOAs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/WOA__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>WOAs</relationshipLabel>
    <relationshipName>WOAs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/WOA__c/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Assessor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>WOAs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WOA__c/fields/Species_Type__c.field-meta.xml
<CustomField>
    <fullName>Species_Type__c</fullName>
    <label>Species Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dairy Cattle</fullName>
            </value>
            <value>
                <fullName>Laying Hen</fullName>
            </value>
            <value>
                <fullName>Pigs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/GenerateWOA.cls
public class GenerateWOA {
    public static void generate(Map<Id,Application__c> newMap, Map<Id,Application__c> oldMap, Boolean skipStageChange){

        Set<Id> appsChangedToAssessment = new Set<Id>();
        for(Application__c app : newMap.values()){
            // for applications
            if(app.Stage__c == 'Assessment' && (oldMap.get(app.Id).Stage__c != 'Assessment' || skipStageChange)){
                appsChangedToAssessment.add(app.Id);
            }
            // for renewal applications
            if(app.Renewal_Stage__c == 'Assessment' && (oldMap.get(app.Id).Renewal_Stage__c != 'Assessment' || skipStageChange)){
                appsChangedToAssessment.add(app.Id);
            }
        }

        // if there are apps in assessment
        if(!appsChangedToAssessment.isEmpty()){
            // for the apps changed to assessmetn query application units and check existing WOA
            Map<Id, List<WOA__c>> appIdToWOAList = getWOAForApplicationsID(appsChangedToAssessment);
            Map<Id, List<Application_Unit__c>> appIdToAppUnits = getAppUnitForApplicationsID(appsChangedToAssessment);

            List<WOA__c> listOfWOAToCreate = new List<WOA__c>();

            for(Id appId : appsChangedToAssessment){
                Application__c app = newMap.get(appId);
                List<Application_Unit__c> appUnitList = appIdToAppUnits.get(appId);
                if(appUnitList != null){
                    List<WOA__c> woaList = appIdToWOAList.get(appId);
                    Map<String, WOA__c> speciesStringWoaMap = new Map<String, WOA__c>();
                    for(Application_Unit__c au : appUnitList){
                        Boolean alreadyExists = false;
                        WOA__c newWOA = new WOA__c();
                        newWOA.Application__c = app.Id;
                        // assign assessor
                        if(app.Assessor__c != null){
                            newWOA.Assessor__c = app.Assessor__c;
                        }
                        

                        // select species
                        if(au.Animals__c == 'Laying Hens'){
                            newWOA.Species_Type__c = 'Laying Hen';
                        }else if(au.Animals__c == 'Pigs'){
                            newWOA.Species_Type__c = 'Pigs';
                        }
                        else if(au.Animals__c == 'Dairy Cattle'){
                            newWOA.Species_Type__c = 'Dairy Cattle';
                        }
                        
                        if(woaList != null){
                            for(WOA__c existingWoa : woaList){
                                if(existingWoa.Species_Type__c == newWOA.Species_Type__c){
                                    alreadyExists = true;
                                }
                            }
                        }
                        

                        if(!alreadyExists && !speciesStringWoaMap.containsKey(newWOA.Species_Type__c)){
                            speciesStringWoaMap.put(newWOA.Species_Type__c, newWOA);
                        }
                    }

                     // add list to create
                    for(WOA__c woa : speciesStringWoaMap.values()){
                        listOfWOAToCreate.add(woa);
                    }
                }
                

               
            }

            if(!listOfWOAToCreate.isEmpty()){
                insert listOfWOAToCreate;
            }
        }
        
    }

    private static Map<Id, List<WOA__c>> getWOAForApplicationsID(Set<Id> appIdSet){
        Map<Id, List<WOA__c>> appIdToWOAList = new  Map<Id, List<WOA__c>>();
        for(WOA__c woa : [SELECT Id, Application__c, Species_Type__c FROM WOA__c WHERE Application__c IN: appIdSet]){
            if(appIdToWOAList.containsKey(woa.Application__c)){
                List<WOA__c> woaList = appIdToWOAList.get(woa.Application__c);
                woaList.add(woa);
                appIdToWOAList.put(woa.Application__c, woaList);
            }else{
                appIdToWOAList.put(woa.Application__c, new List<WOA__c>{ woa });
            }
        }
        return appIdToWOAList;
    }

    private static Map<Id, List<Application_Unit__c>> getAppUnitForApplicationsID(Set<Id> appIdSet){
        //List<String> woaAnimals = new list<String> { 'Laying Hens' , 'Pigs' , 'Dairy Cattle' };
        List<String> woaAnimals = new list<String> { 'Laying Hens' , 'Pigs'};
        Map<Id, List<Application_Unit__c>> appIdToAppUnits = new  Map<Id, List<Application_Unit__c>>();
        for(Application_Unit__c au : [SELECT Id, Business__c, Animals__c, Application__c FROM Application_Unit__c WHERE Application__c IN: appIdSet AND Animals__c IN:woaAnimals AND Business__c = 'Producer']){
            if(appIdToAppUnits.containsKey(au.Application__c)){
                List<Application_Unit__c> auList = appIdToAppUnits.get(au.Application__c);
                auList.add(au);
                appIdToAppUnits.put(au.Application__c, auList);
            }else{
                appIdToAppUnits.put(au.Application__c, new List<Application_Unit__c>{ au });
            }
        }
        return appIdToAppUnits;
    }
}