unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Assessment_Checklist__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Checklist__c</fullName>
    <label>Assessment Checklist</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Assessment_Date__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Date__c</fullName>
    <description>Cannot exceed the deadline date; can be updated if rearranged</description>
    <inlineHelpText>The date the site will be assessed</inlineHelpText>
    <label>Assessment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Assessment_Report__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Report__c</fullName>
    <inlineHelpText>White copy</inlineHelpText>
    <label>Assessment Report</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Function: member services select an assessor; system then automatically emails them.</description>
    <inlineHelpText>This field must be populated in order to mark an Additional Visit as complete.</inlineHelpText>
    <label>Allocated Assessor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>You can only select an assessor user to be allocated for this application.</errorMessage>
        <filterItems>
            <field>User.Assessor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>User.Contract_Assessor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Site__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Assessment_Checklist_Question__c/Assessment_Checklist_Question__c.object-meta.xml
<CustomObject>
    <label>Assessment Checklist Question</label>
    <nameField>
        <displayFormat>CLQ-{00000}</displayFormat>
        <label>Checklist Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Checklist Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Assessment_Checklist_Question__c/fields/Assessment_Checklist__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Checklist__c</fullName>
    <label>Assessment Checklist</label>
    <referenceTo>Assessments__c</referenceTo>
    <relationshipLabel>Assessment Checklist Questions</relationshipLabel>
    <relationshipName>Assessment_Checklist_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Assessment_Checklist_Question__c/fields/Comments_Action__c.field-meta.xml
<CustomField>
    <fullName>Comments_Action__c</fullName>
    <label>Comments/Action</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Assessment_Checklist_Question__c/fields/Compliant__c.field-meta.xml
<CustomField>
    <fullName>Compliant__c</fullName>
    <label>Compliant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Compliant_Value_set</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Assessment_Checklist_Question__c/fields/Standard__c.field-meta.xml
<CustomField>
    <fullName>Standard__c</fullName>
    <label>Standard</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Assessment_Report__c/Assessment_Report__c.object-meta.xml
<CustomObject>
    <label>Assessment Report</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Assessment Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Assessment_Report__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Assessment Reports</relationshipLabel>
    <relationshipName>Assessment_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Assessment_Report__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment</label>
    <referenceTo>Assessments__c</referenceTo>
    <relationshipLabel>Assessment Reports</relationshipLabel>
    <relationshipName>Assessment_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Assessment_Report__c/fields/Assessment_Date__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Date__c</fullName>
    <formula>Application__r.Assessment_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assessment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Assessment_Report__c/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assessment_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Assessments__c/Assessments__c.object-meta.xml
<CustomObject>
    <label>Assessment Checklist</label>
    <nameField>
        <displayFormat>AC-{000000}</displayFormat>
        <label>Checklist No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Checklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Assessments__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipName>Assessments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Assessments__c/fields/Application_Assessor__c.field-meta.xml
<CustomField>
    <fullName>Application_Assessor__c</fullName>
    <formula>Application__r.Assessor__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application Assessor</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Assessments__c/fields/Non_Compliances_Created__c.field-meta.xml
<CustomField>
    <fullName>Non_Compliances_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Non Compliances Created</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Assessments__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Assessment_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Non_Compliance__c/Non_Compliance__c.object-meta.xml
<CustomObject>
    <label>Non-Compliance</label>
    <nameField>
        <label>Standard #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Non-Compliances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Non_Compliance__c/fields/Assessment_Report__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Report__c</fullName>
    <label>Assessment Report</label>
    <referenceTo>Assessment_Report__c</referenceTo>
    <relationshipLabel>Non-Compliances</relationshipLabel>
    <relationshipName>Non_Compliances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Non_Compliance__c/fields/Non_compliance__c.field-meta.xml
<CustomField>
    <fullName>Non_compliance__c</fullName>
    <description>Description of the non-compliance and required rectification.</description>
    <inlineHelpText>Description of the non-compliance and required rectification.</inlineHelpText>
    <label>Non-compliance</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Non_Compliance__c/fields/Standard__c.field-meta.xml
<CustomField>
    <fullName>Standard__c</fullName>
    <description>The full written standard.</description>
    <inlineHelpText>The full written standard.</inlineHelpText>
    <label>Standard</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Standard__c/Standard__c.object-meta.xml
<CustomObject>
    <label>Standard</label>
    <nameField>
        <label>Standards Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/globalValueSets/Assessment_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <masterLabel>Assessment Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Compliant_Value_set.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Yes</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <masterLabel>Compliant Value-set</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/NonComplianceCreation.cls
public class NonComplianceCreation {
    public static void createNonCompliance(List<Assessments__c> newList) {
        Map<Id,Assessments__c> assessmentsComplete = new Map<Id,Assessments__c>();
        for(Assessments__c a : newList){
            if(a.Status__c == 'Completed' && a.Non_Compliances_Created__c == false){
                assessmentsComplete.put(a.Id, a);
            }
        }

        if(!assessmentsComplete.isEmpty()){
            Map<Id,List<Assessment_Checklist_Question__c>> assessmentQuestionMap = new Map<Id,List<Assessment_Checklist_Question__c>>();
            for(Assessment_Checklist_Question__c acq : [SELECT Id, Assessment_Checklist__c, Standard__c, Summary__c, Compliant__c, Comments_Action__c FROM Assessment_Checklist_Question__c WHERE Assessment_Checklist__c IN:assessmentsComplete.keySet() AND Compliant__c ='No']){
                if(assessmentQuestionMap.containsKey(acq.Assessment_Checklist__c)){
                    List<Assessment_Checklist_Question__c> questions = assessmentQuestionMap.get(acq.Assessment_Checklist__c);
                    questions.add(acq);
                    assessmentQuestionMap.put(acq.Assessment_Checklist__c, questions);
                }else{
                    assessmentQuestionMap.put(acq.Assessment_Checklist__c, new List<Assessment_Checklist_Question__c>{acq});
                }
            }

            //List<Assessments__c> assessmentsToUpdate = new List<Assessments__c>();
            Map<Id, Assessment_Report__c> assessmentToReportMap = new Map<Id, Assessment_Report__c>();
            for(Assessments__c a : assessmentsComplete.values()){
                Assessment_Report__c report = new Assessment_Report__c();
                report.Application__c = a.Application__c;
                report.Assessment__c = a.Id;
                report.Assessment_Date__c = Date.today();
                report.Assessor__c = a.Application_Assessor__c;
                assessmentToReportMap.put(a.Id, report);
            }

            if(!assessmentToReportMap.isEmpty()){
                insert assessmentToReportMap.values();

                // now create non compliance
                List<Non_Compliance__c> nonCompliancesToCreate = new  List<Non_Compliance__c>();
                for(Assessments__c a : assessmentsComplete.values()){
                    Assessment_Report__c assReport = assessmentToReportMap.get(a.Id);
                    if(assessmentQuestionMap.containsKey(a.Id)){
                        List<Assessment_Checklist_Question__c> questions = assessmentQuestionMap.get(a.Id);
                        for(Assessment_Checklist_Question__c q : questions){
                            Non_Compliance__c nonCompliance = new Non_Compliance__c();
                            nonCompliance.Assessment_Report__c = assReport.Id;
                            nonCompliance.Name = q.Standard__c;
                            nonCompliance.Standard__c = q.Summary__c;
                            nonCompliance.Non_compliance__c = q.Comments_Action__c;
                            nonCompliancesToCreate.add(nonCompliance);
                            a.Non_Compliances_Created__c = true;
                        }
                    }
                }
                if(!nonCompliancesToCreate.isEmpty()){
                    insert nonCompliancesToCreate;
                }
            }

            
        }
        

    }
}