unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Site__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/recordTypes/Applications.recordType-meta.xml
<RecordType>
    <fullName>Applications</fullName>
    <active>true</active>
    <description>For new applications.</description>
    <label>Applications</label>
</RecordType>

unpackaged/main/default/objects/Application_Line_Item__c/Application_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Application Line Item</label>
    <nameField>
        <displayFormat>APL-{0000}</displayFormat>
        <label>Application Line Item Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application_Line_Item__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Application_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Application_Line_Item__c/fields/Application_Unit__c.field-meta.xml
<CustomField>
    <fullName>Application_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application Unit</label>
    <referenceTo>Application_Unit__c</referenceTo>
    <relationshipLabel>Application Line Items</relationshipLabel>
    <relationshipName>Application_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application_Line_Item__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>List Price Ex Vat</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Application_Line_Item__c/fields/List_Price_Inc_Vat__c.field-meta.xml
<CustomField>
    <fullName>List_Price_Inc_Vat__c</fullName>
    <label>List Price Inc Vat</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Application_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Application Line Items</relationshipLabel>
    <relationshipName>Application_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/Application_Unit__c.object-meta.xml
<CustomObject>
    <label>Application Unit</label>
    <nameField>
        <displayFormat>APUN-{00}</displayFormat>
        <label>APP Unit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application_Unit__c/fields/Animals__c.field-meta.xml
<CustomField>
    <fullName>Animals__c</fullName>
    <formula>TEXT( Unit__r.Animals__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Animals</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Application Units</relationshipLabel>
    <relationshipName>ApplicationUnits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <formula>TEXT(Unit__r.Business__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/fields/Number_of_Animals__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Animals__c</fullName>
    <formula>Unit__r.Number_of_Animals__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Animals</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/fields/Own_Catching__c.field-meta.xml
<CustomField>
    <fullName>Own_Catching__c</fullName>
    <formula>Unit__r.Own_Catching__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Own Catching</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/fields/Own_Transport__c.field-meta.xml
<CustomField>
    <fullName>Own_Transport__c</fullName>
    <formula>Unit__r.Own_Transport__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Own Transport</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/fields/Production__c.field-meta.xml
<CustomField>
    <fullName>Production__c</fullName>
    <formula>TEXT( Unit__r.Production__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Production</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Application Units</relationshipLabel>
    <relationshipName>Application_Units</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Additional_Quantity_Pricing_Component__c.field-meta.xml
<CustomField>
    <fullName>Additional_Quantity_Pricing_Component__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Additional Quantity Pricing Component</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Additional_Quantity_Product__c.field-meta.xml
<CustomField>
    <fullName>Additional_Quantity_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This product is used if the quantity is above the additional quantity threshold.</description>
    <inlineHelpText>This product is used if the quantity is above the additional quantity threshold.</inlineHelpText>
    <label>Additional Quantity Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Parent Products (Additional Quantity Product)</relationshipLabel>
    <relationshipName>Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Animals</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Dynamic_Quantity_Pricing_Component__c.field-meta.xml
<CustomField>
    <fullName>Dynamic_Quantity_Pricing_Component__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dynamic Quantity Pricing Component</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Dynamic_Quantity_Product__c.field-meta.xml
<CustomField>
    <fullName>Dynamic_Quantity_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This product is used if the quantity is above the dynamic quantity threshold.</description>
    <inlineHelpText>This product is used if the quantity is above the dynamic quantity threshold.</inlineHelpText>
    <label>Dynamic Quantity Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Parent Products (Dynamic Quantity Product)</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Pricing_Method__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Method__c</fullName>
    <label>Pricing Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Per Application</fullName>
            </value>
            <value>
                <fullName>Per Site</fullName>
            </value>
            <value>
                <fullName>Dynamic Quantity Price</fullName>
            </value>
            <value>
                <fullName>Additional Quantity Price</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Production__c.field-meta.xml
<CustomField>
    <fullName>Production__c</fullName>
    <label>Production</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Production</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Quantity_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Threshold__c</fullName>
    <label>Quantity Threshold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Unit__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Animals__c.field-meta.xml
<CustomField>
    <fullName>Animals__c</fullName>
    <label>Animals</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Animals</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Number_of_Animals__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Animals__c</fullName>
    <label>Number of Animals</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Own_Catching__c.field-meta.xml
<CustomField>
    <fullName>Own_Catching__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Own Catching</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Own_Transport__c.field-meta.xml
<CustomField>
    <fullName>Own_Transport__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Own Transport</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Production__c.field-meta.xml
<CustomField>
    <fullName>Production__c</fullName>
    <label>Production</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Production</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applying</fullName>
                <default>true</default>
                <label>Applying</label>
            </value>
            <value>
                <fullName>Certified</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Vehicle_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Animals.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Beef Cattle</fullName>
    </customValue>
    <customValue>
        <fullName>Chickens</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy Cattle</fullName>
    </customValue>
    <customValue>
        <fullName>Ducklings</fullName>
    </customValue>
    <customValue>
        <fullName>Ducks</fullName>
    </customValue>
    <customValue>
        <fullName>Laying Hen Chicks</fullName>
    </customValue>
    <customValue>
        <fullName>Laying Hens</fullName>
    </customValue>
    <customValue>
        <fullName>Lumpfish</fullName>
    </customValue>
    <customValue>
        <fullName>Meat Chicken Chicks</fullName>
    </customValue>
    <customValue>
        <fullName>Pigs</fullName>
    </customValue>
    <customValue>
        <fullName>Pullets</fullName>
    </customValue>
    <customValue>
        <fullName>Salmon</fullName>
    </customValue>
    <customValue>
        <fullName>Sheep</fullName>
    </customValue>
    <customValue>
        <fullName>Trout</fullName>
    </customValue>
    <customValue>
        <fullName>Turkey Poults</fullName>
    </customValue>
    <customValue>
        <fullName>Turkeys</fullName>
    </customValue>
    <customValue>
        <fullName>Veal Calves</fullName>
    </customValue>
    <customValue>
        <fullName>Wrasse</fullName>
    </customValue>
    <customValue>
        <fullName>List</fullName>
    </customValue>
    <masterLabel>Animals</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Business.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abattoir</fullName>
    </customValue>
    <customValue>
        <fullName>Catching</fullName>
    </customValue>
    <customValue>
        <fullName>Cleaner Fish</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery</fullName>
    </customValue>
    <customValue>
        <fullName>Haulier</fullName>
    </customValue>
    <customValue>
        <fullName>Producer</fullName>
    </customValue>
    <customValue>
        <fullName>Supply Chain</fullName>
    </customValue>
    <masterLabel>Business</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Production.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abattoir</fullName>
    </customValue>
    <customValue>
        <fullName>Brand/Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Breeding</fullName>
    </customValue>
    <customValue>
        <fullName>Brood</fullName>
    </customValue>
    <customValue>
        <fullName>Calves</fullName>
    </customValue>
    <customValue>
        <fullName>Catching Team</fullName>
    </customValue>
    <customValue>
        <fullName>Cleaner Fish</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Dry Cows</fullName>
    </customValue>
    <customValue>
        <fullName>Finishing</fullName>
    </customValue>
    <customValue>
        <fullName>Flat deck (one-storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Flat deck (two storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Flat deck with Veranda</fullName>
    </customValue>
    <customValue>
        <fullName>Freshwater</fullName>
    </customValue>
    <customValue>
        <fullName>Gilts</fullName>
    </customValue>
    <customValue>
        <fullName>Grazing</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery (On Grower)</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery (Ova)</fullName>
    </customValue>
    <customValue>
        <fullName>Haulier</fullName>
    </customValue>
    <customValue>
        <fullName>Heifers</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-tier (one-storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-tier (two-storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-tier with Veranda</fullName>
    </customValue>
    <customValue>
        <fullName>Packer</fullName>
    </customValue>
    <customValue>
        <fullName>Processor</fullName>
    </customValue>
    <customValue>
        <fullName>Processor/Packer</fullName>
    </customValue>
    <customValue>
        <fullName>Producer</fullName>
    </customValue>
    <customValue>
        <fullName>Rearing</fullName>
    </customValue>
    <customValue>
        <fullName>Retailer</fullName>
    </customValue>
    <customValue>
        <fullName>Breeding to rearing</fullName>
    </customValue>
    <customValue>
        <fullName>Breeding to finishing</fullName>
    </customValue>
    <customValue>
        <fullName>Rearing to finishing</fullName>
    </customValue>
    <masterLabel>Production</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Vehicle_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Helicopter</fullName>
    </customValue>
    <customValue>
        <fullName>Lorry</fullName>
    </customValue>
    <customValue>
        <fullName>Trailer</fullName>
    </customValue>
    <customValue>
        <fullName>Van</fullName>
    </customValue>
    <customValue>
        <fullName>Wellboat</fullName>
    </customValue>
    <customValue>
        <fullName>TBC</fullName>
    </customValue>
    <masterLabel>Vehicle Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/AppUnitHelper.cls
public virtual class AppUnitHelper {

    public static List<Product2> productList;
    public static List<Unit__c> allSiteUnits;
    public static List<Application_Line_Item__c> allExistingLines;
    public static List<PricebookEntry> allPricebookEntires;
    public static List<Application_Unit__c> allApplicationUnits;

    // gets list of all products available for pricing calculation
    public static void getProductList(){
        productList = [
            SELECT 
            Id, 
            Name,
            Business__c,
            Animal__c,
            ProductCode,
            Production__c, 
            IsActive,
            Pricing_Method__c,
            Quantity_Threshold__c,  
            Family,
            Additional_Quantity_Pricing_Component__c,
            Dynamic_Quantity_Pricing_Component__c,
            Additional_Quantity_Product__c,
            Dynamic_Quantity_Product__c,
            Vehicle_Type__c
            FROM   Product2 
            WHERE  IsActive=true
        ];
    }

    // get pricebook entries for pricebook ids passed from application
    public static void getAllPricebookEntries(Set<String> pricebookIds){
        Set<String> productIdSet = new Set<String>();
        for(Product2 p :productList){
            productIdSet.add(p.Id);
        }
        allPricebookEntires = [
            SELECT 
            Id, 
            UnitPrice, 
            Product2Id, 
            Pricebook2Id, 
            IsActive 
            FROM PricebookEntry 
            WHERE 
            IsActive = true 
            AND Pricebook2Id IN :pricebookIds 
            AND Product2Id IN :productIdSet
        ];
    }

    // get price for a product from pricebook
    public static Decimal getPriceForProduct(String productId){
        Decimal price = 0;
        for(PricebookEntry pbe : allPricebookEntires){
            if(pbe.Product2Id == productId){
                price = pbe.UnitPrice;
                break;
            }
        }
        return price;
    }

    // get list of all sites units for the accounts
    public static void getAllSiteUnits(Set<String> siteIds){
        allSiteUnits = [
            SELECT 
            Id,
            Name, 
            Account__c,
            Business__c, 
            Animals__c, 
            Production__c, 
            Own_Transport__c, 
            Own_Catching__c, 
            Number_of_Animals__c,
            Status__c,
            Vehicle_Type__c
            FROM Unit__c 
            WHERE 
            Account__c IN :siteIds
        ];
    }

    // get all existing lines for applications
    public static void getAllExistingLines(Set<String> appIds){
        allExistingLines = [
            SELECT 
            Id,
            Product__c,
            Application__c
            FROM   Application_Line_Item__c
            WHERE  
            Application__c IN :appIds
        ];
    }

    // get all application units for application
    public static void getAllAppUnits(Set<String> appIds){
        allApplicationUnits = [
            SELECT 
            Id,
            Application__c,
            Unit__c,
            Business__c,
            Animals__c,
            Number_of_Animals__c,
            Production__c
            FROM Application_Unit__c
            WHERE
            Application__c =:appIds
        ];
    }

    // get units for the created application units only
    public static Map<Id, Unit__c> getUnitsForCreatedAppUnit(Set<String> unitIds){
        Map<Id, Unit__c> unitMap = new Map<Id, Unit__c>();
        for(Unit__c u: allSiteUnits){
            if(unitIds.contains(u.Id)){
                unitMap.put(u.Id,u);
            }
        }
        return unitMap;
    }

    //find products with business and production
    public static Product2 getProduct(string business, string production){
        Product2 productResult = null;
        for(Product2 p : productList){
            // ensure products returned are not additional quantity pricing component or dynamic quantity pricing component
            if(p.Additional_Quantity_Pricing_Component__c == false && p.Dynamic_Quantity_Pricing_Component__c == false){
                if(p.Business__c == business && p.Production__c.contains(production)){
                    productResult = p;
                }
            }  
        }
        return productResult;
    }
    
    //find products with business, animals and production
    public static Product2 getProduct(string business, string animals, string production, string vehicleType){
        Product2 productResult = null;
        for(Product2 p : productList){
            // ensure products returned are not additional quantity pricing component or dynamic quantity pricing component
            if(p.Additional_Quantity_Pricing_Component__c == false && p.Dynamic_Quantity_Pricing_Component__c == false){
                if(
                    p.Business__c == business && 
                    p.Production__c.contains(production) && 
                    p.Animal__c.contains(animals) &&
                    p.Vehicle_Type__c == vehicleType
                    ){
                        productResult = p;
                }
            }
        }
        return productResult;
    }

    // get additional quantity product
    public static Product2 getAdditionalQuantityProduct(Product2 product){
        Product2 productResult = null;
        for(Product2 p : productList){
            if(p.Id == product.Additional_Quantity_Product__c && p.Additional_Quantity_Pricing_Component__c){
                productResult = p;
            }
        }
        return productResult;
    }

    // get dynamic quantity product
    public static Product2 getDynamicQuantityProduct(Product2 product){
        Product2 productResult = null;
        for(Product2 p : productList){
            if(p.Id == product.Dynamic_Quantity_Product__c && p.Dynamic_Quantity_Pricing_Component__c){
                productResult = p;
            }
        }
        return productResult;
    }

    // check for existing supply chain unit on the site
    public static boolean existingSupplyChainUnit(String siteId, Product2 product, String unitAdded){
        Boolean existingUnit = false;
        for(Unit__c u : allSiteUnits){
            if( 
                u.Business__c == 'Supply Chain' && 
                u.Account__c == siteId && 
                u.Id != unitAdded && 
                u.Status__c == 'Certified' 
            ){
                    existingUnit = true;
            }
        }
        return existingUnit;
    }

    // check for existing units that are price on a per site basis
    public static Boolean existingPerSiteUnit(String siteId, Product2 product, String unitAdded){
        Boolean existingUnit = false;
        for(Unit__c u : allSiteUnits){
            if(
                u.Business__c == product.Business__c &&
                product.Animal__c.contains(u.Animals__c) &&
                product.Production__c.contains(u.Production__c) &&
                u.Account__c == siteId &&
                u.Id != unitAdded &&
                u.Status__c == 'Certified'
            ){
                existingUnit = true;
            }
        }
        return existingUnit;
    }

    // check for existing vehicle, catching 
    public static Boolean existingVehicleOrCatching(String siteId, Product2 product, String unitAdded){
        Boolean existingUnit = false;
        for(Unit__c u : allSiteUnits){
            if(
                u.Business__c == product.Business__c &&
                product.Animal__c.contains(u.Animals__c) &&
                product.Production__c.contains(u.Production__c) &&
                u.Account__c == siteId &&
                u.Id != unitAdded &&
                u.Status__c == 'Certified'
            ){
                existingUnit = true;
            }
        }
        return existingUnit;
    }

    public static Boolean existingLivestockUnit(String siteId, Product2 product, String unitAdded){
        Boolean existingUnit = false;
        for(Unit__c u : allSiteUnits){
            if(
                u.Business__c == product.Business__c &&
                product.Animal__c.contains(u.Animals__c) &&
                product.Production__c.contains(u.Production__c) &&
                u.Account__c == siteId &&
                u.Id != unitAdded &&
                u.Status__c == 'Certified'
            ){
                existingUnit = true;
            }
        }
        return existingUnit;
    }
    public static Decimal existingPoultryUnit(String siteId, Product2 product, String unitAdded){
        Decimal existingUnit = 0;
        for(Unit__c u : allSiteUnits){
            String unitProduction = '';
            if(u.Production__c != null){
                unitProduction = u.Production__c;
            }
            if(
                u.Business__c == product.Business__c &&
                product.Animal__c.contains(u.Animals__c) &&
                product.Production__c.contains(unitProduction) &&
                u.Account__c == siteId &&
                u.Id != unitAdded &&
                u.Status__c == 'Certified'
            ){
                existingUnit = existingUnit + u.Number_Of_Animals__c;
            }
        }
        return existingUnit;
    }
    
    public static Boolean checkExistingLineItem(Id productId, Id appId){
        Boolean existingLineItem = false;
        for(Application_Line_Item__c li : allExistingLines){
            if(
                li.Application__c == appId &&
                li.Product__c == productId
            ){
                existingLineItem = true;
                break;
            }
        }
        return existingLineItem;
    }

    public static boolean checkExistingPigDiscount1(Id appId){
        Boolean existingPigDiscount = false;
        String pigStage1DiscountId = null;
        for(Product2 p : productList){
            if(p.ProductCode == 'PIGSTAGE1DISCOUNT'){
                pigStage1DiscountId = p.Id;
                break;
            }
        }
        if(pigStage1DiscountId != null){
            existingPigDiscount = checkExistingLineItem(pigStage1DiscountId, appId);
        }
        return existingPigDiscount;
    }

    public static boolean checkExistingPigDiscount2(Id appId){
        Boolean existingPigDiscount = false;
        String pigStage2DiscountId = null;
        for(Product2 p : productList){
            if(p.ProductCode == 'PIGSTAGE2DISCOUNT'){
                pigStage2DiscountId = p.Id;
                break;
            }
        }
        if(pigStage2DiscountId != null){
            existingPigDiscount = checkExistingLineItem(pigStage2DiscountId, appId);
        }
        return existingPigDiscount;
    }

    public static Application_Line_Item__c getExistingPigDiscount1LineItem(Id appId){
        String pigStage1DiscountId = null;
        for(Product2 p : productList){
            if(p.ProductCode == 'PIGSTAGE1DISCOUNT'){
                pigStage1DiscountId = p.Id;
                break;
            }
        }
        Application_Line_Item__c existingLineItem = null;
        for(Application_Line_Item__c li : allExistingLines){
            if(
                li.Application__c == appId &&
                li.Product__c == pigStage1DiscountId
            ){
                existingLineItem = li;
                break;
            }
        }
        return existingLineItem;
    }

    public static Application_Line_Item__c getExistingPigDiscount2LineItem(Id appId){
        String pigStage2DiscountId = null;
        for(Product2 p : productList){
            if(p.ProductCode == 'PIGSTAGE2DISCOUNT'){
                pigStage2DiscountId = p.Id;
                break;
            }
        }
        Application_Line_Item__c existingLineItem = null;
        for(Application_Line_Item__c li : allExistingLines){
            if(
                li.Application__c == appId &&
                li.Product__c == pigStage2DiscountId
            ){
                existingLineItem = li;
                break;
            }
        }
        return existingLineItem;
    }

    public static Decimal getTotalAnimalNumbersForSpecies(String species, String applicationId){
        Decimal numAnimals = 0;
        for(Application_Unit__c au : allApplicationUnits){
            if(au.Animals__c == species && au.Application__c == applicationId){
                numAnimals = numAnimals + au.Number_of_Animals__c;
            }
        }
        return numAnimals;
    }

    public static List<Application_Line_Item__c> getExistingPoultryLineItems(Id appId, String species){
        Set<String> poultryProductIds = new Set<String>();
        for(Product2 p : productList){
            if(p.Family == 'Poultry' && p.Animal__c.contains(species)){
                poultryProductIds.add(p.Id);
            }
        }
        List<Application_Line_Item__c> existingLineItems = new List<Application_Line_Item__c>();
        for(Application_Line_Item__c li : allExistingLines){
            if(
                li.Application__c == appId &&
                poultryProductIds.contains(li.Product__c)
            ){
                existingLineItems.add(li);
            }
        }
        return existingLineItems;
    }

    // Create line item from application unit and product passed in
    public static Application_Line_Item__c createLineItem(Id appUnitId, Id appId, Id productId, Double quantity, String headOfficeBillingCountry){
        // get price for product
        Decimal price = getPriceForProduct(productId);
        System.debug('Price => ' + price);
        Application_Line_Item__c appli = new Application_Line_Item__c();
        appli.Application__c = appId;
        appli.Product__c = productId;
        appli.List_Price__c = price;
        appli.Quantity__c = quantity;
        appli.Application_Unit__c = appUnitId;
        if(headOfficeBillingCountry == 'United Kingdom'){
            appli.List_Price_Inc_Vat__c = price + (price * 0.2);
        }else {
            appli.List_Price_Inc_Vat__c = price;
        }
        
        
        return appli;
    }

    public static Application_Line_Item__c createPigStage1DiscountLine(Id appUnitId, Id appId, Double quantity, String headOfficeBillingCountry){
        String pigStage1DiscountId = null;
        for(Product2 p : productList){
            if(p.ProductCode == 'PIGSTAGE1DISCOUNT'){
                pigStage1DiscountId = p.Id;
                break;
            }
        }
        Application_Line_Item__c appli = createLineItem(appUnitId, appId, pigStage1DiscountId, quantity, headOfficeBillingCountry);
        return appli;
    }

    public static Application_Line_Item__c createPigStage2DiscountLine(Id appUnitId, Id appId, Double quantity, String headOfficeBillingCountry){
        String pigStage2DiscountId = null;
        for(Product2 p : productList){
            if(p.ProductCode == 'PIGSTAGE2DISCOUNT'){
                pigStage2DiscountId = p.Id;
                break;
            }
        }
        Application_Line_Item__c appli = createLineItem(appUnitId, appId, pigStage2DiscountId, quantity, headOfficeBillingCountry);
        return appli;
    }

    public static List<Unit__c> getPigBreedingRearingFinishingUnitCount(String siteId){
        Map<String, Unit__c> PigsBreedingRearingFinishing = new Map<String, Unit__c>();
        for(Unit__c u: allSiteUnits){
            if(
                u.Business__c == 'Producer' && 
                u.Animals__c == 'Pigs' && 
                u.Account__c == siteId &&
                u.Status__c == 'Certified' &&
                (
                    u.Production__c == 'Breeding' || 
                    u.Production__c == 'Finishing' || 
                    u.Production__c == 'Rearing'
                )
                ){
                    PigsBreedingRearingFinishing.put(u.Production__c, u);
            }
        }
        return PigsBreedingRearingFinishing.values();
    }

    public static integer getPigBreedingRearingFinishingAppCount(String appId, Set<Id> unitIds){
        Set<String> pigProduction = new Set<String>(); // using set to find unique counts of units with production
        Integer countOfPigsBreedingRearingFinishing = 0;
        for(Application_Unit__c au: allApplicationUnits){
            if(au.Business__c == 'Producer' && au.Animals__c == 'Pigs' && !unitIds.contains(au.Unit__c)){
                if(au.Production__c == 'Breeding' || au.Production__c == 'Finishing' ||  au.Production__c == 'Rearing'){
                    pigProduction.add(au.Production__c);
                }
                if(au.Production__c == 'Breeding to rearing'){
                    pigProduction.add('Breeding');
                    pigProduction.add('Rearing');
                }
                if(au.Production__c == 'Breeding to finishing'){
                    pigProduction.add('Breeding');
                    pigProduction.add('Finishing');
                }
                if(au.Production__c == 'Rearing to finishing'){
                    pigProduction.add('Rearing');
                    pigProduction.add('Finishing');
                }
            }
        }

        for(String s : pigProduction){
            countOfPigsBreedingRearingFinishing++;
        }
        return countOfPigsBreedingRearingFinishing;
    }

}