unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Assessment_Date__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Date__c</fullName>
    <description>Cannot exceed the deadline date; can be updated if rearranged</description>
    <inlineHelpText>The date the site will be assessed</inlineHelpText>
    <label>Assessment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Function: member services select an assessor; system then automatically emails them.</description>
    <inlineHelpText>This field must be populated in order to mark an Additional Visit as complete.</inlineHelpText>
    <label>Allocated Assessor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>You can only select an assessor user to be allocated for this application.</errorMessage>
        <filterItems>
            <field>User.Assessor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>User.Contract_Assessor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Visit_Date__c.field-meta.xml
<CustomField>
    <fullName>Visit_Date__c</fullName>
    <label>Visit Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Visit_Type__c.field-meta.xml
<CustomField>
    <fullName>Visit_Type__c</fullName>
    <inlineHelpText>This field must be populated in order to mark an Additional Visit as complete.</inlineHelpText>
    <label>Visit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Investigation</fullName>
            </value>
            <value>
                <fullName>Sanction</fullName>
            </value>
            <value>
                <fullName>Revisit</fullName>
            </value>
            <value>
                <fullName>Virtual Visit</fullName>
            </value>
            <value>
                <fullName>Monitoring</fullName>
                <isActive>false</isActive>
                <label>Monitoring</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this box is checked, this user will be available to select during the allocation phase of the application/renewals.</description>
    <inlineHelpText>Check this box if the user is an assessor.</inlineHelpText>
    <label>Assessor</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/WOA__c/WOA__c.object-meta.xml
<CustomObject>
    <label>WOA</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>WOA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WOAs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/WOA__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>WOAs</relationshipLabel>
    <relationshipName>WOAs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/WOA__c/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Assessor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>WOAs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WOA__c/fields/CompletingWOA__c.field-meta.xml
<CustomField>
    <fullName>CompletingWOA__c</fullName>
    <description>Are you able to complete a welfare outcome form for this visit?</description>
    <inlineHelpText>Are you able to complete a welfare outcome form for this visit?</inlineHelpText>
    <label>CompletingWOA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WOA__c/fields/FF_Reg_No__c.field-meta.xml
<CustomField>
    <fullName>FF_Reg_No__c</fullName>
    <formula>Application__r.Membership_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FF Reg No</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WOA__c/fields/Form_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Form_Completion_Date__c</fullName>
    <label>WOA Submission Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/WOA__c/fields/Houses__c.field-meta.xml
<CustomField>
    <fullName>Houses__c</fullName>
    <label>Houses</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WOA__c/fields/IsCompleted__c.field-meta.xml
<CustomField>
    <fullName>IsCompleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Submitted</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/WOA__c/fields/Producer__c.field-meta.xml
<CustomField>
    <fullName>Producer__c</fullName>
    <formula>Application__r.Site__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Producer</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WOA__c/fields/Species_Type__c.field-meta.xml
<CustomField>
    <fullName>Species_Type__c</fullName>
    <label>Species Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dairy Cattle</fullName>
            </value>
            <value>
                <fullName>Laying Hen</fullName>
            </value>
            <value>
                <fullName>Pigs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/WOA__c/fields/Visit_Type__c.field-meta.xml
<CustomField>
    <fullName>Visit_Type__c</fullName>
    <label>Visit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RSPCA Assured</fullName>
            </value>
            <value>
                <fullName>RSPCA Monitoring</fullName>
            </value>
            <value>
                <fullName>Freedom Food</fullName>
                <isActive>false</isActive>
                <label>Freedom Food</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/WOAEditController.cls
public without sharing class WOAEditController {

    @AuraEnabled
    public static WOA__c getWOASummaryRecord(String recordId) {
        List<WOA__c> woaList = [SELECT Id, Name, Application__c,Application__r.Assessment_Date__c, FF_Reg_No__c, Form_Completion_Date__c, Houses__c, Producer__c, Species_Type__c, Visit_Date__c, Visit_Type__c, Assessor__c, CompletingWOA__c, IsCompleted__c FROM WOA__c WHERE Id =:recordId];
        return woaList[0];
    }

    @AuraEnabled
    public static List<Assessor> getAssessors(){
        List<Assessor> assessorOptionsList = new List<Assessor>();
        List<User> assessorUsers = [SELECT Id, Name, Assessor__c FROM User WHERE IsActive = true AND Assessor__c = true];
        for(User u : assessorUsers){
            Assessor assessOption = new Assessor();
            assessOption.label = u.Name;
            assessOption.value = u.Id;
            assessorOptionsList.add(assessOption);
        }
        return assessorOptionsList;

    }

    @AuraEnabled
    public static void saveWOASummary(WOA__c woaSummary){
        if(woaSummary != null){
            System.debug('woaSummary => ' + woaSummary);
            update woaSummary;
        }
    }

    public class Assessor {
        @AuraEnabled public String label {get;set;}
        @AuraEnabled public String value {get;set;}
    }
}