unpackaged/main/default/objects/Cows_Housing__c/Cows_Housing__c.object-meta.xml
<CustomObject>
    <label>Cows Housing</label>
    <nameField>
        <displayFormat>CH-{0000}</displayFormat>
        <label>Cows Housing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cows Housings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Cows_Housing__c/fields/Base__c.field-meta.xml
<CustomField>
    <fullName>Base__c</fullName>
    <label>Base</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mats</fullName>
            </value>
            <value>
                <fullName>Mattresses</fullName>
            </value>
            <value>
                <fullName>Deep bedded</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Cows_Housing__c/fields/Base_Other_Text__c.field-meta.xml
<CustomField>
    <fullName>Base_Other_Text__c</fullName>
    <label>Base Other Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Cows_Housing__c/fields/Bedding__c.field-meta.xml
<CustomField>
    <fullName>Bedding__c</fullName>
    <label>Bedding</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Straw</fullName>
            </value>
            <value>
                <fullName>Sawdust</fullName>
            </value>
            <value>
                <fullName>Sand</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Cows_Housing__c/fields/Bedding_Other_Text__c.field-meta.xml
<CustomField>
    <fullName>Bedding_Other_Text__c</fullName>
    <label>Bedding Other Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Cows_Housing__c/fields/Housing_Type__c.field-meta.xml
<CustomField>
    <fullName>Housing_Type__c</fullName>
    <label>Housing Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cubicles</fullName>
            </value>
            <value>
                <fullName>Kennels</fullName>
            </value>
            <value>
                <fullName>Deep litter yar</fullName>
                <label>Deep litter yard</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Cows_Housing__c/fields/WOADairy__c.field-meta.xml
<CustomField>
    <fullName>WOADairy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WOADairy</label>
    <referenceTo>WOADairy__c</referenceTo>
    <relationshipLabel>Cows Housings</relationshipLabel>
    <relationshipName>Cows_Housings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Lameness_Prevalence__c/Lameness_Prevalence__c.object-meta.xml
<CustomObject>
    <label>Lameness Prevalence</label>
    <nameField>
        <displayFormat>LP-{0000}</displayFormat>
        <label>Lameness prevalence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lameness Prevalences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Lameness_Prevalence__c/fields/Date_of_scoring__c.field-meta.xml
<CustomField>
    <fullName>Date_of_scoring__c</fullName>
    <label>Date of scoring</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Lameness_Prevalence__c/fields/No_Of_Score_2_cows__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Score_2_cows__c</fullName>
    <label>No Of Score 2 cows</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lameness_Prevalence__c/fields/No_Of_Score_3_cows__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Score_3_cows__c</fullName>
    <label>No Of Score 3 cows</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lameness_Prevalence__c/fields/Percentage_Of_Score_2_cows__c.field-meta.xml
<CustomField>
    <fullName>Percentage_Of_Score_2_cows__c</fullName>
    <label>% Of Score 2 cows</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Lameness_Prevalence__c/fields/Percentage_Of_Score_3_cows__c.field-meta.xml
<CustomField>
    <fullName>Percentage_Of_Score_3_cows__c</fullName>
    <label>% Of Score 3 cows</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Lameness_Prevalence__c/fields/Total_no_cows_scored__c.field-meta.xml
<CustomField>
    <fullName>Total_no_cows_scored__c</fullName>
    <label>Total no cows scored</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lameness_Prevalence__c/fields/WOADairy__c.field-meta.xml
<CustomField>
    <fullName>WOADairy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WOADairy</label>
    <referenceTo>WOADairy__c</referenceTo>
    <relationshipLabel>Lameness Prevalences</relationshipLabel>
    <relationshipName>Lameness_Prevalences</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Mobility_Scoring__c/Mobility_Scoring__c.object-meta.xml
<CustomObject>
    <label>Mobility Scoring</label>
    <nameField>
        <displayFormat>MS-{0000}</displayFormat>
        <label>Mobility Scoring Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mobility Scorings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Mobility_Scoring__c/fields/How_often__c.field-meta.xml
<CustomField>
    <fullName>How_often__c</fullName>
    <label>How often ?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quaterly</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Mobility_Scoring__c/fields/How_often_Other_Text__c.field-meta.xml
<CustomField>
    <fullName>How_often_Other_Text__c</fullName>
    <label>How often Other Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Mobility_Scoring__c/fields/RoMS__c.field-meta.xml
<CustomField>
    <fullName>RoMS__c</fullName>
    <label>RoMS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Mobility_Scoring__c/fields/Which_cows__c.field-meta.xml
<CustomField>
    <fullName>Which_cows__c</fullName>
    <label>Which cows?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All milking cows (incl.those in the hospital pen)</fullName>
            </value>
            <value>
                <fullName>All milking and dry cows (incl. the hospital pen)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Mobility_Scoring__c/fields/Which_cows_Other_Text__c.field-meta.xml
<CustomField>
    <fullName>Which_cows_Other_Text__c</fullName>
    <label>Which cows Other Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Mobility_Scoring__c/fields/Who_scores__c.field-meta.xml
<CustomField>
    <fullName>Who_scores__c</fullName>
    <label>Who scores</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Veterinary practice</fullName>
            </value>
            <value>
                <fullName>Farm staff</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Mobility_Scoring__c/fields/Who_scores_Other_Text__c.field-meta.xml
<CustomField>
    <fullName>Who_scores_Other_Text__c</fullName>
    <label>Who scores Other Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Mobility_Scoring__c/fields/WOADairy__c.field-meta.xml
<CustomField>
    <fullName>WOADairy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WOADairy</label>
    <referenceTo>WOADairy__c</referenceTo>
    <relationshipLabel>Mobility Scorings</relationshipLabel>
    <relationshipName>Mobility_Scorings</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/WOA__c/WOA__c.object-meta.xml
<CustomObject>
    <label>WOA</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>WOA Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WOAs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/WOADairy__c/WOADairy__c.object-meta.xml
<CustomObject>
    <label>WOADairy</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>WOADairyID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WOAs Dairy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/WOADairy__c/fields/WOA__c.field-meta.xml
<CustomField>
    <fullName>WOA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WOA</label>
    <referenceTo>WOA__c</referenceTo>
    <relationshipLabel>WOAs Dairy</relationshipLabel>
    <relationshipName>WOAs_Dairy</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/WOADairyController.cls
public class WOADairyController {
  @AuraEnabled
  public static WOADairy__c getWOADairy(String recordId) {
    // Get the Map of Schema of WOADairy__c SObject
    Map<String, Schema.SObjectField> fieldMap = WOADairy__c.sObjectType.getDescribe()
      .fields.getMap();

    // Get all of the fields on the object
    Set<String> setFieldNames = fieldMap.keySet();
    list<String> lstFieldNames = new List<String>(setFieldNames);

    // Dynamic Query String.
    List<WOADairy__c> dairyList = Database.query(
      'SELECT ' +
      String.join(lstFieldNames, ',') +
      ' FROM WOADairy__c WHERE WOA__c =:recordId'
    );

    WOADairy__c dairyWoa = new WOADairy__c(WOA__c = recordId);
    if (!dairyList.isEmpty()) {
      dairyWoa = dairyList[0];
    }
    return dairyWoa;
  }

  @AuraEnabled
  public static void saveWOADairy(
    WOADairy__c woaDairy,
    String cowHousing,
    List<String> deletedCHRecords,
    String mobilityScoring,
    List<String> deletedMSRecords,
    String lamenessPrevalence
  ) {
    if (woaDairy != null) {
      WOADairy__c woaDairyRecord = woaDairy;
      if (woaDairyRecord.Id == null) {
        insert woaDairyRecord;
      } else {
        update woaDairyRecord;
      }
      List<Cows_Housing__c> cowHousingList = (List<Cows_Housing__c>) JSON.deserialize(
        cowHousing,
        List<Cows_Housing__c>.class
      );
      if (cowHousingList != null && cowHousingList.size() > 0) {
        for (Cows_Housing__c ch : cowHousingList) {
          ch.WOADairy__c = woaDairyRecord.Id;
        }
        upsert cowHousingList;
      }
      if (deletedCHRecords != null && deletedCHRecords.size() > 0) {
        cowHousingList = new List<Cows_Housing__c>();
        for (String deletedId : deletedCHRecords) {
          Cows_Housing__c ch = new Cows_Housing__c(Id = deletedId);
          cowHousingList.add(ch);
        }
        delete cowHousingList;
      }
      List<Mobility_Scoring__c> mobilityScoringList = (List<Mobility_Scoring__c>) JSON.deserialize(
        mobilityScoring,
        List<Mobility_Scoring__c>.class
      );
      if (mobilityScoringList != null && mobilityScoringList.size() > 0) {
        for (Mobility_Scoring__c ms : mobilityScoringList) {
          ms.WOADairy__c = woaDairyRecord.Id;
        }
        upsert mobilityScoringList;
      }
      if (deletedMSRecords != null && deletedMSRecords.size() > 0) {
        mobilityScoringList = new List<Mobility_Scoring__c>();
        for (String deletedId : deletedMSRecords) {
          Mobility_Scoring__c ms = new Mobility_Scoring__c(Id = deletedId);
          mobilityScoringList.add(ms);
        }
        delete mobilityScoringList;
      }
      List<Lameness_Prevalence__c> Lameness_PrevalenceRecords = (List<Lameness_Prevalence__c>) JSON.deserialize(
        lamenessPrevalence,
        List<Lameness_Prevalence__c>.class
      );
      if (
        Lameness_PrevalenceRecords != null &&
        Lameness_PrevalenceRecords.size() > 0
      ) {
        for (Lameness_Prevalence__c lp : Lameness_PrevalenceRecords) {
          lp.WOADairy__c = woaDairyRecord.Id;
        }
        upsert Lameness_PrevalenceRecords;
      }
    }
  }
  @AuraEnabled
  public static string getCowHousing(String woaDairyId, String recordTypeName) {
    try {
      List<Cows_Housing__c> cowHousingList = [
        SELECT
          Id,
          Housing_Type__c,
          Base__c,
          Base_Other_Text__c,
          Bedding__c,
          Bedding_Other_Text__c
        FROM Cows_Housing__c
        WHERE
          WOADairy__c = :woaDairyId
          AND RecordType.DeveloperName = :recordTypeName
      ];
      return JSON.serialize(cowHousingList);
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
  @AuraEnabled
  public static string getMobilityScoring(String woaDairyId) {
    try {
      List<Mobility_Scoring__c> mobilityScoring = [
        SELECT
          Id,
          How_often__c,
          How_often_Other_Text__c,
          RoMS__c,
          Which_cows_Other_Text__c,
          Which_cows__c,
          Who_scores__c,
          Who_scores_Other_Text__c
        FROM Mobility_Scoring__c
        WHERE WOADairy__c = :woaDairyId
      ];
      return JSON.serialize(mobilityScoring);
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
  @AuraEnabled
  public static string getLamenessPrevalence(String woaDairyId) {
    try {
      List<Lameness_Prevalence__c> lamenessPrevalence = [
        SELECT
          Id,
          Percentage_Of_Score_2_cows__c,
          Percentage_Of_Score_3_cows__c,
          Date_of_scoring__c,
          No_Of_Score_2_cows__c,
          No_Of_Score_3_cows__c,
          Total_no_cows_scored__c
        FROM Lameness_Prevalence__c
        WHERE WOADairy__c = :woaDairyId
      ];
      return JSON.serialize(lamenessPrevalence);
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}