unpackaged/main/default/objects/Checklist_Template__c/Checklist_Template__c.object-meta.xml
<CustomObject>
    <label>Checklist Template</label>
    <nameField>
        <label>Checklist Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklist Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Checklist_Template_Section__c/Checklist_Template_Section__c.object-meta.xml
<CustomObject>
    <label>Checklist Template Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklist Template Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Checklist_Template_Section__c/fields/Checklist_Template__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Template__c</fullName>
    <label>Checklist Template</label>
    <referenceTo>Checklist_Template__c</referenceTo>
    <relationshipLabel>Checklist Template Sections</relationshipLabel>
    <relationshipName>Checklist_Template_Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Checklist_Template_Standard__c/Checklist_Template_Standard__c.object-meta.xml
<CustomObject>
    <label>Checklist Template Standard</label>
    <nameField>
        <label>Standard Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklist Template Standards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Checklist_Template_Standard__c/fields/Checklist_Template__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Template__c</fullName>
    <label>Checklist Template</label>
    <referenceTo>Checklist_Template__c</referenceTo>
    <relationshipName>Checklist_Standards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Checklist_Template_Standard__c/fields/Checklist_Template_Section__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Template_Section__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Checklist Template Section</label>
    <referenceTo>Checklist_Template_Section__c</referenceTo>
    <relationshipName>Checklist_Standards</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Checklist_Template_Standard__c/fields/Checklist_Template_Subsection__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Template_Subsection__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Checklist Template Subsection</label>
    <referenceTo>Checklist_Template_Subsection__c</referenceTo>
    <relationshipName>Checklist_Standards</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Checklist_Template_Standard__c/fields/ContentVersion_URL__c.field-meta.xml
<CustomField>
    <fullName>ContentVersion_URL__c</fullName>
    <label>ContentVersion URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Checklist_Template_Subsection__c/Checklist_Template_Subsection__c.object-meta.xml
<CustomObject>
    <label>Checklist Template Subsection</label>
    <nameField>
        <label>Subsection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklist Template Subsections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Checklist_Template_Subsection__c/fields/Checklist_Template_Section__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Template_Section__c</fullName>
    <label>Checklist Template Section</label>
    <referenceTo>Checklist_Template_Section__c</referenceTo>
    <relationshipLabel>Checklist Template Subsections</relationshipLabel>
    <relationshipName>Checklist_Template_Subsections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/ContentDocumentLinkTriggerHandlerTest.cls
@isTest
public class ContentDocumentLinkTriggerHandlerTest {

    @testSetup static void setup() {
        // Create Checklist Template Standard
        FObject ctsFobject = new FObject('Checklist_Template_Standard__c', 1);
        ctsFobject.insertRecords(true);
    }

    @isTest
    static void insertImageTest(){
        // Get checklist template standard
        List<Checklist_Template_Standard__c> ctsList = [SELECT Id, Checklist_Template__c, Checklist_Template_Section__c, Checklist_Template_Subsection__c, ContentVersion_URL__c FROM Checklist_Template_Standard__c];

        Test.startTest();
        // Insert content version of the image
        ContentVersion contentVersion = new ContentVersion(
            Title = 'TestImage',
            PathOnClient = 'TestImage.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        insert contentVersion;
        
        // Get content document
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        
        //create ContentDocumentLink for checklist template standard record 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = ctsList[0].id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        insert cdl;
        Test.stopTest();
    }
}