unpackaged/main/default/objects/Account/fields/Accounts_Email__c.field-meta.xml
<CustomField>
    <fullName>Accounts_Email__c</fullName>
    <label>Accounts Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is an active account.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Company_Industry__c.field-meta.xml
<CustomField>
    <fullName>Company_Industry__c</fullName>
    <description>Custom Industry muti picklist field for RSPCA Assured members as companies can have more than one industry.</description>
    <label>Company Industry</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company_Industry</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Head_Office_Number__c.field-meta.xml
<CustomField>
    <fullName>Head_Office_Number__c</fullName>
    <inlineHelpText>The first four digits of the full membership number that represents the group</inlineHelpText>
    <label>Head Office Membership Number</label>
    <length>4</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Primary Account(DoNotUse)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Site_Number__c.field-meta.xml
<CustomField>
    <fullName>Site_Number__c</fullName>
    <inlineHelpText>4 digit membership number for site.</inlineHelpText>
    <label>Site Number</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Membership_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Head_Office.recordType-meta.xml
<RecordType>
    <fullName>Head_Office</fullName>
    <active>true</active>
    <description>An Account representing the head office.</description>
    <label>Head Office</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <description>An Account representing a site.</description>
    <label>Site</label>
</RecordType>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Accounts_Email__c.field-meta.xml
<CustomField>
    <fullName>Accounts_Email__c</fullName>
    <formula>Head_Office__r.Accounts_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Accounts Email</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Applicant_Contact__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Application_Approved_By_Certifier__c.field-meta.xml
<CustomField>
    <fullName>Application_Approved_By_Certifier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Certification Review - was the application/renewal complete, correct and paid?</inlineHelpText>
    <label>Application Approved By (Certifier)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Applications2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Application_Approved_By_Office__c.field-meta.xml
<CustomField>
    <fullName>Application_Approved_By_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Administrative review</description>
    <inlineHelpText>Administrative Review - Was the application/renewal complete, correct and paid?</inlineHelpText>
    <label>Application Approved By (Office)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Applications1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Application_Type__c</fullName>
    <label>Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Existing_Member__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Revisit</fullName>
            </value>
            <value>
                <fullName>Levy</fullName>
            </value>
            <value>
                <fullName>Merchandise</fullName>
            </value>
            <value>
                <fullName>Promotion/Partnership</fullName>
            </value>
            <value>
                <fullName>Consultancy</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Approved_for_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Approved_for_Renewal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Approved for Renewal (Certifier)</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Assessment_Approved_By_Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Approved_By_Assessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Technical review - are you satisfied you have completed and submitted all applicable documentation (see documentation below)?</inlineHelpText>
    <label>Assessment Approved By (Assessor)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Applications4</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Assessment_Approved_By_Certifier__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Approved_By_Certifier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Certification review - are you satisfied the assessor has correctly completed and submitted all applicable documentation (see documentation below)?&#39;</inlineHelpText>
    <label>Assessment Approved By (Certifier)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Applications5</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Assessment_Approved_By_Office__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Approved_By_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Administrative review - has the assessor completed and submitted all applicable documentation (see documentation below)?</inlineHelpText>
    <label>Assessment Approved By (Office)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Applications3</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Function: member services select an assessor; system then automatically emails them.</description>
    <inlineHelpText>This field must be populated in order to mark an Additional Visit as complete.</inlineHelpText>
    <label>Allocated Assessor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>You can only select an assessor user to be allocated for this application.</errorMessage>
        <filterItems>
            <field>User.Assessor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>User.Contract_Assessor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Date_Certified__c.field-meta.xml
<CustomField>
    <fullName>Date_Certified__c</fullName>
    <label>Date Certified</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Evidence_Approved_By_Assessor__c.field-meta.xml
<CustomField>
    <fullName>Evidence_Approved_By_Assessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Technical review - are you satisfied with the evidence the member has submitted?</inlineHelpText>
    <label>Evidence Approved By (Assessor)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Applications7</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Evidence_Approved_By_Certifier__c.field-meta.xml
<CustomField>
    <fullName>Evidence_Approved_By_Certifier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Certification review - are you satisfied with the evidence the member has submitted? If not, please complete the relevant rejection fields above.</inlineHelpText>
    <label>Evidence Approved By (Certifier)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Applications8</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Evidence_Approved_By_Office__c.field-meta.xml
<CustomField>
    <fullName>Evidence_Approved_By_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Administrative review - has the member submitted all corrective evidence?</inlineHelpText>
    <label>Evidence Approved By (Office)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Applications6</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Existing_Member__c.field-meta.xml
<CustomField>
    <fullName>Existing_Member__c</fullName>
    <label>Existing Member?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Head_Office__c.field-meta.xml
<CustomField>
    <fullName>Head_Office__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Head Office</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Head Office</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Paid__c.field-meta.xml
<CustomField>
    <fullName>Paid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Paid</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>ApplicationSite</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>Stage field for new applications for new site, update, or transfers. This field is used for the application record type.</description>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Application</fullName>
                <default>true</default>
                <label>Application</label>
            </value>
            <value>
                <fullName>Allocation</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Schedule</fullName>
            </value>
            <value>
                <fullName>Visit</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Site__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/recordTypes/Applications.recordType-meta.xml
<RecordType>
    <fullName>Applications</fullName>
    <active>true</active>
    <description>For new applications.</description>
    <label>Applications</label>
</RecordType>

unpackaged/main/default/objects/Application__c/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <description>For renewal applications</description>
    <label>Renewal</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <formula>IF(Id = Account.Primary_Contact__r.Id , true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates that this contact is the primary contact for the account that it is affiliated with.</inlineHelpText>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this box is checked, this user will be available to select during the allocation phase of the application/renewals.</description>
    <inlineHelpText>Check this box if the user is an assessor.</inlineHelpText>
    <label>Assessor</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/globalValueSets/Company_Industry.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fish</fullName>
    </customValue>
    <customValue>
        <fullName>Livestock</fullName>
    </customValue>
    <customValue>
        <fullName>Poultry</fullName>
    </customValue>
    <customValue>
        <fullName>Supply Chain</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Company Industry</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Membership_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ADDITION</fullName>
    </customValue>
    <customValue>
        <fullName>ARCHIVED</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC5R</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC7R</fullName>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
    </customValue>
    <customValue>
        <fullName>CONPASS</fullName>
    </customValue>
    <customValue>
        <fullName>ENQUIRY</fullName>
        <default>true</default>
        <label>ENQUIRY</label>
    </customValue>
    <customValue>
        <fullName>EVIDENCE</fullName>
    </customValue>
    <customValue>
        <fullName>FAILED</fullName>
    </customValue>
    <customValue>
        <fullName>FALLOW</fullName>
    </customValue>
    <customValue>
        <fullName>LAPSED</fullName>
    </customValue>
    <customValue>
        <fullName>MEMBER</fullName>
    </customValue>
    <customValue>
        <fullName>MONREQ</fullName>
    </customValue>
    <customValue>
        <fullName>NEW</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2R</fullName>
    </customValue>
    <customValue>
        <fullName>NEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>NONFR</fullName>
    </customValue>
    <customValue>
        <fullName>NOTINSCHEME</fullName>
    </customValue>
    <customValue>
        <fullName>PASSED</fullName>
    </customValue>
    <customValue>
        <fullName>PREPANEL</fullName>
    </customValue>
    <customValue>
        <fullName>REINSTATE</fullName>
    </customValue>
    <customValue>
        <fullName>RENEW/REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWA</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWALINP</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWR</fullName>
    </customValue>
    <customValue>
        <fullName>REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>SUSPENDED</fullName>
    </customValue>
    <masterLabel>Membership Status</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/RenewalApplicationReminderTest.cls
@isTest
public class RenewalApplicationReminderTest {
    /*
    @testSetup static void testSetup() {
        Id headOfficeRecordType = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Head_Office').getRecordTypeId();
        Id siteRecordType = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Site').getRecordTypeId();
        Id applicationsRecordType = Schema.SObjectType.Application__c.getRecordTypeInfosByDeveloperName().get('Applications').getRecordTypeId();
        Account headOffice = new Account();
        headOffice.Name = 'head Office';
        headOffice.Status__c = 'Member';
        headOffice.Head_Office_Number__c = '0001';
        headOffice.RecordTypeId = headOfficeRecordType;
        headOffice.Active__c = true;
        headOffice.Company_Industry__c = 'Poultry';
        headOffice.Accounts_Email__c = 'accounts.email@test.com';
        
        insert headOffice;
        
        Account site = new Account();
        site.Name = 'head Office';
        site.Status__c = 'Member';
        site.Site_Number__c = '0001';
        site.RecordTypeId = siteRecordType;
        site.Active__c = true;
        site.Company_Industry__c = 'Poultry';
        
        insert site;
        
        Contact con = new Contact();
        con.FirstName = 'first';
        con.LastName = 'last';
        con.Email = 'test@test.com';
        con.AccountId = site.Id;
        
        insert con;
        
        site.Primary_Contact__c = con.Id;
        update site;
        Profile p = [SELECT Id FROM Profile WHERE Name='Assessors'];
        User u = new User(Alias = 'standt', Email='Assessors@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='Assessors432432pquvndddfsd@testorg.com', Assessor__c = true);
        insert u;
        
        Application__c app = new Application__c();
        app.Site__c = site.Id;
        app.Head_Office__c = headOffice.Id;
        app.RecordTypeId = applicationsRecordType;
        app.Existing_Member__c = 'No';
        app.Application_Type__c = 'New';
        app.Stage__C = 'Certification';
        app.Applicant_Contact__c = con.Id;
        app.Date_Certified__c = Date.today();
        app.Paid__c = true;
        app.Assessment_Approved_By_Assessor__c = u.Id;
        app.Assessment_Approved_By_Certifier__c = u.Id;
        app.Assessment_Approved_By_Office__c = u.Id;
        app.Application_Approved_By_Office__c = u.Id;
        app.Application_Approved_By_Certifier__c = u.Id;
        app.Evidence_Approved_By_Assessor__c = u.Id;
        app.Evidence_Approved_By_Certifier__c = u.Id;
        app.Evidence_Approved_By_Office__c = u.Id;
        app.Approved_for_Renewal__c = true;
        
        insert app;
        
        
        
        site.Membership_Expiry_Date__c = Date.today() +70; // 2 months and 14 days so that renewal is 2 months behind the Membership expiry date
        update site;
        
        
        
    }

    @isTest
    public static void renewalApplicationReminder6Weeks(){
        Test.startTest();        
        List<Application__c> apps = [SELECT Id, Site__c, Site__r.Status__c, Applicant_Contact__c, Membership_Expiry_Date__c, Stage__c, Renewal_Stage__c, Date_Certified__c FROM Application__c];
        RenewalApplicationReminder6Weeks job = new RenewalApplicationReminder6Weeks();
        job.execute(null);
        Test.stopTest();
    }
    @isTest
    public static void renewalApplicationReminder2Weeks(){
        Test.startTest();        
        List<Application__c> apps = [SELECT Id, Site__c, Site__r.Status__c, Applicant_Contact__c, Membership_Expiry_Date__c, Stage__c, Renewal_Stage__c, Date_Certified__c FROM Application__c];
        RenewalApplicationReminder2Weeks job = new RenewalApplicationReminder2Weeks();
        job.execute(null);
        Test.stopTest();
    }*/
}