unpackaged/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is an active account.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Generate_Head_Office_Number__c.field-meta.xml
<CustomField>
    <fullName>Generate_Head_Office_Number__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When this checkbox is ticked (automated process), and the head office number field is empty, a new head office number will be generated.</description>
    <label>Generate Head Office Number</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Generate_Site_Number__c.field-meta.xml
<CustomField>
    <fullName>Generate_Site_Number__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When this checkbox is ticked (automated process), and the site number field is empty, a new site number will be generated.</description>
    <label>Generate Site Number</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Head_Office_Number__c.field-meta.xml
<CustomField>
    <fullName>Head_Office_Number__c</fullName>
    <inlineHelpText>The first four digits of the full membership number that represents the group</inlineHelpText>
    <label>Head Office Membership Number</label>
    <length>4</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Membership_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Membership_Expiry_Date__c</fullName>
    <inlineHelpText>Membership Expiry Date is 1 year after the Certificate Issue Date by Default. However if common renewal date is used, then Membership Expiry Date reflects when the sites will need to renew by from a group level.</inlineHelpText>
    <label>Membership Expiry Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Previous_Assessor__c.field-meta.xml
<CustomField>
    <fullName>Previous_Assessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Previous Assessor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Assessor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Previous_Membership__c.field-meta.xml
<CustomField>
    <fullName>Previous_Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Previous Membership</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transferred Memberships</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Primary Account(DoNotUse)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Site_Number__c.field-meta.xml
<CustomField>
    <fullName>Site_Number__c</fullName>
    <inlineHelpText>4 digit membership number for site.</inlineHelpText>
    <label>Site Number</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Membership_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Transferred_Account__c.field-meta.xml
<CustomField>
    <fullName>Transferred_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox is ticked from the transfer process if the account is currently historic due transfers.</description>
    <inlineHelpText>Checkbox is ticked from the transfer process if the account is currently historic due transfers.</inlineHelpText>
    <label>Transferred Account</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Head_Office.recordType-meta.xml
<RecordType>
    <fullName>Head_Office</fullName>
    <active>true</active>
    <description>An Account representing the head office.</description>
    <label>Head Office</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <description>An Account representing a site.</description>
    <label>Site</label>
</RecordType>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Primary Contact on the related Site Record, populated by a flow</description>
    <inlineHelpText>This field must be populated in order to mark an Additional Visit as complete.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications (Contact)</relationshipLabel>
    <relationshipName>Applications2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Membership_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Membership_Expiry_Date__c</fullName>
    <formula>Site__r.Membership_Expiry_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership Expiry Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Site__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <description>For renewal applications</description>
    <label>Renewal</label>
</RecordType>

unpackaged/main/default/objects/Application_Contact_Role__c/Application_Contact_Role__c.object-meta.xml
<CustomObject>
    <label>Application Contact</label>
    <nameField>
        <displayFormat>CR-{00}</displayFormat>
        <label>Role No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application_Contact_Role__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipName>Application_Contact_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Application_Contact_Role__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Application_Contact_Roles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/Application_Unit__c.object-meta.xml
<CustomObject>
    <label>Application Unit</label>
    <nameField>
        <displayFormat>APUN-{00}</displayFormat>
        <label>APP Unit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application_Unit__c/fields/Animals__c.field-meta.xml
<CustomField>
    <fullName>Animals__c</fullName>
    <formula>TEXT( Unit__r.Animals__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Animals</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Application Units</relationshipLabel>
    <relationshipName>ApplicationUnits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <formula>TEXT(Unit__r.Business__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/fields/Number_of_Animals__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Animals__c</fullName>
    <formula>Unit__r.Number_of_Animals__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Animals</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/fields/Own_Catching__c.field-meta.xml
<CustomField>
    <fullName>Own_Catching__c</fullName>
    <formula>Unit__r.Own_Catching__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Own Catching</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/fields/Own_Transport__c.field-meta.xml
<CustomField>
    <fullName>Own_Transport__c</fullName>
    <formula>Unit__r.Own_Transport__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Own Transport</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Application Units</relationshipLabel>
    <relationshipName>Application_Units</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/asp04__Payment__c/asp04__Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PAY-{000000000}</displayFormat>
        <label>Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/asp04__Payment__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <formula>IF(Id = Account.Primary_Contact__r.Id , true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates that this contact is the primary contact for the account that it is affiliated with.</inlineHelpText>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Unit__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Animals__c.field-meta.xml
<CustomField>
    <fullName>Animals__c</fullName>
    <label>Animals</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Animals</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Chassis_Number__c.field-meta.xml
<CustomField>
    <fullName>Chassis_Number__c</fullName>
    <label>Chassis Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Ingredients__c.field-meta.xml
<CustomField>
    <fullName>Ingredients__c</fullName>
    <label>Ingredients</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Ingredients</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Number_of_Animals__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Animals__c</fullName>
    <label>Number of Animals</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Order_Sizes__c.field-meta.xml
<CustomField>
    <fullName>Order_Sizes__c</fullName>
    <label>Order Sizes</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Small</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Own_Catching__c.field-meta.xml
<CustomField>
    <fullName>Own_Catching__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Own Catching</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applying</fullName>
                <default>true</default>
                <label>Applying</label>
            </value>
            <value>
                <fullName>Certified</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Animals.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Beef Cattle</fullName>
    </customValue>
    <customValue>
        <fullName>Chickens</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy Cattle</fullName>
    </customValue>
    <customValue>
        <fullName>Ducklings</fullName>
    </customValue>
    <customValue>
        <fullName>Ducks</fullName>
    </customValue>
    <customValue>
        <fullName>Laying Hen Chicks</fullName>
    </customValue>
    <customValue>
        <fullName>Laying Hens</fullName>
    </customValue>
    <customValue>
        <fullName>Lumpfish</fullName>
    </customValue>
    <customValue>
        <fullName>Meat Chicken Chicks</fullName>
    </customValue>
    <customValue>
        <fullName>Pigs</fullName>
    </customValue>
    <customValue>
        <fullName>Pullets</fullName>
    </customValue>
    <customValue>
        <fullName>Salmon</fullName>
    </customValue>
    <customValue>
        <fullName>Sheep</fullName>
    </customValue>
    <customValue>
        <fullName>Trout</fullName>
    </customValue>
    <customValue>
        <fullName>Turkey Poults</fullName>
    </customValue>
    <customValue>
        <fullName>Turkeys</fullName>
    </customValue>
    <customValue>
        <fullName>Veal Calves</fullName>
    </customValue>
    <customValue>
        <fullName>Wrasse</fullName>
    </customValue>
    <customValue>
        <fullName>List</fullName>
    </customValue>
    <masterLabel>Animals</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Business.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abattoir</fullName>
    </customValue>
    <customValue>
        <fullName>Catching</fullName>
    </customValue>
    <customValue>
        <fullName>Cleaner Fish</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery</fullName>
    </customValue>
    <customValue>
        <fullName>Haulier</fullName>
    </customValue>
    <customValue>
        <fullName>Producer</fullName>
    </customValue>
    <customValue>
        <fullName>Supply Chain</fullName>
    </customValue>
    <masterLabel>Business</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Ingredients.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Beef</fullName>
    </customValue>
    <customValue>
        <fullName>Chicken</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Duck</fullName>
    </customValue>
    <customValue>
        <fullName>Eggs</fullName>
    </customValue>
    <customValue>
        <fullName>Lamb</fullName>
    </customValue>
    <customValue>
        <fullName>Pork</fullName>
    </customValue>
    <customValue>
        <fullName>Salmon</fullName>
    </customValue>
    <customValue>
        <fullName>Trout</fullName>
    </customValue>
    <customValue>
        <fullName>Turkey</fullName>
    </customValue>
    <customValue>
        <fullName>Veal</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Ingredients</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Membership_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ADDITION</fullName>
    </customValue>
    <customValue>
        <fullName>ARCHIVED</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC5R</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC7R</fullName>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
    </customValue>
    <customValue>
        <fullName>CONPASS</fullName>
    </customValue>
    <customValue>
        <fullName>ENQUIRY</fullName>
        <default>true</default>
        <label>ENQUIRY</label>
    </customValue>
    <customValue>
        <fullName>EVIDENCE</fullName>
    </customValue>
    <customValue>
        <fullName>FAILED</fullName>
    </customValue>
    <customValue>
        <fullName>FALLOW</fullName>
    </customValue>
    <customValue>
        <fullName>LAPSED</fullName>
    </customValue>
    <customValue>
        <fullName>MEMBER</fullName>
    </customValue>
    <customValue>
        <fullName>MONREQ</fullName>
    </customValue>
    <customValue>
        <fullName>NEW</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2R</fullName>
    </customValue>
    <customValue>
        <fullName>NEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>NONFR</fullName>
    </customValue>
    <customValue>
        <fullName>NOTINSCHEME</fullName>
    </customValue>
    <customValue>
        <fullName>PASSED</fullName>
    </customValue>
    <customValue>
        <fullName>PREPANEL</fullName>
    </customValue>
    <customValue>
        <fullName>REINSTATE</fullName>
    </customValue>
    <customValue>
        <fullName>RENEW/REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWA</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWALINP</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWR</fullName>
    </customValue>
    <customValue>
        <fullName>REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>SUSPENDED</fullName>
    </customValue>
    <masterLabel>Membership Status</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/TransferController.cls
global without sharing class TransferController {
	@AuraEnabled
    public static Account getHeadOffice(String accId, String headOfficeNumber){
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Head_Office').getRecordTypeId();
        Account acc = [SELECT Id, Name, Head_Office_Number__c FROM Account WHERE Head_Office_Number__c =:headOfficeNumber AND Id !=:accId AND RecordTypeId=:recordTypeId LIMIT 1];
        System.debug(acc);
        return acc;
    }

    // This method gets the Contact from the community users record or from the Site's primary contact
    @AuraEnabled
    public static Contact fetchCustomerContact(String siteId){
        Contact con = new Contact();
        String customerId = [SELECT Id, ContactId FROM User WHERE Id =: UserInfo.getUserId()].ContactId;
        Account site = [SELECT Id, Primary_Contact__c FROM Account WHERE Id=:siteId];

        if(customerId != null){
            con = [SELECT Id, FirstName, LastName FROM Contact WHERE Id =: customerId];
            return con;
        } else if(site != null){
            con = [SELECT Id, FirstName, LastName FROM Contact WHERE Id =: site.Primary_contact__c];
            return con;
        }
        return null;

    }

    // Create Transfer Application
    @AuraEnabled
    public static SObject createTransferApplication(Application__c app, String transferType, Account transferToAccount, Account oldSite){
        System.debug('Application ==> ' + app);
        System.debug('Transfer Type ==>' + transferType);
        System.debug('Transfer to Group Account ==> ' + transferToAccount);
        System.debug('Old Site Account ==> ' + oldSite);

        
        List<Unit__c> unitToCreate = new List<Unit__c>();
        List<Application_Unit__c> apuToCreate = new List<Application_Unit__c>();

        Id siteRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Site').getRecordTypeId();
        Id headOfficeRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Head_Office').getRecordTypeId();
        Id renewalAppRecordTypeId = Schema.SObjectType.Application__c.getRecordTypeInfosByDeveloperName().get('Renewal').getRecordTypeId();

        if(app != null){
            // Create a new Account with all of the fields from the old account
            Account newSite = oldSite.clone(false,false,false,false);
            newSite.Active__c = false;
            newSite.Status__c = null; 
            newSite.Previous_Membership__c = oldSite.Id;
            newSite.Site_Number__c = null;
            newSite.Generate_Site_Number__c = false;
            newSite.Membership_Expiry_Date__c = null;
            newSite.Head_Office_Number__c = null;
            newSite.Generate_Head_Office_Number__c = false;
            newSite.RecordTypeId = siteRecordTypeId;

            if(transferType == 'Group' && transferToAccount != null){
                newSite.ParentId = transferToAccount.Id;
            }else{
                //Create new head office account when transfer type is independant
                Account newHeadOffice = oldSite.clone(false,false,false,false);
                newHeadOffice.Active__c = false;
                newHeadOffice.Status__c = null;
                newHeadOffice.Previous_Membership__c = null;
                newHeadOffice.Site_Number__c = null;
                newHeadOffice.Generate_Site_Number__c = false;
                newHeadOffice.Membership_Expiry_Date__c = null;
                newHeadOffice.Head_Office_Number__c = null;
                newHeadOffice.Generate_Head_Office_Number__c = false;
                newHeadOffice.Previous_Assessor__c = null;
                newHeadOffice.RecordTypeId = headOfficeRecordTypeId;
                newHeadOffice.ParentId = null;
                
                insert newHeadOffice;

                newSite.ParentId = newHeadOffice.Id;    
            }
            insert newSite;

            //Disable old site account
            oldSite.Active__c = false;
            oldSite.Status__c = 'CANCELLED';
            oldsite.Transferred_Account__c = true;

            update oldSite;

            // Copy over the units from the old site
            for(Unit__c u : [SELECT Id, Account__c, Animals__c, Business__c, Chassis_Number__c, Description__c, Ingredients__c, Number_of_Animals__c, Order_Sizes__c, Own_Catching__c, Own_Transport__c, Production__c, Rearing_System__c, Status__c, Name, Vehicle_Registration__c, Vehicle_Type__c FROM Unit__c WHERE Account__c =:oldSite.Id]){
                if(u != null){
                    Unit__c newUnit = u.clone(false,false,false,false);
                    newUnit.Account__c = newSite.Id;
                    newUnit.Status__c = 'Applying';

                    unitToCreate.add(newUnit);
                }
            }

            if(unitToCreate.size() != 0){
                insert unitToCreate;
            }

            app.Site__c = newSite.Id;
            app.Head_Office__c = newSite.ParentId;
            app.RecordTypeId = renewalAppRecordTypeId;
            app.Stage__c = null;
            insert app;


            // Create application units for the Units added
            if(unitToCreate.size() != 0){
                for(Unit__c u : unitToCreate){
                    Application_Unit__c apu = new Application_Unit__c(Unit__c = u.Id, Application__c = app.Id);
                    apuToCreate.add(apu);
                }
            }
            insert apuToCreate;

            //Transfer the contacts from old site to new site
            List<Contact> contactToUpdate = new List<Contact>();
            for(Contact c: [SELECT Id, AccountId FROM Contact WHERE AccountId =:oldSite.Id]){
                if(c != null){
                    c.AccountId = newSite.Id;
                    contactToUpdate.add(c);
                }
            }
            if(contactToUpdate.size() != 0){
                update contactToUpdate;
            }

            

            Application__c insertedApp = [SELECT Id, Site__c, Applicant_Contact__c, Total_Amount_Inc_VAT__c, Payment_Method__c, Payment_Reference__c FROM Application__c WHERE Id =:app.Id];
            system.debug('Total Amount Inc VAT ==> ' + insertedApp.Total_Amount_Inc_VAT__c);
            Application_Contact_Role__c apc = new Application_Contact_Role__c(Application__c = insertedApp.Id, Contact__c = insertedApp.Applicant_Contact__c);
            insert apc;

            // Send invoice email using future method
            sendInvoiceForTransfer(insertedApp.Id);

            if(insertedApp.Payment_Method__c == 'Card'){
                // Code is commented out due to Card Payment not yet enabled
                /*
                Contact con = [SELECT Id, FirstName, LastName, Email FROM Contact WHERE Id =:insertedApp.Applicant_Contact__c];

                Account acc = [SELECT Id, Name, BillingStreet, BillingCity, BillingPostalCode, BillingCountry FROM Account WHERE Id =: insertedApp.Site__c];
                
                asp04__Payment__c payment = new asp04__Payment__c();
                payment.Application__c = insertedApp.Id;
                payment.asp04__Amount__c = insertedApp.Total_Amount_Inc_VAT__c;
                payment.asp04__Payment_Route_Options__c = 'Card';
                payment.asp04__First_Name__c = con.FirstName;
                payment.asp04__Last_Name__c = con.LastName;
                payment.asp04__Email__c = con.Email;
                payment.asp04__Company_Name__c = acc.Name;
                payment.asp04__Billing_Address_Street__c = acc.BillingStreet;
                payment.asp04__Billing_Address_City__c = acc.BillingCity;
                payment.asp04__Billing_Address_PostalCode__c = acc.BillingPostalCode;
                payment.asp04__Billing_Address_Country__c = acc.BillingCountry;
                
                insert payment;

                asp04__Payment__c insertedPayment = [SELECT Id, Application__c, asp04__Amount__c, Payment_Link__c FROM asp04__Payment__c WHERE Id=:payment.Id];

                insertedPayment.asp04__Success_Endpoint_Long__c = URL.getOrgDomainUrl().toExternalForm() + '/'+ insertedPayment.id;

                update insertedPayment;
                system.debug('Success Link ==> '+ insertedPayment.asp04__Success_Endpoint_Long__c);

                system.debug('Payment Link ==> '+ insertedPayment.Payment_Link__c);

                return insertedPayment;
                */
                // return null can be removed when Card Payment has been enabled and the code has been uncommented.
                return null;
            }else{
                return insertedApp;
            } 
        } else{
            return null;
        }

    }

    @future
    public static void sendInvoiceForTransfer(String applicationId){
        Application__c insertedApp = [SELECT Id, Site__c, Applicant_Contact__c, Send_Application_Confirmation_Email__c, Send_Invoice__c, Payment_Reference__c FROM Application__c WHERE Id =:applicationId];
        //insertedApp.Send_Application_Confirmation_Email__c = true;
        insertedApp.Send_Invoice__c = false; // prevent automatic sending of invoice to members
        update insertedApp;
    }
}