unpackaged/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is an active account.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Final_Renewal_Reminder_Sent__c.field-meta.xml
<CustomField>
    <fullName>Final_Renewal_Reminder_Sent__c</fullName>
    <label>Final Reminder Sent</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Membership_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Membership_Expiry_Date__c</fullName>
    <inlineHelpText>Membership Expiry Date is 1 year after the Certificate Issue Date by Default. However if common renewal date is used, then Membership Expiry Date reflects when the sites will need to renew by from a group level.</inlineHelpText>
    <label>Membership Expiry Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Primary Account(DoNotUse)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <description>Renewal Date is 2 months before Membership Expiry Date.</description>
    <formula>ADDMONTHS(Membership_Expiry_Date__c,-2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Renewal Date is 2 months before Membership Expiry Date.</inlineHelpText>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Renewal_Reminder_Ready__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Reminder_Ready__c</fullName>
    <formula>Latest_Renewal_Price_Date_For__c =  Membership_Expiry_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Reminder Ready</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Six_Week_Renewal_Reminder_Sent__c.field-meta.xml
<CustomField>
    <fullName>Six_Week_Renewal_Reminder_Sent__c</fullName>
    <label>Renewal Invite Sent</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Membership_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/X6_Week_Renewal_Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>X6_Week_Renewal_Scheduled_Date__c</fullName>
    <formula>DATE(YEAR(ADDMONTHS(Membership_Expiry_Date__c, -2)), MONTH(ADDMONTHS(Membership_Expiry_Date__c, -2)), 01)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>6 Week Renewal Scheduled Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <description>An Account representing a site.</description>
    <label>Site</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <formula>IF(Id = Account.Primary_Contact__r.Id , true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates that this contact is the primary contact for the account that it is affiliated with.</inlineHelpText>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Renewal_Reminder_Log__c/Renewal_Reminder_Log__c.object-meta.xml
<CustomObject>
    <description>Stores the logs for renewal application reminders that get sent out to members.</description>
    <label>Renewal Reminder Log</label>
    <nameField>
        <displayFormat>RR-{0000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewal Reminder Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Renewal_Reminder_Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>Error message text.</description>
    <inlineHelpText>Error message text.</inlineHelpText>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Renewal_Reminder_Log__c/fields/Fields__c.field-meta.xml
<CustomField>
    <fullName>Fields__c</fullName>
    <description>Identifies which fields in the object, if any, affected the error condition.</description>
    <inlineHelpText>Identifies which fields in the object, if any, affected the error condition.</inlineHelpText>
    <label>Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Renewal_Reminder_Log__c/fields/Reminder_Name__c.field-meta.xml
<CustomField>
    <fullName>Reminder_Name__c</fullName>
    <label>Reminder Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Renewal_Reminder_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Renewal_Reminder_Log__c/fields/Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Status_Code__c</fullName>
    <description>A code that characterizes the error.</description>
    <inlineHelpText>A code that characterizes the error.</inlineHelpText>
    <label>Status Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Renewal_Reminder_Log__c/fields/Target_Object_Id__c.field-meta.xml
<CustomField>
    <fullName>Target_Object_Id__c</fullName>
    <description>The object ID of the target for which the reminder occurred.</description>
    <inlineHelpText>The object ID of the target for which the reminder occurred.</inlineHelpText>
    <label>Target Object Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/x6WeekRenewalReminderTestDate__c/x6WeekRenewalReminderTestDate__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>6WeekRenewalReminderTestDate</label>
</CustomObject>

unpackaged/main/default/globalValueSets/Membership_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ADDITION</fullName>
    </customValue>
    <customValue>
        <fullName>ARCHIVED</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC5R</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC7R</fullName>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
    </customValue>
    <customValue>
        <fullName>CONPASS</fullName>
    </customValue>
    <customValue>
        <fullName>ENQUIRY</fullName>
        <default>true</default>
        <label>ENQUIRY</label>
    </customValue>
    <customValue>
        <fullName>EVIDENCE</fullName>
    </customValue>
    <customValue>
        <fullName>FAILED</fullName>
    </customValue>
    <customValue>
        <fullName>FALLOW</fullName>
    </customValue>
    <customValue>
        <fullName>LAPSED</fullName>
    </customValue>
    <customValue>
        <fullName>MEMBER</fullName>
    </customValue>
    <customValue>
        <fullName>MONREQ</fullName>
    </customValue>
    <customValue>
        <fullName>NEW</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2R</fullName>
    </customValue>
    <customValue>
        <fullName>NEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>NONFR</fullName>
    </customValue>
    <customValue>
        <fullName>NOTINSCHEME</fullName>
    </customValue>
    <customValue>
        <fullName>PASSED</fullName>
    </customValue>
    <customValue>
        <fullName>PREPANEL</fullName>
    </customValue>
    <customValue>
        <fullName>REINSTATE</fullName>
    </customValue>
    <customValue>
        <fullName>RENEW/REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWA</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWALINP</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWR</fullName>
    </customValue>
    <customValue>
        <fullName>REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>SUSPENDED</fullName>
    </customValue>
    <masterLabel>Membership Status</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/RenewalReminderSixWeeksEmailBatch.cls
public class RenewalReminderSixWeeksEmailBatch implements Database.Batchable<sObject>, Schedulable{
    // Working version of the Bulk Six Week renewal reminder
    public Database.QueryLocator start(Database.BatchableContext bc){
        if(UserInfo.getUserEmail() == 'help@rspcaassured.org.uk'){
            Date reminderDate = Date.today();
            x6WeekRenewalReminderTestDate__c testDateSetting = x6WeekRenewalReminderTestDate__c.getOrgDefaults();
            if(testDateSetting.Use_Test_Date_Data__c == true && testDateSetting.Test_Date__c != null){
                reminderDate = testDateSetting.Test_Date__c;
            }
            List<Account> siteList = [SELECT Id,
                                            Status__c,
                                            Primary_Contact__c,
                                            Primary_Contact__r.Email,
                                            Membership_Expiry_Date__c,
                                            Renewal_Date__c,
                                            Six_Week_Renewal_Reminder_Sent__c,
                                            ParentId
                                            FROM Account
                                            WHERE
                                            Status__c = 'MEMBER'
                                            AND
                                            X6_Week_Renewal_Scheduled_Date__c =:reminderDate
                                            AND 
                                            Six_Week_Renewal_Reminder_Sent__c = null
                                            AND RecordType.DeveloperName = 'Site'
                                            AND ParentId != null
                                            AND Active__c = true
                                            AND Renewal_Reminder_Ready__c = true];
            Set<Id> headOfcIdSet = new Set<Id>();
            for(Account acc : siteList){
                if(acc.ParentId != null){
                    headOfcIdSet.add(acc.ParentId);
                }
            }
            return Database.getQueryLocator('SELECT Id, Primary_Contact__c, Primary_Contact__r.Email FROM Account WHERE Id IN:headOfcIdSet AND Primary_Contact__r.Email != null');
        }else{
            return null;
        }
            
    }

    public void execute(Database.BatchableContext bc, List<Account> actList){
        x6WeekRenewalReminderTestDate__c testDateSetting = x6WeekRenewalReminderTestDate__c.getOrgDefaults();
        
        EmailTemplate emailTemplate = [SELECT ID FROM EmailTemplate WHERE DeveloperName = 'RenewalReminderSixWeek'];
        Set<String> headOfficeRemindersSent = new Set<String>();
        for(Account act : actList){
            Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
            if(testDateSetting.Use_Test_Date_Data__c == true && testDateSetting.Test_Contact_Id__c != null){
                message.setTargetObjectId(testDateSetting.Test_Contact_Id__c); 
                message.setSaveAsActivity(false);
            }else {
                message.setTargetObjectId(act.Primary_Contact__c); 
                message.setSaveAsActivity(true);
            }
            message.setSenderDisplayName('RSPCA Assured'); 
            message.setReplyTo('help@rspcaassured.org.uk');
            message.setUseSignature(false); 
            message.setBccSender(false); 
            message.setTemplateID(emailTemplate.Id); 
            message.setWhatId(act.Id);
            Messaging.SingleEmailMessage[] messages = new List<Messaging.SingleEmailMessage> {message};
            Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
            if (results[0].success){
                System.debug('The email was sent successfully.');
                headOfficeRemindersSent.add(act.Id);
                Renewal_Reminder_Log__c log = new Renewal_Reminder_Log__c(
                    Status__C = 'Success',
                    Target_Object_Id__c = act.Id,
                    Reminder_Name__c = 'Six Week Renewal Reminder From Head Office'
                );
                insert log;
            }else {
                System.debug('The email failed to send: '+results[0].errors[0].message);
                Object sc = (Object)results.get(0).getErrors()[0].getStatusCode();
                Renewal_Reminder_Log__c log = new Renewal_Reminder_Log__c(Status__C = 'Error', Target_Object_Id__c = results.get(0).getErrors()[0].getTargetObjectId(), Error_Message__c = results.get(0).getErrors()[0].getMessage(), Fields__c = results.get(0).getErrors()[0].getFields().toString(), Status_Code__c = sc.toString(), Reminder_Name__c = 'Six Week Renewal Reminder From Head Office');
                insert log;
            }
        }
        if(testDateSetting.Use_Test_Date_Data__c == false){
            // Update site sent checkbox
            List<Account> sites = [SELECT Id, Six_Week_Renewal_Reminder_Sent__c, Final_Renewal_Reminder_Sent__c FROM Account WHERE Status__c = 'MEMBER' AND
            X6_Week_Renewal_Scheduled_Date__c =:Date.today()
            AND 
            Six_Week_Renewal_Reminder_Sent__c = null
            AND RecordType.DeveloperName = 'Site'
            AND ParentId IN: headOfficeRemindersSent
            AND Active__c = true
            AND Renewal_Reminder_Ready__c = true];
            for(Account a : sites){
                a.Six_Week_Renewal_Reminder_Sent__c = Date.today();
            }
            update sites;
        }
        
    }
    
    public void finish(Database.BatchableContext bc){}
    
    public void execute(SchedulableContext sc){
        RenewalReminderSixWeeksEmailBatch obj = new RenewalReminderSixWeeksEmailBatch();
        Database.executeBatch(obj, 1);
    }
}