unpackaged/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is an active account.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Membership_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Membership_Expiry_Date__c</fullName>
    <inlineHelpText>Membership Expiry Date is 1 year after the Certificate Issue Date by Default. However if common renewal date is used, then Membership Expiry Date reflects when the sites will need to renew by from a group level.</inlineHelpText>
    <label>Membership Expiry Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Membership_Number__c.field-meta.xml
<CustomField>
    <fullName>Membership_Number__c</fullName>
    <formula>Parent.Head_Office_Number__c  &amp; &quot;.&quot;  &amp;  Site_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Membership_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <description>An Account representing a site.</description>
    <label>Site</label>
</RecordType>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Assessment_Approved_By_Certifier_Date__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Approved_By_Certifier_Date__c</fullName>
    <label>Assessment Approved By (Certifier) Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Assessment_Date__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Date__c</fullName>
    <description>Cannot exceed the deadline date; can be updated if rearranged</description>
    <inlineHelpText>The date the site will be assessed</inlineHelpText>
    <label>Assessment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Head_Office__c.field-meta.xml
<CustomField>
    <fullName>Head_Office__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Head Office</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Head Office</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Membership_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Membership_Expiry_Date__c</fullName>
    <formula>Site__r.Membership_Expiry_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership Expiry Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Membership_Number__c.field-meta.xml
<CustomField>
    <fullName>Membership_Number__c</fullName>
    <formula>Site__r.Membership_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field must be populated in order to mark an Additional Visit as complete.</inlineHelpText>
    <label>Membership Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>ApplicationSite</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Site__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/Application_Unit__c.object-meta.xml
<CustomObject>
    <label>Application Unit</label>
    <nameField>
        <displayFormat>APUN-{00}</displayFormat>
        <label>APP Unit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application_Unit__c/fields/Animals__c.field-meta.xml
<CustomField>
    <fullName>Animals__c</fullName>
    <formula>TEXT( Unit__r.Animals__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Animals</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Application Units</relationshipLabel>
    <relationshipName>ApplicationUnits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <formula>TEXT(Unit__r.Business__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/fields/Number_of_Animals__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Animals__c</fullName>
    <formula>Unit__r.Number_of_Animals__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Animals</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/fields/Production__c.field-meta.xml
<CustomField>
    <fullName>Production__c</fullName>
    <formula>TEXT( Unit__r.Production__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Production</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Application Units</relationshipLabel>
    <relationshipName>Application_Units</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Checklist_Template__c/Checklist_Template__c.object-meta.xml
<CustomObject>
    <label>Checklist Template</label>
    <nameField>
        <label>Checklist Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklist Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Checklist_Template__c/fields/Scheme_Wording__c.field-meta.xml
<CustomField>
    <fullName>Scheme_Wording__c</fullName>
    <label>Scheme Wording</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Checklist_Template__c/fields/Species__c.field-meta.xml
<CustomField>
    <fullName>Species__c</fullName>
    <label>Species</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Animals</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Checklist_Template__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Unit__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Animals__c.field-meta.xml
<CustomField>
    <fullName>Animals__c</fullName>
    <label>Animals</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Animals</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Animals_List__c.field-meta.xml
<CustomField>
    <fullName>Animals_List__c</fullName>
    <label>List of Animals</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Animals</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Ingredients__c.field-meta.xml
<CustomField>
    <fullName>Ingredients__c</fullName>
    <label>Ingredients</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Ingredients</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Number_of_Animals__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Animals__c</fullName>
    <label>Number of Animals</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Order_Sizes__c.field-meta.xml
<CustomField>
    <fullName>Order_Sizes__c</fullName>
    <label>Order Sizes</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Small</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Production__c.field-meta.xml
<CustomField>
    <fullName>Production__c</fullName>
    <label>Production</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Production</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Rearing_System__c.field-meta.xml
<CustomField>
    <fullName>Rearing_System__c</fullName>
    <label>Rearing System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rearing_System</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applying</fullName>
                <default>true</default>
                <label>Applying</label>
            </value>
            <value>
                <fullName>Certified</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Vehicle_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Animals.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Beef Cattle</fullName>
    </customValue>
    <customValue>
        <fullName>Chickens</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy Cattle</fullName>
    </customValue>
    <customValue>
        <fullName>Ducklings</fullName>
    </customValue>
    <customValue>
        <fullName>Ducks</fullName>
    </customValue>
    <customValue>
        <fullName>Laying Hen Chicks</fullName>
    </customValue>
    <customValue>
        <fullName>Laying Hens</fullName>
    </customValue>
    <customValue>
        <fullName>Lumpfish</fullName>
    </customValue>
    <customValue>
        <fullName>Meat Chicken Chicks</fullName>
    </customValue>
    <customValue>
        <fullName>Pigs</fullName>
    </customValue>
    <customValue>
        <fullName>Pullets</fullName>
    </customValue>
    <customValue>
        <fullName>Salmon</fullName>
    </customValue>
    <customValue>
        <fullName>Sheep</fullName>
    </customValue>
    <customValue>
        <fullName>Trout</fullName>
    </customValue>
    <customValue>
        <fullName>Turkey Poults</fullName>
    </customValue>
    <customValue>
        <fullName>Turkeys</fullName>
    </customValue>
    <customValue>
        <fullName>Veal Calves</fullName>
    </customValue>
    <customValue>
        <fullName>Wrasse</fullName>
    </customValue>
    <customValue>
        <fullName>List</fullName>
    </customValue>
    <masterLabel>Animals</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Business.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abattoir</fullName>
    </customValue>
    <customValue>
        <fullName>Catching</fullName>
    </customValue>
    <customValue>
        <fullName>Cleaner Fish</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery</fullName>
    </customValue>
    <customValue>
        <fullName>Haulier</fullName>
    </customValue>
    <customValue>
        <fullName>Producer</fullName>
    </customValue>
    <customValue>
        <fullName>Supply Chain</fullName>
    </customValue>
    <masterLabel>Business</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Ingredients.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Beef</fullName>
    </customValue>
    <customValue>
        <fullName>Chicken</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Duck</fullName>
    </customValue>
    <customValue>
        <fullName>Eggs</fullName>
    </customValue>
    <customValue>
        <fullName>Lamb</fullName>
    </customValue>
    <customValue>
        <fullName>Pork</fullName>
    </customValue>
    <customValue>
        <fullName>Salmon</fullName>
    </customValue>
    <customValue>
        <fullName>Trout</fullName>
    </customValue>
    <customValue>
        <fullName>Turkey</fullName>
    </customValue>
    <customValue>
        <fullName>Veal</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Ingredients</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Membership_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ADDITION</fullName>
    </customValue>
    <customValue>
        <fullName>ARCHIVED</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC5R</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC7R</fullName>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
    </customValue>
    <customValue>
        <fullName>CONPASS</fullName>
    </customValue>
    <customValue>
        <fullName>ENQUIRY</fullName>
        <default>true</default>
        <label>ENQUIRY</label>
    </customValue>
    <customValue>
        <fullName>EVIDENCE</fullName>
    </customValue>
    <customValue>
        <fullName>FAILED</fullName>
    </customValue>
    <customValue>
        <fullName>FALLOW</fullName>
    </customValue>
    <customValue>
        <fullName>LAPSED</fullName>
    </customValue>
    <customValue>
        <fullName>MEMBER</fullName>
    </customValue>
    <customValue>
        <fullName>MONREQ</fullName>
    </customValue>
    <customValue>
        <fullName>NEW</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2R</fullName>
    </customValue>
    <customValue>
        <fullName>NEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>NONFR</fullName>
    </customValue>
    <customValue>
        <fullName>NOTINSCHEME</fullName>
    </customValue>
    <customValue>
        <fullName>PASSED</fullName>
    </customValue>
    <customValue>
        <fullName>PREPANEL</fullName>
    </customValue>
    <customValue>
        <fullName>REINSTATE</fullName>
    </customValue>
    <customValue>
        <fullName>RENEW/REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWA</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWALINP</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWR</fullName>
    </customValue>
    <customValue>
        <fullName>REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>SUSPENDED</fullName>
    </customValue>
    <masterLabel>Membership Status</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Production.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abattoir</fullName>
    </customValue>
    <customValue>
        <fullName>Brand/Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Breeding</fullName>
    </customValue>
    <customValue>
        <fullName>Brood</fullName>
    </customValue>
    <customValue>
        <fullName>Calves</fullName>
    </customValue>
    <customValue>
        <fullName>Catching Team</fullName>
    </customValue>
    <customValue>
        <fullName>Cleaner Fish</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Dry Cows</fullName>
    </customValue>
    <customValue>
        <fullName>Finishing</fullName>
    </customValue>
    <customValue>
        <fullName>Flat deck (one-storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Flat deck (two storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Flat deck with Veranda</fullName>
    </customValue>
    <customValue>
        <fullName>Freshwater</fullName>
    </customValue>
    <customValue>
        <fullName>Gilts</fullName>
    </customValue>
    <customValue>
        <fullName>Grazing</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery (On Grower)</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery (Ova)</fullName>
    </customValue>
    <customValue>
        <fullName>Haulier</fullName>
    </customValue>
    <customValue>
        <fullName>Heifers</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-tier (one-storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-tier (two-storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-tier with Veranda</fullName>
    </customValue>
    <customValue>
        <fullName>Packer</fullName>
    </customValue>
    <customValue>
        <fullName>Processor</fullName>
    </customValue>
    <customValue>
        <fullName>Processor/Packer</fullName>
    </customValue>
    <customValue>
        <fullName>Producer</fullName>
    </customValue>
    <customValue>
        <fullName>Rearing</fullName>
    </customValue>
    <customValue>
        <fullName>Retailer</fullName>
    </customValue>
    <masterLabel>Production</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Rearing_System.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Barn</fullName>
    </customValue>
    <customValue>
        <fullName>Free Range</fullName>
    </customValue>
    <customValue>
        <fullName>Indoor</fullName>
    </customValue>
    <customValue>
        <fullName>Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Outdoor Bred</fullName>
    </customValue>
    <customValue>
        <fullName>Outdoor Reared</fullName>
    </customValue>
    <customValue>
        <fullName>n/a</fullName>
    </customValue>
    <customValue>
        <fullName>Pasture</fullName>
    </customValue>
    <masterLabel>Rearing System</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Vehicle_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Helicopter</fullName>
    </customValue>
    <customValue>
        <fullName>Lorry</fullName>
    </customValue>
    <customValue>
        <fullName>Trailer</fullName>
    </customValue>
    <customValue>
        <fullName>Van</fullName>
    </customValue>
    <customValue>
        <fullName>Wellboat</fullName>
    </customValue>
    <customValue>
        <fullName>TBC</fullName>
    </customValue>
    <masterLabel>Vehicle Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CertificatesControllerTest.cls
@isTest
public class CertificatesControllerTest {

    @isTest
    public static void supplyChainCertificateTest() {
        Account act = new Account();
        act.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Head Office').getRecordTypeId();
        act.Name = 'Test Head Office';
        act.Status__c = 'ENQUIRY';
        insert act;
        
        Account site = new Account();
        site.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Site').getRecordTypeId();
        site.Name = 'Test Site';
        site.ParentId = act.Id;
        site.Active__c = true;
        site.Membership_Expiry_Date__c = Date.today().addDays(42);
        insert site;
        
        Application__c newApplication = new Application__c();
        newApplication.Site__c = site.Id;
        newApplication.Head_Office__c = act.Id;
        newApplication.Assessment_Approved_By_Certifier_Date__c = System.today() + 2;
        newApplication.Assessment_Date__c = System.today() + 1;
        insert newApplication; 
        
        // Create Checklist Template
        Checklist_Template__c ChecklistTemplateObj = new Checklist_Template__c();
        ChecklistTemplateObj.Name = 'Salmon Test';
        ChecklistTemplateObj.Species__c = 'Salmon';
        ChecklistTemplateObj.Animals_List__c = 'Salmon';
        ChecklistTemplateObj.Start_Date__c = System.Today();
        ChecklistTemplateObj.End_Date__c = System.Today() + 30;
        ChecklistTemplateObj.Scheme_Wording__c = 'Testing Salmon';
        insert ChecklistTemplateObj;
       
        // Create certified units
       
        
		Unit__c unit1 = new Unit__c();
        unit1.Account__c = site.Id;
        unit1.Name = '01';
        unit1.Business__c = 'Producer';
        unit1.Production__c = 'Freshwater';
        unit1.Animals__c = 'Salmon';
        unit1.Number_Of_Animals__c = 100;
        unit1.Status__c = 'Certified';
        unit1.Rearing_System__c = 'n/a';
        insert unit1;
        
        Unit__c unit3 = new Unit__c();
        unit3.Account__c = site.Id;
        unit3.Name = '01';
        unit3.Business__c = 'Supply Chain';
        unit3.Ingredients__c = 'Beef';
        unit3.Production__c = 'Processor';
        unit3.Order_Sizes__C = 'Single';
        unit3.Status__c = 'Certified';
        insert unit3;

        Unit__c unit2 = new Unit__c();
        unit2.Account__c = site.Id;
        unit2.Name = '02';
        unit2.Business__c = 'Supply Chain';
        unit2.Ingredients__c = 'Beef';
        unit2.Production__c = 'Processor';
        unit2.Order_Sizes__C = 'Single';
        unit2.Status__c = 'Certified';
        insert unit2;
        
        Unit__c unit4 = new Unit__c();
        unit4.Account__c = site.Id;
        unit4.Name = '04';
        unit4.Business__c = 'Abattoir';
        unit4.Status__c = 'Certified';
        unit4.Animals__c = 'Salmon';
       	insert unit4;
        
        Application_Unit__c apu = new Application_Unit__c();
        apu.Unit__c = unit1.Id;
        apu.Application__c = newApplication.Id;
        insert apu;
        
        Application_Unit__c apu1= new Application_Unit__c();
        apu1.unit__c = unit4.Id;
        apu1.application__c = newApplication.Id;
        insert apu1;

        PageReference pageRef = Page.SupplyChainCertificate;
        Test.setCurrentPage(pageRef);
        
        // Add parameters to page URL
        ApexPages.currentPage().getParameters().put('Id', site.Id);
        ApexPages.currentPage().getParameters().put('species', 'Salmon');

        // Instantiate a new controller with all parameters in the page
        CertificatesController controller = new CertificatesController(); 
        controller.getSupplyChainUnits();
        controller.getSCISchemeTexts();
        controller.getSCISchemeTitle();

        ApexPages.StandardController sc = new ApexPages.StandardController(site);
        DownloadCertificatesController downloadCertificates = new DownloadCertificatesController(sc);

        //Get Head Office Account for Bulk Certificates Download
        FObject siteObj1 = DataFactory.getDefHeadOfficeAccounts();
        siteObj1.insertRecords(true);
        Account headOffice = [SELECT Id, Name, Membership_Number__c, ParentId FROM Account WHERE Site = 'HeadOffice' LIMIT 1];
        
        site.ParentId = headOffice.Id;
        update site;
	
        ApexPages.StandardController sc1 = new ApexPages.StandardController(headOffice);
        BulkDownloadCertificatesController bulkDownloadCertificates = new BulkDownloadCertificatesController(sc1);


        
    }

    @isTest
    public static void troutCertificateTest() {
        Account act = new Account();
        act.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Head Office').getRecordTypeId();
        act.Name = 'Test Head Office';
        act.Status__c = 'ENQUIRY';
        insert act;
        
        Account site = new Account();
        site.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Site').getRecordTypeId();
        site.Name = 'Test Site';
        site.ParentId = act.Id;
        site.Active__c = true;
        site.Membership_Expiry_Date__c = Date.today().addDays(42);
        insert site;
        
        Application__c newApplication = new Application__c();
        newApplication.Site__c = site.Id;
        newApplication.Head_Office__c = act.Id;
        newApplication.Assessment_Approved_By_Certifier_Date__c = System.today() + 2;
        newApplication.Assessment_Date__c = System.today() + 1;
        insert newApplication; 
                // Create certified units
        Unit__c unit1 = new Unit__c();
        unit1.Account__c = site.Id;
        unit1.Name = '01';
        unit1.Business__c = 'Producer';
        unit1.Production__c = 'Freshwater';
        unit1.Animals__c = 'Trout';
        unit1.Number_Of_Animals__c = 100;
        unit1.Status__c = 'Certified';
        unit1.Rearing_System__c = 'n/a';
        insert unit1;

        Unit__c unit2 = new Unit__c();
        unit2.Account__c = site.Id;
        unit2.Name = '02';
        unit2.Business__c = 'Producer';
        unit2.Production__c = 'Freshwater';
        unit2.Animals__c = 'Trout';
        unit2.Number_Of_Animals__c = 100;
        unit2.Status__c = 'Certified';
        unit2.Rearing_System__c = 'n/a';
        insert unit2;
        
         // Create Checklist Template
        Checklist_Template__c ChecklistTemplateObj = new Checklist_Template__c();
        ChecklistTemplateObj.Name = 'Trout Test';
        ChecklistTemplateObj.Species__c = 'Trout';
        ChecklistTemplateObj.Animals_List__c = 'Trout';
        ChecklistTemplateObj.Start_Date__c = System.Today();
        ChecklistTemplateObj.End_Date__c = System.Today() + 30;
        ChecklistTemplateObj.Scheme_Wording__c = 'Testing Trout';
        insert ChecklistTemplateObj;
		
        Application_Unit__c apu = new Application_Unit__c();
        apu.Unit__c = unit1.Id;
        apu.Application__c = newApplication.Id;
        insert apu;
        
        PageReference pageRef = Page.TroutCertificate;
        Test.setCurrentPage(pageRef);
        
        // Add parameters to page URL
        ApexPages.currentPage().getParameters().put('Id', site.Id);
		ApexPages.currentPage().getParameters().put('species', 'Trout');
        // Instantiate a new controller with all parameters in the page
        CertificatesController controller = new CertificatesController(); 
        controller.getTroutAnimalScheme();
        controller.getTroutAnimals();
        controller.getTroutRearingSystems();

        ApexPages.StandardController sc = new ApexPages.StandardController(site);
        DownloadCertificatesController downloadCertificates = new DownloadCertificatesController(sc);

        //Get Head Office Account for Bulk Certificates Download
        FObject siteObj1 = DataFactory.getDefHeadOfficeAccounts();
        siteObj1.insertRecords(true);
        Account headOffice = [SELECT Id, Name, Membership_Number__c, ParentId FROM Account WHERE Site = 'HeadOffice' LIMIT 1];
        
        site.ParentId = headOffice.Id;
        update site;

        ApexPages.StandardController sc1 = new ApexPages.StandardController(headOffice);
        BulkDownloadCertificatesController bulkDownloadCertificates = new BulkDownloadCertificatesController(sc1);
        
    }

    @isTest
    public static void nsfUkasCertificateTest1() {
        Account act = new Account();
        act.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Head Office').getRecordTypeId();
        act.Name = 'Test Head Office';
        act.Status__c = 'ENQUIRY';
        insert act;
        
        Account site = new Account();
        site.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Site').getRecordTypeId();
        site.Name = 'Test Site';
        site.ParentId = act.Id;
        site.Active__c = true;
        site.Membership_Expiry_Date__c = Date.today().addDays(42);
        insert site;
        
        Application__c newApplication = new Application__c();
        newApplication.Site__c = site.Id;
        newApplication.Head_Office__c = act.Id;
        newApplication.Assessment_Approved_By_Certifier_Date__c = System.today() + 2;
        newApplication.Assessment_Date__c = System.today() + 1;
        insert newApplication; 
                // Create certified units
        Unit__c unit1 = new Unit__c();
        unit1.Account__c = site.Id;
        unit1.Name = '01';
        unit1.Business__c = 'Producer';
        unit1.Production__c = 'Freshwater';
        unit1.Animals__c = 'Trout';
        unit1.Number_Of_Animals__c = 100;
        unit1.Status__c = 'Certified';
        unit1.Rearing_System__c = 'n/a';
        insert unit1;

        Unit__c unit2 = new Unit__c();
        unit2.Account__c = site.Id;
        unit2.Name = '02';
        unit2.Business__c = 'Producer';
        unit2.Production__c = 'Freshwater';
        unit2.Animals__c = 'Trout';
        unit2.Number_Of_Animals__c = 100;
        unit2.Status__c = 'Certified';
        unit2.Rearing_System__c = 'n/a';
        insert unit2;
        
         // Create Checklist Template
        Checklist_Template__c ChecklistTemplateObj = new Checklist_Template__c();
        ChecklistTemplateObj.Name = 'Trout Test';
        ChecklistTemplateObj.Species__c = 'Trout';
        ChecklistTemplateObj.Animals_List__c = 'Trout';
        ChecklistTemplateObj.Start_Date__c = System.Today();
        ChecklistTemplateObj.End_Date__c = System.Today() + 30;
        ChecklistTemplateObj.Scheme_Wording__c = 'Testing Trout';
        insert ChecklistTemplateObj;
		
        Application_Unit__c apu = new Application_Unit__c();
        apu.Unit__c = unit1.Id;
        apu.Application__c = newApplication.Id;
        insert apu;

        // Create certified units
        Unit__c unit3 = new Unit__c();
        unit3.Account__c = site.Id;
        unit3.Name = '01';
        unit3.Business__c = 'Producer';
        unit3.Production__c = 'Producer';
        unit3.Animals__c = 'Chickens';
        unit3.Number_Of_Animals__c = 10000;
        unit3.Status__c = 'Certified';
        unit3.Rearing_System__c = 'Free Range';
        insert unit3;

        PageReference pageRef = Page.NSFUKASCertification;
        Test.setCurrentPage(pageRef);
        
        // Add parameters to page URL
        ApexPages.currentPage().getParameters().put('Id', site.Id);
		ApexPages.currentPage().getParameters().put('species', 'Trout');
        // Instantiate a new controller with all parameters in the page
        CertificatesController controller = new CertificatesController(); 
        controller.getAllAnimalScheme();
        controller.getAllAnimals();
        controller.getAllAnimalRearingSystems();

        ApexPages.StandardController sc = new ApexPages.StandardController(site);
        DownloadCertificatesController downloadCertificates = new DownloadCertificatesController(sc);

        //Get Head Office Account for Bulk Certificates Download
        FObject siteObj1 = DataFactory.getDefHeadOfficeAccounts();
        siteObj1.insertRecords(true);
        Account headOffice = [SELECT Id, Name, Membership_Number__c, ParentId FROM Account WHERE Site = 'HeadOffice' LIMIT 1];
        
        site.ParentId = headOffice.Id;
        update site;

        ApexPages.StandardController sc1 = new ApexPages.StandardController(headOffice);
        BulkDownloadCertificatesController bulkDownloadCertificates = new BulkDownloadCertificatesController(sc1);
        
    }
    @isTest
    public static void nsfUkasCertificateTest2() {
        Account act = new Account();
        act.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Head Office').getRecordTypeId();
        act.Name = 'Test Head Office';
        act.Status__c = 'ENQUIRY';
        insert act;
        
        Account site = new Account();
        site.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Site').getRecordTypeId();
        site.Name = 'Test Site';
        site.ParentId = act.Id;
        site.Active__c = true;
        site.Membership_Expiry_Date__c = Date.today().addDays(42);
        insert site;
        
        Application__c newApplication = new Application__c();
        newApplication.Site__c = site.Id;
        newApplication.Head_Office__c = act.Id;
        newApplication.Assessment_Approved_By_Certifier_Date__c = System.today() + 2;
        newApplication.Assessment_Date__c = System.today() + 1;
        insert newApplication; 
                // Create certified units
        Unit__c unit1 = new Unit__c();
        unit1.Account__c = site.Id;
        unit1.Name = '01';
        unit1.Business__c = 'Producer';
        unit1.Production__c = 'Freshwater';
        unit1.Animals__c = 'Trout';
        unit1.Number_Of_Animals__c = 100;
        unit1.Status__c = 'Certified';
        unit1.Rearing_System__c = 'n/a';
        insert unit1;

        Unit__c unit2 = new Unit__c();
        unit2.Account__c = site.Id;
        unit2.Name = '02';
        unit2.Business__c = 'Producer';
        unit2.Production__c = 'Freshwater';
        unit2.Animals__c = 'Trout';
        unit2.Number_Of_Animals__c = 100;
        unit2.Status__c = 'Certified';
        unit2.Rearing_System__c = 'n/a';
        insert unit2;
        
         // Create Checklist Template
        Checklist_Template__c ChecklistTemplateObj = new Checklist_Template__c();
        ChecklistTemplateObj.Name = 'Trout Test';
        ChecklistTemplateObj.Species__c = 'Trout';
        ChecklistTemplateObj.Animals_List__c = 'Trout';
        ChecklistTemplateObj.Start_Date__c = System.Today();
        ChecklistTemplateObj.End_Date__c = System.Today() + 30;
        ChecklistTemplateObj.Scheme_Wording__c = 'Testing Trout';
        insert ChecklistTemplateObj;
		
        Application_Unit__c apu = new Application_Unit__c();
        apu.Unit__c = unit1.Id;
        apu.Application__c = newApplication.Id;
        insert apu;
        // Create certified units
        Unit__c unit3 = new Unit__c();
        unit3.Account__c = site.Id;
        unit3.Name = '01';
        unit3.Business__c = 'Producer';
        unit3.Production__c = 'Producer';
        unit3.Animals__c = 'Ducks';
        unit3.Number_Of_Animals__c = 10000;
        unit3.Status__c = 'Certified';
        unit3.Rearing_System__c = 'Free Range';
        insert unit3;

        Unit__c unit4 = new Unit__c();
        unit4.Account__c = site.Id;
        unit4.Name = '02';
        unit4.Business__c = 'Producer';
        unit4.Production__c = 'Producer';
        unit4.Animals__c = 'Chickens';
        unit4.Number_Of_Animals__c = 20000;
        unit4.Status__c = 'Certified';
        unit4.Rearing_System__c = 'Organic';
        insert unit4;

        PageReference pageRef = Page.NSFUKASCertification;
        Test.setCurrentPage(pageRef);
        
        // Add parameters to page URL
        ApexPages.currentPage().getParameters().put('Id', site.Id);
        ApexPages.currentPage().getParameters().put('species', 'Trout');

        // Instantiate a new controller with all parameters in the page
        CertificatesController controller = new CertificatesController(); 
        controller.getAllAnimalScheme();
        controller.getAllAnimals();
        controller.getAllAnimalRearingSystems();

        ApexPages.StandardController sc = new ApexPages.StandardController(site);
        DownloadCertificatesController downloadCertificates = new DownloadCertificatesController(sc);

        //Get Head Office Account for Bulk Certificates Download
        FObject siteObj1 = DataFactory.getDefHeadOfficeAccounts();
        siteObj1.insertRecords(true);
        Account headOffice = [SELECT Id, Name, Membership_Number__c, ParentId FROM Account WHERE Site = 'HeadOffice' LIMIT 1];
        
        site.ParentId = headOffice.Id;
        update site;

        ApexPages.StandardController sc1 = new ApexPages.StandardController(headOffice);
        BulkDownloadCertificatesController bulkDownloadCertificates = new BulkDownloadCertificatesController(sc1);
        
    }
    @isTest
    public static void loadData(){
        Account act = new Account();
        act.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Head Office').getRecordTypeId();
        act.Name = 'Test Head Office';
        act.Status__c = 'ENQUIRY';
        insert act;
        
        Account site = new Account();
        site.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Site').getRecordTypeId();
        site.Name = 'Test Site';
        site.ParentId = act.Id;
        site.Active__c = true;
        site.Membership_Expiry_Date__c = Date.today().addDays(42);
        insert site;
        
        Application__c newApplication = new Application__c();
        newApplication.Site__c = site.Id;
        newApplication.Head_Office__c = act.Id;
        newApplication.Assessment_Approved_By_Certifier_Date__c = System.today() + 2;
        newApplication.Assessment_Date__c = System.today() + 1;
        insert newApplication; 
        
        Checklist_Template__c ChecklistTemplateObj = new Checklist_Template__c();
        ChecklistTemplateObj.Name = 'Salmon Test';
        ChecklistTemplateObj.Species__c = 'Salmon';
        ChecklistTemplateObj.Animals_List__c = 'Salmon';
        ChecklistTemplateObj.Start_Date__c = System.Today();
        ChecklistTemplateObj.End_Date__c = System.Today() + 30;
        ChecklistTemplateObj.Scheme_Wording__c = 'Testing Salmon';
        insert ChecklistTemplateObj;
        
       
        List<Unit__c> units = new List<Unit__c>();
        // Create certified units
        Unit__c unit1 = new Unit__c();
        unit1.Account__c = site.Id;
        unit1.Name = '01';
        unit1.Business__c = 'Supply Chain';
        unit1.Ingredients__c = 'Beef';
        unit1.Production__c = 'Processor';
        unit1.Order_Sizes__C = 'Single';
        unit1.Status__c = 'Certified';
        units.add(unit1);
        
        Unit__c unit2 = new Unit__c();
        unit2.Account__c = site.Id;
        unit2.Name = '02';
        unit2.Business__c = 'Supply Chain';
        unit2.Ingredients__c = 'Beef';
        unit2.Production__c = 'Processor';
        unit2.Order_Sizes__C = 'Single';
        unit2.Status__c = 'Certified';
        units.add(unit2);
        
        Unit__c unit3 = new Unit__c();
        unit3.Account__c = site.Id;
        unit3.Name = '03';
        unit3.Business__c = 'Producer';
        unit3.Status__c = 'Certified';
        unit3.Animals__c = 'Salmon';
        units.add(unit3);
        
        
        
        Unit__c unit5 = new Unit__c();
        unit5.Account__c = site.Id;
        unit5.Name = '05';
        unit5.Business__c = 'Catching';
        unit5.Status__c = 'Certified';
        unit5.Animals__c = 'Ducks';
        units.add(unit5);
        
        Unit__c unit6 = new Unit__c();
        unit6.Account__c = site.Id;
        unit6.Name = '05';
        unit6.Business__c = 'Hatchery';
        unit6.Status__c = 'Certified';
        unit6.Animals__c = 'Salmon';
        units.add(unit6);
        
        Unit__c unit7 = new Unit__c();
        unit7.Account__c = site.Id;
        unit7.Name = '05';
        unit7.Business__c = 'Haulier';
        unit7.Status__c = 'Certified';
        unit7.Animals__c = 'Salmon';
        unit7.Vehicle_Type__c = 'Wellboat';
        units.add(unit7);
        
        Unit__c unit8 = new Unit__c();
        unit8.Account__c = site.Id;
        unit8.Name = '05';
        unit8.Business__c = 'Haulier';
        unit8.Status__c = 'Certified';
        unit8.Animals__c = 'Salmon';
        unit8.Vehicle_Type__c = 'Helicopter';
        units.add(unit8);
        insert units;
        
        Application_Unit__c newapp = new Application_Unit__c();
        newapp.Application__c = newApplication.Id;
        newapp.Unit__c = units[0].Id;
        Insert newapp;
        
        Application_Unit__c newapp1 = new Application_Unit__c();
        newapp1.Application__c = newApplication.Id;
        newapp1.Unit__c = units[1].Id;
        Insert newapp1;
        
        Application_Unit__c newapp2 = new Application_Unit__c();
        newapp2.Application__c = newApplication.Id;
        newapp2.Unit__c = units[2].Id;
        Insert newapp2;
        
        Application_Unit__c newapp3 = new Application_Unit__c();
        newapp3.Application__c = newApplication.Id;
        newapp3.Unit__c = units[3].Id;
        Insert newapp3;
        
        Application_Unit__c newapp4 = new Application_Unit__c();
        newapp4.Application__c = newApplication.Id;
        newapp4.Unit__c = units[4].Id;
        Insert newapp4;
        
        Application_Unit__c newapp5 = new Application_Unit__c();
        newapp5.Application__c = newApplication.Id;
        newapp5.Unit__c = units[5].Id;
        Insert newapp5;
        
        PageReference pageRef = Page.NSFUKASCertification;
        Test.setCurrentPage(pageRef);
        
        // Add parameters to page URL
        ApexPages.currentPage().getParameters().put('Id', site.Id);
		ApexPages.currentPage().getParameters().put('species', 'Salmon');
        // Instantiate a new controller with all parameters in the page
        CertificatesController controller = new CertificatesController(); 
        controller.getAllAnimalScheme();
        controller.getAllAnimals();
        controller.getAllAnimalRearingSystems();

        ApexPages.StandardController sc = new ApexPages.StandardController(site);
        DownloadCertificatesController downloadCertificates = new DownloadCertificatesController(sc);

    }
}