unpackaged/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is an active account.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Company_Industry__c.field-meta.xml
<CustomField>
    <fullName>Company_Industry__c</fullName>
    <description>Custom Industry muti picklist field for RSPCA Assured members as companies can have more than one industry.</description>
    <label>Company Industry</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company_Industry</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Membership_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Membership_Expiry_Date__c</fullName>
    <inlineHelpText>Membership Expiry Date is 1 year after the Certificate Issue Date by Default. However if common renewal date is used, then Membership Expiry Date reflects when the sites will need to renew by from a group level.</inlineHelpText>
    <label>Membership Expiry Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Pig_Discount_Eligibility__c.field-meta.xml
<CustomField>
    <fullName>Pig_Discount_Eligibility__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pig Discount Eligibility</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Primary Account(DoNotUse)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Membership_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <description>An Account representing a site.</description>
    <label>Site</label>
</RecordType>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Application_Type__c</fullName>
    <label>Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Existing_Member__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Revisit</fullName>
            </value>
            <value>
                <fullName>Levy</fullName>
            </value>
            <value>
                <fullName>Merchandise</fullName>
            </value>
            <value>
                <fullName>Promotion/Partnership</fullName>
            </value>
            <value>
                <fullName>Consultancy</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Existing_Member__c.field-meta.xml
<CustomField>
    <fullName>Existing_Member__c</fullName>
    <label>Existing Member?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Membership_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Membership_Expiry_Date__c</fullName>
    <formula>Site__r.Membership_Expiry_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership Expiry Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>ApplicationSite</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>Stage field for new applications for new site, update, or transfers. This field is used for the application record type.</description>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Application</fullName>
                <default>true</default>
                <label>Application</label>
            </value>
            <value>
                <fullName>Allocation</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Schedule</fullName>
            </value>
            <value>
                <fullName>Visit</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Site__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/recordTypes/Applications.recordType-meta.xml
<RecordType>
    <fullName>Applications</fullName>
    <active>true</active>
    <description>For new applications.</description>
    <label>Applications</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <formula>IF(Id = Account.Primary_Contact__r.Id , true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates that this contact is the primary contact for the account that it is affiliated with.</inlineHelpText>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Additional_Quantity_Pricing_Component__c.field-meta.xml
<CustomField>
    <fullName>Additional_Quantity_Pricing_Component__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Additional Quantity Pricing Component</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Animal__c.field-meta.xml
<CustomField>
    <fullName>Animal__c</fullName>
    <label>Animal</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Animals</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Dynamic_Quantity_Pricing_Component__c.field-meta.xml
<CustomField>
    <fullName>Dynamic_Quantity_Pricing_Component__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dynamic Quantity Pricing Component</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Pricing_Method__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Method__c</fullName>
    <label>Pricing Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Per Application</fullName>
            </value>
            <value>
                <fullName>Per Site</fullName>
            </value>
            <value>
                <fullName>Dynamic Quantity Price</fullName>
            </value>
            <value>
                <fullName>Additional Quantity Price</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Production__c.field-meta.xml
<CustomField>
    <fullName>Production__c</fullName>
    <label>Production</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Production</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Quantity_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Threshold__c</fullName>
    <label>Quantity Threshold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Renewal_Price_Line__c/Renewal_Price_Line__c.object-meta.xml
<CustomObject>
    <label>Renewal Price Line</label>
    <nameField>
        <label>Renewal Price Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Renewal Price Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Renewal_Price_Line__c/fields/Production__c.field-meta.xml
<CustomField>
    <fullName>Production__c</fullName>
    <label>Production</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Renewal_Price_Line__c/fields/Renewal_Price_Report__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Price_Report__c</fullName>
    <label>Renewal Price Report</label>
    <referenceTo>Renewal_Price_Report__c</referenceTo>
    <relationshipLabel>Renewal Price Lines</relationshipLabel>
    <relationshipName>Renewal_Price_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Renewal_Price_Line__c/fields/Total_Inc_VAT__c.field-meta.xml
<CustomField>
    <fullName>Total_Inc_VAT__c</fullName>
    <label>Total Inc VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Renewal_Price_Report__c/Renewal_Price_Report__c.object-meta.xml
<CustomObject>
    <label>Renewal Price Report</label>
    <nameField>
        <displayFormat>RPR{000}</displayFormat>
        <label>Renewal Price Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewal Price Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Renewal_Price_Report__c/fields/Membership_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Membership_Expiry_Date__c</fullName>
    <description>The renewal price report is for the following membership expiry date.</description>
    <inlineHelpText>The renewal price report is for the following membership expiry date.</inlineHelpText>
    <label>Membership Expiry Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Renewal_Price_Report__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Renewal Price Reports</relationshipLabel>
    <relationshipName>Renewal_Price_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Renewal_Price_Report__c/fields/Total_Inc_VAT__c.field-meta.xml
<CustomField>
    <fullName>Total_Inc_VAT__c</fullName>
    <label>Total Inc VAT</label>
    <summarizedField>Renewal_Price_Line__c.Total_Inc_VAT__c</summarizedField>
    <summaryForeignKey>Renewal_Price_Line__c.Renewal_Price_Report__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Unit__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Production__c.field-meta.xml
<CustomField>
    <fullName>Production__c</fullName>
    <label>Production</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Production</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applying</fullName>
                <default>true</default>
                <label>Applying</label>
            </value>
            <value>
                <fullName>Certified</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Vehicle_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Animals.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Beef Cattle</fullName>
    </customValue>
    <customValue>
        <fullName>Chickens</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy Cattle</fullName>
    </customValue>
    <customValue>
        <fullName>Ducklings</fullName>
    </customValue>
    <customValue>
        <fullName>Ducks</fullName>
    </customValue>
    <customValue>
        <fullName>Laying Hen Chicks</fullName>
    </customValue>
    <customValue>
        <fullName>Laying Hens</fullName>
    </customValue>
    <customValue>
        <fullName>Lumpfish</fullName>
    </customValue>
    <customValue>
        <fullName>Meat Chicken Chicks</fullName>
    </customValue>
    <customValue>
        <fullName>Pigs</fullName>
    </customValue>
    <customValue>
        <fullName>Pullets</fullName>
    </customValue>
    <customValue>
        <fullName>Salmon</fullName>
    </customValue>
    <customValue>
        <fullName>Sheep</fullName>
    </customValue>
    <customValue>
        <fullName>Trout</fullName>
    </customValue>
    <customValue>
        <fullName>Turkey Poults</fullName>
    </customValue>
    <customValue>
        <fullName>Turkeys</fullName>
    </customValue>
    <customValue>
        <fullName>Veal Calves</fullName>
    </customValue>
    <customValue>
        <fullName>Wrasse</fullName>
    </customValue>
    <customValue>
        <fullName>List</fullName>
    </customValue>
    <masterLabel>Animals</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Business.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abattoir</fullName>
    </customValue>
    <customValue>
        <fullName>Catching</fullName>
    </customValue>
    <customValue>
        <fullName>Cleaner Fish</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery</fullName>
    </customValue>
    <customValue>
        <fullName>Haulier</fullName>
    </customValue>
    <customValue>
        <fullName>Producer</fullName>
    </customValue>
    <customValue>
        <fullName>Supply Chain</fullName>
    </customValue>
    <masterLabel>Business</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Company_Industry.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fish</fullName>
    </customValue>
    <customValue>
        <fullName>Livestock</fullName>
    </customValue>
    <customValue>
        <fullName>Poultry</fullName>
    </customValue>
    <customValue>
        <fullName>Supply Chain</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Company Industry</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Membership_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ADDITION</fullName>
    </customValue>
    <customValue>
        <fullName>ARCHIVED</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC5R</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC7R</fullName>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
    </customValue>
    <customValue>
        <fullName>CONPASS</fullName>
    </customValue>
    <customValue>
        <fullName>ENQUIRY</fullName>
        <default>true</default>
        <label>ENQUIRY</label>
    </customValue>
    <customValue>
        <fullName>EVIDENCE</fullName>
    </customValue>
    <customValue>
        <fullName>FAILED</fullName>
    </customValue>
    <customValue>
        <fullName>FALLOW</fullName>
    </customValue>
    <customValue>
        <fullName>LAPSED</fullName>
    </customValue>
    <customValue>
        <fullName>MEMBER</fullName>
    </customValue>
    <customValue>
        <fullName>MONREQ</fullName>
    </customValue>
    <customValue>
        <fullName>NEW</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2R</fullName>
    </customValue>
    <customValue>
        <fullName>NEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>NONFR</fullName>
    </customValue>
    <customValue>
        <fullName>NOTINSCHEME</fullName>
    </customValue>
    <customValue>
        <fullName>PASSED</fullName>
    </customValue>
    <customValue>
        <fullName>PREPANEL</fullName>
    </customValue>
    <customValue>
        <fullName>REINSTATE</fullName>
    </customValue>
    <customValue>
        <fullName>RENEW/REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWA</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWALINP</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWR</fullName>
    </customValue>
    <customValue>
        <fullName>REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>SUSPENDED</fullName>
    </customValue>
    <masterLabel>Membership Status</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Production.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abattoir</fullName>
    </customValue>
    <customValue>
        <fullName>Brand/Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Breeding</fullName>
    </customValue>
    <customValue>
        <fullName>Brood</fullName>
    </customValue>
    <customValue>
        <fullName>Calves</fullName>
    </customValue>
    <customValue>
        <fullName>Catching Team</fullName>
    </customValue>
    <customValue>
        <fullName>Cleaner Fish</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Dry Cows</fullName>
    </customValue>
    <customValue>
        <fullName>Finishing</fullName>
    </customValue>
    <customValue>
        <fullName>Flat deck (one-storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Flat deck (two storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Flat deck with Veranda</fullName>
    </customValue>
    <customValue>
        <fullName>Freshwater</fullName>
    </customValue>
    <customValue>
        <fullName>Gilts</fullName>
    </customValue>
    <customValue>
        <fullName>Grazing</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery (On Grower)</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery (Ova)</fullName>
    </customValue>
    <customValue>
        <fullName>Haulier</fullName>
    </customValue>
    <customValue>
        <fullName>Heifers</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-tier (one-storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-tier (two-storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-tier with Veranda</fullName>
    </customValue>
    <customValue>
        <fullName>Packer</fullName>
    </customValue>
    <customValue>
        <fullName>Processor</fullName>
    </customValue>
    <customValue>
        <fullName>Processor/Packer</fullName>
    </customValue>
    <customValue>
        <fullName>Producer</fullName>
    </customValue>
    <customValue>
        <fullName>Rearing</fullName>
    </customValue>
    <customValue>
        <fullName>Retailer</fullName>
    </customValue>
    <customValue>
        <fullName>Breeding to rearing</fullName>
    </customValue>
    <masterLabel>Production</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Vehicle_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Helicopter</fullName>
    </customValue>
    <customValue>
        <fullName>Lorry</fullName>
    </customValue>
    <customValue>
        <fullName>Trailer</fullName>
    </customValue>
    <customValue>
        <fullName>Van</fullName>
    </customValue>
    <customValue>
        <fullName>Wellboat</fullName>
    </customValue>
    <customValue>
        <fullName>TBC</fullName>
    </customValue>
    <masterLabel>Vehicle Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/RenewalPriceCheckerTest.cls
@isTest
public class RenewalPriceCheckerTest {
	@testSetup
    static void loadData(){
        List<Product2> productList = New List<Product2>();
        Product2 product = New Product2();
        product.Name= 'testProduct';
        product.Business__c='Supply Chain';
        product.Animal__c='Pigs';
        product.ProductCode='PIGSTAGE1DISCOUNT';
        product.Production__c='Processor';  
        product.IsActive=true;
        product.Pricing_Method__c='Per Site';
        product.Quantity_Threshold__c=5; 
        product.Family='Vehicle';
        product.Additional_Quantity_Pricing_Component__c=false;
        product.Dynamic_Quantity_Pricing_Component__c=false;        
        product.Vehicle_Type__c='Van';
        productList.add(product);
        
        product = New Product2();
        product.Name= 'testProduct2';
        product.Business__c='Abattoir';
        product.Animal__c='Pigs';
        product.ProductCode='PIGSTAGE1DISCOUNT';
        product.Production__c='Rearing';  
        product.IsActive=true;
        product.Pricing_Method__c='Per Site';
        product.Quantity_Threshold__c=5; 
        product.Family='Vehicle';
        product.Additional_Quantity_Pricing_Component__c=false;
        product.Dynamic_Quantity_Pricing_Component__c=false;        
        product.Vehicle_Type__c='Van';
        productList.add(product);
        
        product = New Product2();
        product.Name= 'testProduct3';
        product.Business__c='Producer';
        product.Animal__c='Pigs';
        product.ProductCode='PIGSTAGE1DISCOUNT';
        product.Production__c='Breeding to rearing';  
        product.IsActive=true;
        product.Pricing_Method__c='Per Site';
        product.Quantity_Threshold__c=5; 
        product.Family='Vehicle';
        productList.add(product);
        
        product = New Product2();
        product.Name= 'testProduct4';
        product.Business__c='Producer';
        product.Animal__c='Beef Cattle';
        product.ProductCode='PIGSTAGE1DISCOUNT';
        product.Production__c='Finishing';  
        product.IsActive=true;
        product.Pricing_Method__c='Dynamic Quantity Price';
        product.Quantity_Threshold__c=5; 
        //product.Dynamic_Quantity_Pricing_Component__c = true;
        product.Family='Vehicle';
        productList.add(product);
        
        
        product = New Product2();
        product.Name= 'testProduct4';
        product.Business__c='Producer';
        product.Animal__c='Chickens';
        product.ProductCode='PIGSTAGE1DISCOUNT';
        product.Production__c='Producer';  
        product.IsActive=true;
        product.Pricing_Method__c='Additional Quantity Price';
        product.Quantity_Threshold__c=5; 
        product.Family='Vehicle';
        productList.add(product);
        
        product = New Product2();
        product.Name= 'testProduct4';
        product.Business__c='Catching';
        product.Animal__c='Turkeys';
        product.ProductCode='PIGSTAGE1DISCOUNT';
        product.Production__c='Catching Team';  
        product.IsActive=true;
        product.Pricing_Method__c='Additional Quantity Price';
        product.Quantity_Threshold__c=5; 
        //product.Additional_Quantity_Pricing_Component__c = true;
        product.Family='Vehicle';
        productList.add(product);
        
        insert productList;
        
       Account act = new Account();
        act.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Head Office').getRecordTypeId();
        act.Name = 'Test Head Office';
        act.Status__c = 'ENQUIRY';
        insert act;

        Contact cnt = new Contact();
        cnt.AccountId = act.Id;
        cnt.FirstName = 'Test';
        cnt.LastName = 'Name';
        cnt.Email = 'test@test.com';
        insert cnt;

        act.Primary_Contact__c = cnt.Id;
        update act;

        Account site = new Account();
        site.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Site').getRecordTypeId();
        site.Name = 'Test Site';
        site.ParentId = act.Id;
        site.Company_Industry__c = 'Fish';
        site.Active__c = true;
        site.Membership_Expiry_Date__c = Date.today().addDays(14);
        site.Status__c = 'Member';
        site.Pig_Discount_Eligibility__c = true;
        insert site;

		Renewal_Price_Report__c report = new Renewal_Price_Report__c();
        report.Site__c = site.Id;
        report.Membership_Expiry_Date__c = Date.today().addDays(14);
        insert report;
        Renewal_Price_Line__c line = new Renewal_Price_Line__c();
        line.Renewal_Price_Report__c = report.Id;
        line.Total_Inc_VAT__c = 100;
        insert line;

        Application__c app = new Application__c();
        app.RecordTypeId = Schema.SObjectType.Application__c.getRecordTypeInfosByName().get('Applications').getRecordTypeId();
        app.Existing_Member__c = 'No';
        app.Application_Type__c = 'New';
        app.Stage__c = 'Application';
        app.Head_Office__c = act.Id;
        app.Site__c = site.Id;
        app.Applicant_Contact__c = cnt.Id;
        insert app;     


        List<Unit__c> units = new List<unit__c>();
        Unit__c unit1 = new Unit__c();
        unit1.Account__c = site.Id;
        unit1.Name = '01';
        unit1.Business__c = 'Supply Chain';
        unit1.Ingredients__c = 'Beef';
        unit1.Production__c = 'Processor';
        unit1.Order_Sizes__C = 'Single';
        unit1.Status__c = 'Certified';
        units.add(unit1);

        Unit__c unit2 = new Unit__c();
        unit2.Account__c = site.Id;
        unit2.Name = '02';
        unit2.Business__c = 'Supply Chain';
        unit2.Ingredients__c = 'Beef';
        unit2.Production__c = 'Processor';
        unit2.Order_Sizes__C = 'Single';
        unit2.Status__c = 'Certified';
        units.add(unit2);
        
        Unit__c unit3 = new Unit__c();
        unit3.Account__c = site.Id;
        unit3.Name = '03';
        unit3.Business__c = 'Producer';
        unit3.Production__c = 'Rearing';
        unit3.Status__c = 'Certified';
        unit3.Animals__c = 'Pigs';
        units.add(unit3);
        
        unit3 = new Unit__c();
        unit3.Account__c = site.Id;
        unit3.Name = '04';
        unit3.Business__c = 'Producer';
        unit3.Production__c = 'Breeding';
        unit3.Status__c = 'Certified';
        unit3.Animals__c = 'Ducks';
        units.add(unit3);

        
        
        unit3 = new Unit__c();
        unit3.Account__c = site.Id;
        unit3.Name = '05';
        unit3.Business__c = 'Catching';
        unit3.Production__c = 'Catching Team';
        unit3.Status__c = 'Certified';
        unit3.Animals__c = 'Ducks';
        units.add(unit3);
        
        unit3 = new Unit__c();
        unit3.Account__c = site.Id;
        unit3.Name = '05';
        unit3.Business__c = 'Hatchery';
        unit3.Production__c = 'Hatchery';
        unit3.Status__c = 'Certified';
        unit3.Animals__c = 'Salmon';
        units.add(unit3);
        
        unit3 = new Unit__c();
        unit3.Account__c =site.Id;
        unit3.Name = '05';
        unit3.Business__c = 'Haulier';
        unit3.Production__c = 'Haulier';
        unit3.Status__c = 'Certified';
        unit3.Animals__c = 'Salmon';
        unit3.Vehicle_Type__c = 'Wellboat';
        units.add(unit3);
        insert units;
    }
    @isTest
    static void testmethod1(){
        Account act = [SELECT Id FROM Account WHERE Name='Test Site'];
        RenewalPriceChecker checker = new RenewalPriceChecker();
        checker.accId = act.Id;
        checker.createRenewalPriceReport(act.Id);
    }

    @isTest
    static void testmethod2(){
        Account act = [SELECT Id FROM Account WHERE Name='Test Site'];
        List<Unit__c> units = new List<unit__c>();
        Unit__c unit3 = new Unit__c();
        

        unit3 = new Unit__c();
        unit3.Account__c = act.Id;
        unit3.Name = '06';
        unit3.Business__c = 'Producer';
        unit3.Production__c = 'Breeding to rearing';
        unit3.Status__c = 'Certified';
        unit3.Animals__c = 'Pigs';
        units.add(unit3);
        
        insert units;


        RenewalPriceChecker checker = new RenewalPriceChecker();
        checker.accId = act.Id;
        checker.createRenewalPriceReport(act.Id);
        checker.getNetAmount();
        checker.getVatAmount();
    }

    @isTest
    static void testmethod3(){
        List<RenewalPriceChecker.RenewalPriceUnitLine> listSite = new List<RenewalPriceChecker.RenewalPriceUnitLine>();
        RenewalPriceChecker checker = new RenewalPriceChecker();
        
    }

    @isTest
    static void testmethod4(){        
        List<RenewalPriceChecker.RenewalPriceUnitLine> listHO = new List<RenewalPriceChecker.RenewalPriceUnitLine>();
        RenewalPriceChecker checker = new RenewalPriceChecker();
        listHO = checker.getRenewalPriceLineForHeadOffice();
        
    }
    @isTest
    static void testmethod5(){
        Account act = [SELECT Id FROM Account WHERE Name='Test Site'];
        List<Unit__c> units = new List<unit__c>();
        Unit__c unit3 = new Unit__c();
        unit3 = new Unit__c();
        unit3.Account__c = act.Id;
        unit3.Name = '06';
        unit3.Business__c = 'Producer';
        unit3.Production__c = 'Finishing';
        unit3.Status__c = 'Certified';
        unit3.Animals__c = 'Beef Cattle';
        units.add(unit3);
        insert units;
        Product2 product = New Product2();
        product.Name= 'testProduct4';
        product.Business__c='Producer';
        product.Animal__c='Beef Cattle';
        product.ProductCode='PIGSTAGE1DISCOUNT';
        product.Production__c='Finishing';  
        product.IsActive=true;
        product.Pricing_Method__c='Additional Quantity Price';
        product.Quantity_Threshold__c=5; 
        product.Additional_Quantity_Pricing_Component__c = true;
        product.Family='Vehicle';
        product.Additional_Quantity_Product__c = [SELECT Id FROM Product2 WHERE Animal__c = 'Beef Cattle'].Id;
        insert product;

        RenewalPriceChecker checker = new RenewalPriceChecker();
        checker.accId = act.Id;
        checker.createRenewalPriceReport(act.Id);
        
    }
    @isTest
    static void testmethod6(){
        Account act = [SELECT Id FROM Account WHERE Name='Test Site'];
        List<Unit__c> units = new List<unit__c>();
        Unit__c unit3 = new Unit__c();
        unit3 = new Unit__c();
        unit3.Account__c = act.Id;
        unit3.Name = '06';
        unit3.Business__c = 'Producer';
        unit3.Production__c = 'Producer';
        unit3.Status__c = 'Certified';
        unit3.Animals__c = 'Chickens';
        unit3.Number_of_Animals__c = 5;
        unit3.Own_Transport__c = true;
        units.add(unit3);
        insert units;
        RenewalPriceChecker checker = new RenewalPriceChecker();
        checker.accId = act.Id;
        checker.createRenewalPriceReport(act.Id);
        
    }
    @isTest
    static void testmethod8(){
        Account act = [SELECT Id FROM Account WHERE Name='Test Site'];
        List<Unit__c> units = new List<unit__c>();
        Unit__c unit3 = new Unit__c();
        unit3 = new Unit__c();
        unit3.Account__c = act.Id;
        unit3.Name = '06';
        unit3.Business__c = 'Producer';
        unit3.Production__c = 'Producer';
        unit3.Status__c = 'Certified';
        unit3.Animals__c = 'Chickens';
        unit3.Number_of_Animals__c = 5;
        units.add(unit3);
        insert units;
        RenewalPriceChecker checker = new RenewalPriceChecker();
        checker.accId = act.Id;
        checker.createRenewalPriceReport(act.Id);
        
    }
    @isTest
    static void testmethod7(){
        Account act = [SELECT Id FROM Account WHERE Name='Test Site'];
        RenewalPriceChecker checker = new RenewalPriceChecker();
        checker.accId = act.Id;
        checker.getRenewalPriceLineForSite();
    }
    @isTest
    static void testmethod9(){
        Account act = [SELECT Id FROM Account WHERE Name='Test Site'];
        List<Unit__c> units = new List<unit__c>();
        Unit__c unit3 = new Unit__c();
        unit3 = new Unit__c();
        unit3.Account__c = act.Id;
        unit3.Name = '06';
        unit3.Business__c = 'Catching';
        unit3.Production__c = 'Catching Team';
        unit3.Status__c = 'Certified';
        unit3.Animals__c = 'List';
        unit3.Animals_List__c = 'Turkeys';
        unit3.Number_of_Animals__c = 5;
        units.add(unit3);
        insert units;
        RenewalPriceChecker checker = new RenewalPriceChecker();
        checker.accId = act.Id;
        checker.createRenewalPriceReport(act.Id);
        
    }
    @isTest
    static void testmethod10(){
        Account act = [SELECT Id FROM Account WHERE Name='Test Site'];
        List<Unit__c> units = new List<unit__c>();
        Unit__c unit3 = new Unit__c();
        unit3 = new Unit__c();
        unit3.Account__c = act.Id;
        unit3.Name = '06';
        unit3.Business__c = 'Catching';
        unit3.Production__c = 'Catching Team';
        unit3.Status__c = 'Certified';
        unit3.Animals__c = 'List';
        unit3.Animals_List__c = 'Turkeys';
        unit3.Number_of_Animals__c = 5;
        units.add(unit3);
        unit3 = new Unit__c();
        unit3.Account__c = act.Id;
        unit3.Name = '07';
        unit3.Business__c = 'Catching';
        unit3.Production__c = 'Catching Team';
        unit3.Status__c = 'Certified';
        unit3.Animals__c = 'List';
        unit3.Animals_List__c = 'Turkeys';
        unit3.Number_of_Animals__c = 5;
        units.add(unit3);
        insert units;
        Product2 product = New Product2();
        product.Name= 'testProduct4';
        product.Business__c='Catching';
        product.Animal__c='Turkeys';
        product.ProductCode='PIGSTAGE1DISCOUNT';
        product.Production__c='Catching Team';  
        product.IsActive=true;
        product.Pricing_Method__c='Additional Quantity Price';
        product.Quantity_Threshold__c=5; 
        product.Additional_Quantity_Pricing_Component__c = true;
        product.Family='Vehicle';
        product.Additional_Quantity_Product__c = [SELECT Id FROM Product2 WHERE Animal__c = 'Turkeys'].Id;
        insert product;
        RenewalPriceChecker checker = new RenewalPriceChecker();
        checker.accId = act.Id;
        checker.createRenewalPriceReport(act.Id);
        checker.findDynamicQuantityPricing(unit3,product);
        product.Family ='Poultry';
        product.Business__c = 'Catching team';
        checker.findAdditionalQuantityPricing(unit3,product);
    }
}