unpackaged/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is an active account.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Company_Industry__c.field-meta.xml
<CustomField>
    <fullName>Company_Industry__c</fullName>
    <description>Custom Industry muti picklist field for RSPCA Assured members as companies can have more than one industry.</description>
    <label>Company Industry</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company_Industry</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <description>List of counties for UK</description>
    <label>County</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>County</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Head_Office_Number__c.field-meta.xml
<CustomField>
    <fullName>Head_Office_Number__c</fullName>
    <inlineHelpText>The first four digits of the full membership number that represents the group</inlineHelpText>
    <label>Head Office Membership Number</label>
    <length>4</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Membership_Number__c.field-meta.xml
<CustomField>
    <fullName>Membership_Number__c</fullName>
    <formula>Parent.Head_Office_Number__c  &amp; &quot;.&quot;  &amp;  Site_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Primary Account(DoNotUse)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Site_Number__c.field-meta.xml
<CustomField>
    <fullName>Site_Number__c</fullName>
    <inlineHelpText>4 digit membership number for site.</inlineHelpText>
    <label>Site Number</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Membership_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Head_Office.recordType-meta.xml
<RecordType>
    <fullName>Head_Office</fullName>
    <active>true</active>
    <description>An Account representing the head office.</description>
    <label>Head Office</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <description>An Account representing a site.</description>
    <label>Site</label>
</RecordType>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Agreement__c.field-meta.xml
<CustomField>
    <fullName>Agreement__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>I have read and agreed to the terms of the SCI Certification UK scheme regulations and RSPCA Assured membership agreement.</inlineHelpText>
    <label>Agreement</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Applicant_Contact__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Applicant_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Full_Name__c</fullName>
    <formula>Applicant_Contact__r.FirstName  &amp; &quot; &quot;  &amp;  Applicant_Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant Full Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Application_Type__c</fullName>
    <label>Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Existing_Member__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Revisit</fullName>
            </value>
            <value>
                <fullName>Levy</fullName>
            </value>
            <value>
                <fullName>Merchandise</fullName>
            </value>
            <value>
                <fullName>Promotion/Partnership</fullName>
            </value>
            <value>
                <fullName>Consultancy</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Function: member services select an assessor; system then automatically emails them.</description>
    <inlineHelpText>This field must be populated in order to mark an Additional Visit as complete.</inlineHelpText>
    <label>Allocated Assessor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>You can only select an assessor user to be allocated for this application.</errorMessage>
        <filterItems>
            <field>User.Assessor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>User.Contract_Assessor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Existing_Member__c.field-meta.xml
<CustomField>
    <fullName>Existing_Member__c</fullName>
    <label>Existing Member?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Head_Office__c.field-meta.xml
<CustomField>
    <fullName>Head_Office__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Head Office</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Head Office</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Membership_Number__c.field-meta.xml
<CustomField>
    <fullName>Membership_Number__c</fullName>
    <formula>Site__r.Membership_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field must be populated in order to mark an Additional Visit as complete.</inlineHelpText>
    <label>Membership Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/No_Offences__c.field-meta.xml
<CustomField>
    <fullName>No_Offences__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>I confirm that I do not have any previous convictions or pending prosecutions relating to any offence involving the care, handling, transport, slaughter or sale of animals or produce.</inlineHelpText>
    <label>No Offences</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BACS</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
                <isActive>false</isActive>
                <label>Card</label>
            </value>
            <value>
                <fullName>Cheque</fullName>
                <isActive>false</isActive>
                <label>Cheque</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Signatory_Contact__c.field-meta.xml
<CustomField>
    <fullName>Signatory_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Signatory Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications (Signatory Contact)</relationshipLabel>
    <relationshipName>Applications1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>ApplicationSite</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Site_Name__c.field-meta.xml
<CustomField>
    <fullName>Site_Name__c</fullName>
    <formula>Site__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>Stage field for new applications for new site, update, or transfers. This field is used for the application record type.</description>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Application</fullName>
                <default>true</default>
                <label>Application</label>
            </value>
            <value>
                <fullName>Allocation</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Schedule</fullName>
            </value>
            <value>
                <fullName>Visit</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Site__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Assessment_Report__c/Assessment_Report__c.object-meta.xml
<CustomObject>
    <label>Assessment Report</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Assessment Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Assessment_Report__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Assessment Reports</relationshipLabel>
    <relationshipName>Assessment_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Assessment_Report__c/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assessment_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <description>List of counties for the UK</description>
    <label>County</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>County</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <formula>IF(Id = Account.Primary_Contact__r.Id , true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates that this contact is the primary contact for the account that it is affiliated with.</inlineHelpText>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Company_Industry__c.field-meta.xml
<CustomField>
    <fullName>Company_Industry__c</fullName>
    <description>Custom Industry Multi Picklist field for RSPCA Assured as a company can have more than one industry value selected.</description>
    <label>Company Industry</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company_Industry</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this box is checked, this user will be available to select during the allocation phase of the application/renewals.</description>
    <inlineHelpText>Check this box if the user is an assessor.</inlineHelpText>
    <label>Assessor</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/globalValueSets/Company_Industry.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fish</fullName>
    </customValue>
    <customValue>
        <fullName>Livestock</fullName>
    </customValue>
    <customValue>
        <fullName>Poultry</fullName>
    </customValue>
    <customValue>
        <fullName>Supply Chain</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Company Industry</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/County.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Aberdeenshire</fullName>
    </customValue>
    <customValue>
        <fullName>Angus</fullName>
    </customValue>
    <customValue>
        <fullName>Argyll &amp; Bute</fullName>
    </customValue>
    <customValue>
        <fullName>Ayrshire</fullName>
    </customValue>
    <customValue>
        <fullName>Banffshire</fullName>
    </customValue>
    <customValue>
        <fullName>Bath and North East Somerset</fullName>
    </customValue>
    <customValue>
        <fullName>Bedfordshire</fullName>
    </customValue>
    <customValue>
        <fullName>Berkshire</fullName>
    </customValue>
    <customValue>
        <fullName>Berwickshire</fullName>
    </customValue>
    <customValue>
        <fullName>Blaenau Gwent</fullName>
    </customValue>
    <customValue>
        <fullName>Bridgend</fullName>
    </customValue>
    <customValue>
        <fullName>Bristol</fullName>
    </customValue>
    <customValue>
        <fullName>Buckinghamshire</fullName>
    </customValue>
    <customValue>
        <fullName>Caerphilly</fullName>
    </customValue>
    <customValue>
        <fullName>Caithness</fullName>
    </customValue>
    <customValue>
        <fullName>Cambridgeshire</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiff</fullName>
    </customValue>
    <customValue>
        <fullName>Carmarthenshire</fullName>
    </customValue>
    <customValue>
        <fullName>Ceredigion</fullName>
    </customValue>
    <customValue>
        <fullName>Cheshire</fullName>
    </customValue>
    <customValue>
        <fullName>Clackmannanshire</fullName>
    </customValue>
    <customValue>
        <fullName>Clwyd</fullName>
    </customValue>
    <customValue>
        <fullName>Conwy</fullName>
    </customValue>
    <customValue>
        <fullName>Cornwall</fullName>
    </customValue>
    <customValue>
        <fullName>Antrim</fullName>
        <label>County Antrim</label>
    </customValue>
    <customValue>
        <fullName>Armagh</fullName>
        <label>County Armagh</label>
    </customValue>
    <customValue>
        <fullName>County Cork</fullName>
    </customValue>
    <customValue>
        <fullName>County Donegal</fullName>
    </customValue>
    <customValue>
        <fullName>Down</fullName>
        <label>County Down</label>
    </customValue>
    <customValue>
        <fullName>County Durham</fullName>
    </customValue>
    <masterLabel>County</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Membership_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ADDITION</fullName>
    </customValue>
    <customValue>
        <fullName>ARCHIVED</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC5R</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC7R</fullName>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
    </customValue>
    <customValue>
        <fullName>CONPASS</fullName>
    </customValue>
    <customValue>
        <fullName>ENQUIRY</fullName>
        <default>true</default>
        <label>ENQUIRY</label>
    </customValue>
    <customValue>
        <fullName>EVIDENCE</fullName>
    </customValue>
    <customValue>
        <fullName>FAILED</fullName>
    </customValue>
    <customValue>
        <fullName>FALLOW</fullName>
    </customValue>
    <customValue>
        <fullName>LAPSED</fullName>
    </customValue>
    <customValue>
        <fullName>MEMBER</fullName>
    </customValue>
    <customValue>
        <fullName>MONREQ</fullName>
    </customValue>
    <customValue>
        <fullName>NEW</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2R</fullName>
    </customValue>
    <customValue>
        <fullName>NEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>NONFR</fullName>
    </customValue>
    <customValue>
        <fullName>NOTINSCHEME</fullName>
    </customValue>
    <customValue>
        <fullName>PASSED</fullName>
    </customValue>
    <customValue>
        <fullName>PREPANEL</fullName>
    </customValue>
    <customValue>
        <fullName>REINSTATE</fullName>
    </customValue>
    <customValue>
        <fullName>RENEW/REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWA</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWALINP</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWR</fullName>
    </customValue>
    <customValue>
        <fullName>REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>SUSPENDED</fullName>
    </customValue>
    <masterLabel>Membership Status</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/NotificationsComponentControllerTest.cls
@isTest
public class NotificationsComponentControllerTest {
    @testSetup static void setup() {

        // Create System Admin User with Role to create the account
        FObject adminUser = new FObject('User', 1);
        adminUser.setDefinition('ProfileId', 'static lookup(Profile) field(Name) value(System Administrator) source(salesforce)');
        adminUser.setDefinition('Alias','static value(testadm)');
        adminUser.setDefinition('LastName','static value(testadmin)');
        adminUser.setDefinition('UserName','static value(testadmin543434234324@test.com)');
        adminUser.setDefinition('Email','static value(testadmin@test.com)');
        adminUser.setDefinition('UserRoleId', 'random lookup(UserRole) source(forceea)');
        adminUser.setDefinition('Assessor__c', 'static value(true)');
        adminUser.insertRecords(true);
        List<User> insertedUsers = FObject.getInsertedRecords('User');
        User insertedAdminUser = new User();
        for(User u : insertedUsers){
            if(u.Alias == 'testadm'){
                insertedAdminUser = u;
            }
        }

        System.runAs(insertedAdminUser){        
            // Lead record
            Lead l = new Lead(
                FirstName = 'first',
                LastName = 'last',
                Email = 'test@test.com',
                Company = 'TestCompany',
                Company_Industry__C = 'Fish'
            );
            insert l;
        
            // Site Account Record type
            String siteRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Site').getRecordTypeId();
            // Head Office Account Record type
            String headOfficeRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Head_Office').getRecordTypeId();

        

            // Account Records
            List<Account> accList = new List<Account>();
            Account headOffice = new Account(
                Name = 'Test Head Office',
                RecordTypeId = headOfficeRecordTypeId,
                Status__c = 'Member',
                Head_Office_Number__c = '4342',
                Active__c = true,
                OwnerId = insertedAdminUser.Id
            );
            Account site = new Account(
                Name = 'test Site',
                RecordTypeId = siteRecordTypeId,
                Company_Industry__C = 'Fish',
                Status__c = 'Member',
                Site_Number__c = '1245',
                OwnerId = insertedAdminUser.Id
            );
            accList.add(headOffice);
            accList.add(site);
            insert accList;

            // Contact Records
            Contact con = new Contact(
                FirstName = 'First',
                LastName = 'Last',
                Email = 'test324324325234@test.com',
                AccountId = site.Id
            );

            insert con;

            site.Primary_Contact__c = con.Id;

            update site;

            // Application Record
            Application__c app = new Application__c(
                Existing_Member__c = 'No',
                Stage__c = 'Application',
                Application_Type__c = 'New',
                Head_Office__c = headOffice.Id,
                Site__c = site.Id,
                No_Offences__c = true,
                Agreement__c = true,
                Agreement_Date__c = Date.today(),
                Signatory_Contact__c = con.Id,
                Payment_Method__c = 'BACS',
                Applicant_Contact__c = con.id
            );

            insert app;
        }

        
    }

    @isTest
    static void getEnquiresTest(){
        List<Lead> leadList = [SELECT Id, Name, Company, Company_Industry__c, CreatedDate, IsConverted FROM Lead WHERE IsConverted = false];
        test.startTest();
        NotificationsComponentController obj = new NotificationsComponentController();
        obj.getEnquires();
        test.stopTest();
    }

    @isTest
    static void getApplicationsTest(){
        List<Application__c> appList = [SELECT Id, Name, Membership_Number__c, Applicant_Full_Name__c, Site_Name__c, Site__r.Company_Industry__c, Site__r.County__c, CreatedDate FROM Application__c];
        test.startTest();
        NotificationsComponentController obj = new NotificationsComponentController();
        obj.getApplications();
        test.stopTest();
    }

    @isTest
    static void getPaidApplicationsTest(){
        List<Application__c> appList = [SELECT Id, Name, Membership_Number__c, Applicant_Full_Name__c, Site_Name__c, Site__r.Company_Industry__c, Site__r.County__c, CreatedDate FROM Application__c];
        for(Application__c app : appList){
            app.Paid__c = true;
        }
        update appList;
        test.startTest();
        NotificationsComponentController obj = new NotificationsComponentController();
        obj.getPaidApplications();
        test.stopTest();
    }

    @isTest
    static void getPaidCardApplicationsTest(){
        List<Application__c> appList = [SELECT Id, Name, Membership_Number__c, Applicant_Full_Name__c, Site_Name__c, Site__r.Company_Industry__c, Site__r.County__c, CreatedDate FROM Application__c];
        for(Application__c app : appList){
            app.Paid__c = true;
        }
        update appList;
        test.startTest();
        NotificationsComponentController obj = new NotificationsComponentController();
        obj.getPaidCardApplications();
        test.stopTest();
    }

    @isTest
    static void getPendingBacsChequeApplicationsTest(){
        List<Application__c> appList = [SELECT Id, Name, Membership_Number__c, Applicant_Full_Name__c, Site_Name__c, Site__r.Company_Industry__c, Site__r.County__c, CreatedDate FROM Application__c];
        test.startTest();
        NotificationsComponentController obj = new NotificationsComponentController();
        obj.getPendingBacsChequeApplications();
        test.stopTest();
    }

    @isTest
    static void getAllocationApplicationsTest(){
        List<Application__c> appList = [SELECT Id, Name, Membership_Number__c, Applicant_Full_Name__c, Site_Name__c, Site__r.Company_Industry__c, Site__r.County__c, CreatedDate FROM Application__c];
        for(Application__c app : appList){
            app.Paid__c = true;
            app.Stage__c = 'Allocation';
        }
        update appList;
        test.startTest();
        NotificationsComponentController obj = new NotificationsComponentController();
        obj.getAllocationApplications();
        test.stopTest();
    }

    @isTest
    static void getAssessorAllocationsTest(){
        //Get user
        User u = [SELECT Id, LastName, Email, Assessor__c FROM User WHERE Assessor__c = true LIMIT 1];
        List<Application__c> appList = [SELECT Id, Name, Membership_Number__c, Applicant_Full_Name__c, Site_Name__c, Site__r.Company_Industry__c, Site__r.County__c, CreatedDate FROM Application__c];
        for(Application__c app : appList){
            app.Paid__c = true;
            app.Stage__c = 'Allocation';
            // update assessor field
            app.Assessor__c = u.Id;
            app.Allocation_Status__c = 'Pending';
        }
        update appList;
        test.startTest();
        NotificationsComponentController obj = new NotificationsComponentController();
        obj.assessorId = u.Id;
        obj.getAssessorAllocations();
        test.stopTest();
    }

    @isTest
    static void getAssessmentBookingsPendingTest(){
        //Get user
        User u = [SELECT Id, LastName, Email, Assessor__c FROM User WHERE Assessor__c = true LIMIT 1];
        List<Application__c> appList = [SELECT Id, Name, Membership_Number__c, Applicant_Full_Name__c, Site_Name__c, Site__r.Company_Industry__c, Site__r.County__c, CreatedDate FROM Application__c];
        for(Application__c app : appList){
            app.Paid__c = true;
            app.Stage__c = 'Assessment';
            // update assessor field
            app.Assessor__c = u.Id;
            app.Allocation_Status__c = 'Accepted';
            app.Assessment_Date__c = null;
        }
        update appList;
        test.startTest();
        NotificationsComponentController obj = new NotificationsComponentController();
        obj.assessorId = u.Id;
        obj.getAssessmentBookingsPending();
        test.stopTest();
    }

    @isTest
    static void getAssessmentReportsPendingTest(){
        //Get user
        User u = [SELECT Id, LastName, Email, Assessor__c FROM User WHERE Assessor__c = true LIMIT 1];
        List<Application__c> appList = [SELECT Id, Name, Membership_Number__c, Applicant_Full_Name__c, Site_Name__c, Site__r.Company_Industry__c, Site__r.County__c, CreatedDate FROM Application__c];
        for(Application__c app : appList){
            app.Paid__c = true;
            app.Stage__c = 'Assessment';
            // update assessor field
            app.Assessor__c = u.Id;
            app.Allocation_Status__c = 'Accepted';
            app.Assessment_Date__c = Date.today() + 14;
        }
        update appList;
        test.startTest();
        NotificationsComponentController obj = new NotificationsComponentController();
        obj.assessorId = u.Id;
        obj.getAssessmentReportsPending();
        test.stopTest();
    }

    @isTest
    static void getAssessorApprovalsPendingTest(){
        //Get user
        User u = [SELECT Id, LastName, Email, Assessor__c FROM User WHERE Assessor__c = true LIMIT 1];
        List<Application__c> appList = [SELECT Id, Name, Membership_Number__c, Applicant_Full_Name__c, Site_Name__c, Site__r.Company_Industry__c, Site__r.County__c, CreatedDate FROM Application__c];
        for(Application__c app : appList){
            app.Paid__c = true;
            app.Stage__c = 'Compliance';
            // update assessor field
            app.Assessor__c = u.Id;
            app.Allocation_Status__c = 'Accepted';
            app.Assessment_Date__c = Date.today() + 14;
            app.Assessment_Checklist__c = 'test.com';
            app.Assessment_Report__c = 'test.com';
            app.DTA__c = 'Yes';
        }
        update appList;
        test.startTest();
        NotificationsComponentController obj = new NotificationsComponentController();
        obj.assessorId = u.Id;
        obj.getAssessorApprovalsPending();
        test.stopTest();
    }

    @isTest
    static void getRejectionApplicationsTest(){
        User u = [SELECT Id, LastName, Email, Assessor__c FROM User WHERE Assessor__c = true LIMIT 1];
        List<Application__c> appList = [SELECT Id, Name, Membership_Number__c, Applicant_Full_Name__c, Site_Name__c, Site__r.Company_Industry__c, Site__r.County__c, CreatedDate FROM Application__c];
        for(Application__c app : appList){
            app.Paid__c = true;
            app.Stage__c = 'Compliance';
            // update assessor field
            app.Assessor__c = u.Id;
            app.Allocation_Status__c = 'Accepted';
            app.Assessment_Date__c = Date.today() + 14;
            app.Reject__c = true;
            app.Rejection_Date__c = Datetime.now().addHours(-48);
            app.Reason_for_rejection__c = 'No evidence';
            app.Assessment_Checklist__c = 'test.com';
            app.Assessment_Report__c = 'test.com';
            app.DTA__c = 'Yes';
        }
        update appList;
        test.startTest();
        NotificationsComponentController obj = new NotificationsComponentController();
        obj.getRejectionApplications();
        test.stopTest();
    }

    @isTest
    static void getApprovalApplicationsOfficeTest(){
        User u = [SELECT Id, LastName, Email, Assessor__c FROM User WHERE Assessor__c = true LIMIT 1];
        List<Application__c> appList = [SELECT Id, Name, Membership_Number__c, Applicant_Full_Name__c, Site_Name__c, Site__r.Company_Industry__c, Site__r.County__c, CreatedDate FROM Application__c];
        for(Application__c app : appList){
            app.Paid__c = true;
            app.Stage__c = 'Compliance';
            // update assessor field
            app.Assessor__c = u.Id;
            app.Allocation_Status__c = 'Accepted';
            app.Assessment_Date__c = Date.today() + 14;
            app.Assessment_Checklist__c = 'test.com';
            app.Assessment_Report__c = 'test.com';
            app.DTA__c = 'Yes';
        }
        update appList;
        test.startTest();
        NotificationsComponentController obj = new NotificationsComponentController();
        obj.getApprovalApplicationsOffice();
        test.stopTest();
    }

    @isTest
    static void getApprovalApplicationsNSFTest(){
        User u = [SELECT Id, LastName, Email, Assessor__c FROM User WHERE Assessor__c = true LIMIT 1];
        List<Application__c> appList = [SELECT Id, Name, Membership_Number__c, Applicant_Full_Name__c, Site_Name__c, Site__r.Company_Industry__c, Site__r.County__c, CreatedDate FROM Application__c];
        for(Application__c app : appList){
            app.Paid__c = true;
            app.Stage__c = 'Compliance';
            // update assessor field
            app.Assessor__c = u.Id;
            app.Allocation_Status__c = 'Accepted';
            app.Assessment_Date__c = Date.today() + 14;
            app.Assessment_Checklist__c = 'test.com';
            app.Assessment_Report__c = 'test.com';
            app.DTA__c = 'Yes';
        }
        update appList;
        test.startTest();
        NotificationsComponentController obj = new NotificationsComponentController();
        obj.getApprovalApplicationsNSF();
        test.stopTest();
    }

    @isTest
    static void getCertifiedApplicationsTest(){
        User u = [SELECT Id, LastName, Email, Assessor__c FROM User LIMIT 1];
        List<Application__c> appList = [SELECT Id, Name, Applicant_Contact__c, Membership_Number__c, Applicant_Full_Name__c, Site_Name__c, Site__r.Company_Industry__c, Site__r.County__c, CreatedDate FROM Application__c];
        
        for(Application__c app : appList){
            app.Paid__c = true;
            app.Stage__c = 'Certification';
            // update assessor field
            app.Allocation_Status__c = 'Accepted';
            app.Assessment_Date__c = Date.today() + 14;
            app.Application_Approved_By_Office__c = u.Id;
            app.Application_Approved_By_Certifier__c = u.Id;
            app.Assessment_Approved_By_Office__c = u.Id;
            app.Assessment_Approved_By_Assessor__c = u.Id;
            app.Assessment_Approved_By_Certifier__c = u.Id;
            app.Evidence_Approved_By_Office__c = u.Id;
            app.Evidence_Approved_By_Assessor__c = u.Id;
            app.Evidence_Approved_By_Certifier__c = u.Id;
            app.Approved_for_Renewal__c = true;
            app.DTA__c = 'Yes';
        }
        
        update appList;
        test.startTest();
        NotificationsComponentController obj = new NotificationsComponentController();
        obj.getCertifiedApplications();
        test.stopTest();
    }
}