unpackaged/main/default/objects/Account/fields/Administrator__c.field-meta.xml
<CustomField>
    <fullName>Administrator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Auto-populated with the username of the user who requests this site for suspension.</description>
    <inlineHelpText>Auto-populated with the username of the user who requests this site for suspension.</inlineHelpText>
    <label>Administrator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Approval_Certifier__c.field-meta.xml
<CustomField>
    <fullName>Approval_Certifier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval (Certifier)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Approved__c.field-meta.xml
<CustomField>
    <fullName>Approved__c</fullName>
    <label>Approved</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Date_Requested_For_Suspension__c.field-meta.xml
<CustomField>
    <fullName>Date_Requested_For_Suspension__c</fullName>
    <label>Date Requested for Suspended</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Date_Suspended__c.field-meta.xml
<CustomField>
    <fullName>Date_Suspended__c</fullName>
    <label>Date Suspended</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Further_Information__c.field-meta.xml
<CustomField>
    <fullName>Further_Information__c</fullName>
    <label>Further Information</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reinstate</fullName>
            </value>
            <value>
                <fullName>Withdraw</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Outcome_Approved_By_Certifier__c.field-meta.xml
<CustomField>
    <fullName>Outcome_Approved_By_Certifier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outcome Approved By (Certifier)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts4</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Reason_for_Suspension__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Suspension__c</fullName>
    <description>Additional long text field for users to populate the reason for suspension, if it is not already listed.</description>
    <inlineHelpText>Please populate if the reason for suspension is not listed on the picklist.</inlineHelpText>
    <label>Other Reason for Suspension</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Reason_For_Suspension_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Reason_For_Suspension_Picklist__c</fullName>
    <description>Complaint; Incident; Assessment; Monitoring Visit; Evidence Not Returned; Other</description>
    <label>Reason For Suspension</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>Incident</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Monitoring Visit</fullName>
            </value>
            <value>
                <fullName>Evidence Not Returned</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Request_for_Suspension__c.field-meta.xml
<CustomField>
    <fullName>Request_for_Suspension__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this box if this site is under suspension. An email will automatically send for suspension approval.</inlineHelpText>
    <label>Request for Suspension</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Suspension_History__c/Suspension_History__c.object-meta.xml
<CustomObject>
    <label>Suspension History</label>
    <nameField>
        <displayFormat>SH-{0000}</displayFormat>
        <label>Suspension History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suspension Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Suspension_History__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Suspension Histories</relationshipLabel>
    <relationshipName>Suspension_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Suspension_History__c/fields/Administrator__c.field-meta.xml
<CustomField>
    <fullName>Administrator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Administrator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Suspension_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Suspension_History__c/fields/Approval_Certifier__c.field-meta.xml
<CustomField>
    <fullName>Approval_Certifier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval (Certifier)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Suspension_Histories1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Suspension_History__c/fields/Approved__c.field-meta.xml
<CustomField>
    <fullName>Approved__c</fullName>
    <label>Approved</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Suspension_History__c/fields/Date_Requested_for_Suspension__c.field-meta.xml
<CustomField>
    <fullName>Date_Requested_for_Suspension__c</fullName>
    <label>Date Requested for Suspension</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Suspension_History__c/fields/Date_Suspended__c.field-meta.xml
<CustomField>
    <fullName>Date_Suspended__c</fullName>
    <label>Date Suspended</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Suspension_History__c/fields/Further_Information__c.field-meta.xml
<CustomField>
    <fullName>Further_Information__c</fullName>
    <label>Further Information</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Suspension_History__c/fields/Outcome_Approved_By_Certifier__c.field-meta.xml
<CustomField>
    <fullName>Outcome_Approved_By_Certifier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outcome Approved By (Certifier)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Suspension_Histories2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Suspension_History__c/fields/Reason_For_Suspension__c.field-meta.xml
<CustomField>
    <fullName>Reason_For_Suspension__c</fullName>
    <label>Reason For Suspension</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ClearSuspensionCntrl.cls
public class ClearSuspensionCntrl {
    
    private ApexPages.StandardController standardController;
    
    public ClearSuspensionCntrl(ApexPages.StandardController standardController){
        this.standardController = standardController;
    }
    
    public PageReference createSuspensionHistory(){
        Id actId = standardController.getId();
        Account act = [SELECT Id, Name, Request_for_Suspension__c, Date_Requested_For_Suspension__c, 
                       Reason_For_Suspension_Picklist__c, Reason_for_Suspension__c, Administrator__c, 
                       Approval_Certifier__c, Approved__c, Outcome_Approved_By_Certifier__c, Further_Information__c, 
                       Date_Suspended__c, Outcome__c FROM Account WHERE Id =: actId];
        if(act.Request_for_Suspension__c){
            /** Create suspension history record **/
            Suspension_History__c ssh = new Suspension_History__c();
            ssh.Account__c = act.Id;
            ssh.Administrator__c = act.Administrator__c;
            ssh.Approved__c = act.Approved__c;
            ssh.Approval_Certifier__c = act.Approval_Certifier__c;
            ssh.Date_Requested_for_Suspension__c = act.Date_Requested_For_Suspension__c;
            ssh.Date_Suspended__c = act.Date_Suspended__c;
            ssh.Further_Information__c = act.Further_Information__c;
            if(act.Reason_For_Suspension_Picklist__c == 'Other'){
                ssh.Reason_For_Suspension__c = act.Reason_for_Suspension__c;
            }else{
                ssh.Reason_For_Suspension__c = act.Reason_For_Suspension_Picklist__c;
            }
            ssh.Outcome__c = act.Outcome__c;
            ssh.Outcome_Approved_By_Certifier__c = act.Outcome_Approved_By_Certifier__c;
			
            /** clear suspension fields on account record **/
            act.Request_for_Suspension__c = false;
            act.Reason_For_Suspension_Picklist__c = null;
            act.Reason_for_Suspension__c = null;
            act.Date_Requested_For_Suspension__c = null;
            act.Administrator__c = null;
            act.Approval_Certifier__c = null;
            act.Approved__c = null;
            act.Date_Suspended__c = null;
            act.Further_Information__c = null;
            act.Outcome__c = null;
            act.Outcome_Approved_By_Certifier__c = null;
            try{
                insert ssh;
                update act;
            }catch(DMLException e){
                System.debug('Error while clearing suspension '+e.getMessage());
            }
        }
        PageReference pg = new PageReference('/'+act.Id);
        pg.setRedirect(true);
        return pg;  
    }
}