unpackaged/main/default/objects/Account/fields/Certificate_Expiry_Date_Calculated__c.field-meta.xml
<CustomField>
    <fullName>Certificate_Expiry_Date_Calculated__c</fullName>
    <formula>ADDMONTHS(Certificate_Issue_Date__c,12)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Certificate Expiry Date Calculated</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Certificate_Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Certificate_Issue_Date__c</fullName>
    <label>Certificate Issue Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <description>List of counties for UK</description>
    <label>County</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>County</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Membership_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Membership_Expiry_Date__c</fullName>
    <inlineHelpText>Membership Expiry Date is 1 year after the Certificate Issue Date by Default. However if common renewal date is used, then Membership Expiry Date reflects when the sites will need to renew by from a group level.</inlineHelpText>
    <label>Membership Expiry Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Membership_Number__c.field-meta.xml
<CustomField>
    <fullName>Membership_Number__c</fullName>
    <formula>Parent.Head_Office_Number__c  &amp; &quot;.&quot;  &amp;  Site_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Previous_Assessment_Date__c.field-meta.xml
<CustomField>
    <fullName>Previous_Assessment_Date__c</fullName>
    <label>Previous Assessment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Membership_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Assessment_Approved_By_Assessor_Date__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Approved_By_Assessor_Date__c</fullName>
    <label>Assessment Approved By (Assessor) Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Assessment_Approved_By_Certifier_Date__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Approved_By_Certifier_Date__c</fullName>
    <label>Assessment Approved By (Certifier) Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Assessment_Date__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Date__c</fullName>
    <description>Cannot exceed the deadline date; can be updated if rearranged</description>
    <inlineHelpText>The date the site will be assessed</inlineHelpText>
    <label>Assessment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Membership_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Membership_Expiry_Date__c</fullName>
    <formula>Site__r.Membership_Expiry_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership Expiry Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Membership_Number__c.field-meta.xml
<CustomField>
    <fullName>Membership_Number__c</fullName>
    <formula>Site__r.Membership_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field must be populated in order to mark an Additional Visit as complete.</inlineHelpText>
    <label>Membership Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Previous_Assessment_Date__c.field-meta.xml
<CustomField>
    <fullName>Previous_Assessment_Date__c</fullName>
    <label>Previous Assessment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>ApplicationSite</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>Stage field for new applications for new site, update, or transfers. This field is used for the application record type.</description>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Application</fullName>
                <default>true</default>
                <label>Application</label>
            </value>
            <value>
                <fullName>Allocation</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Schedule</fullName>
            </value>
            <value>
                <fullName>Visit</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Site__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <description>For renewal applications</description>
    <label>Renewal</label>
</RecordType>

unpackaged/main/default/objects/Application_Unit__c/Application_Unit__c.object-meta.xml
<CustomObject>
    <label>Application Unit</label>
    <nameField>
        <displayFormat>APUN-{00}</displayFormat>
        <label>APP Unit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application_Unit__c/fields/Animals__c.field-meta.xml
<CustomField>
    <fullName>Animals__c</fullName>
    <formula>TEXT( Unit__r.Animals__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Animals</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Application Units</relationshipLabel>
    <relationshipName>ApplicationUnits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <formula>TEXT(Unit__r.Business__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Business</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/fields/Own_Transport__c.field-meta.xml
<CustomField>
    <fullName>Own_Transport__c</fullName>
    <formula>Unit__r.Own_Transport__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Own Transport</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/fields/Production__c.field-meta.xml
<CustomField>
    <fullName>Production__c</fullName>
    <formula>TEXT( Unit__r.Production__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Production</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Application Units</relationshipLabel>
    <relationshipName>Application_Units</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Checklist_Template__c/Checklist_Template__c.object-meta.xml
<CustomObject>
    <label>Checklist Template</label>
    <nameField>
        <label>Checklist Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklist Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Checklist_Template__c/fields/Scheme_Wording__c.field-meta.xml
<CustomField>
    <fullName>Scheme_Wording__c</fullName>
    <label>Scheme Wording</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Checklist_Template__c/fields/Species__c.field-meta.xml
<CustomField>
    <fullName>Species__c</fullName>
    <label>Species</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Animals</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Checklist_Template__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Checklist_Template__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard Checklist</fullName>
            </value>
            <value>
                <fullName>Welfare Outcome Checklist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Unit__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Animals__c.field-meta.xml
<CustomField>
    <fullName>Animals__c</fullName>
    <label>Animals</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Animals</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Animals_List__c.field-meta.xml
<CustomField>
    <fullName>Animals_List__c</fullName>
    <label>List of Animals</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Animals</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Own_Transport__c.field-meta.xml
<CustomField>
    <fullName>Own_Transport__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Own Transport</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Production__c.field-meta.xml
<CustomField>
    <fullName>Production__c</fullName>
    <label>Production</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Production</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Rearing_System__c.field-meta.xml
<CustomField>
    <fullName>Rearing_System__c</fullName>
    <label>Rearing System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rearing_System</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applying</fullName>
                <default>true</default>
                <label>Applying</label>
            </value>
            <value>
                <fullName>Certified</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Vehicle_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Animals.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Beef Cattle</fullName>
    </customValue>
    <customValue>
        <fullName>Chickens</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy Cattle</fullName>
    </customValue>
    <customValue>
        <fullName>Ducklings</fullName>
    </customValue>
    <customValue>
        <fullName>Ducks</fullName>
    </customValue>
    <customValue>
        <fullName>Laying Hen Chicks</fullName>
    </customValue>
    <customValue>
        <fullName>Laying Hens</fullName>
    </customValue>
    <customValue>
        <fullName>Lumpfish</fullName>
    </customValue>
    <customValue>
        <fullName>Meat Chicken Chicks</fullName>
    </customValue>
    <customValue>
        <fullName>Pigs</fullName>
    </customValue>
    <customValue>
        <fullName>Pullets</fullName>
    </customValue>
    <customValue>
        <fullName>Salmon</fullName>
    </customValue>
    <customValue>
        <fullName>Sheep</fullName>
    </customValue>
    <customValue>
        <fullName>Trout</fullName>
    </customValue>
    <customValue>
        <fullName>Turkey Poults</fullName>
    </customValue>
    <customValue>
        <fullName>Turkeys</fullName>
    </customValue>
    <customValue>
        <fullName>Veal Calves</fullName>
    </customValue>
    <customValue>
        <fullName>Wrasse</fullName>
    </customValue>
    <customValue>
        <fullName>List</fullName>
    </customValue>
    <masterLabel>Animals</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Business.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abattoir</fullName>
    </customValue>
    <customValue>
        <fullName>Catching</fullName>
    </customValue>
    <customValue>
        <fullName>Cleaner Fish</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery</fullName>
    </customValue>
    <customValue>
        <fullName>Haulier</fullName>
    </customValue>
    <customValue>
        <fullName>Producer</fullName>
    </customValue>
    <customValue>
        <fullName>Supply Chain</fullName>
    </customValue>
    <masterLabel>Business</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/County.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Aberdeenshire</fullName>
    </customValue>
    <customValue>
        <fullName>Angus</fullName>
    </customValue>
    <customValue>
        <fullName>Argyll &amp; Bute</fullName>
    </customValue>
    <customValue>
        <fullName>Ayrshire</fullName>
    </customValue>
    <customValue>
        <fullName>Banffshire</fullName>
    </customValue>
    <customValue>
        <fullName>Bath and North East Somerset</fullName>
    </customValue>
    <customValue>
        <fullName>Bedfordshire</fullName>
    </customValue>
    <customValue>
        <fullName>Berkshire</fullName>
    </customValue>
    <customValue>
        <fullName>Berwickshire</fullName>
    </customValue>
    <customValue>
        <fullName>Blaenau Gwent</fullName>
    </customValue>
    <customValue>
        <fullName>Bridgend</fullName>
    </customValue>
    <customValue>
        <fullName>Bristol</fullName>
    </customValue>
    <customValue>
        <fullName>Buckinghamshire</fullName>
    </customValue>
    <customValue>
        <fullName>Caerphilly</fullName>
    </customValue>
    <customValue>
        <fullName>Caithness</fullName>
    </customValue>
    <customValue>
        <fullName>Cambridgeshire</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiff</fullName>
    </customValue>
    <customValue>
        <fullName>Carmarthenshire</fullName>
    </customValue>
    <customValue>
        <fullName>Ceredigion</fullName>
    </customValue>
    <customValue>
        <fullName>Cheshire</fullName>
    </customValue>
    <customValue>
        <fullName>Clackmannanshire</fullName>
    </customValue>
    <customValue>
        <fullName>Clwyd</fullName>
    </customValue>
    <customValue>
        <fullName>Conwy</fullName>
    </customValue>
    <customValue>
        <fullName>Cornwall</fullName>
    </customValue>
    <customValue>
        <fullName>Antrim</fullName>
        <label>County Antrim</label>
    </customValue>
    <customValue>
        <fullName>Armagh</fullName>
        <label>County Armagh</label>
    </customValue>
    <customValue>
        <fullName>County Cork</fullName>
    </customValue>
    <customValue>
        <fullName>County Donegal</fullName>
    </customValue>
    <customValue>
        <fullName>Down</fullName>
        <label>County Down</label>
    </customValue>
    <customValue>
        <fullName>County Durham</fullName>
    </customValue>
    <masterLabel>County</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Membership_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ADDITION</fullName>
    </customValue>
    <customValue>
        <fullName>ARCHIVED</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC5R</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC7R</fullName>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
    </customValue>
    <customValue>
        <fullName>CONPASS</fullName>
    </customValue>
    <customValue>
        <fullName>ENQUIRY</fullName>
        <default>true</default>
        <label>ENQUIRY</label>
    </customValue>
    <customValue>
        <fullName>EVIDENCE</fullName>
    </customValue>
    <customValue>
        <fullName>FAILED</fullName>
    </customValue>
    <customValue>
        <fullName>FALLOW</fullName>
    </customValue>
    <customValue>
        <fullName>LAPSED</fullName>
    </customValue>
    <customValue>
        <fullName>MEMBER</fullName>
    </customValue>
    <customValue>
        <fullName>MONREQ</fullName>
    </customValue>
    <customValue>
        <fullName>NEW</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2R</fullName>
    </customValue>
    <customValue>
        <fullName>NEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>NONFR</fullName>
    </customValue>
    <customValue>
        <fullName>NOTINSCHEME</fullName>
    </customValue>
    <customValue>
        <fullName>PASSED</fullName>
    </customValue>
    <customValue>
        <fullName>PREPANEL</fullName>
    </customValue>
    <customValue>
        <fullName>REINSTATE</fullName>
    </customValue>
    <customValue>
        <fullName>RENEW/REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWA</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWALINP</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWR</fullName>
    </customValue>
    <customValue>
        <fullName>REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>SUSPENDED</fullName>
    </customValue>
    <masterLabel>Membership Status</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Production.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abattoir</fullName>
    </customValue>
    <customValue>
        <fullName>Brand/Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Breeding</fullName>
    </customValue>
    <customValue>
        <fullName>Brood</fullName>
    </customValue>
    <customValue>
        <fullName>Calves</fullName>
    </customValue>
    <customValue>
        <fullName>Catching Team</fullName>
    </customValue>
    <customValue>
        <fullName>Cleaner Fish</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Dry Cows</fullName>
    </customValue>
    <customValue>
        <fullName>Finishing</fullName>
    </customValue>
    <customValue>
        <fullName>Flat deck (one-storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Flat deck (two storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Flat deck with Veranda</fullName>
    </customValue>
    <customValue>
        <fullName>Freshwater</fullName>
    </customValue>
    <customValue>
        <fullName>Gilts</fullName>
    </customValue>
    <customValue>
        <fullName>Grazing</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery (On Grower)</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery (Ova)</fullName>
    </customValue>
    <customValue>
        <fullName>Haulier</fullName>
    </customValue>
    <customValue>
        <fullName>Heifers</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-tier (one-storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-tier (two-storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-tier with Veranda</fullName>
    </customValue>
    <customValue>
        <fullName>Packer</fullName>
    </customValue>
    <customValue>
        <fullName>Processor</fullName>
    </customValue>
    <customValue>
        <fullName>Processor/Packer</fullName>
    </customValue>
    <customValue>
        <fullName>Producer</fullName>
    </customValue>
    <customValue>
        <fullName>Rearing</fullName>
    </customValue>
    <customValue>
        <fullName>Retailer</fullName>
    </customValue>
    <masterLabel>Production</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Rearing_System.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Barn</fullName>
    </customValue>
    <customValue>
        <fullName>Free Range</fullName>
    </customValue>
    <customValue>
        <fullName>Indoor</fullName>
    </customValue>
    <customValue>
        <fullName>Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Outdoor Bred</fullName>
    </customValue>
    <customValue>
        <fullName>Outdoor Reared</fullName>
    </customValue>
    <customValue>
        <fullName>n/a</fullName>
    </customValue>
    <customValue>
        <fullName>Pasture</fullName>
    </customValue>
    <masterLabel>Rearing System</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Vehicle_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Helicopter</fullName>
    </customValue>
    <customValue>
        <fullName>Lorry</fullName>
    </customValue>
    <customValue>
        <fullName>Trailer</fullName>
    </customValue>
    <customValue>
        <fullName>Van</fullName>
    </customValue>
    <customValue>
        <fullName>Wellboat</fullName>
    </customValue>
    <customValue>
        <fullName>TBC</fullName>
    </customValue>
    <masterLabel>Vehicle Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CertificatesController.cls
public class CertificatesController {
    public Account currentRecord{get;set;}
    public Checklist_Template__c chechlistTemplateRecord{get;set;}
    public Application_Unit__c ApplicationUnitRecord{get;set;}
    public String startDate{get;set;}
    public String endDate{get;set;}
    public String species{ get; set; }


    public Map<Integer, String> monthsMap = new Map<Integer, String>{
        1  => 'January',
        2  => 'February',
        3  => 'March',
        4  => 'April',
        5  => 'May',
        6  => 'June',
        7  => 'July',
        8  => 'August',
        9  => 'September',
        10 => 'October',
        11 => 'November',
        12 => 'December'
    };

    public CertificatesController() {
        currentRecord = [SELECT Id, Name, Parent.Name, Membership_Number__c, Membership_Expiry_Date__c, Certificate_Issue_Date__c, Previous_Assessment_Date__c, Certificate_Expiry_Date_Calculated__c, BillingStreet, BillingCity, County__c, BillingCountry, BillingPostalcode
                         FROM Account WHERE Id = :ApexPages.currentPage().getParameters().get('id')];
        
        species = ApexPages.currentPage().getParameters().get('species');
        System.debug('species '+species);
        // Getting Application records based on Account Records
        System.debug('App Unit '+[SELECT Id,Name,Application__c,Application__r.Name,Application__r.Stage__c,Application__r.Assessment_Approved_By_Assessor_Date__c,Application__r.Assessment_Date__c, Application__r.Previous_Assessment_Date__c,Application__r.Site__c, Application__r.Site__r.Name,Application__r.Status__c,Animals__c FROM Application_Unit__c]);
        ApplicationUnitRecord = [SELECT Id,Name,Application__c,Application__r.Name,Application__r.Stage__c,Application__r.Assessment_Approved_By_Assessor_Date__c,Application__r.Assessment_Date__c, Application__r.Previous_Assessment_Date__c,Application__r.Site__c, Application__r.Site__r.Name,Application__r.Status__c,Animals__c FROM Application_Unit__c WHERE Application__r.Site__c =:ApexPages.currentPage().getParameters().get('id') AND Application__r.Assessment_Approved_By_Certifier_Date__c != NULL AND Animals__c =:species ORDER BY Application__r.Name DESC LIMIT 1];
        
		
        // Getting Checklist Template Record based on Renewal Date and Species.
        List<Checklist_Template__c> chechlistTemplateList = [SELECT Id, Name, Type__c, Species__c, Status__c, Animals_List__c, Start_Date__c, End_Date__c, Scheme_Wording__c
                                                             FROM Checklist_Template__c WHERE Species__c = :species];

        System.debug('chechlistTemplateList '+chechlistTemplateList);
        for(Checklist_Template__c objCT: chechlistTemplateList){
            System.debug('objCT.Start_Date__c '+objCT.Start_Date__c);
            System.debug('objCT.End_Date__c '+objCT.End_Date__c);
            if(ApplicationUnitRecord.Application__r.Assessment_Date__c >= objCT.Start_Date__c && ApplicationUnitRecord.Application__r.Assessment_Date__c <= objCT.End_Date__c){
                chechlistTemplateRecord = objCT;
            }
        }                            

        if(currentRecord.Certificate_Issue_Date__c != null){
            startDate = currentRecord.Certificate_Issue_Date__c.day() + ' ' + monthsMap.get(currentRecord.Certificate_Issue_Date__c.month()) + ' ' + currentRecord.Certificate_Issue_Date__c.year();
        }
        if(currentRecord.Membership_Expiry_Date__c != null){
            endDate = currentRecord.Membership_Expiry_Date__c.day() + ' ' + monthsMap.get(currentRecord.Membership_Expiry_Date__c.month()) + ' ' + currentRecord.Membership_Expiry_Date__c.year();
        }
    }
    //method to get a list of supply chain units
    public List<Unit__c> getSupplyChainUnits(){
        List<Unit__c> unitList = [SELECT Id, Name, Account__c, Business__c, Description__c, Animals__c, Production__c, Rearing_System__c, Status__c, Vehicle_Registration__c, Vehicle_Type__c, Own_Transport__c FROM Unit__c WHERE Account__c =:currentRecord.Id AND Status__c = 'Certified' AND Business__c = 'Supply Chain'];
        return unitList;
    }

    // Method to get a list of trout units
    public List<Unit__c> getTrouts(){
        Set<String> businessSet = new Set<String>{
            'Hatchery',
            'Haulier',
            'Abattoir',
            'Producer'
        };
        List<Unit__c> troutList = [SELECT Id, Name, Account__c, Business__c, Description__c, Animals__c, Production__c, Rearing_System__c, Status__c, Vehicle_Registration__c, Vehicle_Type__c, Own_Transport__c FROM Unit__c WHERE Account__c =:currentRecord.Id AND Status__c = 'Certified' AND Business__c IN:businessSet AND Animals__c = 'Trout'];
        return troutList;
    } 

    //method to get a list of Animals Units exluding trout
    public List<Unit__c> getNSFUKASUnits(){
        Set<String> businessSet = new Set<String>{
            'Hatchery',
            'Haulier',
            'Abattoir',
            'Producer',
            'Cleaner Fish',
            'Catching'
        };
        // Old query has trout and new query does not
        //List<Unit__c> unitList = [SELECT Id, Name, Account__c, Business__c, Description__c, Animals__c, Production__c, Rearing_System__c, Status__c, Vehicle_Registration__c, Own_Transport__c FROM Unit__c WHERE Account__c =:currentRecord.Id AND Status__c = 'Certified' AND Business__c IN:businessSet AND Animals__c != 'Trout'];
        List<Unit__c> unitList = [SELECT Id, Name, Account__c, Business__c, Description__c, Animals__c, Production__c, Rearing_System__c, Status__c, Vehicle_Registration__c,Vehicle_Type__c, Own_Transport__c FROM Unit__c WHERE Account__c =:currentRecord.Id AND Status__c = 'Certified' AND Business__c IN:businessSet];
        return unitList;
    }

    // This method gets the animals list for the trout certification with the word "Scheme" or "Schemes" appended to it
    public String getTroutAnimalScheme() {
        String animalsString = '';
        Set<String> animalsSet = new Set<String>();
        for(Unit__c u : getTrouts()){
            animalsSet.add(u.Animals__c);
        }
        // Converting set to list in order to the the initial value from 0
        List<String> animalsList = new List<String>(animalsSet);
        // place the first animal from the set
        if(animalsSet.size() > 0){
            animalsString = animalsList[0];
        }
        // add additonal animals to the string with concatanation
        if(animalsSet.size() > 1){
            //Commented out as the query inside geTrouts() methods is filtering animals by trout so there will only be 1 animal inside the set
            /*
            for(String animal: animalsSet){
                if(animal != animalsString){
                    animalsString = animalsString + ' and ' + animal; 
                }
            }
            // adding "Schemes" for plural animals
            animalsString = animalsString + ' Schemes';
            */
        }else{
            // adding "Scheme" for singulr animal
            animalsString = animalsString + ' Scheme';
        }
        return animalsString;
    }

    // This method gets the animals list for the trout certification
    public String getTroutAnimals() {
        String animalsString = '';
        Set<String> animalsSet = new Set<String>();
        for(Unit__c u : getTrouts()){
            animalsSet.add(u.Animals__c);
        }
        // Converting set to list in order to the the initial value from 0
        List<String> animalsList = new List<String>(animalsSet);
        // place the first animal from the list
        if(animalsList.size() > 0){
            animalsString = animalsList[0];
        }
        // add additonal animals to the string with concatanation
        if(animalsList.size() > 1){
            //Commented out as the query inside geTrouts() methods is filtering animals by trout so there will only be 1 animal inside the set
            /*
            for(String animal: animalsList){
                if(animal != animalsString){
                    animalsString = animalsString + ' and ' + animal; 
                }
            }
            */
        }
        return animalsString;
    }

    public String getTroutRearingSystems(){
        String rearingSystemAnimalString = '';
        Set<String> rearingSystemAnimalSet = new Set<String>();
        for(Unit__c u : getTrouts()){
            rearingSystemAnimalSet.add(u.Rearing_System__c + ' ' + u.Animals__c);
        }
        // Converting set to list in order to the the initial value from 0
        List<String> rearingSystemAnimalList = new List<String>(rearingSystemAnimalSet);
        // Place the first Rearing System Animal from the list
        if(rearingSystemAnimalList.size() > 0){
            rearingSystemAnimalString = rearingSystemAnimalList[0];
        }
        // add additional rearing system animals to the string with concatenation
        if(rearingSystemAnimalList.size() > 1){
            //Commented out as the query inside geTrouts() methods is filtering animals by trout so there will only be 1 animal inside the set
            /*
            for(String rearingAnimal : rearingSystemAnimalList){
                if(rearingAnimal != rearingSystemAnimalString){
                    rearingSystemAnimalString = rearingSystemAnimalString + ' and ' + rearingAnimal;
                }
            }
            // adding "Units" for plural animals
            rearingSystemAnimalString = rearingSystemAnimalString + ' Units';
            */
        }else {
            // adding "Scheme" for singulr animal
            rearingSystemAnimalString = rearingSystemAnimalString + ' Unit';
        }

        return rearingSystemAnimalString;
    }
    
    // This method gets the animals list for the NSF UKAS certification with the word "Scheme" or "Schemes" appended to it
    public String getAllAnimalScheme() {
        String animalsString = '';
        Set<String> animalsSet = new Set<String>();
        for(Unit__c u : getNSFUKASUnits()){
            animalsSet.add(u.Animals__c);
        }
        // Converting set to list in order to the the initial value from 0
        List<String> animalsList = new List<String>(animalsSet);
        // place the first animal from the set
        if(animalsSet.size() > 0){
            animalsString = animalsList[0];
        }
        // add additonal animals to the string with concatanation
        if(animalsSet.size() > 1){
            for(String animal: animalsSet){
                if(animal != animalsString){
                    animalsString = animalsString + ' and ' + animal; 
                }
            }
            // adding "Schemes" for plural animals
            animalsString = animalsString + ' Schemes';
        }else{
            // adding "Scheme" for singulr animal
            animalsString = animalsString + ' Scheme';
        }
        return animalsString;
    }

    // This method gets the animals list for the NSF UKAS certification. Get's all except trouts.
    public String getAllAnimals() {
        String animalsString = '';
        Set<String> animalsSet = new Set<String>();
        for(Unit__c u : getNSFUKASUnits()){
            animalsSet.add(u.Animals__c);
        }
        // Converting set to list in order to the the initial value from 0
        List<String> animalsList = new List<String>(animalsSet);
        // place the first animal from the list
        if(animalsList.size() > 0){
            animalsString = animalsList[0];
        }
        // add additonal animals to the string with concatanation
        if(animalsList.size() > 1){
            for(String animal: animalsList){
                if(animal != animalsString){
                    animalsString = animalsString + ' and ' + animal; 
                }
            }
        }
        return animalsString;
    }

    // This method gets the rearing system for all amimals except for trout
    public String getAllAnimalRearingSystems(){
        String rearingSystemAnimalString = '';
        Set<String> rearingSystemAnimalSet = new Set<String>();
        for(Unit__c u : getNSFUKASUnits()){
            rearingSystemAnimalSet.add(u.Rearing_System__c + ' ' + u.Animals__c);
        }
        // Converting set to list in order to the the initial value from 0
        List<String> rearingSystemAnimalList = new List<String>(rearingSystemAnimalSet);
        // Place the first Rearing System Animal from the list
        if(rearingSystemAnimalList.size() > 0){
            rearingSystemAnimalString = rearingSystemAnimalList[0];
        }
        // add additional rearing system animals to the string with concatenation
        if(rearingSystemAnimalList.size() > 1){
            for(String rearingAnimal : rearingSystemAnimalList){
                if(rearingAnimal != rearingSystemAnimalString){
                    rearingSystemAnimalString = rearingSystemAnimalString + ' and ' + rearingAnimal;
                }
            }
            // adding "Units" for plural animals
            rearingSystemAnimalString = rearingSystemAnimalString + ' Units';
        }else {
            // adding "Scheme" for singulr animal
            rearingSystemAnimalString = rearingSystemAnimalString + ' Unit';
        }

        return rearingSystemAnimalString;
    }

    // get SCI Scheme Texts
    // Updated the logic based on Checklist Template record
    public String getSCISchemeTexts(){
        
        Set<String> checklistTextSet = new Set<String>();
        if(chechlistTemplateRecord != null){
            for (Unit__c u : getNSFUKASUnits()){
                if (u.Business__c == 'Producer'){
                    if (u.Animals__c == chechlistTemplateRecord.Species__c){
                        checklistTextSet.add(chechlistTemplateRecord.Scheme_Wording__c);
                    }
                }
                if (u.Business__c == 'Abattoir'){
                    if (u.Animals__c == 'Salmon'){
                        if (chechlistTemplateRecord.Species__c == 'Salmon'){
                            checklistTextSet.add(chechlistTemplateRecord.Scheme_Wording__c);
                        }
                    } else{
                        if (chechlistTemplateRecord.Species__c == 'Abattoir'){
                            checklistTextSet.add(chechlistTemplateRecord.Scheme_Wording__c);
                        }
                    }
                }
                if (u.Business__c == 'Catching'){
                    if (chechlistTemplateRecord.Species__c == 'Catching'){
                        checklistTextSet.add(chechlistTemplateRecord.Scheme_Wording__c);
                    }
                }
                if (u.Business__c == 'Hatchery'){
                    if (u.Animals__c == 'Salmon'){
                        if (chechlistTemplateRecord.Species__c == 'Salmon'){
                            checklistTextSet.add(chechlistTemplateRecord.Scheme_Wording__c);
                        }
                    } else{
                        if (chechlistTemplateRecord.Species__c == 'Hatchery'){
                            checklistTextSet.add(chechlistTemplateRecord.Scheme_Wording__c);
                        }
                    }
                }
                if (u.Business__c == 'Haulier'){
                    if (u.Animals__c == 'Salmon'){
                        if (u.Vehicle_Type__c == 'Wellboat'){
                            if (chechlistTemplateRecord.Species__c == 'Salmon'){
                                checklistTextSet.add(chechlistTemplateRecord.Scheme_Wording__c);
                            }
                        }
                        if (u.Vehicle_Type__c == 'Helicopter'){
                            if (chechlistTemplateRecord.Species__c == 'Salmon'){
                                checklistTextSet.add(chechlistTemplateRecord.Scheme_Wording__c);
                            }
                        }
                    } else{
                        if (u.Own_Transport__c){
                            if (chechlistTemplateRecord.Species__c == 'Own Transport'){
                                checklistTextSet.add(chechlistTemplateRecord.Scheme_Wording__c);
                            }
                        } else{
                            if (chechlistTemplateRecord.Species__c == 'Haulier'){
                                checklistTextSet.add(chechlistTemplateRecord.Scheme_Wording__c);
                            }
                        }
                    }
                }
            }
            if(checklistTextSet.size() == 0 && chechlistTemplateRecord.Scheme_Wording__c != null){
                checklistTextSet.add(chechlistTemplateRecord.Scheme_Wording__c);
            }
        }
        String checklistTextString = '';
        
        // Converting set to list in order to the the initial value from 0
        List<String> checklistTextValuesFromSet = new List<String>(checklistTextSet);
        // place the first animal from the set
        if (checklistTextValuesFromSet.size() > 0){
            checklistTextString = checklistTextValuesFromSet[0];
        }
        
        // add additonal scheme to the string with concatanation
        if (checklistTextValuesFromSet.size() > 1){
            for (String scheme : checklistTextValuesFromSet){
                if (scheme != checklistTextString){
                    checklistTextString = checklistTextString + ' and ' + scheme;
                }
            }
        }
        return checklistTextString;
    }
    
    // get SCI Scheme Texts
    // Updated the logic based on Checklist Template record
    public String getSCISchemeTitle(){
        Set<String> checklistTitle = new Set<String>();
        if(chechlistTemplateRecord != null){
            for (Unit__c u : getNSFUKASUnits()){
                if (u.Business__c == 'Producer'){
                    if (u.Animals__c == chechlistTemplateRecord.Species__c){
                        checklistTitle.add(chechlistTemplateRecord.Name);
                    }
                }
                if (u.Business__c == 'Abattoir'){
                    if (u.Animals__c == 'Salmon'){
                        if (chechlistTemplateRecord.Species__c == 'Salmon'){
                            checklistTitle.add(chechlistTemplateRecord.Name);
                        }
                    } else{
                        if (chechlistTemplateRecord.Species__c == 'Abattoir'){
                            // do nothing as the Scheme title will be 'RSPCA Assured Scheme'
                        }
                    }
                }
                if (u.Business__c == 'Catching'){
                    if (chechlistTemplateRecord.Species__c == 'Catching'){
                        checklistTitle.add(chechlistTemplateRecord.Name);
                    }
                }
                if (u.Business__c == 'Hatchery'){
                    if (u.Animals__c == 'Salmon'){
                        if (chechlistTemplateRecord.Species__c == 'Salmon'){
                            checklistTitle.add(chechlistTemplateRecord.Name);
                        }
                    } else{
                        if (chechlistTemplateRecord.Species__c == 'Hatchery'){
                            checklistTitle.add(chechlistTemplateRecord.Name);
                        }
                    }
                }
                if (u.Business__c == 'Haulier'){
                    if (u.Animals__c == 'Salmon'){
                        if (u.Vehicle_Type__c == 'Wellboat'){
                            if (chechlistTemplateRecord.Species__c == 'Salmon'){
                                checklistTitle.add(chechlistTemplateRecord.Name);
                            }
                        }
                        if (u.Vehicle_Type__c == 'Helicopter'){
                            if (chechlistTemplateRecord.Species__c == 'Salmon'){
                                checklistTitle.add(chechlistTemplateRecord.Name);
                            }
                        }
                    } else{
                        if (u.Own_Transport__c){
                            if (chechlistTemplateRecord.Species__c == 'Own Transport'){
                                checklistTitle.add(chechlistTemplateRecord.Name);
                            }
                        } else{
                            if (chechlistTemplateRecord.Species__c == 'Haulier'){
                                // do nothing as the Scheme title will be 'RSPCA Assured Scheme'
                            }
                        }
                    }
                }
            }
            if(checklistTitle.size() == 0 && chechlistTemplateRecord.Name != null){
                checklistTitle.add(chechlistTemplateRecord.Name);   
            }
        }
        System.debug('checklistTitle ' + checklistTitle);
        String checklistTitleString = '';
        
        // Converting set to list in order to the the initial value from 0
        List<String> checklistTitleValuesFromSet = new List<String>(checklistTitle);
        System.debug('checklistTitleValuesFromSet ' + checklistTitleValuesFromSet);
        // place the first animal from the set
        if (checklistTitleValuesFromSet.size() > 0){
            checklistTitleString = checklistTitleValuesFromSet[0];
            
            // add additonal scheme to the string with concatanation
            if (checklistTitleValuesFromSet.size() > 1){
                for (String scheme : checklistTitleValuesFromSet){
                    if (scheme != checklistTitleString){
                        checklistTitleString = checklistTitleString + ' and ' + scheme;
                    }
                }
            }
        } else{
            checklistTitleString = 'Scheme';
        }
        return checklistTitleString;
    }
}