unpackaged/main/default/objects/Account/fields/Certificate_Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Certificate_Issue_Date__c</fullName>
    <label>Certificate Issue Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <description>List of counties for UK</description>
    <label>County</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>County</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Membership_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Membership_Expiry_Date__c</fullName>
    <inlineHelpText>Membership Expiry Date is 1 year after the Certificate Issue Date by Default. However if common renewal date is used, then Membership Expiry Date reflects when the sites will need to renew by from a group level.</inlineHelpText>
    <label>Membership Expiry Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Membership_Number__c.field-meta.xml
<CustomField>
    <fullName>Membership_Number__c</fullName>
    <formula>Parent.Head_Office_Number__c  &amp; &quot;.&quot;  &amp;  Site_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/VAT_Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>VAT_Registration_Number__c</fullName>
    <label>VAT Registration Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Applicant_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Full_Name__c</fullName>
    <formula>Applicant_Contact__r.FirstName  &amp; &quot; &quot;  &amp;  Applicant_Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant Full Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Application_Type__c</fullName>
    <label>Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Existing_Member__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Revisit</fullName>
            </value>
            <value>
                <fullName>Levy</fullName>
            </value>
            <value>
                <fullName>Merchandise</fullName>
            </value>
            <value>
                <fullName>Promotion/Partnership</fullName>
            </value>
            <value>
                <fullName>Consultancy</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Calculated_Stage__c.field-meta.xml
<CustomField>
    <fullName>Calculated_Stage__c</fullName>
    <formula>IF(RecordType.DeveloperName == &#39;Renewal&#39;,TEXT( Renewal_Stage__c) ,TEXT(Stage__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Calculated Stage</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Custom_Invoice_Message__c.field-meta.xml
<CustomField>
    <fullName>Custom_Invoice_Message__c</fullName>
    <label>Custom Invoice Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Head_Office__c.field-meta.xml
<CustomField>
    <fullName>Head_Office__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Head Office</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Head Office</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Membership_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Membership_Expiry_Date__c</fullName>
    <formula>Site__r.Membership_Expiry_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership Expiry Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Membership_Number__c.field-meta.xml
<CustomField>
    <fullName>Membership_Number__c</fullName>
    <formula>Site__r.Membership_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field must be populated in order to mark an Additional Visit as complete.</inlineHelpText>
    <label>Membership Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Payment_Reference__c.field-meta.xml
<CustomField>
    <fullName>Payment_Reference__c</fullName>
    <description>Payment Reference autogenerated by salesforce.</description>
    <formula>Sage_Invoice__r.Invoice_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Reference</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>ApplicationSite</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Site_Name__c.field-meta.xml
<CustomField>
    <fullName>Site_Name__c</fullName>
    <formula>Site__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/VAT_Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>VAT_Registration_Number__c</fullName>
    <description>VAT Registration Number from head office.</description>
    <formula>Head_Office__r.VAT_Registration_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>VAT Registration Number from head office.</inlineHelpText>
    <label>VAT Registration Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <description>For renewal applications</description>
    <label>Renewal</label>
</RecordType>

unpackaged/main/default/globalValueSets/County.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Aberdeenshire</fullName>
    </customValue>
    <customValue>
        <fullName>Angus</fullName>
    </customValue>
    <customValue>
        <fullName>Argyll &amp; Bute</fullName>
    </customValue>
    <customValue>
        <fullName>Ayrshire</fullName>
    </customValue>
    <customValue>
        <fullName>Banffshire</fullName>
    </customValue>
    <customValue>
        <fullName>Bath and North East Somerset</fullName>
    </customValue>
    <customValue>
        <fullName>Bedfordshire</fullName>
    </customValue>
    <customValue>
        <fullName>Berkshire</fullName>
    </customValue>
    <customValue>
        <fullName>Berwickshire</fullName>
    </customValue>
    <customValue>
        <fullName>Blaenau Gwent</fullName>
    </customValue>
    <customValue>
        <fullName>Bridgend</fullName>
    </customValue>
    <customValue>
        <fullName>Bristol</fullName>
    </customValue>
    <customValue>
        <fullName>Buckinghamshire</fullName>
    </customValue>
    <customValue>
        <fullName>Caerphilly</fullName>
    </customValue>
    <customValue>
        <fullName>Caithness</fullName>
    </customValue>
    <customValue>
        <fullName>Cambridgeshire</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiff</fullName>
    </customValue>
    <customValue>
        <fullName>Carmarthenshire</fullName>
    </customValue>
    <customValue>
        <fullName>Ceredigion</fullName>
    </customValue>
    <customValue>
        <fullName>Cheshire</fullName>
    </customValue>
    <customValue>
        <fullName>Clackmannanshire</fullName>
    </customValue>
    <customValue>
        <fullName>Clwyd</fullName>
    </customValue>
    <customValue>
        <fullName>Conwy</fullName>
    </customValue>
    <customValue>
        <fullName>Cornwall</fullName>
    </customValue>
    <customValue>
        <fullName>Antrim</fullName>
        <label>County Antrim</label>
    </customValue>
    <customValue>
        <fullName>Armagh</fullName>
        <label>County Armagh</label>
    </customValue>
    <customValue>
        <fullName>County Cork</fullName>
    </customValue>
    <customValue>
        <fullName>County Donegal</fullName>
    </customValue>
    <customValue>
        <fullName>Down</fullName>
        <label>County Down</label>
    </customValue>
    <customValue>
        <fullName>County Durham</fullName>
    </customValue>
    <masterLabel>County</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/InvoicePDFController.cls
public class InvoicePDFController {
    public Application__c currentRecord{get;set;}
    public Date EndDate{get;set;}
    public Date startDate{get;set;}
    public InvoicePDFController(ApexPages.StandardController controller) {
        currentRecord = [
            SELECT Id, Name, Applicant_Full_Name__c, Site_Name__c, Head_Office__r.Name, 
            Head_Office__r.BillingStreet, Head_Office__r.BillingCity, Head_Office__r.County__c, 
            Head_Office__r.BillingCountry, Head_Office__r.BillingPostalcode, Invoice_Date__c, 
            Payment_Due_Date__c, Payment_Reference__c, VAT_Registration_Number__c, 
            Head_Office__r.ia_crm__IntacctID__c, PO_Number__c,Membership_Number__c,Site__r.Name,
            Membership_Expiry_Date__c,Application_Type__c,Custom_Invoice_Message__c,Site__c,
            RecordType.DeveloperName,Calculated_Stage__c,Site__r.Certificate_Issue_Date__c
            FROM Application__c 
            WHERE Id = :ApexPages.currentPage().getParameters().get('id')
        ];
        System.debug('====currentRecord==='+ currentRecord);
        if(currentRecord.Membership_Expiry_Date__c != null && currentRecord.RecordType.DeveloperName == 'Renewal'){
            if(currentRecord.Calculated_Stage__c == 'Renewal'){
                startDate = currentRecord.Membership_Expiry_Date__c;
                EndDate = currentRecord.Membership_Expiry_Date__c.addMonths(12);
            }else if(currentRecord.Site__c != null){//if(currentRecord.Calculated_Stage__c == 'Certification')
                startDate = currentRecord.Site__r.Certificate_Issue_Date__c;
                EndDate = currentRecord.Membership_Expiry_Date__c;
            }
            
        }
    }
    /*public InvoicePDFController() {
        
    }*/
}