unpackaged/main/default/objects/Account/fields/Certificate_Expiry_Date_Calculated__c.field-meta.xml
<CustomField>
    <fullName>Certificate_Expiry_Date_Calculated__c</fullName>
    <formula>ADDMONTHS(Certificate_Issue_Date__c,12)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Certificate Expiry Date Calculated</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Certificate_Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>Certificate_Issue_Date__c</fullName>
    <label>Certificate Issue Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <description>List of counties for UK</description>
    <label>County</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>County</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Membership_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Membership_Expiry_Date__c</fullName>
    <inlineHelpText>Membership Expiry Date is 1 year after the Certificate Issue Date by Default. However if common renewal date is used, then Membership Expiry Date reflects when the sites will need to renew by from a group level.</inlineHelpText>
    <label>Membership Expiry Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Membership_Number__c.field-meta.xml
<CustomField>
    <fullName>Membership_Number__c</fullName>
    <formula>Parent.Head_Office_Number__c  &amp; &quot;.&quot;  &amp;  Site_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Membership_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SchemeCertificateText__mdt/SchemeCertificateText__mdt.object-meta.xml
<CustomObject>
    <label>SchemeCertificateText</label>
    <pluralLabel>SchemeCertificateTexts</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/SchemeCertificateText__mdt/fields/Scheme_Wording__c.field-meta.xml
<CustomField>
    <fullName>Scheme_Wording__c</fullName>
    <label>Scheme Wording</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SchemeCertificateText__mdt/fields/Species_Type__c.field-meta.xml
<CustomField>
    <fullName>Species_Type__c</fullName>
    <label>Species Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Unit__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Animals__c.field-meta.xml
<CustomField>
    <fullName>Animals__c</fullName>
    <label>Animals</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Animals</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Own_Transport__c.field-meta.xml
<CustomField>
    <fullName>Own_Transport__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Own Transport</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Production__c.field-meta.xml
<CustomField>
    <fullName>Production__c</fullName>
    <label>Production</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Production</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Rearing_System__c.field-meta.xml
<CustomField>
    <fullName>Rearing_System__c</fullName>
    <label>Rearing System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rearing_System</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applying</fullName>
                <default>true</default>
                <label>Applying</label>
            </value>
            <value>
                <fullName>Certified</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Vehicle_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Animals.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Beef Cattle</fullName>
    </customValue>
    <customValue>
        <fullName>Chickens</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy Cattle</fullName>
    </customValue>
    <customValue>
        <fullName>Ducklings</fullName>
    </customValue>
    <customValue>
        <fullName>Ducks</fullName>
    </customValue>
    <customValue>
        <fullName>Laying Hen Chicks</fullName>
    </customValue>
    <customValue>
        <fullName>Laying Hens</fullName>
    </customValue>
    <customValue>
        <fullName>Lumpfish</fullName>
    </customValue>
    <customValue>
        <fullName>Meat Chicken Chicks</fullName>
    </customValue>
    <customValue>
        <fullName>Pigs</fullName>
    </customValue>
    <customValue>
        <fullName>Pullets</fullName>
    </customValue>
    <customValue>
        <fullName>Salmon</fullName>
    </customValue>
    <customValue>
        <fullName>Sheep</fullName>
    </customValue>
    <customValue>
        <fullName>Trout</fullName>
    </customValue>
    <customValue>
        <fullName>Turkey Poults</fullName>
    </customValue>
    <customValue>
        <fullName>Turkeys</fullName>
    </customValue>
    <customValue>
        <fullName>Veal Calves</fullName>
    </customValue>
    <customValue>
        <fullName>Wrasse</fullName>
    </customValue>
    <customValue>
        <fullName>List</fullName>
    </customValue>
    <masterLabel>Animals</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Business.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abattoir</fullName>
    </customValue>
    <customValue>
        <fullName>Catching</fullName>
    </customValue>
    <customValue>
        <fullName>Cleaner Fish</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery</fullName>
    </customValue>
    <customValue>
        <fullName>Haulier</fullName>
    </customValue>
    <customValue>
        <fullName>Producer</fullName>
    </customValue>
    <customValue>
        <fullName>Supply Chain</fullName>
    </customValue>
    <masterLabel>Business</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/County.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Aberdeenshire</fullName>
    </customValue>
    <customValue>
        <fullName>Angus</fullName>
    </customValue>
    <customValue>
        <fullName>Argyll &amp; Bute</fullName>
    </customValue>
    <customValue>
        <fullName>Ayrshire</fullName>
    </customValue>
    <customValue>
        <fullName>Banffshire</fullName>
    </customValue>
    <customValue>
        <fullName>Bath and North East Somerset</fullName>
    </customValue>
    <customValue>
        <fullName>Bedfordshire</fullName>
    </customValue>
    <customValue>
        <fullName>Berkshire</fullName>
    </customValue>
    <customValue>
        <fullName>Berwickshire</fullName>
    </customValue>
    <customValue>
        <fullName>Blaenau Gwent</fullName>
    </customValue>
    <customValue>
        <fullName>Bridgend</fullName>
    </customValue>
    <customValue>
        <fullName>Bristol</fullName>
    </customValue>
    <customValue>
        <fullName>Buckinghamshire</fullName>
    </customValue>
    <customValue>
        <fullName>Caerphilly</fullName>
    </customValue>
    <customValue>
        <fullName>Caithness</fullName>
    </customValue>
    <customValue>
        <fullName>Cambridgeshire</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiff</fullName>
    </customValue>
    <customValue>
        <fullName>Carmarthenshire</fullName>
    </customValue>
    <customValue>
        <fullName>Ceredigion</fullName>
    </customValue>
    <customValue>
        <fullName>Cheshire</fullName>
    </customValue>
    <customValue>
        <fullName>Clackmannanshire</fullName>
    </customValue>
    <customValue>
        <fullName>Clwyd</fullName>
    </customValue>
    <customValue>
        <fullName>Conwy</fullName>
    </customValue>
    <customValue>
        <fullName>Cornwall</fullName>
    </customValue>
    <customValue>
        <fullName>Antrim</fullName>
        <label>County Antrim</label>
    </customValue>
    <customValue>
        <fullName>Armagh</fullName>
        <label>County Armagh</label>
    </customValue>
    <customValue>
        <fullName>County Cork</fullName>
    </customValue>
    <customValue>
        <fullName>County Donegal</fullName>
    </customValue>
    <customValue>
        <fullName>Down</fullName>
        <label>County Down</label>
    </customValue>
    <customValue>
        <fullName>County Durham</fullName>
    </customValue>
    <masterLabel>County</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Membership_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ADDITION</fullName>
    </customValue>
    <customValue>
        <fullName>ARCHIVED</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC5R</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC7R</fullName>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
    </customValue>
    <customValue>
        <fullName>CONPASS</fullName>
    </customValue>
    <customValue>
        <fullName>ENQUIRY</fullName>
        <default>true</default>
        <label>ENQUIRY</label>
    </customValue>
    <customValue>
        <fullName>EVIDENCE</fullName>
    </customValue>
    <customValue>
        <fullName>FAILED</fullName>
    </customValue>
    <customValue>
        <fullName>FALLOW</fullName>
    </customValue>
    <customValue>
        <fullName>LAPSED</fullName>
    </customValue>
    <customValue>
        <fullName>MEMBER</fullName>
    </customValue>
    <customValue>
        <fullName>MONREQ</fullName>
    </customValue>
    <customValue>
        <fullName>NEW</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2R</fullName>
    </customValue>
    <customValue>
        <fullName>NEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>NONFR</fullName>
    </customValue>
    <customValue>
        <fullName>NOTINSCHEME</fullName>
    </customValue>
    <customValue>
        <fullName>PASSED</fullName>
    </customValue>
    <customValue>
        <fullName>PREPANEL</fullName>
    </customValue>
    <customValue>
        <fullName>REINSTATE</fullName>
    </customValue>
    <customValue>
        <fullName>RENEW/REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWA</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWALINP</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWR</fullName>
    </customValue>
    <customValue>
        <fullName>REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>SUSPENDED</fullName>
    </customValue>
    <masterLabel>Membership Status</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Production.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abattoir</fullName>
    </customValue>
    <customValue>
        <fullName>Brand/Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Breeding</fullName>
    </customValue>
    <customValue>
        <fullName>Brood</fullName>
    </customValue>
    <customValue>
        <fullName>Calves</fullName>
    </customValue>
    <customValue>
        <fullName>Catching Team</fullName>
    </customValue>
    <customValue>
        <fullName>Cleaner Fish</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Dry Cows</fullName>
    </customValue>
    <customValue>
        <fullName>Finishing</fullName>
    </customValue>
    <customValue>
        <fullName>Flat deck (one-storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Flat deck (two storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Flat deck with Veranda</fullName>
    </customValue>
    <customValue>
        <fullName>Freshwater</fullName>
    </customValue>
    <customValue>
        <fullName>Gilts</fullName>
    </customValue>
    <customValue>
        <fullName>Grazing</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery (On Grower)</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery (Ova)</fullName>
    </customValue>
    <customValue>
        <fullName>Haulier</fullName>
    </customValue>
    <customValue>
        <fullName>Heifers</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-tier (one-storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-tier (two-storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-tier with Veranda</fullName>
    </customValue>
    <customValue>
        <fullName>Packer</fullName>
    </customValue>
    <customValue>
        <fullName>Processor</fullName>
    </customValue>
    <customValue>
        <fullName>Processor/Packer</fullName>
    </customValue>
    <customValue>
        <fullName>Producer</fullName>
    </customValue>
    <customValue>
        <fullName>Rearing</fullName>
    </customValue>
    <customValue>
        <fullName>Retailer</fullName>
    </customValue>
    <masterLabel>Production</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Rearing_System.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Barn</fullName>
    </customValue>
    <customValue>
        <fullName>Free Range</fullName>
    </customValue>
    <customValue>
        <fullName>Indoor</fullName>
    </customValue>
    <customValue>
        <fullName>Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Outdoor Bred</fullName>
    </customValue>
    <customValue>
        <fullName>Outdoor Reared</fullName>
    </customValue>
    <customValue>
        <fullName>n/a</fullName>
    </customValue>
    <customValue>
        <fullName>Pasture</fullName>
    </customValue>
    <masterLabel>Rearing System</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Vehicle_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Helicopter</fullName>
    </customValue>
    <customValue>
        <fullName>Lorry</fullName>
    </customValue>
    <customValue>
        <fullName>Trailer</fullName>
    </customValue>
    <customValue>
        <fullName>Van</fullName>
    </customValue>
    <customValue>
        <fullName>Wellboat</fullName>
    </customValue>
    <customValue>
        <fullName>TBC</fullName>
    </customValue>
    <masterLabel>Vehicle Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CertificatesPerSpeciesController.cls
public with sharing class CertificatesPerSpeciesController {
    public Account currentRecord{get;set;}

    public String startDate{get;set;}
    public String endDate{get;set;}
    public String species{get;set;}
    public Map<Integer, String> monthsMap = new Map<Integer, String>{
        1  => 'January',
        2  => 'February',
        3  => 'March',
        4  => 'April',
        5  => 'May',
        6  => 'June',
        7  => 'July',
        8  => 'August',
        9  => 'September',
        10 => 'October',
        11 => 'November',
        12 => 'December'
    };

    public CertificatesPerSpeciesController() {
        currentRecord = [SELECT Id, Name, Parent.Name, Membership_Number__c, Membership_Expiry_Date__c, Certificate_Issue_Date__c, Certificate_Expiry_Date_Calculated__c, BillingStreet, BillingCity, County__c, BillingCountry, BillingPostalcode FROM Account WHERE Id = :ApexPages.currentPage().getParameters().get('id')];
        species = ApexPages.currentPage().getParameters().get('species');
        if(currentRecord.Certificate_Issue_Date__c != null){
            startDate = currentRecord.Certificate_Issue_Date__c.day() + ' ' + monthsMap.get(currentRecord.Certificate_Issue_Date__c.month()) + ' ' + currentRecord.Certificate_Issue_Date__c.year();
        }
        if(currentRecord.Membership_Expiry_Date__c != null){
            endDate = currentRecord.Membership_Expiry_Date__c.day() + ' ' + monthsMap.get(currentRecord.Membership_Expiry_Date__c.month()) + ' ' + currentRecord.Membership_Expiry_Date__c.year();

        }
    }
    //method to get a list of supply chain units
    public List<Unit__c> getSupplyChainUnits(){
        List<Unit__c> unitList = new List<Unit__c>();
        if(String.isNotBlank(species)){
            unitList = [SELECT Id, Name, Account__c, Business__c, Description__c, Animals__c, Production__c, Rearing_System__c, Status__c, Vehicle_Registration__c, Vehicle_Type__c, Own_Transport__c FROM Unit__c WHERE Account__c =:currentRecord.Id AND Status__c = 'Certified' AND Business__c = 'Supply Chain' AND Animals__c =:species];
        }else{
            unitList = [SELECT Id, Name, Account__c, Business__c, Description__c, Animals__c, Production__c, Rearing_System__c, Status__c, Vehicle_Registration__c, Vehicle_Type__c, Own_Transport__c FROM Unit__c WHERE Account__c =:currentRecord.Id AND Status__c = 'Certified' AND Business__c = 'Supply Chain'];
        }
        return unitList;
    }

    // Method to get a list of trout units
    public List<Unit__c> getTrouts(){
        Set<String> businessSet = new Set<String>{
            'Hatchery',
            'Haulier',
            'Abattoir',
            'Producer'
        };
        List<Unit__c> troutList = [SELECT Id, Name, Account__c, Business__c, Description__c, Animals__c, Production__c, Rearing_System__c, Status__c, Vehicle_Registration__c, Vehicle_Type__c, Own_Transport__c FROM Unit__c WHERE Account__c =:currentRecord.Id AND Status__c = 'Certified' AND Business__c IN:businessSet AND Animals__c = 'Trout'];
        return troutList;
    } 

    //method to get a list of Animals Units exluding trout
    public List<Unit__c> getNSFUKASUnits(){
        Set<String> businessSet = new Set<String>{
            'Hatchery',
            'Haulier',
            'Abattoir',
            'Producer',
            'Cleaner Fish',
            'Catching'
        };
        // Old query has trout and new query does not
        //List<Unit__c> unitList = [SELECT Id, Name, Account__c, Business__c, Description__c, Animals__c, Production__c, Rearing_System__c, Status__c, Vehicle_Registration__c, Own_Transport__c FROM Unit__c WHERE Account__c =:currentRecord.Id AND Status__c = 'Certified' AND Business__c IN:businessSet AND Animals__c != 'Trout'];
        List<Unit__c> unitList = new List<Unit__c>();
        if(String.isNotBlank(species)){
            unitList = [SELECT Id, Name, Account__c, Business__c, Description__c, Animals__c, Production__c, Rearing_System__c, Status__c, Vehicle_Registration__c,Vehicle_Type__c, Own_Transport__c FROM Unit__c WHERE Account__c =:currentRecord.Id AND Status__c = 'Certified' AND Business__c IN:businessSet AND Animals__c =:species];
        }else{
            unitList = [SELECT Id, Name, Account__c, Business__c, Description__c, Animals__c, Production__c, Rearing_System__c, Status__c, Vehicle_Registration__c,Vehicle_Type__c, Own_Transport__c FROM Unit__c WHERE Account__c =:currentRecord.Id AND Status__c = 'Certified' AND Business__c IN:businessSet];
        }
        return unitList;
    }

    // This method gets the animals list for the trout certification with the word "Scheme" or "Schemes" appended to it
    public String getTroutAnimalScheme() {
        String animalsString = '';
        Set<String> animalsSet = new Set<String>();
        for(Unit__c u : getTrouts()){
            animalsSet.add(u.Animals__c);
        }
        // Converting set to list in order to the the initial value from 0
        List<String> animalsList = new List<String>(animalsSet);
        // place the first animal from the set
        if(animalsSet.size() > 0){
            animalsString = animalsList[0];
        }
        // add additonal animals to the string with concatanation
        if(animalsSet.size() > 1){
            //Commented out as the query inside geTrouts() methods is filtering animals by trout so there will only be 1 animal inside the set
            /*
            for(String animal: animalsSet){
                if(animal != animalsString){
                    animalsString = animalsString + ' and ' + animal; 
                }
            }
            // adding "Schemes" for plural animals
            animalsString = animalsString + ' Schemes';
			*/
        }else{
            // adding "Scheme" for singulr animal
            animalsString = animalsString + ' Scheme';
        }
        return animalsString;
    }

    // This method gets the animals list for the trout certification
    public String getTroutAnimals() {
        String animalsString = '';
        Set<String> animalsSet = new Set<String>();
        for(Unit__c u : getTrouts()){
            animalsSet.add(u.Animals__c);
        }
        // Converting set to list in order to the the initial value from 0
        List<String> animalsList = new List<String>(animalsSet);
        // place the first animal from the list
        if(animalsList.size() > 0){
            animalsString = animalsList[0];
        }
        // add additonal animals to the string with concatanation
        if(animalsList.size() > 1){
            //Commented out as the query inside geTrouts() methods is filtering animals by trout so there will only be 1 animal inside the set
            /*
            for(String animal: animalsList){
                if(animal != animalsString){
                    animalsString = animalsString + ' and ' + animal; 
                }
            }
			*/
        }
        return animalsString;
    }

    public String getTroutRearingSystems(){
        String rearingSystemAnimalString = '';
        Set<String> rearingSystemAnimalSet = new Set<String>();
        for(Unit__c u : getTrouts()){
            rearingSystemAnimalSet.add(u.Rearing_System__c + ' ' + u.Animals__c);
        }
        // Converting set to list in order to the the initial value from 0
        List<String> rearingSystemAnimalList = new List<String>(rearingSystemAnimalSet);
        // Place the first Rearing System Animal from the list
        if(rearingSystemAnimalList.size() > 0){
            rearingSystemAnimalString = rearingSystemAnimalList[0];
        }
        // add additional rearing system animals to the string with concatenation
        if(rearingSystemAnimalList.size() > 1){
            //Commented out as the query inside geTrouts() methods is filtering animals by trout so there will only be 1 animal inside the set
            /*
            for(String rearingAnimal : rearingSystemAnimalList){
                if(rearingAnimal != rearingSystemAnimalString){
                    rearingSystemAnimalString = rearingSystemAnimalString + ' and ' + rearingAnimal;
                }
            }
            // adding "Units" for plural animals
            rearingSystemAnimalString = rearingSystemAnimalString + ' Units';
			*/
        }else {
            // adding "Scheme" for singulr animal
            rearingSystemAnimalString = rearingSystemAnimalString + ' Unit';
        }

        return rearingSystemAnimalString;
    }
    
    // This method gets the animals list for the NSF UKAS certification with the word "Scheme" or "Schemes" appended to it
    public String getAllAnimalScheme() {
        String animalsString = '';
        Set<String> animalsSet = new Set<String>();
        for(Unit__c u : getNSFUKASUnits()){
            animalsSet.add(u.Animals__c);
        }
        // Converting set to list in order to the the initial value from 0
        List<String> animalsList = new List<String>(animalsSet);
        // place the first animal from the set
        if(animalsSet.size() > 0){
            animalsString = animalsList[0];
        }
        // add additonal animals to the string with concatanation
        if(animalsSet.size() > 1){
            for(String animal: animalsSet){
                if(animal != animalsString){
                    animalsString = animalsString + ' and ' + animal; 
                }
            }
            // adding "Schemes" for plural animals
            animalsString = animalsString + ' Schemes';
        }else{
            // adding "Scheme" for singulr animal
            animalsString = animalsString + ' Scheme';
        }
        return animalsString;
    }

    // This method gets the animals list for the NSF UKAS certification. Get's all except trouts.
    public String getAllAnimals() {
        String animalsString = '';
        Set<String> animalsSet = new Set<String>();
        for(Unit__c u : getNSFUKASUnits()){
            animalsSet.add(u.Animals__c);
        }
        // Converting set to list in order to the the initial value from 0
        List<String> animalsList = new List<String>(animalsSet);
        // place the first animal from the list
        if(animalsList.size() > 0){
            animalsString = animalsList[0];
        }
        // add additonal animals to the string with concatanation
        if(animalsList.size() > 1){
            for(String animal: animalsList){
                if(animal != animalsString){
                    animalsString = animalsString + ' and ' + animal; 
                }
            }
        }
        return animalsString;
    }

    // This method gets the rearing system for all amimals except for trout
    public String getAllAnimalRearingSystems(){
        String rearingSystemAnimalString = '';
        Set<String> rearingSystemAnimalSet = new Set<String>();
        for(Unit__c u : getNSFUKASUnits()){
            rearingSystemAnimalSet.add(u.Rearing_System__c + ' ' + u.Animals__c);
        }
        // Converting set to list in order to the the initial value from 0
        List<String> rearingSystemAnimalList = new List<String>(rearingSystemAnimalSet);
        // Place the first Rearing System Animal from the list
        if(rearingSystemAnimalList.size() > 0){
            rearingSystemAnimalString = rearingSystemAnimalList[0];
        }
        // add additional rearing system animals to the string with concatenation
        if(rearingSystemAnimalList.size() > 1){
            for(String rearingAnimal : rearingSystemAnimalList){
                if(rearingAnimal != rearingSystemAnimalString){
                    rearingSystemAnimalString = rearingSystemAnimalString + ' and ' + rearingAnimal;
                }
            }
            // adding "Units" for plural animals
            rearingSystemAnimalString = rearingSystemAnimalString + ' Units';
        }else {
            // adding "Scheme" for singulr animal
            rearingSystemAnimalString = rearingSystemAnimalString + ' Unit';
        }

        return rearingSystemAnimalString;
    }

    // get SCI Scheme Texts
    public String getSCISchemeTexts(){
        List<SchemeCertificateText__mdt> schemeTextList = SchemeCertificateText__mdt.getAll().values();
        Set<String> schemeTextSet = new Set<String>();
        for(Unit__c u : getNSFUKASUnits()){
            for(SchemeCertificateText__mdt scheme : schemeTextList){
                if(u.Business__c == 'Producer'){
                    if(u.Animals__c == scheme.Species_Type__c){
                        schemeTextSet.add(scheme.Scheme_Wording__c);
                    }
                }
                if(u.Business__c == 'Abattoir'){
                    if(u.Animals__c == 'Salmon'){
                        if(scheme.Species_Type__c == 'Salmon Abattoir'){
                            schemeTextSet.add(scheme.Scheme_Wording__c);
                        }
                    }else{
                        if(scheme.Species_Type__c == 'Abattoir'){
                            schemeTextSet.add(scheme.Scheme_Wording__c);
                        }
                    }
                }
                if(u.Business__c == 'Catching'){
                    if(scheme.Species_Type__c == 'Catching'){
                        schemeTextSet.add(scheme.Scheme_Wording__c);
                    }
                }
                if(u.Business__c == 'Hatchery'){
                    if(u.Animals__c == 'Salmon'){
                        if(scheme.Species_Type__c == 'Salmon Hatchery'){
                            schemeTextSet.add(scheme.Scheme_Wording__c);
                        }
                    }else{
                        if(scheme.Species_Type__c == 'Hatchery'){
                            schemeTextSet.add(scheme.Scheme_Wording__c);
                        }
                    }
                }
                if(u.Business__c == 'Haulier'){
                    if(u.Animals__c == 'Salmon'){
                        if(u.Vehicle_Type__c == 'Wellboat'){
                            if(scheme.Species_Type__c == 'Salmon Wellboat'){
                                schemeTextSet.add(scheme.Scheme_Wording__c);
                            }
                        }
                        if(u.Vehicle_Type__c == 'Helicopter'){
                            if(scheme.Species_Type__c == 'Salmon Helicopter'){
                                schemeTextSet.add(scheme.Scheme_Wording__c);
                            }
                        }
                    }else{
                        if(u.Own_Transport__c){
                            if(scheme.Species_Type__c == 'Own Transport'){
                                schemeTextSet.add(scheme.Scheme_Wording__c);
                            }
                        }else{
                            if(scheme.Species_Type__c == 'Haulier'){
                                schemeTextSet.add(scheme.Scheme_Wording__c);
                            }
                        }
                    }
                }
                
            }
        }

        String schemeTextString = '';

        // Converting set to list in order to the the initial value from 0
        List<String> schemeTextValuesFromSet = new List<String>(schemeTextSet);
        // place the first animal from the set
        if(schemeTextValuesFromSet.size() > 0){
            schemeTextString = schemeTextValuesFromSet[0];
        }
        
        // add additonal scheme to the string with concatanation
        if(schemeTextValuesFromSet.size() > 1){
            for(String scheme: schemeTextValuesFromSet){
                if(scheme != schemeTextString){
                    schemeTextString = schemeTextString + ' and ' + scheme; 
                }
            }
        }
        return schemeTextString;

    }

    // get SCI Scheme Texts
    public String getSCISchemeTitle(){
        List<SchemeCertificateText__mdt> schemeTextList = SchemeCertificateText__mdt.getAll().values();
        Set<String> schemeTitle = new Set<String>();
        for(Unit__c u : getNSFUKASUnits()){
            for(SchemeCertificateText__mdt scheme : schemeTextList){
                if(u.Business__c == 'Producer'){
                    if(u.Animals__c == scheme.Species_Type__c){
                        schemeTitle.add(scheme.MasterLabel);
                    }
                }
                if(u.Business__c == 'Abattoir'){
                    if(u.Animals__c == 'Salmon'){
                        if(scheme.Species_Type__c == 'Salmon Abattoir'){
                            schemeTitle.add(scheme.MasterLabel);
                        }
                    }else{
                        if(scheme.Species_Type__c == 'Abattoir'){
                            // do nothing as the Scheme title will be 'RSPCA Assured Scheme'
                        }
                    }
                }
                if(u.Business__c == 'Catching'){
                    if(scheme.Species_Type__c == 'Catching'){
                        schemeTitle.add(scheme.MasterLabel);
                    }
                }
                if(u.Business__c == 'Hatchery'){
                    if(u.Animals__c == 'Salmon'){
                        if(scheme.Species_Type__c == 'Salmon Hatchery'){
                            schemeTitle.add(scheme.MasterLabel);
                        }
                    }else{
                        if(scheme.Species_Type__c == 'Hatchery'){
                            schemeTitle.add(scheme.MasterLabel);
                        }
                    }
                }
                if(u.Business__c == 'Haulier'){
                    if(u.Animals__c == 'Salmon'){
                        if(u.Vehicle_Type__c == 'Wellboat'){
                            if(scheme.Species_Type__c == 'Salmon Wellboat'){
                                schemeTitle.add(scheme.MasterLabel);
                            }
                        }
                        if(u.Vehicle_Type__c == 'Helicopter'){
                            if(scheme.Species_Type__c == 'Salmon Helicopter'){
                                schemeTitle.add(scheme.MasterLabel);
                            }
                        }
                    }else{
                        if(u.Own_Transport__c){
                            if(scheme.Species_Type__c == 'Own Transport'){
                                schemeTitle.add(scheme.MasterLabel);
                            }
                        }else{
                            if(scheme.Species_Type__c == 'Haulier'){
                                // do nothing as the Scheme title will be 'RSPCA Assured Scheme'
                            }
                        }
                    }
                }
                
            }
        }

        String schemeTitleString = '';

        // Converting set to list in order to the the initial value from 0
        List<String> schemeTitleValuesFromSet = new List<String>(schemeTitle);
        // place the first animal from the set
        if(schemeTitleValuesFromSet.size() > 0){
            schemeTitleString = schemeTitleValuesFromSet[0];

             // add additonal scheme to the string with concatanation
            if(schemeTitleValuesFromSet.size() > 1){
                for(String scheme: schemeTitleValuesFromSet){
                    if(scheme != schemeTitleString){
                        schemeTitleString = schemeTitleString + ' and ' + scheme; 
                    }
                }
            }
        }else {
            schemeTitleString = 'Scheme';
        }
        
       
        return schemeTitleString;

    }
}