unpackaged/main/default/objects/Account/fields/Company_Industry__c.field-meta.xml
<CustomField>
    <fullName>Company_Industry__c</fullName>
    <description>Custom Industry muti picklist field for RSPCA Assured members as companies can have more than one industry.</description>
    <label>Company Industry</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company_Industry</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <description>List of counties for UK</description>
    <label>County</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>County</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Membership_Number__c.field-meta.xml
<CustomField>
    <fullName>Membership_Number__c</fullName>
    <formula>Parent.Head_Office_Number__c  &amp; &quot;.&quot;  &amp;  Site_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <description>An Account representing a site.</description>
    <label>Site</label>
</RecordType>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Allocation_Status__c.field-meta.xml
<CustomField>
    <fullName>Allocation_Status__c</fullName>
    <label>Allocation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
                <default>true</default>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Applicant_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Full_Name__c</fullName>
    <formula>Applicant_Contact__r.FirstName  &amp; &quot; &quot;  &amp;  Applicant_Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant Full Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Assessment_Approved_By_Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Approved_By_Assessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Technical review - are you satisfied you have completed and submitted all applicable documentation (see documentation below)?</inlineHelpText>
    <label>Assessment Approved By (Assessor)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Applications4</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Assessment_Date__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Date__c</fullName>
    <description>Cannot exceed the deadline date; can be updated if rearranged</description>
    <inlineHelpText>The date the site will be assessed</inlineHelpText>
    <label>Assessment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Assessment_Deadline__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Deadline__c</fullName>
    <description>Auto-populated with date 3 months from the date of application, or 10 months from the date of renewal.</description>
    <inlineHelpText>The date by which the assessment must have been completed</inlineHelpText>
    <label>Assessment Deadline</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Assessment_Report__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Report__c</fullName>
    <inlineHelpText>White copy</inlineHelpText>
    <label>Assessment Report</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Function: member services select an assessor; system then automatically emails them.</description>
    <inlineHelpText>This field must be populated in order to mark an Additional Visit as complete.</inlineHelpText>
    <label>Allocated Assessor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>You can only select an assessor user to be allocated for this application.</errorMessage>
        <filterItems>
            <field>User.Assessor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>User.Contract_Assessor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Evidence_Approved_By_Assessor__c.field-meta.xml
<CustomField>
    <fullName>Evidence_Approved_By_Assessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Technical review - are you satisfied with the evidence the member has submitted?</inlineHelpText>
    <label>Evidence Approved By (Assessor)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Applications7</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Evidence_Deadline__c.field-meta.xml
<CustomField>
    <fullName>Evidence_Deadline__c</fullName>
    <description>The date by which evidence needs to be submitted.</description>
    <inlineHelpText>The date by which evidence needs to be submitted.</inlineHelpText>
    <label>Evidence Deadline</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Membership_Number__c.field-meta.xml
<CustomField>
    <fullName>Membership_Number__c</fullName>
    <formula>Site__r.Membership_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field must be populated in order to mark an Additional Visit as complete.</inlineHelpText>
    <label>Membership Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Paid__c.field-meta.xml
<CustomField>
    <fullName>Paid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Paid</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BACS</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
                <isActive>false</isActive>
                <label>Card</label>
            </value>
            <value>
                <fullName>Cheque</fullName>
                <isActive>false</isActive>
                <label>Cheque</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Renewal_Stage__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Stage__c</fullName>
    <description>Stage for renewal application. This stage is used in renewal record type.</description>
    <label>Renewal Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Allocation</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>ApplicationSite</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Site_Name__c.field-meta.xml
<CustomField>
    <fullName>Site_Name__c</fullName>
    <formula>Site__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>Stage field for new applications for new site, update, or transfers. This field is used for the application record type.</description>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Application</fullName>
                <default>true</default>
                <label>Application</label>
            </value>
            <value>
                <fullName>Allocation</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Schedule</fullName>
            </value>
            <value>
                <fullName>Visit</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/recordTypes/Applications.recordType-meta.xml
<RecordType>
    <fullName>Applications</fullName>
    <active>true</active>
    <description>For new applications.</description>
    <label>Applications</label>
</RecordType>

unpackaged/main/default/objects/Application__c/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <description>For renewal applications</description>
    <label>Renewal</label>
</RecordType>

unpackaged/main/default/objects/Assessment_Report__c/Assessment_Report__c.object-meta.xml
<CustomObject>
    <label>Assessment Report</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Assessment Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Assessment_Report__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Assessment Reports</relationshipLabel>
    <relationshipName>Assessment_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Assessment_Report__c/fields/Assessment_Date__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Date__c</fullName>
    <formula>Application__r.Assessment_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assessment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Assessment_Report__c/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assessment_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Derogation_Exception__c/Derogation_Exception__c.object-meta.xml
<CustomObject>
    <label>Derogation/Exception</label>
    <nameField>
        <displayFormat>D/E-{0000}</displayFormat>
        <label>Derrogation/Exception Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Derogations/Exceptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Derogation_Exception__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site/Head Office</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Derogation/Exception can only be requested for Site.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Site</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Derogations/Exceptions</relationshipLabel>
    <relationshipName>Derogations_Exceptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Derogation_Exception__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Request</fullName>
                <default>true</default>
                <label>Request</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Company_Industry__c.field-meta.xml
<CustomField>
    <fullName>Company_Industry__c</fullName>
    <description>Custom Industry Multi Picklist field for RSPCA Assured as a company can have more than one industry value selected.</description>
    <label>Company Industry</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company_Industry</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <description>List of Counties for the UK</description>
    <label>County</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>County</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this box is checked, this user will be available to select during the allocation phase of the application/renewals.</description>
    <inlineHelpText>Check this box if the user is an assessor.</inlineHelpText>
    <label>Assessor</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/globalValueSets/Company_Industry.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fish</fullName>
    </customValue>
    <customValue>
        <fullName>Livestock</fullName>
    </customValue>
    <customValue>
        <fullName>Poultry</fullName>
    </customValue>
    <customValue>
        <fullName>Supply Chain</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Company Industry</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/County.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Aberdeenshire</fullName>
    </customValue>
    <customValue>
        <fullName>Angus</fullName>
    </customValue>
    <customValue>
        <fullName>Argyll &amp; Bute</fullName>
    </customValue>
    <customValue>
        <fullName>Ayrshire</fullName>
    </customValue>
    <customValue>
        <fullName>Banffshire</fullName>
    </customValue>
    <customValue>
        <fullName>Bath and North East Somerset</fullName>
    </customValue>
    <customValue>
        <fullName>Bedfordshire</fullName>
    </customValue>
    <customValue>
        <fullName>Berkshire</fullName>
    </customValue>
    <customValue>
        <fullName>Berwickshire</fullName>
    </customValue>
    <customValue>
        <fullName>Blaenau Gwent</fullName>
    </customValue>
    <customValue>
        <fullName>Bridgend</fullName>
    </customValue>
    <customValue>
        <fullName>Bristol</fullName>
    </customValue>
    <customValue>
        <fullName>Buckinghamshire</fullName>
    </customValue>
    <customValue>
        <fullName>Caerphilly</fullName>
    </customValue>
    <customValue>
        <fullName>Caithness</fullName>
    </customValue>
    <customValue>
        <fullName>Cambridgeshire</fullName>
    </customValue>
    <customValue>
        <fullName>Cardiff</fullName>
    </customValue>
    <customValue>
        <fullName>Carmarthenshire</fullName>
    </customValue>
    <customValue>
        <fullName>Ceredigion</fullName>
    </customValue>
    <customValue>
        <fullName>Cheshire</fullName>
    </customValue>
    <customValue>
        <fullName>Clackmannanshire</fullName>
    </customValue>
    <customValue>
        <fullName>Clwyd</fullName>
    </customValue>
    <customValue>
        <fullName>Conwy</fullName>
    </customValue>
    <customValue>
        <fullName>Cornwall</fullName>
    </customValue>
    <customValue>
        <fullName>Antrim</fullName>
        <label>County Antrim</label>
    </customValue>
    <customValue>
        <fullName>Armagh</fullName>
        <label>County Armagh</label>
    </customValue>
    <customValue>
        <fullName>County Cork</fullName>
    </customValue>
    <customValue>
        <fullName>County Donegal</fullName>
    </customValue>
    <customValue>
        <fullName>Down</fullName>
        <label>County Down</label>
    </customValue>
    <customValue>
        <fullName>County Durham</fullName>
    </customValue>
    <masterLabel>County</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/NotificationsComponentController.cls
public class NotificationsComponentController {
    // Get the base URL.
    public String sfdcBaseURL{get;set;}

    // True if lists below return data
    // for Membership Services
    public Boolean hasEnquires{get;set;}
    public Boolean hasApplications{get;set;}
    public Boolean hasPaidApplications{get;set;}
    public Boolean hasExpiringApplications{get;set;}
    public Boolean hasAllocations{get;set;}
    public Boolean hasRejections{get;set;}
    public Boolean hasApprovalsOffice{get;set;}
    public Boolean hasCertifications{get;set;}
    public Boolean hasDerogationExceptions{get;set;}
    
    // for Accounts
    public Boolean hasPaidCardApplications{get;set;}
    public Boolean hasPendingBacsChequeApplications{get;set;}

    // for NSF
    public boolean hasApprovalsNSF{get;set;}
    public boolean hasSuspensionsPendingApproval{get;set;}

    // for Assessors
    public Id assessorId{get;set;}
    public Boolean hasAssessorAllocations{get;set;}
    public Boolean hasAssessmentBookingsPending{get;set;}
    public Boolean hasAssessmentReportsPending{get;set;}
    public Boolean hasAssessorApprovalsPending{get;set;}

    public NotificationsComponentController(){
        sfdcBaseURL = URL.getSalesforceBaseUrl().toExternalForm();
    }
    // Get List of Enquires
    public List<Lead> getEnquires(){
        List<Lead> leadList = [SELECT Id, Name, Company, Company_Industry__c, CreatedDate, IsConverted FROM Lead WHERE IsConverted = false];
        if(leadList.size() > 0){
            hasEnquires = true;
        }
        return leadList;
    }

    // Get list of Applications
    public List<Application__c> getApplications(){
        List<Application__c> appList = [SELECT Id, Name, Membership_Number__c, Applicant_Full_Name__c, Site_Name__c, Site__r.Company_Industry__c, Site__r.County__c, CreatedDate FROM Application__c WHERE Paid__c = false AND ((RecordType.Name = 'Applications' AND Stage__c = 'Application') OR (RecordType.Name = 'Renewal' AND Renewal_Stage__c = 'Renewal'))];
        if(appList.size() > 0){
            hasApplications = true;
        }
        return appList;
    }

    // Get List of Paid Applications
    public List<Application__c> getPaidApplications(){
        List<Application__c> appList = [SELECT Id, Name, Membership_Number__c, Applicant_Full_Name__c, Site_Name__c, Payment_Method__c, Date_of_Payment__c FROM Application__c WHERE Paid__c = true AND ((RecordType.Name = 'Applications' AND Stage__c = 'Application') OR (RecordType.Name = 'Renewal' AND Renewal_Stage__c = 'Renewal'))];
        if(appList.size() > 0){
            hasPaidApplications = true;
        }
        return appList;
    }

    // Get List of Paid Card Applications
    public List<Application__c> getPaidCardApplications(){
        List<Application__c> appList = [SELECT Id, Name, Membership_Number__c, Applicant_Full_Name__c, Site_Name__c, Payment_Method__c, Date_of_Payment__c FROM Application__c WHERE Paid__c = true AND Payment_Method__c = 'Card' AND (Stage__c = 'Application' OR Renewal_Stage__c = 'Renewal')];
        if(appList.size() > 0){
            hasPaidCardApplications = true;
        }
        return appList;
    }

    // Get List of Paid BACS/Cheque Applications
    public List<Application__c> getPendingBacsChequeApplications(){
        List<Application__c> appList = [SELECT Id, Name, Membership_Number__c, Applicant_Full_Name__c, Site_Name__c, Payment_Method__c, Date_of_Payment__c, CreatedDate FROM Application__c WHERE Paid__c = false AND (Payment_Method__c = 'BACS' OR Payment_Method__c = 'Cheque') AND (Stage__c = 'Application' OR Renewal_Stage__c = 'Renewal')];
        if(appList.size() > 0){
            hasPendingBacsChequeApplications = true;
        }
        return appList;
    }

    // Get List of Allocation Applications
    public List<Application__c> getAllocationApplications(){
        List<Application__c> appList = [SELECT Id, Name, Membership_Number__c, Applicant_Full_Name__c, Site_Name__c, Site__r.Company_Industry__c, Site__r.County__c  FROM Application__c WHERE Stage__c = 'Allocation' OR Renewal_Stage__c = 'Allocation'];
        if(appList.size() > 0){
            hasAllocations = true;
        }
        return appList;
    }

    // Get List of Assessor Allocation Applications
    public List<Application__c> getAssessorAllocations(){
        List<Application__c> appList = [SELECT Id, Name, Membership_Number__c, Applicant_Full_Name__c, Site_Name__c, Site__r.Company_Industry__c, Site__r.County__c, Assessor__c, Assessment_Deadline__c  FROM Application__c WHERE (Stage__c = 'Allocation' OR Renewal_Stage__c = 'Allocation') AND Assessor__c = :assessorId AND Allocation_Status__c = 'Pending'];
        if(appList.size() > 0){
            hasAssessorAllocations = true;
        }
        return appList;
    }

    // Get List of Applications where Assessor allocation status is accepted and Assessment Date is blank
    public List<Application__c> getAssessmentBookingsPending(){
        List<Application__c> appList = [SELECT Id, Name, Membership_Number__c, Applicant_Full_Name__c, Site_Name__c, Site__r.Company_Industry__c, Site__r.County__c, Assessor__c, Assessment_Deadline__c, Assessment_Date__c  FROM Application__c WHERE (Stage__c = 'Assessment' OR Renewal_Stage__c = 'Assessment') AND Assessor__c = :assessorId AND Allocation_Status__c = 'Accepted' AND Assessment_Date__c = null];
        if(appList.size() > 0){
            hasAssessmentBookingsPending = true;
        }
        return appList;
    }

    // Get List of Applications where Assessor allocation status is accepted and Assessment Date is booked and Assessment Report is blank
    public List<Application__c> getAssessmentReportsPending(){
        List<Application__c> appList = [SELECT Id, Name, Membership_Number__c, Applicant_Full_Name__c, Site_Name__c, Site__r.Company_Industry__c, Site__r.County__c, Assessor__c, Assessment_Deadline__c, Assessment_Date__c, Evidence_Deadline__c  FROM Application__c WHERE (Stage__c = 'Assessment' OR Renewal_Stage__c = 'Assessment') AND Assessor__c = :assessorId AND Allocation_Status__c = 'Accepted' AND Assessment_Date__c != null AND Assessment_Report__c = null];
        if(appList.size() > 0){
            hasAssessmentReportsPending = true;
        }
        return appList;
    }

    // Get List of Applications for Assessor where approvals are pending
    public List<Application__c> getAssessorApprovalsPending(){
        List<Application__c> appList = [SELECT Id, Name, Membership_Number__c, Applicant_Full_Name__c, Site_Name__c, Site__r.Company_Industry__c, Site__r.County__c, Assessor__c, Assessment_Deadline__c, Assessment_Date__c, Evidence_Deadline__c  FROM Application__c WHERE (Stage__c = 'Compliance' OR Renewal_Stage__c = 'Compliance') AND Assessor__c = :assessorId AND (Assessment_Approved_By_Assessor__c = null  OR Evidence_Approved_By_Assessor__c = null)];
        if(appList.size() > 0){
            hasAssessorApprovalsPending = true;
        }
        return appList;
    }

    // Get List of Rejected Application
    public List<Application__c> getRejectionApplications(){
        Datetime last72Hours = Datetime.now().addHours(-72);
        List<Application__c> appList = [SELECT Id, Name, Membership_Number__c, Applicant_Full_Name__c, Site_Name__c, Site__r.Company_Industry__c, Site__r.County__c, Membership_Expiry_Date__c   FROM Application__c WHERE Reject__c = true AND Rejection_Date__c >= :last72Hours];
        if(appList.size() > 0){
            hasRejections = true;
        }
        return appList;
    }

    // Get List of Approvals Application for office
    public List<Application__c> getApprovalApplicationsOffice(){
        List<Application__c> appList = [SELECT Id, Name, Membership_Number__c, Applicant_Full_Name__c, Site_Name__c, Site__r.Company_Industry__c, Site__r.County__c, Membership_Expiry_Date__c  FROM Application__c WHERE (Application_Approved_By_Office__c = null OR Assessment_Approved_By_Office__c = null OR Evidence_Approved_By_Office__c = null) AND (Stage__c = 'Compliance' OR Renewal_Stage__c = 'Compliance')];
        if(appList.size() > 0){
            hasApprovalsOffice = true;
        }
        return appList;
    }

    // get list of Approvals Application for NSF

    // Get List of Approvals Application
    public List<Application__c> getApprovalApplicationsNSF(){
        List<Application__c> appList = [SELECT Id, Name, Membership_Number__c, Applicant_Full_Name__c, Site_Name__c, Site__r.Company_Industry__c, Site__r.County__c, Membership_Expiry_Date__c  FROM Application__c WHERE (Application_Approved_By_Certifier__c = null OR Assessment_Approved_By_Certifier__c = null OR Evidence_Approved_By_Certifier__c = null) AND (Stage__c = 'Compliance' OR Renewal_Stage__c = 'Compliance')];
        if(appList.size() > 0){
            hasApprovalsNSF = true;
        }
        return appList;
    }

    // Get List of Certified Application
    public List<Application__c> getCertifiedApplications(){
        List<Application__c> appList = [SELECT Id, Name, Membership_Number__c, Applicant_Full_Name__c, Site_Name__c, Site__r.Company_Industry__c, Site__r.County__c, Membership_Expiry_Date__c  FROM Application__c WHERE Stage__c = 'Certification' OR Renewal_Stage__c = 'Certification'];
        if(appList.size() > 0){
            hasCertifications = true;
        }
        return appList;
    }

    public List<Derogation_Exception__c> getDerogationExceptions(){
        List<Derogation_Exception__c> DerogationExceptions = [SELECT Id, Name, Derogation_Exception__c, Site__r.Name, Stage__c, Standard_number__c, Start_Date__c FROM Derogation_Exception__c WHERE Granted_by__c = null AND Granted_Date__c = null];
        if(DerogationExceptions.size() > 0){
            hasDerogationExceptions = true;
        }
        return DerogationExceptions;
    }

    // Get list of Suspensions on Account Pending Approval
    public List<Account> getSuspensionsPendingApproval(){
        List<Account> accList = [SELECT Id, Name, Membership_Number__c, Date_Requested_For_Suspension__c, Reason_for_Suspension__c, Administrator__r.Name, Approved__c FROM Account WHERE RecordType.DeveloperName = 'Site' AND Request_for_Suspension__c = true AND Administrator__c != null AND Approved__c = 'Pending'];
        if(accList.size() > 0){
            hasCertifications = true;
        }
        return accList;
    }



}