unpackaged/main/default/objects/Account/fields/Company_Industry__c.field-meta.xml
<CustomField>
    <fullName>Company_Industry__c</fullName>
    <description>Custom Industry muti picklist field for RSPCA Assured members as companies can have more than one industry.</description>
    <label>Company Industry</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company_Industry</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Date_Suspended_No_Evidence__c.field-meta.xml
<CustomField>
    <fullName>Date_Suspended_No_Evidence__c</fullName>
    <label>Suspension Due to Non-return of Evidence</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Membership_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <description>An Account representing a site.</description>
    <label>Site</label>
</RecordType>

unpackaged/main/default/globalValueSets/Company_Industry.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fish</fullName>
    </customValue>
    <customValue>
        <fullName>Livestock</fullName>
    </customValue>
    <customValue>
        <fullName>Poultry</fullName>
    </customValue>
    <customValue>
        <fullName>Supply Chain</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Company Industry</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Membership_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ADDITION</fullName>
    </customValue>
    <customValue>
        <fullName>ARCHIVED</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC5R</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC7R</fullName>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
    </customValue>
    <customValue>
        <fullName>CONPASS</fullName>
    </customValue>
    <customValue>
        <fullName>ENQUIRY</fullName>
        <default>true</default>
        <label>ENQUIRY</label>
    </customValue>
    <customValue>
        <fullName>EVIDENCE</fullName>
    </customValue>
    <customValue>
        <fullName>FAILED</fullName>
    </customValue>
    <customValue>
        <fullName>FALLOW</fullName>
    </customValue>
    <customValue>
        <fullName>LAPSED</fullName>
    </customValue>
    <customValue>
        <fullName>MEMBER</fullName>
    </customValue>
    <customValue>
        <fullName>MONREQ</fullName>
    </customValue>
    <customValue>
        <fullName>NEW</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2R</fullName>
    </customValue>
    <customValue>
        <fullName>NEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>NONFR</fullName>
    </customValue>
    <customValue>
        <fullName>NOTINSCHEME</fullName>
    </customValue>
    <customValue>
        <fullName>PASSED</fullName>
    </customValue>
    <customValue>
        <fullName>PREPANEL</fullName>
    </customValue>
    <customValue>
        <fullName>REINSTATE</fullName>
    </customValue>
    <customValue>
        <fullName>RENEW/REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWA</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWALINP</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWR</fullName>
    </customValue>
    <customValue>
        <fullName>REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>SUSPENDED</fullName>
    </customValue>
    <masterLabel>Membership Status</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/WithdrawAccountBatchTest.cls
@isTest
public class WithdrawAccountBatchTest {

    @isTest
    static void UpdateAccountStatusTest(){
        Account headOfc = new Account();
        headOfc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Head Office').getRecordTypeId();
        headOfc.Name = 'Test Head Office';
        headOfc.Status__c = 'ENQUIRY';
        insert headOfc;
        
        Account site = new Account();
        site.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Site').getRecordTypeId();
        site.Name = 'Test Site';
        site.ParentId = headOfc.Id;
        site.Company_Industry__c = 'Fish';
        site.Status__c = 'ENQUIRY';
        site.Date_Suspended_No_Evidence__c = Date.today().addDays(-90);
        insert site;

        Test.startTest();
        WithdrawAccountBatch obj = new WithdrawAccountBatch();
        obj.execute(null);
        Test.stopTest();
    }
}