unpackaged/main/default/objects/Account/fields/Create_Renewal_Price_Report__c.field-meta.xml
<CustomField>
    <fullName>Create_Renewal_Price_Report__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Create Renewal Price Report</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Final_Renewal_Reminder_Sent__c.field-meta.xml
<CustomField>
    <fullName>Final_Renewal_Reminder_Sent__c</fullName>
    <label>Final Reminder Sent</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Membership_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Membership_Expiry_Date__c</fullName>
    <inlineHelpText>Membership Expiry Date is 1 year after the Certificate Issue Date by Default. However if common renewal date is used, then Membership Expiry Date reflects when the sites will need to renew by from a group level.</inlineHelpText>
    <label>Membership Expiry Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Membership_Number__c.field-meta.xml
<CustomField>
    <fullName>Membership_Number__c</fullName>
    <formula>Parent.Head_Office_Number__c  &amp; &quot;.&quot;  &amp;  Site_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Pig_Discount_Eligibility__c.field-meta.xml
<CustomField>
    <fullName>Pig_Discount_Eligibility__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pig Discount Eligibility</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Renewal_Reminder_Ready__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Reminder_Ready__c</fullName>
    <formula>Latest_Renewal_Price_Date_For__c =  Membership_Expiry_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal Reminder Ready</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Site_Number__c.field-meta.xml
<CustomField>
    <fullName>Site_Number__c</fullName>
    <inlineHelpText>4 digit membership number for site.</inlineHelpText>
    <label>Site Number</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Six_Week_Renewal_Reminder_Sent__c.field-meta.xml
<CustomField>
    <fullName>Six_Week_Renewal_Reminder_Sent__c</fullName>
    <label>Renewal Invite Sent</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Membership_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/X2_Week_Renewal_Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>X2_Week_Renewal_Scheduled_Date__c</fullName>
    <formula>DATE(YEAR(ADDMONTHS(Membership_Expiry_Date__c, -1)), MONTH(ADDMONTHS(Membership_Expiry_Date__c, -1)), 02)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>2 Week Renewal Scheduled Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/X6_Week_Renewal_Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>X6_Week_Renewal_Scheduled_Date__c</fullName>
    <formula>DATE(YEAR(ADDMONTHS(Membership_Expiry_Date__c, -2)), MONTH(ADDMONTHS(Membership_Expiry_Date__c, -2)), 01)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>6 Week Renewal Scheduled Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <description>An Account representing a site.</description>
    <label>Site</label>
</RecordType>

unpackaged/main/default/objects/Product2/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Pricing_Method__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Method__c</fullName>
    <label>Pricing Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Per Application</fullName>
            </value>
            <value>
                <fullName>Per Site</fullName>
            </value>
            <value>
                <fullName>Dynamic Quantity Price</fullName>
            </value>
            <value>
                <fullName>Additional Quantity Price</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Production__c.field-meta.xml
<CustomField>
    <fullName>Production__c</fullName>
    <label>Production</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Production</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Quantity_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Threshold__c</fullName>
    <label>Quantity Threshold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Renewal_Price_Line__c/Renewal_Price_Line__c.object-meta.xml
<CustomObject>
    <label>Renewal Price Line</label>
    <nameField>
        <label>Renewal Price Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Renewal Price Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Renewal_Price_Line__c/fields/Animal_Or_Ingrediants__c.field-meta.xml
<CustomField>
    <fullName>Animal_Or_Ingrediants__c</fullName>
    <label>Animal Or Ingrediants</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Renewal_Price_Line__c/fields/Membership_Number__c.field-meta.xml
<CustomField>
    <fullName>Membership_Number__c</fullName>
    <formula>Renewal_Price_Report__r.Site__r.Membership_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Renewal_Price_Line__c/fields/Number_Of_Animals__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Animals__c</fullName>
    <label>Number Of Animals</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Renewal_Price_Line__c/fields/Production__c.field-meta.xml
<CustomField>
    <fullName>Production__c</fullName>
    <label>Production</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Renewal_Price_Line__c/fields/Renewal_Price_Report__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Price_Report__c</fullName>
    <label>Renewal Price Report</label>
    <referenceTo>Renewal_Price_Report__c</referenceTo>
    <relationshipLabel>Renewal Price Lines</relationshipLabel>
    <relationshipName>Renewal_Price_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Renewal_Price_Line__c/fields/Total_Inc_VAT__c.field-meta.xml
<CustomField>
    <fullName>Total_Inc_VAT__c</fullName>
    <label>Total Inc VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Renewal_Price_Line__c/fields/UnitId__c.field-meta.xml
<CustomField>
    <fullName>UnitId__c</fullName>
    <label>UnitId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Renewal_Price_Report__c/Renewal_Price_Report__c.object-meta.xml
<CustomObject>
    <label>Renewal Price Report</label>
    <nameField>
        <displayFormat>RPR{000}</displayFormat>
        <label>Renewal Price Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewal Price Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Renewal_Price_Report__c/fields/Membership_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Membership_Expiry_Date__c</fullName>
    <description>The renewal price report is for the following membership expiry date.</description>
    <inlineHelpText>The renewal price report is for the following membership expiry date.</inlineHelpText>
    <label>Membership Expiry Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Renewal_Price_Report__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Renewal Price Reports</relationshipLabel>
    <relationshipName>Renewal_Price_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Renewal_Price_Report__c/fields/Total_Inc_VAT__c.field-meta.xml
<CustomField>
    <fullName>Total_Inc_VAT__c</fullName>
    <label>Total Inc VAT</label>
    <summarizedField>Renewal_Price_Line__c.Total_Inc_VAT__c</summarizedField>
    <summaryForeignKey>Renewal_Price_Line__c.Renewal_Price_Report__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Renewal_Price_Report__c/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <label>VAT</label>
    <summarizedField>Renewal_Price_Line__c.VAT__c</summarizedField>
    <summaryForeignKey>Renewal_Price_Line__c.Renewal_Price_Report__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Unit__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Animals__c.field-meta.xml
<CustomField>
    <fullName>Animals__c</fullName>
    <label>Animals</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Animals</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Ingredients__c.field-meta.xml
<CustomField>
    <fullName>Ingredients__c</fullName>
    <label>Ingredients</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Ingredients</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Number_of_Animals__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Animals__c</fullName>
    <label>Number of Animals</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Own_Catching__c.field-meta.xml
<CustomField>
    <fullName>Own_Catching__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Own Catching</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Own_Transport__c.field-meta.xml
<CustomField>
    <fullName>Own_Transport__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Own Transport</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Production__c.field-meta.xml
<CustomField>
    <fullName>Production__c</fullName>
    <label>Production</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Production</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applying</fullName>
                <default>true</default>
                <label>Applying</label>
            </value>
            <value>
                <fullName>Certified</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Vehicle_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/x2WeekRenewalReminderTestDate__c/x2WeekRenewalReminderTestDate__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>2WeekRenewalReminderTestDate</label>
</CustomObject>

unpackaged/main/default/objects/x2WeekRenewalReminderTestDate__c/fields/Use_Test_Date_Data__c.field-meta.xml
<CustomField>
    <fullName>Use_Test_Date_Data__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Use Test Date Data</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/globalValueSets/Animals.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Beef Cattle</fullName>
    </customValue>
    <customValue>
        <fullName>Chickens</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy Cattle</fullName>
    </customValue>
    <customValue>
        <fullName>Ducklings</fullName>
    </customValue>
    <customValue>
        <fullName>Ducks</fullName>
    </customValue>
    <customValue>
        <fullName>Laying Hen Chicks</fullName>
    </customValue>
    <customValue>
        <fullName>Laying Hens</fullName>
    </customValue>
    <customValue>
        <fullName>Lumpfish</fullName>
    </customValue>
    <customValue>
        <fullName>Meat Chicken Chicks</fullName>
    </customValue>
    <customValue>
        <fullName>Pigs</fullName>
    </customValue>
    <customValue>
        <fullName>Pullets</fullName>
    </customValue>
    <customValue>
        <fullName>Salmon</fullName>
    </customValue>
    <customValue>
        <fullName>Sheep</fullName>
    </customValue>
    <customValue>
        <fullName>Trout</fullName>
    </customValue>
    <customValue>
        <fullName>Turkey Poults</fullName>
    </customValue>
    <customValue>
        <fullName>Turkeys</fullName>
    </customValue>
    <customValue>
        <fullName>Veal Calves</fullName>
    </customValue>
    <customValue>
        <fullName>Wrasse</fullName>
    </customValue>
    <customValue>
        <fullName>List</fullName>
    </customValue>
    <masterLabel>Animals</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Business.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abattoir</fullName>
    </customValue>
    <customValue>
        <fullName>Catching</fullName>
    </customValue>
    <customValue>
        <fullName>Cleaner Fish</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery</fullName>
    </customValue>
    <customValue>
        <fullName>Haulier</fullName>
    </customValue>
    <customValue>
        <fullName>Producer</fullName>
    </customValue>
    <customValue>
        <fullName>Supply Chain</fullName>
    </customValue>
    <masterLabel>Business</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Ingredients.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Beef</fullName>
    </customValue>
    <customValue>
        <fullName>Chicken</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Duck</fullName>
    </customValue>
    <customValue>
        <fullName>Eggs</fullName>
    </customValue>
    <customValue>
        <fullName>Lamb</fullName>
    </customValue>
    <customValue>
        <fullName>Pork</fullName>
    </customValue>
    <customValue>
        <fullName>Salmon</fullName>
    </customValue>
    <customValue>
        <fullName>Trout</fullName>
    </customValue>
    <customValue>
        <fullName>Turkey</fullName>
    </customValue>
    <customValue>
        <fullName>Veal</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Ingredients</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Membership_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ADDITION</fullName>
    </customValue>
    <customValue>
        <fullName>ARCHIVED</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC5R</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC7R</fullName>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
    </customValue>
    <customValue>
        <fullName>CONPASS</fullName>
    </customValue>
    <customValue>
        <fullName>ENQUIRY</fullName>
        <default>true</default>
        <label>ENQUIRY</label>
    </customValue>
    <customValue>
        <fullName>EVIDENCE</fullName>
    </customValue>
    <customValue>
        <fullName>FAILED</fullName>
    </customValue>
    <customValue>
        <fullName>FALLOW</fullName>
    </customValue>
    <customValue>
        <fullName>LAPSED</fullName>
    </customValue>
    <customValue>
        <fullName>MEMBER</fullName>
    </customValue>
    <customValue>
        <fullName>MONREQ</fullName>
    </customValue>
    <customValue>
        <fullName>NEW</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2R</fullName>
    </customValue>
    <customValue>
        <fullName>NEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>NONFR</fullName>
    </customValue>
    <customValue>
        <fullName>NOTINSCHEME</fullName>
    </customValue>
    <customValue>
        <fullName>PASSED</fullName>
    </customValue>
    <customValue>
        <fullName>PREPANEL</fullName>
    </customValue>
    <customValue>
        <fullName>REINSTATE</fullName>
    </customValue>
    <customValue>
        <fullName>RENEW/REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWA</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWALINP</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWR</fullName>
    </customValue>
    <customValue>
        <fullName>REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>SUSPENDED</fullName>
    </customValue>
    <masterLabel>Membership Status</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Production.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abattoir</fullName>
    </customValue>
    <customValue>
        <fullName>Brand/Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Breeding</fullName>
    </customValue>
    <customValue>
        <fullName>Brood</fullName>
    </customValue>
    <customValue>
        <fullName>Calves</fullName>
    </customValue>
    <customValue>
        <fullName>Catching Team</fullName>
    </customValue>
    <customValue>
        <fullName>Cleaner Fish</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Dry Cows</fullName>
    </customValue>
    <customValue>
        <fullName>Finishing</fullName>
    </customValue>
    <customValue>
        <fullName>Flat deck (one-storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Flat deck (two storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Flat deck with Veranda</fullName>
    </customValue>
    <customValue>
        <fullName>Freshwater</fullName>
    </customValue>
    <customValue>
        <fullName>Gilts</fullName>
    </customValue>
    <customValue>
        <fullName>Grazing</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery (On Grower)</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery (Ova)</fullName>
    </customValue>
    <customValue>
        <fullName>Haulier</fullName>
    </customValue>
    <customValue>
        <fullName>Heifers</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-tier (one-storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-tier (two-storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-tier with Veranda</fullName>
    </customValue>
    <customValue>
        <fullName>Packer</fullName>
    </customValue>
    <customValue>
        <fullName>Processor</fullName>
    </customValue>
    <customValue>
        <fullName>Processor/Packer</fullName>
    </customValue>
    <customValue>
        <fullName>Producer</fullName>
    </customValue>
    <customValue>
        <fullName>Rearing</fullName>
    </customValue>
    <customValue>
        <fullName>Retailer</fullName>
    </customValue>
    <customValue>
        <fullName>Breeding to rearing</fullName>
    </customValue>
    <customValue>
        <fullName>Breeding to finishing</fullName>
    </customValue>
    <customValue>
        <fullName>Rearing to finishing</fullName>
    </customValue>
    <masterLabel>Production</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Vehicle_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Helicopter</fullName>
    </customValue>
    <customValue>
        <fullName>Lorry</fullName>
    </customValue>
    <customValue>
        <fullName>Trailer</fullName>
    </customValue>
    <customValue>
        <fullName>Van</fullName>
    </customValue>
    <customValue>
        <fullName>Wellboat</fullName>
    </customValue>
    <customValue>
        <fullName>TBC</fullName>
    </customValue>
    <masterLabel>Vehicle Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/RenewalPriceChecker.cls
public class RenewalPriceChecker extends AppUnitHelper{
    public Id accId {get; set;}
    public List<LineItem> lineItems {get;set;}
    public Account site {get;set;}
    public Decimal totalAmount {get;set;}
    public String groupName {get;set;}

    public RenewalPriceChecker() {
        lineItems = new List<LineItem>();
    }

    public void getRenewalPriceForUnits(List<Unit__c> unitsList){

        List<Unit__c> certifiedUnits = filterByCertifiedUnits(unitsList);
        

        if(!certifiedUnits.isEmpty()){
            getAllSiteUnits(getSiteIdsforUnits(certifiedUnits));
            getProductList();
            loadPriceBookEntries();
            findPricingForUnits(certifiedUnits);
        }
    }

    private List<Unit__c> filterByCertifiedUnits(List<Unit__c> unitList){
        List<Unit__c> certifiedUnits = new List<Unit__c>();
        // check which units are 'Certified'.
        for(Unit__c u : unitList){
            if(u.Status__c == 'Certified'){
                certifiedUnits.add(u);
            }
        }
        return certifiedUnits;
    }

    private Set<String> getSiteIdsforUnits(List<Unit__c> unitList){
        Set<String> siteIds = new Set<String>();
        for(Unit__c u : unitList){
            siteIds.add(u.Account__c);
        }
        return siteIds;
    }

    private void loadPriceBookEntries(){
        // query pricebooks
        List<Pricebook2> pricebooks = getPricebooks();
        // Find membership pricebook
        String memberPricebookId = getMembershipPricebookId(pricebooks);
        // query pricebook entries for the pricebook on the application
        if(memberPricebookId != null){
            getAllPricebookEntries(new Set<String> {memberPricebookId});
        }else {
            String standardPricebookId = getStandardPricebookId(pricebooks); 
            getAllPricebookEntries(new Set<String> {standardPricebookId});
        }
    }

    private List<Pricebook2> getPricebooks(){
        List<Pricebook2> pricebooks = [SELECT Id, Name FROM Pricebook2];
        return pricebooks;
    }

    private String getMembershipPricebookId(List<Pricebook2> pricebookList){
        // Find membership pricebook
        String memberPricebookId;
        for(Pricebook2 pb : pricebookList){
            if(pb.Name == 'Membership Price Book'){
                memberPricebookId = pb.Id;
            }
        }
        return memberPricebookId;
    }

    private String getStandardPricebookId(List<Pricebook2> pricebookList){
        // Find standard pricebook
        String standardPricebookId;
        for(Pricebook2 pb : pricebookList){
            if(pb.IsStandard){
                standardPricebookId = pb.Id;
            }
        }
        return standardPricebookId;
    }

    private void findPricingForUnits(List<Unit__c> unitList){
        Set<String> pigProduction = new Set<String>(); // using set to find unique counts of units with production
        for(Unit__c u : unitList){
            if(u.Business__c =='Supply Chain'){
                findSupplyChainPricing(u);
            }
            if(u.Business__c != null && u.Animals__c != null && u.Production__c != null){
                String vehicleType = u.Vehicle_Type__c;
                // if business is haulier then do not filter the getProduct method by vehicle type
                if(u.Business__c == 'Haulier' && u.Animals__c != 'Salmon'&& u.Animals__c != 'Trout'){
                    vehicleType = null;
                }
                //find product with matching fields
                Product2 unitProduct = AppUnitHelper.getProduct(u.Business__c, u.Animals__c, u.Production__c, vehicleType);
                if(unitProduct != null){
                    if(unitProduct.Pricing_Method__c == 'Per Site'){
                        findPerSiteUnitPricing(u, unitProduct);
                    }
                    if(unitProduct.Pricing_Method__c == 'Dynamic Quantity Price'){
                        findDynamicQuantityPricing(u, unitProduct);
                    }
                    if(unitProduct.Pricing_Method__c == 'Additional Quantity Price'){
                        findAdditionalQuantityPricing(u, unitProduct);
                    }
                }
            }
            if(u.Business__c == 'Producer' && u.Animals__c == 'Pigs'){
                if(u.Production__c == 'Breeding' || u.Production__c == 'Finishing' ||  u.Production__c == 'Rearing'){
                    pigProduction.add(u.Production__c);
                }
                if(u.Production__c == 'Breeding to rearing'){
                    pigProduction.add('Breeding');
                    pigProduction.add('Rearing');
                }
                if(u.Production__c == 'Breeding to finishing'){
                    pigProduction.add('Breeding');
                    pigProduction.add('Finishing');
                }
                if(u.Production__c == 'Rearing to finishing'){
                    pigProduction.add('Rearing');
                    pigProduction.add('Finishing');
                }
            }
        }

        if(site.Pig_Discount_Eligibility__c){
            LineItem item = new LineItem();
            if(pigProduction.size() == 1){
                String pigStage1DiscountId = '';
                for(Product2 p: AppUnitHelper.productList){
                    if(p.ProductCode == 'PIGSTAGE1DISCOUNT'){
                        pigStage1DiscountId = p.Id;
                        break;
                    }
                }
                
                item.lineDescription = 'Pigs Stage 1 Discount';
                item.priceExVAT = getPriceForProduct(pigStage1DiscountId);
                item.animalOrIngrediants = 'Pigs';
                item.quantity = 1;
                item.subtotal = item.priceExVAT * item.quantity;
                if(site.Parent.BillingCountry == 'United Kingdom'){
                    item.vat = item.subtotal * 0.2;
                }
                item.production = 'Discount';
                lineItems.add(item);
            }else if(pigProduction.size() == 2){
                String pigStage2DiscountId = '';
                for(Product2 p: AppUnitHelper.productList){
                    if(p.ProductCode == 'PIGSTAGE2DISCOUNT'){
                        pigStage2DiscountId = p.Id;
                        break;
                    }
                }
                item.lineDescription = 'Pigs Stage 2 Discount';
                item.priceExVAT = getPriceForProduct(pigStage2DiscountId);
                item.animalOrIngrediants = 'Pigs';
                item.quantity = 1;
                item.subtotal = item.priceExVAT * item.quantity;
                if(site.Parent.BillingCountry == 'United Kingdom'){
                    item.vat = item.subtotal * 0.2;
                }
                item.production = 'Discount';
                lineItems.add(item);
            }
        }


    }

    private void findSupplyChainPricing(Unit__c unit){
        Map<String, LineItem> productNameToLineItem = new Map<String, LineItem>();
        for(LineItem li : lineItems){
            productNameToLineItem.put(li.lineDescription, li);
        }
        //find the supply chain product
        Product2 unitProduct = AppUnitHelper.getProduct(unit.Business__c, unit.Production__c);
        if(unitProduct != null){
            LineItem item = new LineItem();
            item.lineDescription = unitProduct.Name;
            item.priceExVAT = getPriceForProduct(unitProduct.Id);
            item.animalOrIngrediants = unit.Ingredients__c;
            item.numberOfAnimals = unit.Number_of_Animals__c;
            item.quantity = 1;
            item.subtotal = item.priceExVAT * item.quantity;
            if(site.Parent.BillingCountry == 'United Kingdom'){
                item.vat = item.subtotal * 0.2;
            }
            item.production = unit.Production__c;
            item.unitId = unit.Id;
            productNameToLineItem.put(item.lineDescription, item);
        }
        lineItems = productNameToLineItem.values();
    }

    private void findPerSiteUnitPricing(Unit__c unit, Product2 unitProduct){
        Map<String, LineItem> productNameToLineItem = new Map<String, LineItem>();
        for(LineItem li : lineItems){
            productNameToLineItem.put(li.lineDescription, li);
        }

        LineItem item = new LineItem();
        item.lineDescription = unitProduct.Name;
        item.production = unit.Production__c;
        item.priceExVAT = getPriceForProduct(unitProduct.Id);
        item.animalOrIngrediants = unit.Animals__c;
        item.numberOfAnimals = unit.Number_of_Animals__c;
        item.quantity = 1;
        item.subtotal = item.priceExVAT * item.quantity;
        if(site.Parent.BillingCountry == 'United Kingdom'){
            item.vat = item.subtotal * 0.2;
        }
        item.production = unit.Production__c;
        item.unitId = unit.Id;
        productNameToLineItem.put(item.lineDescription, item);
        lineItems = productNameToLineItem.values();
    }

    private void findDynamicQuantityPricing(Unit__c unit, Product2 unitProduct){
        Product2 dynamicQuantityProduct = getDynamicQuantityProduct(unitProduct);
        //if the number of animals is less than or equal to the quantity threshold
        if(unit.Number_of_Animals__c <= unitProduct.Quantity_Threshold__c){
            LineItem item = new LineItem();
            item.lineDescription = unitProduct.Name;
            item.priceExVAT = getPriceForProduct(unitProduct.Id);
            item.animalOrIngrediants = unit.Animals__c;
            item.numberOfAnimals = unit.Number_of_Animals__c;
            item.quantity = 1;
            item.subtotal = item.priceExVAT * item.quantity;
            if(site.Parent.BillingCountry == 'United Kingdom'){
                item.vat = item.subtotal * 0.2;
            }
            item.production = unit.Production__c;
            item.unitId = unit.Id;
            lineItems.add(item);
        }else{
            LineItem item = new LineItem();
            item.lineDescription = dynamicQuantityProduct.Name;
            item.priceExVAT = getPriceForProduct(dynamicQuantityProduct.Id);
            item.animalOrIngrediants = unit.Animals__c;
            item.numberOfAnimals = unit.Number_of_Animals__c;
            item.quantity = 1;
            item.subtotal = item.priceExVAT * item.quantity;
            if(site.Parent.BillingCountry == 'United Kingdom'){
                item.vat = item.subtotal * 0.2;
            }
            item.production = unit.Production__c;
            item.unitId = unit.Id;
            lineItems.add(item);
        }
    }

    private void findAdditionalQuantityPricing(Unit__c unit, Product2 unitProduct){
        Map<String, LineItem> productNameToLineItem = new Map<String, LineItem>();
        for(LineItem li : lineItems){
            productNameToLineItem.put(li.lineDescription, li);
        }

        Boolean existingLineItem = false;
        if(productNameToLineItem.containsKey(unitProduct.Name)){
            existingLineItem = true;
        }

        Product2 additionalQuantityProduct = getAdditionalQuantityProduct(unitProduct);
        if((unitProduct.Family == 'Vehicle') || (unitProduct.Business__c =='Catching')){
            if(!existingLineItem){ // If line item does not exist on application, then standard price is applied
                if((unitProduct.Family == 'Vehicle') && (!unit.Own_Transport__c) ){
                    LineItem item = new LineItem();
                    item.lineDescription = unitProduct.Name;
                    item.priceExVAT = getPriceForProduct(unitProduct.Id);
                    item.animalOrIngrediants = unit.Animals__c;
                    item.numberOfAnimals = unit.Number_of_Animals__c;
                    item.quantity = 1;
                    item.subtotal = item.priceExVAT * item.quantity;
                    if(site.Parent.BillingCountry == 'United Kingdom'){
                        item.vat = item.subtotal * 0.2;
                    }
                    item.production = unit.Production__c;
                    item.unitId = unit.Id;
                    lineItems.add(item);
                }
                if((unitProduct.Family == 'Vehicle') && (unit.Own_Transport__c) ){
                    LineItem item = new LineItem();
                    item.lineDescription = unitProduct.Name;
                    item.priceExVAT = 0;
                    item.animalOrIngrediants = unit.Animals__c;
                    item.numberOfAnimals = unit.Number_of_Animals__c;
                    item.quantity = 1;
                    item.subtotal = item.priceExVAT * item.quantity;
                    if(site.Parent.BillingCountry == 'United Kingdom'){
                        item.vat = item.subtotal * 0.2;
                    }
                    item.production = unit.Production__c;
                    item.unitId = unit.Id;
                    lineItems.add(item);
                }
                if((!unit.Own_Catching__c) && (unitProduct.Business__c =='Catching') ){
                    LineItem item = new LineItem();
                    item.lineDescription = unitProduct.Name;
                    item.priceExVAT = getPriceForProduct(unitProduct.Id);
                    item.animalOrIngrediants = unit.Animals__c;
                    item.numberOfAnimals = unit.Number_of_Animals__c;
                    item.quantity = 1;
                    item.subtotal = item.priceExVAT * item.quantity;
                    if(site.Parent.BillingCountry == 'United Kingdom'){
                        item.vat = item.subtotal * 0.2;
                    }
                    item.production = unit.Production__c;
                    item.unitId = unit.Id;
                    lineItems.add(item);
                }
            }else { // If line item does exist on application, then Additional quantity price is applied
                if((unitProduct.Family == 'Vehicle') && (!unit.Own_Transport__c) ){
                    LineItem item = new LineItem();
                    item.lineDescription = additionalQuantityProduct.Name;
                    item.priceExVAT = getPriceForProduct(additionalQuantityProduct.Id);
                    item.animalOrIngrediants = unit.Animals__c;
                    item.numberOfAnimals = unit.Number_of_Animals__c;
                    item.quantity = 1;
                    item.subtotal = item.priceExVAT * item.quantity;
                    if(site.Parent.BillingCountry == 'United Kingdom'){
                        item.vat = item.subtotal * 0.2;
                    }
                    item.production = unit.Production__c;
                    item.unitId = unit.Id;
                    lineItems.add(item);
                }
                if((unitProduct.Family == 'Vehicle') && (unit.Own_Transport__c) ){
                    LineItem item = new LineItem();
                    item.lineDescription = additionalQuantityProduct.Name;
                    item.priceExVAT = 0;
                    item.animalOrIngrediants = unit.Animals__c;
                    item.numberOfAnimals = unit.Number_of_Animals__c;
                    item.quantity = 1;
                    item.subtotal = item.priceExVAT * item.quantity;
                    if(site.Parent.BillingCountry == 'United Kingdom'){
                        item.vat = item.subtotal * 0.2;
                    }
                    item.production = unit.Production__c;
                    item.unitId = unit.Id;
                    lineItems.add(item);
                }
                if((!unit.Own_Catching__c) && (unitProduct.Business__c =='Catching') ){
                    LineItem item = new LineItem();
                    item.lineDescription = additionalQuantityProduct.Name;
                    item.priceExVAT = getPriceForProduct(additionalQuantityProduct.Id);
                    item.animalOrIngrediants = unit.Animals__c;
                    item.numberOfAnimals = unit.Number_of_Animals__c;
                    item.quantity = 1;
                    item.subtotal = item.priceExVAT * item.quantity;
                    if(site.Parent.BillingCountry == 'United Kingdom'){
                        item.vat = item.subtotal * 0.2;
                    }
                    item.production = unit.Production__c;
                    item.unitId = unit.Id;
                    lineItems.add(item);
                }
            }
        }else{
            if(unitProduct.Family == 'Poultry'){ 
                Decimal existingNumberOfAnimals = unit.Number_of_Animals__c;
                List<LineItem> listItemsToKeep = new List<LineItem>();
                for(LineItem li : lineItems){
                    if(li.animalOrIngrediants == unit.Animals__c){
                        existingNumberOfAnimals = existingNumberOfAnimals + li.numberOfAnimals;
                    }else{
                        listItemsToKeep.add(li);
                    }
                }
                
                //if the number of animals is less than or equal to the quantity threshold
                if(existingNumberOfAnimals <= unitProduct.Quantity_Threshold__c){
                    LineItem item = new LineItem();
                    item.lineDescription = unitProduct.Name;
                    item.priceExVAT = getPriceForProduct(unitProduct.Id);
                    item.animalOrIngrediants = unit.Animals__c;
                    item.numberOfAnimals = existingNumberOfAnimals;
                    item.quantity = 1;
                    item.subtotal = item.priceExVAT * item.quantity;
                    if(site.Parent.BillingCountry == 'United Kingdom'){
                        item.vat = item.subtotal * 0.2;
                    }
                    item.production = unit.Production__c;
                    item.unitId = unit.Id;
                    listItemsToKeep.add(item);
                }else{
                    // add 1 standard price fee and then 1 additional membership fee with quantity from the variable
                    List<Application_Line_Item__c> initialUnits = new List<Application_Line_Item__c>();
                    double q = Math.ceil(existingNumberOfAnimals / unitProduct.Quantity_Threshold__c);
                    // line 1
                    LineItem item1 = new LineItem();
                    item1.lineDescription = unitProduct.Name;
                    item1.priceExVAT = getPriceForProduct(unitProduct.Id);
                    item1.animalOrIngrediants = unit.Animals__c;
                    item1.numberOfAnimals = unitProduct.Quantity_Threshold__c;
                    item1.quantity = 1;
                    item1.subtotal = item1.priceExVAT;
                    if(site.Parent.BillingCountry == 'United Kingdom'){
                        item1.vat = item1.subtotal * 0.2;
                    }
                    item1.production = unit.Production__c;
                    item1.unitId = unit.Id;
                    System.debug('item1 => ' + item1);
                    listItemsToKeep.add(item1);

                    // Line 2
                    LineItem item2 = new LineItem();
                    item2.lineDescription = additionalQuantityProduct.Name;
                    item2.priceExVAT = getPriceForProduct(additionalQuantityProduct.Id);
                    item2.animalOrIngrediants = unit.Animals__c;
                    item2.numberOfAnimals = existingNumberOfAnimals - unitProduct.Quantity_Threshold__c;
                    item2.quantity = q-1;
                    item2.subtotal = item2.priceExVAT * item2.quantity;
                    if(site.Parent.BillingCountry == 'United Kingdom'){
                        item2.vat = item2.subtotal * 0.2;
                    }
                    item2.production = unit.Production__c;
                    item2.unitId = unit.Id;
                    System.debug('item2 => ' + item2);
                    listItemsToKeep.add(item2);
                }
                
                lineItems = listItemsToKeep;
                System.debug('lineItems => ' + lineItems);
                
            }
        }
    
    }

    public class LineItem{
        public String lineDescription{get;set;}
        public Decimal priceExVAT{get;set;}
        public String animalOrIngrediants {get;set;}
        public Decimal numberOfAnimals {get;set;}
        public Double quantity {get;set;}
        public Decimal subtotal {get;set;}
        public Decimal vat {get;set;}
        public String production {get;set;}
        public String unitId {get;set;}

    }

    public List<RenewalPriceChecker.RenewalPriceUnitLine> getRenewalPriceLineForSite(){
        List<RenewalPriceUnitLine> rpulList = new List<RenewalPriceUnitLine>();
        List<Renewal_Price_Report__c> rpr = [SELECT Id, Site__r.Parent.Name, Name,Total_Inc_VAT__c, CreatedDate FROM Renewal_Price_Report__c WHERE Site__c = :accId AND Site__r.Renewal_Reminder_Ready__c = true ORDER BY CreatedDate DESC LIMIT 1];
        totalAmount = rpr[0].Total_Inc_VAT__c;
        groupName = rpr[0].Site__r.Parent.Name;
        List<AggregateResult> aggregateResultList = [SELECT Max(Animal_Or_Ingrediants__c)animalOrIngrediants, SUM(Number_Of_Animals__c)numberOfAnimals, SUM(Total_Inc_VAT__c)totalIncVAT, MAX(Production__c)production, UnitId__c, MAX(Renewal_Price_Report__r.Site__r.Membership_Number__c)membershipNumber, MAX(Renewal_Price_Report__r.Site__r.Name)siteName, MAX(Renewal_Price_Report__r.Membership_Expiry_Date__c)expiryDate FROM Renewal_Price_Line__c WHERE Renewal_Price_Report__r.Site__c = :accId AND Renewal_Price_Report__c = :rpr[0].Id GROUP BY UnitId__c];
        for(AggregateResult ar : aggregateResultList){
            RenewalPriceUnitLine rpul = new RenewalPriceUnitLine();
            rpul.member = (String)ar.get('siteName');
            if((String)ar.get('animalOrIngrediants') == 'Pigs' && (String)ar.get('production') == 'Discount'){
                rpul.member = 'Pig Discount';
            }
            rpul.membershipNumber = '';
            if(ar.get('membershipNumber') != null){
                rpul.membershipNumber = (String)ar.get('membershipNumber');
            }
            String animalsOrIngrediants = '';
            if((String)ar.get('animalOrIngrediants') != null){
                animalsOrIngrediants = (String)ar.get('animalOrIngrediants');
            }
            rpul.unitName = animalsOrIngrediants +' '+ (String)ar.get('production');
            if((Double)ar.get('numberOfAnimals') > 0){
                rpul.unitName =  rpul.unitName + ' (Qty: ' + Math.round((Double)ar.get('numberOfAnimals')) +')' ;
            }
            rpul.amountDue = ((Decimal)ar.get('totalIncVAT')).setScale(2);
            rpul.expiryDate = '';
            if((Date)ar.get('expiryDate') != null){
                rpul.expiryDate = String.valueOf(((Date)ar.get('expiryDate')).day()).leftPad(2,'0') +'/'+ String.valueOf(((Date)ar.get('expiryDate')).month()).leftPad(2,'0') +'/'+ String.valueOf(((Date)ar.get('expiryDate')).year());
            }
            rpulList.add(rpul);
        }
        return rpulList;
    }

    public List<RenewalPriceChecker.RenewalPriceUnitLine> getRenewalPriceLineForHeadOffice(){
        Date invitationReminderDate = Date.today();
        x6WeekRenewalReminderTestDate__c testDateSettingInvitation = x6WeekRenewalReminderTestDate__c.getOrgDefaults();
        if(testDateSettingInvitation.Use_Test_Date_Data__c == true && testDateSettingInvitation.Test_Date__c != null){
            invitationReminderDate = testDateSettingInvitation.Test_Date__c;
        }
        Date finalReminderDate = Date.today();
        x2WeekRenewalReminderTestDate__c testDateSettingFinal = x2WeekRenewalReminderTestDate__c.getOrgDefaults();
        if(testDateSettingFinal.Use_Test_Date_Data__c == true && testDateSettingFinal.Test_Date__c != null){
            finalReminderDate = testDateSettingFinal.Test_Date__c;
        }
        

        List<RenewalPriceUnitLine> rpulList = new List<RenewalPriceUnitLine>();
        totalAmount = 0;
        groupName = '';
        Set<String> reportIds = new Set<String>(); 
        List<AggregateResult> renewalReportAgg = [SELECT MAX(Id)id, MAX(Site__r.Parent.Name)headOfficeName, MAX(Total_Inc_VAT__c)totalIncVat, MAX(CreatedDate) FROM Renewal_Price_Report__c WHERE Site__r.ParentId = :accId AND Site__r.Renewal_Reminder_Ready__c = true AND (Site__r.Final_Renewal_Reminder_Sent__c = null OR Site__r.Six_Week_Renewal_Reminder_Sent__c = null) AND Site__r.Status__c = 'MEMBER' AND (Site__r.X6_Week_Renewal_Scheduled_Date__c =:invitationReminderDate OR Site__r.X2_Week_Renewal_Scheduled_Date__c =:finalReminderDate) GROUP BY Site__c];
        for(AggregateResult ar : renewalReportAgg){
            groupName = (String)ar.get('headOfficeName');
            reportIds.add( (String)ar.get('id') );
        }
        List<AggregateResult> aggregateResultList = [SELECT Max(Animal_Or_Ingrediants__c)animalOrIngrediants, SUM(Number_Of_Animals__c)numberOfAnimals, SUM(Total_Inc_VAT__c)totalIncVAT, MAX(Production__c)production, UnitId__c, MAX(Renewal_Price_Report__r.Site__r.Membership_Number__c)membershipNumber, MAX(Renewal_Price_Report__r.Site__r.Name)siteName, MAX(Renewal_Price_Report__r.Membership_Expiry_Date__c)expiryDate FROM Renewal_Price_Line__c WHERE Renewal_Price_Report__r.Site__r.ParentId = :accId AND Renewal_Price_Report__c IN :reportIds GROUP BY Renewal_Price_Report__r.Site__r.Site_Number__c, UnitId__c ORDER BY Renewal_Price_Report__r.Site__r.Site_Number__c ASC];
        for(AggregateResult ar : aggregateResultList){
            RenewalPriceUnitLine rpul = new RenewalPriceUnitLine();
            rpul.member = (String)ar.get('siteName');
            if((String)ar.get('animalOrIngrediants') == 'Pigs' && (String)ar.get('production') == 'Discount'){
                rpul.member = rpul.member + ' Pig Discount';
            }
            rpul.membershipNumber = '';
            if(ar.get('membershipNumber') != null){
                rpul.membershipNumber = (String)ar.get('membershipNumber');
            }
            String animalsOrIngrediants = '';
            if((String)ar.get('animalOrIngrediants') != null){
                animalsOrIngrediants = (String)ar.get('animalOrIngrediants');
            }
            rpul.unitName = animalsOrIngrediants +' '+ (String)ar.get('production');
            if((Double)ar.get('numberOfAnimals') > 0){
                rpul.unitName =  rpul.unitName + ' (Qty: ' + Math.round((Double)ar.get('numberOfAnimals')) +')' ;
            }
            rpul.amountDue = ((Decimal)ar.get('totalIncVAT')).setScale(2);
            rpul.expiryDate = '';
            if((Date)ar.get('expiryDate') != null){
                rpul.expiryDate = String.valueOf(((Date)ar.get('expiryDate')).day()).leftPad(2,'0') +'/'+ String.valueOf(((Date)ar.get('expiryDate')).month()).leftPad(2,'0') +'/'+ String.valueOf(((Date)ar.get('expiryDate')).year());
            }
            rpulList.add(rpul);


            totalAmount = totalAmount + rpul.amountDue;
        }
        return rpulList;
    }

    public void createRenewalPriceReport(String accountId){
        site = [SELECT Id, Parent.BillingCountry, Membership_Expiry_Date__c, Pig_Discount_Eligibility__c, Create_Renewal_Price_Report__c FROM Account WHERE ID =:accountId];
        List<Unit__c> unitsRecords = [SELECT Id, Name, Account__c, Animals__c, Business__c, Chassis_Number__c, Description__c, House_Type__c, Ingredients__c, Order_Sizes__c, Own_Catching__c, Own_Transport__c, Production__c, Rearing_System__c, Status__c, Vehicle_Registration__c, Vehicle_Type__c, Number_of_Animals__c FROM Unit__c WHERE Account__c =:accountId AND Status__c = 'Certified'];
        getRenewalPriceForUnits(unitsRecords);
        if(!lineItems.isEmpty()){
            Renewal_Price_Report__c rpr = new Renewal_Price_Report__c();
            rpr.Site__c = accountId;
            rpr.Membership_Expiry_Date__c = site.Membership_Expiry_Date__c;
            insert rpr;
            List<Renewal_Price_Line__c> rplList = new List<Renewal_Price_Line__c>();
            for(RenewalPriceChecker.LineItem li : lineItems){
                Renewal_Price_Line__c rpl = new Renewal_Price_Line__c();
                rpl.Renewal_Price_Report__c = rpr.Id;
                rpl.Name = li.lineDescription;
                rpl.Price_Ex_VAT__c = li.priceExVAT;
                rpl.Animal_Or_Ingrediants__c = li.animalOrIngrediants;
                rpl.Number_Of_Animals__c = li.numberOfAnimals;
                rpl.Quantity__c = li.quantity;
                rpl.Subtotal__c = li.subtotal;
                rpl.VAT__c = 0;
                if(li.vat != null){
                    rpl.VAT__c = li.vat;
                }
                rpl.Total_Inc_VAT__c = rpl.Subtotal__c + rpl.VAT__c;
                rpl.Production__c = li.production;
                rpl.UnitId__c = li.unitId;
                rplList.add(rpl);
            }
            insert rplList;
        }
        
    }

    public class RenewalPriceUnitLine{
        public String member{get;set;}
        public String membershipNumber{get;set;}
        public String unitName {get;set;}
        public String expiryDate {get;set;}
        public Decimal amountDue {get;set;}
    }

    public Decimal getNetAmount(){
        Decimal netAmount = 0;
        for(LineItem li : lineItems){
            netAmount = netAmount + li.subtotal;
        }
        return netAmount;
    }

    public Decimal getVatAmount(){
        Decimal vatAmount = 0;
        for(LineItem li : lineItems){
            vatAmount = vatAmount + li.vat;
        }
        return vatAmount;
    }

}