unpackaged/main/default/objects/Account/fields/Date_Suspended_No_Evidence__c.field-meta.xml
<CustomField>
    <fullName>Date_Suspended_No_Evidence__c</fullName>
    <label>Suspension Due to Non-return of Evidence</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Membership_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Evidence__c.field-meta.xml
<CustomField>
    <fullName>Evidence__c</fullName>
    <inlineHelpText>Link to evidence folder</inlineHelpText>
    <label>Evidence</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Evidence_Deadline__c.field-meta.xml
<CustomField>
    <fullName>Evidence_Deadline__c</fullName>
    <description>The date by which evidence needs to be submitted.</description>
    <inlineHelpText>The date by which evidence needs to be submitted.</inlineHelpText>
    <label>Evidence Deadline</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Extension_Deadline__c.field-meta.xml
<CustomField>
    <fullName>Extension_Deadline__c</fullName>
    <label>Extension Deadline</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>ApplicationSite</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Site__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Membership_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ADDITION</fullName>
    </customValue>
    <customValue>
        <fullName>ARCHIVED</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC5R</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC7R</fullName>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
    </customValue>
    <customValue>
        <fullName>CONPASS</fullName>
    </customValue>
    <customValue>
        <fullName>ENQUIRY</fullName>
        <default>true</default>
        <label>ENQUIRY</label>
    </customValue>
    <customValue>
        <fullName>EVIDENCE</fullName>
    </customValue>
    <customValue>
        <fullName>FAILED</fullName>
    </customValue>
    <customValue>
        <fullName>FALLOW</fullName>
    </customValue>
    <customValue>
        <fullName>LAPSED</fullName>
    </customValue>
    <customValue>
        <fullName>MEMBER</fullName>
    </customValue>
    <customValue>
        <fullName>MONREQ</fullName>
    </customValue>
    <customValue>
        <fullName>NEW</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2R</fullName>
    </customValue>
    <customValue>
        <fullName>NEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>NONFR</fullName>
    </customValue>
    <customValue>
        <fullName>NOTINSCHEME</fullName>
    </customValue>
    <customValue>
        <fullName>PASSED</fullName>
    </customValue>
    <customValue>
        <fullName>PREPANEL</fullName>
    </customValue>
    <customValue>
        <fullName>REINSTATE</fullName>
    </customValue>
    <customValue>
        <fullName>RENEW/REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWA</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWALINP</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWR</fullName>
    </customValue>
    <customValue>
        <fullName>REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>SUSPENDED</fullName>
    </customValue>
    <masterLabel>Membership Status</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/SuspendAccountBatch.cls
public class SuspendAccountBatch implements Database.Batchable<sObject>, Schedulable{

    public Database.QueryLocator start(Database.BatchableContext bc){
        String query = 'SELECT Id, Name, Evidence__c, Evidence_Deadline__c, Extension_Deadline__c, Site__c FROM Application__c';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<Application__c> appList){
        Date dt = Date.today();
        List<Account> actUpdateList = new List<Account>();
        Set<Id> accIdSet = new Set<Id>();
        for(Application__c app : appList){
            if(app.Site__c != null){
                accIdSet.add(app.Site__c);
            }
        }

        List<Account> actList = [SELECT Id, Name, Status__c FROM Account WHERE Id IN: accIdSet];

        for(Application__c app : appList){
            for(Account act : actList){
                if(app.Extension_Deadline__c != null && app.Evidence__c == null 
                   && app.Extension_Deadline__c <= dt && app.Site__c == act.Id){
                       act.Status__c = 'SUSPENDED';
                       act.Date_Suspended_No_Evidence__c = Date.today();
                       actUpdateList.add(act);
                   }else if(app.Evidence_Deadline__c != null && app.Evidence__c == null 
                            && app.Evidence_Deadline__c <= dt && app.Site__c == act.Id){
                                act.Status__c = 'SUSPENDED';
                                act.Date_Suspended_No_Evidence__c = Date.today();
                                actUpdateList.add(act);
                   }
            }
        }

        if(actUpdateList.size() > 0){
            try{
                update actUpdateList;
            }catch(DMLException e){
                System.debug('Error updating Account Status to suspended '+e.getMessage());
            }
        }
    }

    public void finish(Database.BatchableContext bc){}

    public void execute(SchedulableContext sc){
        SuspendAccountBatch obj = new SuspendAccountBatch();
        Database.executeBatch(obj);
    }
}