unpackaged/main/default/objects/Account/fields/Date_Suspended_No_Evidence__c.field-meta.xml
<CustomField>
    <fullName>Date_Suspended_No_Evidence__c</fullName>
    <label>Suspension Due to Non-return of Evidence</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Membership_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Membership_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ADDITION</fullName>
    </customValue>
    <customValue>
        <fullName>ARCHIVED</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC5R</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC7R</fullName>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
    </customValue>
    <customValue>
        <fullName>CONPASS</fullName>
    </customValue>
    <customValue>
        <fullName>ENQUIRY</fullName>
        <default>true</default>
        <label>ENQUIRY</label>
    </customValue>
    <customValue>
        <fullName>EVIDENCE</fullName>
    </customValue>
    <customValue>
        <fullName>FAILED</fullName>
    </customValue>
    <customValue>
        <fullName>FALLOW</fullName>
    </customValue>
    <customValue>
        <fullName>LAPSED</fullName>
    </customValue>
    <customValue>
        <fullName>MEMBER</fullName>
    </customValue>
    <customValue>
        <fullName>MONREQ</fullName>
    </customValue>
    <customValue>
        <fullName>NEW</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2R</fullName>
    </customValue>
    <customValue>
        <fullName>NEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>NONFR</fullName>
    </customValue>
    <customValue>
        <fullName>NOTINSCHEME</fullName>
    </customValue>
    <customValue>
        <fullName>PASSED</fullName>
    </customValue>
    <customValue>
        <fullName>PREPANEL</fullName>
    </customValue>
    <customValue>
        <fullName>REINSTATE</fullName>
    </customValue>
    <customValue>
        <fullName>RENEW/REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWA</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWALINP</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWR</fullName>
    </customValue>
    <customValue>
        <fullName>REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>SUSPENDED</fullName>
    </customValue>
    <customValue>
        <fullName>WITHDRAWN</fullName>
    </customValue>
    <masterLabel>Membership Status</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/WithdrawAccountBatch.cls
public class WithdrawAccountBatch implements Database.Batchable<sObject>, Schedulable{

    public Database.QueryLocator start(Database.BatchableContext bc){
        String query = 'SELECT Id, Name, Status__c, Date_Suspended_No_Evidence__c FROM Account WHERE Date_Suspended_No_Evidence__c != null';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<Account> actList){
        List<Account> ActUpdateList = new List<Account>();
        for(Account act : actList){
            if(act.Date_Suspended_No_Evidence__c.addDays(90) >= Date.today()){
                act.Status__c = 'WITHDRAWN';
                ActUpdateList.add(act);
            } 
        }
        if(ActUpdateList.size() > 0){
            try{
                update ActUpdateList;
            }catch(DMLException e){
                System.debug('Error while updating Account Status to Withdrawn '+e.getMessage());
            }
        }
    }

    public void finish(Database.BatchableContext bc){}

    public void execute(SchedulableContext sc){
        WithdrawAccountBatch obj = new WithdrawAccountBatch();
        Database.executeBatch(obj);
    }
}