unpackaged/main/default/objects/Account/fields/Generate_Head_Office_Number__c.field-meta.xml
<CustomField>
    <fullName>Generate_Head_Office_Number__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When this checkbox is ticked (automated process), and the head office number field is empty, a new head office number will be generated.</description>
    <label>Generate Head Office Number</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Generate_Site_Number__c.field-meta.xml
<CustomField>
    <fullName>Generate_Site_Number__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When this checkbox is ticked (automated process), and the site number field is empty, a new site number will be generated.</description>
    <label>Generate Site Number</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Head_Office_Number__c.field-meta.xml
<CustomField>
    <fullName>Head_Office_Number__c</fullName>
    <inlineHelpText>The first four digits of the full membership number that represents the group</inlineHelpText>
    <label>Head Office Membership Number</label>
    <length>4</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Site_Number__c.field-meta.xml
<CustomField>
    <fullName>Site_Number__c</fullName>
    <inlineHelpText>4 digit membership number for site.</inlineHelpText>
    <label>Site Number</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <description>An Account representing a site.</description>
    <label>Site</label>
</RecordType>

unpackaged/main/default/classes/AccountTriggerHandlerTest.cls
@isTest
public class AccountTriggerHandlerTest {
    @isTest
    static void createSiteNumberTest() {
        // Create Head office account
        FObject headOffice = DataFactory.getDefHeadOfficeAccounts();
        headOffice.setDefinition('Head_Office_Number__c', 'static value(1234)');// Set Head Office Number
        headOffice.insertRecords(true);
        //AccountTriggerHandler.firstRunBeforeUpdate = true;
        // Create Site 1 account with existing Site number
        FObject site1 = DataFactory.getDefSiteAccounts();
        site1.setDefinition('ParentId', 'static lookup(Account) field(Site) value(HeadOffice) source(forceea)');
        site1.setDefinition('Site_Number__c', 'static value(0001)');
        site1.insertRecords(true);

        //AccountTriggerHandler.firstRunBeforeUpdate = true;
        // Create Site 2 account with generate site number checked
        FObject site2 = DataFactory.getDefSiteAccounts();
        site2.setDefinition('ParentId', 'static lookup(Account) field(Site) value(HeadOffice) source(forceea)');
        site2.setDefinition('Generate_Site_Number__c', 'static value(true)');
        site2.insertRecords(true);

        
    }
    @isTest
    static void createHeadOfficeNumberTest() {
        // Create Head Office 1 account with head office number populated
        FObject headOffice1 = DataFactory.getDefHeadOfficeAccounts();
        headOffice1.setDefinition('Head_Office_Number__c', 'static value(1234)');
        headOffice1.insertRecords(true);

        //AccountTriggerHandler.firstRunBeforeUpdate = true;
        // Create Head Office 2 account with generate head office number checked
        FObject headOffice2 = DataFactory.getDefHeadOfficeAccounts();
        headOffice2.setDefinition('Generate_Head_Office_Number__c', 'static value(true)');
        headOffice2.insertRecords(true);

    }
}