unpackaged/main/default/objects/Account/fields/Head_Office_Number__c.field-meta.xml
<CustomField>
    <fullName>Head_Office_Number__c</fullName>
    <inlineHelpText>The first four digits of the full membership number that represents the group</inlineHelpText>
    <label>Head Office Membership Number</label>
    <length>4</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Previous_Assessor__c.field-meta.xml
<CustomField>
    <fullName>Previous_Assessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Previous Assessor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Assessor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Primary Account(DoNotUse)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Site_Number__c.field-meta.xml
<CustomField>
    <fullName>Site_Number__c</fullName>
    <inlineHelpText>4 digit membership number for site.</inlineHelpText>
    <label>Site Number</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Membership_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <description>An Account representing a site.</description>
    <label>Site</label>
</RecordType>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Agreement__c.field-meta.xml
<CustomField>
    <fullName>Agreement__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>I have read and agreed to the terms of the SCI Certification UK scheme regulations and RSPCA Assured membership agreement.</inlineHelpText>
    <label>Agreement</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Application_Type__c</fullName>
    <label>Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Existing_Member__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Revisit</fullName>
            </value>
            <value>
                <fullName>Levy</fullName>
            </value>
            <value>
                <fullName>Merchandise</fullName>
            </value>
            <value>
                <fullName>Promotion/Partnership</fullName>
            </value>
            <value>
                <fullName>Consultancy</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Function: member services select an assessor; system then automatically emails them.</description>
    <inlineHelpText>This field must be populated in order to mark an Additional Visit as complete.</inlineHelpText>
    <label>Allocated Assessor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>You can only select an assessor user to be allocated for this application.</errorMessage>
        <filterItems>
            <field>User.Assessor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>User.Contract_Assessor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Existing_Member__c.field-meta.xml
<CustomField>
    <fullName>Existing_Member__c</fullName>
    <label>Existing Member?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Head_Office__c.field-meta.xml
<CustomField>
    <fullName>Head_Office__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Head Office</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Head Office</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/No_Offences__c.field-meta.xml
<CustomField>
    <fullName>No_Offences__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>I confirm that I do not have any previous convictions or pending prosecutions relating to any offence involving the care, handling, transport, slaughter or sale of animals or produce.</inlineHelpText>
    <label>No Offences</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BACS</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
                <isActive>false</isActive>
                <label>Card</label>
            </value>
            <value>
                <fullName>Cheque</fullName>
                <isActive>false</isActive>
                <label>Cheque</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Renewal_Stage__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Stage__c</fullName>
    <description>Stage for renewal application. This stage is used in renewal record type.</description>
    <label>Renewal Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Allocation</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Signatory_Contact__c.field-meta.xml
<CustomField>
    <fullName>Signatory_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Signatory Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications (Signatory Contact)</relationshipLabel>
    <relationshipName>Applications1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>ApplicationSite</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Site__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <description>For renewal applications</description>
    <label>Renewal</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <formula>IF(Id = Account.Primary_Contact__r.Id , true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates that this contact is the primary contact for the account that it is affiliated with.</inlineHelpText>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Production__c.field-meta.xml
<CustomField>
    <fullName>Production__c</fullName>
    <label>Production</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Production</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Species_Discount_Extra__c.field-meta.xml
<CustomField>
    <fullName>Species_Discount_Extra__c</fullName>
    <label>Species Discount Extra</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Standard_Price__c.field-meta.xml
<CustomField>
    <fullName>Standard_Price__c</fullName>
    <label>Standard Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Unit__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Animals__c.field-meta.xml
<CustomField>
    <fullName>Animals__c</fullName>
    <label>Animals</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Animals</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Ingredients__c.field-meta.xml
<CustomField>
    <fullName>Ingredients__c</fullName>
    <label>Ingredients</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Ingredients</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Order_Sizes__c.field-meta.xml
<CustomField>
    <fullName>Order_Sizes__c</fullName>
    <label>Order Sizes</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Small</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Production__c.field-meta.xml
<CustomField>
    <fullName>Production__c</fullName>
    <label>Production</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Production</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applying</fullName>
                <default>true</default>
                <label>Applying</label>
            </value>
            <value>
                <fullName>Certified</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this box is checked, this user will be available to select during the allocation phase of the application/renewals.</description>
    <inlineHelpText>Check this box if the user is an assessor.</inlineHelpText>
    <label>Assessor</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/globalValueSets/Animals.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Beef Cattle</fullName>
    </customValue>
    <customValue>
        <fullName>Chickens</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy Cattle</fullName>
    </customValue>
    <customValue>
        <fullName>Ducklings</fullName>
    </customValue>
    <customValue>
        <fullName>Ducks</fullName>
    </customValue>
    <customValue>
        <fullName>Laying Hen Chicks</fullName>
    </customValue>
    <customValue>
        <fullName>Laying Hens</fullName>
    </customValue>
    <customValue>
        <fullName>Lumpfish</fullName>
    </customValue>
    <customValue>
        <fullName>Meat Chicken Chicks</fullName>
    </customValue>
    <customValue>
        <fullName>Pigs</fullName>
    </customValue>
    <customValue>
        <fullName>Pullets</fullName>
    </customValue>
    <customValue>
        <fullName>Salmon</fullName>
    </customValue>
    <customValue>
        <fullName>Sheep</fullName>
    </customValue>
    <customValue>
        <fullName>Trout</fullName>
    </customValue>
    <customValue>
        <fullName>Turkey Poults</fullName>
    </customValue>
    <customValue>
        <fullName>Turkeys</fullName>
    </customValue>
    <customValue>
        <fullName>Veal Calves</fullName>
    </customValue>
    <customValue>
        <fullName>Wrasse</fullName>
    </customValue>
    <customValue>
        <fullName>List</fullName>
    </customValue>
    <masterLabel>Animals</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Business.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abattoir</fullName>
    </customValue>
    <customValue>
        <fullName>Catching</fullName>
    </customValue>
    <customValue>
        <fullName>Cleaner Fish</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery</fullName>
    </customValue>
    <customValue>
        <fullName>Haulier</fullName>
    </customValue>
    <customValue>
        <fullName>Producer</fullName>
    </customValue>
    <customValue>
        <fullName>Supply Chain</fullName>
    </customValue>
    <masterLabel>Business</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Ingredients.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Beef</fullName>
    </customValue>
    <customValue>
        <fullName>Chicken</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Duck</fullName>
    </customValue>
    <customValue>
        <fullName>Eggs</fullName>
    </customValue>
    <customValue>
        <fullName>Lamb</fullName>
    </customValue>
    <customValue>
        <fullName>Pork</fullName>
    </customValue>
    <customValue>
        <fullName>Salmon</fullName>
    </customValue>
    <customValue>
        <fullName>Trout</fullName>
    </customValue>
    <customValue>
        <fullName>Turkey</fullName>
    </customValue>
    <customValue>
        <fullName>Veal</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Ingredients</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Membership_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ADDITION</fullName>
    </customValue>
    <customValue>
        <fullName>ARCHIVED</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC5R</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC7R</fullName>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
    </customValue>
    <customValue>
        <fullName>CONPASS</fullName>
    </customValue>
    <customValue>
        <fullName>ENQUIRY</fullName>
        <default>true</default>
        <label>ENQUIRY</label>
    </customValue>
    <customValue>
        <fullName>EVIDENCE</fullName>
    </customValue>
    <customValue>
        <fullName>FAILED</fullName>
    </customValue>
    <customValue>
        <fullName>FALLOW</fullName>
    </customValue>
    <customValue>
        <fullName>LAPSED</fullName>
    </customValue>
    <customValue>
        <fullName>MEMBER</fullName>
    </customValue>
    <customValue>
        <fullName>MONREQ</fullName>
    </customValue>
    <customValue>
        <fullName>NEW</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2R</fullName>
    </customValue>
    <customValue>
        <fullName>NEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>NONFR</fullName>
    </customValue>
    <customValue>
        <fullName>NOTINSCHEME</fullName>
    </customValue>
    <customValue>
        <fullName>PASSED</fullName>
    </customValue>
    <customValue>
        <fullName>PREPANEL</fullName>
    </customValue>
    <customValue>
        <fullName>REINSTATE</fullName>
    </customValue>
    <customValue>
        <fullName>RENEW/REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWA</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWALINP</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWR</fullName>
    </customValue>
    <customValue>
        <fullName>REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>SUSPENDED</fullName>
    </customValue>
    <masterLabel>Membership Status</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Production.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abattoir</fullName>
    </customValue>
    <customValue>
        <fullName>Brand/Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Breeding</fullName>
    </customValue>
    <customValue>
        <fullName>Brood</fullName>
    </customValue>
    <customValue>
        <fullName>Calves</fullName>
    </customValue>
    <customValue>
        <fullName>Catching Team</fullName>
    </customValue>
    <customValue>
        <fullName>Cleaner Fish</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Dry Cows</fullName>
    </customValue>
    <customValue>
        <fullName>Finishing</fullName>
    </customValue>
    <customValue>
        <fullName>Flat deck (one-storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Flat deck (two storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Flat deck with Veranda</fullName>
    </customValue>
    <customValue>
        <fullName>Freshwater</fullName>
    </customValue>
    <customValue>
        <fullName>Gilts</fullName>
    </customValue>
    <customValue>
        <fullName>Grazing</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery (On Grower)</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery (Ova)</fullName>
    </customValue>
    <customValue>
        <fullName>Haulier</fullName>
    </customValue>
    <customValue>
        <fullName>Heifers</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-tier (one-storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-tier (two-storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-tier with Veranda</fullName>
    </customValue>
    <customValue>
        <fullName>Packer</fullName>
    </customValue>
    <customValue>
        <fullName>Processor</fullName>
    </customValue>
    <customValue>
        <fullName>Processor/Packer</fullName>
    </customValue>
    <customValue>
        <fullName>Producer</fullName>
    </customValue>
    <customValue>
        <fullName>Rearing</fullName>
    </customValue>
    <customValue>
        <fullName>Retailer</fullName>
    </customValue>
    <masterLabel>Production</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/TransferControllerTest.cls
@isTest
public class TransferControllerTest {
    /*
    @isTest
    public static void fetchCustomerContactWithUser() {
        // Create System Admin User with Role to create the account
        FObject adminUser = new FObject('User', 1);
        adminUser.setDefinition('ProfileId', 'static lookup(Profile) field(Name) value(System Administrator) source(salesforce)');
        adminUser.setDefinition('Alias','static value(testadm)');
        adminUser.setDefinition('LastName','static value(testadmin)');
        adminUser.setDefinition('UserName','static value(testadmin543434234324@test.com)');
        adminUser.setDefinition('Email','static value(testadmin@test.com)');
        adminUser.setDefinition('UserRoleId', 'random lookup(UserRole) source(forceea)');
        adminUser.insertRecords(true);
        List<User> insertedUsers = FObject.getInsertedRecords('User');
        User insertedAdminUser = new User();
        for(User u : insertedUsers){
            if(u.Alias == 'testadm'){
                insertedAdminUser = u;
            }
        }

        System.runAs(insertedAdminUser){
            // Account
            FObject acc = DataFactory.getDefSiteAccounts();
            //acc.setDefinition('Primary_Contact__c', 'random lookup(Contact) source(forceaa)');
            acc.insertRecords(true);
            
            // Contact
            FObject con = DataFactory.getDefContact();
            con.setDefinition('AccountId', 'random lookup(Account) source(forceea)');
            con.insertRecords(true);
        }
        

        // Create customer user to run the tests with
        FObject customerUser = new FObject('User', 1);
        customerUser.setDefinition('ProfileId', 'static lookup(Profile) field(Name) value(RSPCA Assured Community User Site) source(salesforce)');
        customerUser.setDefinition('ContactId', 'random lookup(Contact) source(forceea)');
        customerUser.setDefinition('Alias','static value(test)');
        customerUser.setDefinition('LastName','static value(Last)');
        customerUser.setDefinition('UserName','static value(tester@test.com)');
        customerUser.setDefinition('Email','static value(tester@test.com)');
        customerUser.insertRecords(true);
        List<User> users = FObject.getInsertedRecords('User');
        List<Account> accounts = FObject.getInsertedRecords('Account');
        User insertedCustomerUser = new User();
        for(User u : users){
            if(u.Alias == 'test'){
                insertedCustomerUser = u;
            }
        }
        Test.startTest();
        System.runAs(insertedCustomerUser){
            TransferController.fetchCustomerContact(accounts[0].Id);
            
        }
        Test.stopTest();
    }

    @isTest
    public static void fetchCustomerContactWithoutUser() {
        // Account
        FObject acc = DataFactory.getDefSiteAccounts();
        acc.insertRecords(true);
        
        // Contact
        FObject con = DataFactory.getDefContact();
        con.setDefinition('FirstName', 'static value(test)');
        con.setDefinition('AccountId', 'random lookup(Account) source(forceea)');
        con.insertRecords(true);
        List<Contact> contacts = FObject.getInsertedRecords('Contact');
        List<Account> accounts = FObject.getInsertedRecords('Account');
        Account accRecord = accounts[0];
        accRecord.Primary_Contact__c = contacts[0].Id;
        update accRecord;
        TransferController.fetchCustomerContact(accounts[0].Id);
    }

    @isTest
    public static void createTransferApplication() {
        // Create joinFee product
        FObject joinFee = new FObject('Product2', 1);
        joinFee.setDefinition('Name','static value(Joining Fee)');
        joinFee.setDefinition('ProductCode','static value(JOINFEE)');
        joinFee.setDefinition('IsActive','static value(true)');
        joinFee.setDefinition('Standard_Price__c','static value(28.80)');
        joinFee.insertRecords(true);
        
        // Create revisitFee product
        FObject revisitFee = new FObject('Product2', 1);
        revisitFee.setDefinition('Name','static value(Revisit)');
        revisitFee.setDefinition('ProductCode','static value(REVISIT)');
        revisitFee.setDefinition('IsActive','static value(true)');
        revisitFee.setDefinition('Standard_Price__c','static value(119)');
        revisitFee.insertRecords(true);

        // Create species discount product
        FObject speciesDiscount = new FObject('Product2', 1);
        speciesDiscount.setDefinition('Name','static value(Species Discount)');
        speciesDiscount.setDefinition('ProductCode','static value(SPECIESDISCOUNT)');
        speciesDiscount.setDefinition('IsActive','static value(true)');
        speciesDiscount.setDefinition('Standard_Price__c','static value(-59.50)');
        speciesDiscount.setDefinition('Species_Discount_Extra__c','static value(-88.00)');
        speciesDiscount.insertRecords(true);

        // Create Head office account
        FObject headOffice = DataFactory.getDefHeadOfficeAccounts();
        headOffice.setDefinition('Head_Office_Number__c', 'static value(1234)');// Set Head Office Number
        headOffice.insertRecords(true);
        // Create Site 1 account with existing Site number
        FObject site1 = DataFactory.getDefSiteAccounts();
        site1.setDefinition('ParentId', 'static lookup(Account) field(Site) value(HeadOffice) source(forceea)');
        site1.setDefinition('Site_Number__c', 'static value(0001)');
        site1.insertRecords(true);

        List<Account> accounts = FObject.getInsertedRecords('Account');
        Account siteRecord = new Account();
        Account headOfficeRecord = new Account();
        for(Account acc : accounts){
            if(acc.Site_Number__c == '0001'){
                siteRecord = acc;
            }
            if(acc.Head_Office_Number__c == '1234'){
                headOfficeRecord = acc;
            }
        }
        // Create user for assessor
        FObject assessor = new FObject('User', 1);
        assessor.setDefinition('ProfileId', 'static lookup(Profile) field(Name) value(System Administrator) source(salesforce)');
        //assessor.setDefinition('ContactId', 'random lookup(Contact) source(forceea)');
        assessor.setDefinition('Alias','static value(test)');
        assessor.setDefinition('LastName','static value(Last)');
        assessor.setDefinition('UserName','static value(tester5346435324455345@test.com)');
        assessor.setDefinition('Email','static value(tester@test.com)');
        assessor.setDefinition('Assessor__c', 'static value(true)');
        assessor.insertRecords(true);
        List<User> users = FObject.getInsertedRecords('User');

        // Create primary contact
        Contact c = new Contact();
        c.FirstName = 'first';
        c.LastName = 'last';
        c.Email = 'test@test.com';
        c.AccountId = siteRecord.Id;
        insert c;

        siteRecord.Primary_Contact__c = c.Id;
        siteRecord.Previous_Assessor__c = users[0].Id;

        update siteRecord;

        // Create Units
        List<Unit__c> unitList = new List<Unit__c>();
        Unit__c unit1 = new Unit__c();
        unit1.Account__c = siteRecord.Id;
        unit1.Name = '01';
        unit1.Business__c = 'Supply Chain';
        unit1.Ingredients__c = 'Beef';
        unit1.Production__c = 'Processor';
        unit1.Order_Sizes__C = 'Single';
        unit1.Status__c = 'Certified';
        unitList.add(unit1);

        Unit__c unit2 = new Unit__c();
        unit2.Account__c = siteRecord.Id;
        unit2.Name = '02';
        unit2.Business__c = 'Abattoir';
        unit2.Animals__c = 'Beef Cattle';
        unit2.Production__c = 'Abattoir';
        unit1.Status__c = 'Certified';
        unitList.add(unit2);

        insert unitList;
        TransferController.getHeadOffice(siteRecord.Id, headOfficeRecord.Head_Office_Number__c);

        // Create transfer application
        FObject application = new FObject('Application__c', 1);
        application.setDefinition('Site__c', 'static lookup(Account) field(Site_Number__c) value(0001) source(forceea)');
        application.setDefinition('Head_Office__c', 'static lookup(Account) field(Head_Office_Number__c) value(1234) source(forceea)');
        application.setDefinition('RecordTypeId', 'static value(Renewal)');
        application.setDefinition('Renewal_Stage__c', 'static value(Renewal)');
        application.setDefinition('Existing_Member__c', 'static value(Yes)');
        application.setDefinition('Application_Type__c', 'static value(Transfer)');
        application.setDefinition('Payment_Method__c', 'static value(BACS)');
        application.setDefinition('Agreement__c', 'static value(true)');
        application.setDefinition('No_Offences__c', 'static value(true)');
        application.insertRecords(true);

        List<Application__c> insertedApps = FObject.getInsertedRecords('Application__c');

        Application__c application2 = insertedApps[0].clone(false,false,false,false);
        application2.Signatory_Contact__c = c.Id;
        application2.Applicant_Contact__c = c.Id;
        application2.Agreement_Date__c = Date.today();

        // Create independant transfer
        TransferController.createTransferApplication(application2, 'Independant', null, siteRecord);

        
    }*/
}