unpackaged/main/default/objects/Account/fields/ia_crm__Sync_With_Intacct__c.field-meta.xml
<CustomField>
    <fullName>ia_crm__Sync_With_Intacct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync With Intacct</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Membership_Number__c.field-meta.xml
<CustomField>
    <fullName>Membership_Number__c</fullName>
    <formula>Parent.Head_Office_Number__c  &amp; &quot;.&quot;  &amp;  Site_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Bulk_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Renewal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bulk Renewal</label>
    <referenceTo>Bulk_Renewal__c</referenceTo>
    <relationshipLabel>Renewal Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Head_Office__c.field-meta.xml
<CustomField>
    <fullName>Head_Office__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Head Office</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Head Office</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Payment_Reference__c.field-meta.xml
<CustomField>
    <fullName>Payment_Reference__c</fullName>
    <description>Payment Reference autogenerated by salesforce.</description>
    <formula>Sage_Invoice__r.Invoice_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Reference</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Pricebook_Id__c.field-meta.xml
<CustomField>
    <fullName>Pricebook_Id__c</fullName>
    <label>Pricebook Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Sage_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sage_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sage Invoice</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>ApplicationSite</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Application__c/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <description>For renewal applications</description>
    <label>Renewal</label>
</RecordType>

unpackaged/main/default/objects/Application_Line_Item__c/Application_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Application Line Item</label>
    <nameField>
        <displayFormat>APL-{0000}</displayFormat>
        <label>Application Line Item Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application_Line_Item__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Application_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Application_Line_Item__c/fields/Application_Unit__c.field-meta.xml
<CustomField>
    <fullName>Application_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application Unit</label>
    <referenceTo>Application_Unit__c</referenceTo>
    <relationshipLabel>Application Line Items</relationshipLabel>
    <relationshipName>Application_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application_Line_Item__c/fields/Item_Description__c.field-meta.xml
<CustomField>
    <fullName>Item_Description__c</fullName>
    <formula>Product__r.Description</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Item Description</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application_Line_Item__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>List Price Ex Vat</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Application_Line_Item__c/fields/List_Price_Inc_Vat__c.field-meta.xml
<CustomField>
    <fullName>List_Price_Inc_Vat__c</fullName>
    <label>List Price Inc Vat</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Application_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Application Line Items</relationshipLabel>
    <relationshipName>Application_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application_Line_Item__c/fields/Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Subtotal__c</fullName>
    <formula>List_Price__c  *  Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subtotal</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/Application_Unit__c.object-meta.xml
<CustomObject>
    <label>Application Unit</label>
    <nameField>
        <displayFormat>APUN-{00}</displayFormat>
        <label>APP Unit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application_Unit__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Application Units</relationshipLabel>
    <relationshipName>ApplicationUnits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Application_Unit__c/fields/Number_of_Animals__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Animals__c</fullName>
    <formula>Unit__r.Number_of_Animals__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Animals</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Bulk_Renewal__c/Bulk_Renewal__c.object-meta.xml
<CustomObject>
    <description>Object to record the renewal applications created from bulk renewing.</description>
    <label>Bulk Renewal</label>
    <nameField>
        <displayFormat>BR{000000}</displayFormat>
        <label>Bulk Renewal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bulk Renewals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bulk_Renewal__c/fields/Application_Contact__c.field-meta.xml
<CustomField>
    <fullName>Application_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bulk Renewals</relationshipLabel>
    <relationshipName>Bulk_Renewals</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Bulk_Renewal__c/fields/Create_Sage_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Create_Sage_Invoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Create Sage Invoice</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Bulk_Renewal__c/fields/Head_Office__c.field-meta.xml
<CustomField>
    <fullName>Head_Office__c</fullName>
    <label>Head Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bulk Renewals</relationshipLabel>
    <relationshipName>Bulk_Renewals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Bulk_Renewal__c/fields/Payment_Reference__c.field-meta.xml
<CustomField>
    <fullName>Payment_Reference__c</fullName>
    <formula>Sage_Invoice__r.Invoice_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Reference</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bulk_Renewal__c/fields/Sage_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sage_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sage Invoice</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bulk Renewals</relationshipLabel>
    <relationshipName>Bulk_Renewals</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Roles__c.field-meta.xml
<CustomField>
    <fullName>Roles__c</fullName>
    <label>Roles</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administration Contact</fullName>
            </value>
            <value>
                <fullName>Agricultural/Technical Contact</fullName>
            </value>
            <value>
                <fullName>Artwork Contact</fullName>
            </value>
            <value>
                <fullName>Assessments Contact</fullName>
            </value>
            <value>
                <fullName>Certification Contact</fullName>
            </value>
            <value>
                <fullName>Compliance Contact</fullName>
            </value>
            <value>
                <fullName>Membership Fee Contact</fullName>
            </value>
            <value>
                <fullName>Licence Fee Contact</fullName>
            </value>
            <value>
                <fullName>Traceability Contact</fullName>
            </value>
            <value>
                <fullName>Payments Contact</fullName>
            </value>
            <value>
                <fullName>Partnerships Commercial Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Invoices &amp; Credit Notes</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Bulk_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Renewal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bulk Renewal</label>
    <referenceTo>Bulk_Renewal__c</referenceTo>
    <relationshipLabel>Sage Invoices</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/ia_crm__Intacct_Transaction__c.field-meta.xml
<CustomField>
    <fullName>ia_crm__Intacct_Transaction__c</fullName>
    <label>Intacct Transaction</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales Invoice</fullName>
            </value>
            <value>
                <fullName>Sales Order</fullName>
            </value>
            <value>
                <fullName>Sales Quote</fullName>
            </value>
            <value>
                <fullName>Sales Credit Note</fullName>
            </value>
            <value>
                <fullName>Shipper</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/ia_crm__Sync_With_Intacct__c.field-meta.xml
<CustomField>
    <fullName>ia_crm__Sync_With_Intacct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync With Intacct</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beef</fullName>
            </value>
            <value>
                <fullName>Chicken</fullName>
            </value>
            <value>
                <fullName>Dairy</fullName>
            </value>
            <value>
                <fullName>Eggs</fullName>
            </value>
            <value>
                <fullName>Lamb</fullName>
            </value>
            <value>
                <fullName>Pork</fullName>
            </value>
            <value>
                <fullName>Salmon</fullName>
            </value>
            <value>
                <fullName>Salmon &amp; Trout</fullName>
            </value>
            <value>
                <fullName>Trout</fullName>
            </value>
            <value>
                <fullName>Turkey</fullName>
            </value>
            <value>
                <fullName>Veal</fullName>
            </value>
            <value>
                <fullName>Value Added</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The site this line item applies to.</description>
    <inlineHelpText>The site this line item applies to.</inlineHelpText>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/ia_crm__Sync_with_Intacct__c.field-meta.xml
<CustomField>
    <fullName>ia_crm__Sync_with_Intacct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync With Intacct</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/SendBulkRenewalInvoiceController.cls
public with sharing class SendBulkRenewalInvoiceController {
    @AuraEnabled
    public static string getContacts(String recordId){
        try {
            Bulk_Renewal__c bulkRenewal = [
                SELECT Id,Head_Office__c FROM Bulk_Renewal__c WHERE Id=:recordId
            ];
            List<Contact> contacts = [
                SELECT Id,Name,Email From Contact WHERE AccountId=:bulkRenewal.Head_Office__c AND Roles__c includes ('Invoice Contact')
            ];
            return JSON.serialize(contacts);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static string createInvoice(String recordId){
        try {
            Id orderEntryRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('OrderEntry').getRecordTypeId();

            Bulk_Renewal__c bulkRenewal = [
                SELECT Id,Head_Office__c,Head_Office__r.Name,CreatedDate,Create_Sage_Invoice__c,Sage_Invoice__c,Application_Contact__c
                FROM Bulk_Renewal__c WHERE Id=:recordId
            ];
            bulkRenewal.Create_Sage_Invoice__c = true;
            List<Application_Line_Item__c> renewalAppLineItems = [
                SELECT Id, Product__c, Product__r.Name, Application__c, Application__r.Pricebook_Id__c, 
                Application__r.Site__c, Application__r.Bulk_Renewal__c, Application_Unit__c, Item_Description__c,
                    List_Price__c, List_Price_Inc_Vat__c, Quantity__c, Subtotal__c, Number_of_Animals__c 
                    FROM   Application_Line_Item__c WHERE Application__r.Bulk_Renewal__c = :recordId
            ];
            system.debug('renewalAppLineItems:::'+renewalAppLineItems);
            if(bulkRenewal.Create_Sage_Invoice__c ){
                if(bulkRenewal.Sage_Invoice__c == null && renewalAppLineItems != null && renewalAppLineItems.size()>0){
                    String pricebookId = renewalAppLineItems[0].Application__r.Pricebook_Id__c;
                    String bulkRenewalCreatedDate = bulkRenewal.CreatedDate.format('dd/MM/yyyy');
                    Opportunity invoiceOpp = new Opportunity();
                    invoiceOpp.Name = bulkRenewal.Head_Office__r.Name + ' Bulk Renewal ' + bulkRenewalCreatedDate;
                    invoiceOpp.CloseDate = Date.today();
                    invoiceOpp.AccountId = bulkRenewal.Head_Office__c;
                    invoiceOpp.StageName = 'Prospecting';
                    invoiceOpp.Pricebook2Id = pricebookId;
                    invoiceOpp.Bulk_Renewal__c = bulkRenewal.Id;
                    invoiceOpp.ia_crm__Intacct_Transaction__c = 'Sales Invoice';
                    invoiceOpp.RecordTypeId = orderEntryRecordTypeId;
                    if(bulkRenewal.Application_Contact__c != null){
                        invoiceOpp.ia_crm__Bill_to__c = bulkRenewal.Application_Contact__c;
                    }

                    insert invoiceOpp;

                    List<OpportunityLineItem> oppProdToInsert = new List<OpportunityLineItem>();
                    for(Application_Line_Item__c item : renewalAppLineItems){
                        OpportunityLineItem oppItem = new OpportunityLineItem(
                            OpportunityId = invoiceOpp.Id,
                            Site__c = item.Application__r.Site__c,
                            Product2Id = item.Product__c,
                            Quantity = item.Quantity__c,
                            UnitPrice = item.List_Price__c
                        );
                        oppProdToInsert.add(oppItem);
                    }
                    if(oppProdToInsert.size() > 0){
                        insert oppProdToInsert;
                        invoiceOpp.StageName = 'Closed Won';
                        invoiceOpp.ia_crm__Sync_With_Intacct__c = true;
                        update invoiceOpp;
                    }
                    bulkRenewal.Sage_Invoice__c = invoiceOpp.id;
                    TriggerHandler.bypass('BulkRenewalTriggerHandler');
                    update bulkRenewal;
                    TriggerHandler.clearBypass('BulkRenewalTriggerHandler');
                }
                
            }
            return JSON.serialize(bulkRenewal);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static string sendMultipleInvoices(List<String> contactId,String message,String recordId){
        Id orderEntryRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('OrderEntry').getRecordTypeId();

        Bulk_Renewal__c bulkRenewal = [
            SELECT Id,Head_Office__c,Head_Office__r.Name,CreatedDate,Create_Sage_Invoice__c,Sage_Invoice__c,Application_Contact__c
            FROM Bulk_Renewal__c WHERE Id=:recordId
        ];
        if(bulkRenewal.Sage_Invoice__c != null){
            sendBulkRenewalInvoice(recordId,contactId);
        }
        return JSON.serialize(bulkRenewal);
    }
    public static void sendBulkRenewalInvoice(String bulkRenewalId,List<String> contactIds){
        EmailTemplate emailTemplate = [SELECT ID FROM EmailTemplate WHERE Name = 'Bulk Renewal Invoice Email'];
        Bulk_Renewal__c br = [SELECT Id,Payment_Reference__c,Head_Office__r.Membership_Number__c,  Application_Contact__c, Invoice_Email_Sent__c,Name,Custom_Invoice_Message__c FROM Bulk_Renewal__c WHERE Id =:bulkRenewalId];
        PageReference reportPage = new PageReference('/apex/BulkRenewalInvoicePDF');
        reportPage.getParameters().put('id', br.Id);
        Blob reportPdf;
        if(!Test.isRunningTest()){
          reportPdf = reportPage.getContentAsPDF();
        }else{
            reportPdf = Blob.valueOf('Test');
        }
        ContentVersion cv = new ContentVersion();
        cv.VersionData = reportPdf;
        cv.Title = br.Name;
        cv.PathOnClient = br.Name+'.pdf';
        cv.Description = br.Name;
        cv.isMajorVersion = true;
        insert cv;
        
        Messaging.SingleEmailMessage[] messages = new List<Messaging.SingleEmailMessage>();
        for(String contactId:contactIds){
            Messaging.SingleEmailMessage message = Messaging.renderStoredEmailTemplate(emailTemplate.Id, contactId, br.Id);
            message.setSenderDisplayName('RSPCA Assured'); 
            message.setReplyTo('accounts@rspcaassured.org.uk');
            message.setUseSignature(false); 
            message.setBccSender(false); 
            message.setSaveAsActivity(true);
            message.setSubject('Invoice for your Bulk Renewal: '+br.Payment_Reference__c);//+br.Head_Office__r.Membership_Number__c
            message.setEntityAttachments(new list<Id> {cv.Id});
            messages.add(message);
        }
        Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
        if (results[0].success){
            System.debug('The email was sent successfully.');
            br.Invoice_Email_Sent__c = true;
            update br;
        }else {
            System.debug('The email failed to send: '+results[0].errors[0].message);
        }
    }
}