unpackaged/main/default/objects/Account/fields/ia_crm__Sync_With_Intacct__c.field-meta.xml
<CustomField>
    <fullName>ia_crm__Sync_With_Intacct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync With Intacct</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Membership_Number__c.field-meta.xml
<CustomField>
    <fullName>Membership_Number__c</fullName>
    <formula>Parent.Head_Office_Number__c  &amp; &quot;.&quot;  &amp;  Site_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sage_Intacct_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Sage_Intacct_Customer_Number__c</fullName>
    <displayFormat>AC{000000}</displayFormat>
    <label>Sage Intacct Customer Number</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Applicant_Contact__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Application_Type__c</fullName>
    <label>Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Existing_Member__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Revisit</fullName>
            </value>
            <value>
                <fullName>Levy</fullName>
            </value>
            <value>
                <fullName>Merchandise</fullName>
            </value>
            <value>
                <fullName>Promotion/Partnership</fullName>
            </value>
            <value>
                <fullName>Consultancy</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Head_Office__c.field-meta.xml
<CustomField>
    <fullName>Head_Office__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Head Office</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Head Office</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Membership_Number__c.field-meta.xml
<CustomField>
    <fullName>Membership_Number__c</fullName>
    <formula>Site__r.Membership_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field must be populated in order to mark an Additional Visit as complete.</inlineHelpText>
    <label>Membership Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Pricebook_Id__c.field-meta.xml
<CustomField>
    <fullName>Pricebook_Id__c</fullName>
    <label>Pricebook Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Sage_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sage_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sage Invoice</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>ApplicationSite</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Site_Name__c.field-meta.xml
<CustomField>
    <fullName>Site_Name__c</fullName>
    <formula>Site__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <formula>IF( Head_Office__r.BillingCountry = &#39;United Kingdom&#39;,
				Amount_Ex_VAT__c * 0.2,
			0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>If Head Office billing country is the United Kingdom, then the VAT is 20%. Otherwise, VAT is 0%.</inlineHelpText>
    <label>VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Amount_Inc_VAT__c.field-meta.xml
<CustomField>
    <fullName>Amount_Inc_VAT__c</fullName>
    <formula>Amount +  VAT__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Inc. VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Invoices &amp; Credit Notes</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Credit_Note_Details__c.field-meta.xml
<CustomField>
    <fullName>Credit_Note_Details__c</fullName>
    <label>Credit Note Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Credit_Note_Number__c.field-meta.xml
<CustomField>
    <fullName>Credit_Note_Number__c</fullName>
    <label>Credit Note Number</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Credit_Reason__c.field-meta.xml
<CustomField>
    <fullName>Credit_Reason__c</fullName>
    <label>Credit Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Invoice Error</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/ia_crm__Intacct_Transaction__c.field-meta.xml
<CustomField>
    <fullName>ia_crm__Intacct_Transaction__c</fullName>
    <label>Intacct Transaction</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales Invoice</fullName>
            </value>
            <value>
                <fullName>Sales Order</fullName>
            </value>
            <value>
                <fullName>Sales Quote</fullName>
            </value>
            <value>
                <fullName>Sales Credit Note</fullName>
            </value>
            <value>
                <fullName>Shipper</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/ia_crm__Sync_With_Intacct__c.field-meta.xml
<CustomField>
    <fullName>ia_crm__Sync_With_Intacct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync With Intacct</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <label>Invoice Number</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Purchase_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order_Number__c</fullName>
    <label>Purchase Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Tax_Point_Date__c.field-meta.xml
<CustomField>
    <fullName>Tax_Point_Date__c</fullName>
    <label>Tax Point Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <formula>IF(Application__r.VAT__c &gt; 0,
			 Amount * 0.2,
			0
	)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The site this line item applies to.</description>
    <inlineHelpText>The site this line item applies to.</inlineHelpText>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Total_Price_Inc_VAT__c.field-meta.xml
<CustomField>
    <fullName>Total_Price_Inc_VAT__c</fullName>
    <formula>TotalPrice +  VAT__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price Inc VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <formula>IF( Opportunity.Application__r.VAT__c   &gt; 0 , 
			  TotalPrice  * 0.2,
			 0
			)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/ia_crm__Sync_with_Intacct__c.field-meta.xml
<CustomField>
    <fullName>ia_crm__Sync_with_Intacct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync With Intacct</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/CreateCreditNoteController.cls
public class CreateCreditNoteController {

    @AuraEnabled
    public static Application__c getApplication(String recordId){
        Application__c application = [SELECT Id, Site__c, Site_Name__c, Head_Office__c, Applicant_Contact__c,  Application_Type__c, Sage_Invoice__c, Pricebook_Id__c FROM Application__c WHERE Id =:recordId];

        return application;
    }

    // replace AccountNumber with Sage_Intacct_Customer_Number__c
    @AuraEnabled
    public static Opportunity getInvoice(String recordId){
        Opportunity opp = [SELECT Id, Name, Amount, Amount_Inc_VAT__c, VAT__c, Invoice_Number__c, Account.Sage_Intacct_Customer_Number__c, Application__r.Membership_Number__c, Account.BillingCountry FROM Opportunity WHERE Id =:recordId];
        return opp;
    }

    @AuraEnabled
    public static List<OpportunityLineItem> getInvoiceLineItems(String recordId){
        List<OpportunityLineItem> oppLines = [SELECT Id,Opportunity.Application__r.Name, OpportunityId, Product2.Name, Quantity, UnitPrice, TotalPrice, Total_Price_Inc_VAT__c FROM OpportunityLineItem WHERE OpportunityId = :recordId];
        return oppLines;
    }

    @AuraEnabled
    public static List<CreditNoteLineWrapper> getCreditLines(List<String> oppLineIds){
        List<OpportunityLineItem> oppLines = [SELECT Id, OpportunityId, Product2Id, Product2.Name, Quantity, UnitPrice, TotalPrice, Total_Price_Inc_VAT__c FROM OpportunityLineItem WHERE Id IN:oppLineIds];
        
        List<CreditNoteLineWrapper> creditNoteLines = new List<CreditNoteLineWrapper>();
        for(OpportunityLineItem lineItem : oppLines){
            CreditNoteLineWrapper cnl = new CreditNoteLineWrapper();
            cnl.productName = lineItem.Product2.Name;
            cnl.oppLineId = lineItem.Id;
            cnl.listPrice = lineItem.UnitPrice;
            cnl.maxListPrice = lineItem.UnitPrice;
            cnl.quantity = lineItem.Quantity;
            cnl.maxQuantity = lineItem.Quantity;
            cnl.productId = lineItem.Product2Id;
            creditNoteLines.add(cnl);
        }

        return creditNoteLines;
    }

    @AuraEnabled
    public static Opportunity createCreditNote(Application__c application, List<CreditNoteLineWrapper> creditNoteLinesWrapper, String creditNoteReason, String purchaseOrder, String creditNoteDetails){
        if(application != null && creditNoteLinesWrapper != null && creditNoteReason != null){
            // get Order Entry Record Type for opportunity
            Id orderEntryRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('OrderEntry').getRecordTypeId();
            
            String creditNoteDate = Datetime.now().format('dd/MM/yyyy');
            Opportunity creditNoteOpp = new Opportunity();
            creditNoteOpp.Name = application.Site_Name__c + ' ' + application.Application_Type__c + ' ' + creditNoteDate + ' Credit Note';
            creditNoteOpp.CloseDate = Date.today();
            creditNoteOpp.AccountId = application.Head_Office__c;
            creditNoteOpp.StageName = 'Prospecting';
            creditNoteOpp.Pricebook2Id = application.Pricebook_Id__c;
            creditNoteOpp.Application__c = application.Id;
            creditNoteOpp.ia_crm__Intacct_Transaction__c = 'Sales Credit Note';
            creditNoteOpp.RecordTypeId = orderEntryRecordTypeId;
            creditNoteOpp.Credit_Reason__c = creditNoteReason;
            creditNoteOpp.Tax_Point_Date__c = Date.today();
            creditNoteOpp.Purchase_Order_Number__c = purchaseOrder;
            creditNoteOpp.Credit_Note_Details__c = creditNoteDetails;
            if(application.Applicant_Contact__c != null){
                creditNoteOpp.ia_crm__Bill_to__c = application.Applicant_Contact__c;
            }

            insert creditNoteOpp;

            
            List<OpportunityLineItem> oppProdToInsert = new List<OpportunityLineItem>();
            for(CreditNoteLineWrapper cnlw : creditNoteLinesWrapper){
                OpportunityLineItem oppItem = new OpportunityLineItem(
                    OpportunityId = creditNoteOpp.Id,
                    Site__c = application.Site__c,
                    Product2Id = cnlw.productId,
                    Quantity = cnlw.quantity,
                    UnitPrice = cnlw.listPrice
                );
                oppProdToInsert.add(oppItem);
            }
            if(oppProdToInsert.size() > 0){
                insert oppProdToInsert;
                creditNoteOpp.StageName = 'Closed Won';
                creditNoteOpp.ia_crm__Sync_With_Intacct__c = true;
                update creditNoteOpp;
            }
            
            Opportunity creditNoteCreated = [SELECT Id, Name, Credit_Note_Number__c, Credit_Reason__c, Amount, VAT__c, Amount_Inc_VAT__c FROM Opportunity WHERE Id =:creditNoteOpp.Id];
            return creditNoteCreated;
        }else{
            return null;
        }
    }

    public class CreditNoteLineWrapper{
        @AuraEnabled public String oppLineId {get;set;}
        @AuraEnabled public String productName {get;set;}
        @AuraEnabled public Decimal listPrice {get;set;}
        @AuraEnabled public Decimal maxListPrice {get;set;}
        @AuraEnabled public Decimal quantity {get;set;}
        @AuraEnabled public Decimal maxQuantity {get;set;}
        @AuraEnabled public String productId {get;set;}
    }
}