unpackaged/main/default/objects/Account/fields/Membership_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Membership_Expiry_Date__c</fullName>
    <inlineHelpText>Membership Expiry Date is 1 year after the Certificate Issue Date by Default. However if common renewal date is used, then Membership Expiry Date reflects when the sites will need to renew by from a group level.</inlineHelpText>
    <label>Membership Expiry Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Assessment_Checklist__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Checklist__c</fullName>
    <label>Assessment Checklist</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Assessment_Report__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Report__c</fullName>
    <inlineHelpText>White copy</inlineHelpText>
    <label>Assessment Report</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Bulk_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Renewal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bulk Renewal</label>
    <referenceTo>Bulk_Renewal__c</referenceTo>
    <relationshipLabel>Renewal Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Existing_Member__c.field-meta.xml
<CustomField>
    <fullName>Existing_Member__c</fullName>
    <label>Existing Member?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Extension_Deadline__c.field-meta.xml
<CustomField>
    <fullName>Extension_Deadline__c</fullName>
    <label>Extension Deadline</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Extension_Granted__c.field-meta.xml
<CustomField>
    <fullName>Extension_Granted__c</fullName>
    <label>Extension Granted?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Extension_Granted_On__c.field-meta.xml
<CustomField>
    <fullName>Extension_Granted_On__c</fullName>
    <description>The date that the extension was granted on.</description>
    <inlineHelpText>The date that the extension was granted on.</inlineHelpText>
    <label>Extension Granted On</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Extension_Period__c.field-meta.xml
<CustomField>
    <fullName>Extension_Period__c</fullName>
    <description>Auto-populates Extension Deadline field with date, based on number of weeks from the original deadline date</description>
    <label>Extension Period</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Extension_Granted__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 Week</fullName>
            </value>
            <value>
                <fullName>2 Weeks</fullName>
            </value>
            <value>
                <fullName>3 Weeks</fullName>
            </value>
            <value>
                <fullName>4 Weeks</fullName>
            </value>
            <value>
                <fullName>5 Weeks</fullName>
            </value>
            <value>
                <fullName>6 Weeks</fullName>
            </value>
            <value>
                <fullName>2 Months</fullName>
            </value>
            <value>
                <fullName>3 Months</fullName>
            </value>
            <value>
                <fullName>4 Months</fullName>
            </value>
            <value>
                <fullName>5 Months</fullName>
            </value>
            <value>
                <fullName>6 Months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Membership_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Membership_Expiry_Date__c</fullName>
    <formula>Site__r.Membership_Expiry_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership Expiry Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Paid__c.field-meta.xml
<CustomField>
    <fullName>Paid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Paid</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Reason_for_extension__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_extension__c</fullName>
    <description>Reason for the deadline being extended.</description>
    <inlineHelpText>Reason for the deadline being extended.</inlineHelpText>
    <label>Reason for extension</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Send_Application_Confirmation_Email__c.field-meta.xml
<CustomField>
    <fullName>Send_Application_Confirmation_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Application Confirmation Email</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>Stage field for new applications for new site, update, or transfers. This field is used for the application record type.</description>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Application</fullName>
                <default>true</default>
                <label>Application</label>
            </value>
            <value>
                <fullName>Allocation</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Schedule</fullName>
            </value>
            <value>
                <fullName>Visit</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <description>For renewal applications</description>
    <label>Renewal</label>
</RecordType>

unpackaged/main/default/objects/Assessment_Report__c/Assessment_Report__c.object-meta.xml
<CustomObject>
    <label>Assessment Report</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Assessment Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Assessment_Report__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Assessment Reports</relationshipLabel>
    <relationshipName>Assessment_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Bulk_Renewal__c/Bulk_Renewal__c.object-meta.xml
<CustomObject>
    <description>Object to record the renewal applications created from bulk renewing.</description>
    <label>Bulk Renewal</label>
    <nameField>
        <displayFormat>BR{000000}</displayFormat>
        <label>Bulk Renewal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bulk Renewals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Product2/fields/Standard_Price__c.field-meta.xml
<CustomField>
    <fullName>Standard_Price__c</fullName>
    <label>Standard Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/ApplicationTriggerHandlerTest.cls
@isTest
public class ApplicationTriggerHandlerTest {

    @isTest
    static Application__c createApplication(){
        // Create joinFee product
        FObject joinFee = new FObject('Product2', 1);
        joinFee.setDefinition('Name','static value(Joining Fee)');
        joinFee.setDefinition('ProductCode','static value(JOINFEE)');
        joinFee.setDefinition('IsActive','static value(true)');
        joinFee.setDefinition('Standard_Price__c','static value(28.80)');
        joinFee.insertRecords(true);
        
        // Create revisitFee product
        FObject revisitFee = new FObject('Product2', 1);
        revisitFee.setDefinition('Name','static value(Revisit)');
        revisitFee.setDefinition('ProductCode','static value(REVISIT)');
        revisitFee.setDefinition('IsActive','static value(true)');
        revisitFee.setDefinition('Standard_Price__c','static value(114.24)');
        revisitFee.insertRecords(true);

        // Create Application
        FObject application = DataFactory.getDefNewApplications();
        application.setDefinition('Existing_Member__c', 'static value(No)');
        application.insertRecords(true);

        // do assertions
        List<Account> insertedAccounts = FObject.getInsertedRecords('Account');
        List<Contact> insertedCon = FObject.getInsertedRecords('Contact');
        List<Application__c> insertedApp = FObject.getInsertedRecords('Application__c');
        System.debug('Acc Size => ' + insertedAccounts.size());
        System.debug('Con Size => ' + insertedCon.size());
        System.debug('App Size => ' + insertedApp.size());
        System.assert(insertedAccounts.size() == 2);
        System.assert(insertedCon.size() == 1);
        System.assert(insertedApp.size() == 1);
        return insertedApp[0];
    }

    @isTest
    static void createRenewalApplication(){
        // Create lateRenewalFee product
        FObject lateRenewalFee = new FObject('Product2', 1);
        lateRenewalFee.setDefinition('Name','static value(Late Renewal Fee)');
        lateRenewalFee.setDefinition('ProductCode','static value(LATEFEE)');
        lateRenewalFee.setDefinition('IsActive','static value(true)');
        lateRenewalFee.setDefinition('Standard_Price__c','static value(30)');
        lateRenewalFee.insertRecords(true);

        // Create renewal Application
        FObject application = DataFactory.getDefRenewalApplications();
        //application.setDefinition('Existing_Member__c', 'static value(No)');
        application.insertRecords(true);

        // do assertions
        List<Account> insertedAccounts = FObject.getInsertedRecords('Account');
        List<Contact> insertedCon = FObject.getInsertedRecords('Contact');
        List<Application__c> insertedApp = FObject.getInsertedRecords('Application__c');
        System.debug('Acc Size => ' + insertedAccounts.size());
        System.debug('Con Size => ' + insertedCon.size());
        System.debug('App Size => ' + insertedApp.size());
        System.assert(insertedAccounts.size() == 2);
        System.assert(insertedCon.size() == 1);
        System.assert(insertedApp.size() == 1);

        for(Account a : insertedAccounts){
            a.Membership_Expiry_Date__c = Date.today();
        }
        update insertedAccounts;

        Application__c clonedRenewal = insertedApp[0].clone(false,false,false,false);
        clonedRenewal.Id = null;
        insert clonedRenewal;


    }

    @isTest
    static void sendApplicationConfirmationEmail(){
        Application__c app = createApplication();
        app.Send_Application_Confirmation_Email__c = true;
        update app;
    }

    @isTest
    static void applicationWithBulkRenewal(){
        // create bulk renewal object
        FObject bulkRenewal = new FObject('Bulk_Renewal__c', 1);

        // Create Application
        FObject renewalApplication = DataFactory.getDefRenewalApplications();
        renewalApplication.setDefinition('Existing_Member__c', 'static value(Yes)');
        renewalApplication.setDefinition('Bulk_Renewal__c', 'random lookup(Bulk_Renewal__c) source(forceea)');
        renewalApplication.insertRecords(true);

    }
    /*
    @isTest(SeeAllData = true)
    static void sendExtensionGrantedEmail(){
        Application__c app = createApplication();
        app.Extension_Granted__c = 'Yes';
        app.Extension_Period__c = '3 Weeks';
        app.Extension_Granted_On__c = Date.today();
        app.Extension_Deadline__c = Date.today();
        app.Reason_for_extension__c = 'test reason';
        update app;
    }*/
    /*
    @isTest(SeeAllData = true)
    static void sendAssessmentCompleteEmail(){
        Application__c app = createApplication();
        app.Stage__c = 'Assessment';
        app.Paid__c = true;
        app.Assessment_Checklist__c = 'Test link';
        app.Assessment_Report__c = 'Test link';
        update app;

        app.Stage__c = 'Compliance';
        update app;
    }
    */
}