unpackaged/main/default/objects/Account/fields/Membership_Number__c.field-meta.xml
<CustomField>
    <fullName>Membership_Number__c</fullName>
    <formula>Parent.Head_Office_Number__c  &amp; &quot;.&quot;  &amp;  Site_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Primary Account(DoNotUse)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Applicant_Contact__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Assessment_Date__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Date__c</fullName>
    <description>Cannot exceed the deadline date; can be updated if rearranged</description>
    <inlineHelpText>The date the site will be assessed</inlineHelpText>
    <label>Assessment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Evidence__c.field-meta.xml
<CustomField>
    <fullName>Evidence__c</fullName>
    <inlineHelpText>Link to evidence folder</inlineHelpText>
    <label>Evidence</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Evidence_Deadline__c.field-meta.xml
<CustomField>
    <fullName>Evidence_Deadline__c</fullName>
    <description>The date by which evidence needs to be submitted.</description>
    <inlineHelpText>The date by which evidence needs to be submitted.</inlineHelpText>
    <label>Evidence Deadline</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Evidence_Reminder_Date__c.field-meta.xml
<CustomField>
    <fullName>Evidence_Reminder_Date__c</fullName>
    <formula>Evidence_Deadline__c - 7</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Evidence Reminder Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Extension_Deadline__c.field-meta.xml
<CustomField>
    <fullName>Extension_Deadline__c</fullName>
    <label>Extension Deadline</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Final_Evidence_Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Final_Evidence_Email_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Stop 21 Day Evidence Reminder</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Head_Office__c.field-meta.xml
<CustomField>
    <fullName>Head_Office__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Head Office</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Head Office</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Membership_Number__c.field-meta.xml
<CustomField>
    <fullName>Membership_Number__c</fullName>
    <formula>Site__r.Membership_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field must be populated in order to mark an Additional Visit as complete.</inlineHelpText>
    <label>Membership Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/recordTypes/Additional_Visit.recordType-meta.xml
<RecordType>
    <fullName>Additional_Visit</fullName>
    <active>true</active>
    <description>Used to record the additional visit process for a site under sanction</description>
    <label>Additional Visit</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <formula>IF(Id = Account.Primary_Contact__r.Id , true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates that this contact is the primary contact for the account that it is affiliated with.</inlineHelpText>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/SendFinalEvidenceReminderEmailBatch.cls
public class SendFinalEvidenceReminderEmailBatch implements Database.Batchable<sObject>, Schedulable {

    public Database.QueryLocator start(Database.BatchableContext bc){
        Date before21Days = system.today().addDays(-21);
        /*List<Application__c> evdAppList = [
            SELECT Id, Name FROM Application__c 
            WHERE  Applicant_Contact__r.Email != null AND Evidence_Deadline__c != null 
            AND Extension_Deadline__c = null AND Final_Evidence_Email_Sent__c = false 
            AND Evidence_Reminder_Date__c =:Date.today()
        ];
        Set<Id> appIdSet = new Set<Id>();
        for(Application__c app : evdAppList){
            appIdSet.add(app.Id);
        }*/
        String query = 'SELECT Id,RecordType.DeveloperName, Membership_Number__c,Head_Office__c, Head_Office__r.Primary_Contact__c,Head_Office__r.Primary_Contact__r.Email, Final_Evidence_Email_Sent__c,Assessment_Date__c FROM Application__c WHERE Head_Office__r.Primary_Contact__r.Email != null AND Assessment_Date__c = :before21Days AND Final_Evidence_Email_Sent__c = false AND Evidence__c = NULL';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<Application__c> appList){
        OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = 'help@rspcaassured.org.uk'];
        EmailTemplate emailTemplate = [SELECT ID FROM EmailTemplate WHERE Name = 'Evidence Reminder'];
        EmailTemplate additionalVisitEmailTemplate = [SELECT ID FROM EmailTemplate WHERE Name = 'Evidence Reminder for Additional Visits'];
        List<Application__c> appUpdateList = new List<Application__c>();
        for(Application__c app : appList){
            Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
            message.setTargetObjectId(app.Head_Office__r.Primary_Contact__c); 
            //message.setSenderDisplayName('RSPCA Assured'); 
            message.setReplyTo('help@rspcaassured.org.uk');
            message.setOrgWideEmailAddressId(owea.get(0).Id);
            message.setUseSignature(false); 
            message.setBccSender(false); 
            message.setSaveAsActivity(true);
            if(app.RecordType.DeveloperName == 'Additional_Visit'){
            	message.setTemplateID(additionalVisitEmailTemplate.Id); 
            }else{
            	message.setTemplateID(emailTemplate.Id); 
            }
            message.setWhatId(app.Id);
            message.toAddresses = new String[] {app.Head_Office__r.Primary_Contact__r.Email};//
                Messaging.SingleEmailMessage[] messages = new List<Messaging.SingleEmailMessage> {message};
                    Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
            if (results[0].success){
                System.debug('The email was sent successfully.');
                app.Final_Evidence_Email_Sent__c = true;
                appUpdateList.add(app);
            }else {
                System.debug('The email failed to send: '+results[0].errors[0].message);
            }
        }
        try{
            update appUpdateList;
        }catch(DMLException e){
            System.debug('Error updating Final Evidence Email Sent on Application '+e.getMessage());
        }
    }

    public void finish(Database.BatchableContext bc){}
    
    public void execute(SchedulableContext sc){
        SendFinalEvidenceReminderEmailBatch obj = new SendFinalEvidenceReminderEmailBatch();
        Database.executeBatch(obj);
    }
}