unpackaged/main/default/objects/Account/fields/Membership_Number__c.field-meta.xml
<CustomField>
    <fullName>Membership_Number__c</fullName>
    <formula>Parent.Head_Office_Number__c  &amp; &quot;.&quot;  &amp;  Site_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sage_Intacct_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Sage_Intacct_Customer_Number__c</fullName>
    <displayFormat>AC{000000}</displayFormat>
    <label>Sage Intacct Customer Number</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Membership_Number__c.field-meta.xml
<CustomField>
    <fullName>Membership_Number__c</fullName>
    <formula>Site__r.Membership_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This field must be populated in order to mark an Additional Visit as complete.</inlineHelpText>
    <label>Membership Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Sage_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sage_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sage Invoice</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <formula>IF( Head_Office__r.BillingCountry = &#39;United Kingdom&#39;,
				Amount_Ex_VAT__c * 0.2,
			0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>If Head Office billing country is the United Kingdom, then the VAT is 20%. Otherwise, VAT is 0%.</inlineHelpText>
    <label>VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Amount_Inc_VAT__c.field-meta.xml
<CustomField>
    <fullName>Amount_Inc_VAT__c</fullName>
    <formula>Amount +  VAT__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Inc. VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Invoices &amp; Credit Notes</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Credit_Note_Approver__c.field-meta.xml
<CustomField>
    <fullName>Credit_Note_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Credit Note Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Credit_Note_Number__c.field-meta.xml
<CustomField>
    <fullName>Credit_Note_Number__c</fullName>
    <label>Credit Note Number</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/ia_crm__Intacct_Transaction__c.field-meta.xml
<CustomField>
    <fullName>ia_crm__Intacct_Transaction__c</fullName>
    <label>Intacct Transaction</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales Invoice</fullName>
            </value>
            <value>
                <fullName>Sales Order</fullName>
            </value>
            <value>
                <fullName>Sales Quote</fullName>
            </value>
            <value>
                <fullName>Sales Credit Note</fullName>
            </value>
            <value>
                <fullName>Shipper</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <label>Invoice Number</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Purchase_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order_Number__c</fullName>
    <label>Purchase Order Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/VAT__c.field-meta.xml
<CustomField>
    <fullName>VAT__c</fullName>
    <formula>IF(Application__r.VAT__c &gt; 0,
			 Amount * 0.2,
			0
	)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/DownloadCreditNoteController.cls
public with sharing class DownloadCreditNoteController {
  public Opportunity currentRecord { get; set; }
  public Boolean allowedToDownload { get; set; }
  public String downloadCreditNotePdfUrl { get; set; }
  public String todaysDate { get; set; }
  public DownloadCreditNoteController() {
    currentRecord = [
      SELECT Id, Name, ia_crm__Intacct_Transaction__c, Credit_Note_Number__c,Credit_Note_Approver__r.Name,
      Application__r.Membership_Number__c,Purchase_Order_Number__c,Amount,Vat__c,Amount_Inc_VAT__c,
      Account.Name,Account.BillingStreet,Account.BillingState,Account.BillingCity,Account.BillingCountry,
      Account.BillingPostalCode,Application__r.Sage_Invoice__r.Invoice_Number__c,Account.Sage_Intacct_Customer_Number__c
      FROM Opportunity
      WHERE Id = :ApexPages.currentPage().getParameters().get('id')
    ];
    todaysDate = String.valueOf(system.today());
  }
  public DownloadCreditNoteController(ApexPages.StandardController controller) {
    currentRecord = [
      SELECT Id, Name, ia_crm__Intacct_Transaction__c, Credit_Note_Number__c
      FROM Opportunity
      WHERE Id = :controller.getRecord().Id
    ];
    if (currentRecord.ia_crm__Intacct_Transaction__c == 'Sales Credit Note') {
      allowedToDownload = true;
      downloadCreditNotePdfUrl =
        System.URL.getSalesforceBaseUrl().toExternalForm() +
        '/apex/DownloadCreditNotePdf' +
        '?id=' +
        currentRecord.Id;
    } else {
      allowedToDownload = false;
    }
  }
}