unpackaged/main/default/objects/Account/fields/Membership_Number__c.field-meta.xml
<CustomField>
    <fullName>Membership_Number__c</fullName>
    <formula>Parent.Head_Office_Number__c  &amp; &quot;.&quot;  &amp;  Site_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Membership_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <description>An Account representing a site.</description>
    <label>Site</label>
</RecordType>

unpackaged/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Unit__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Animals__c.field-meta.xml
<CustomField>
    <fullName>Animals__c</fullName>
    <label>Animals</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Animals</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Production__c.field-meta.xml
<CustomField>
    <fullName>Production__c</fullName>
    <label>Production</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Production</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Rearing_System__c.field-meta.xml
<CustomField>
    <fullName>Rearing_System__c</fullName>
    <label>Rearing System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rearing_System</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applying</fullName>
                <default>true</default>
                <label>Applying</label>
            </value>
            <value>
                <fullName>Certified</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Animals.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Beef Cattle</fullName>
    </customValue>
    <customValue>
        <fullName>Chickens</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy Cattle</fullName>
    </customValue>
    <customValue>
        <fullName>Ducklings</fullName>
    </customValue>
    <customValue>
        <fullName>Ducks</fullName>
    </customValue>
    <customValue>
        <fullName>Laying Hen Chicks</fullName>
    </customValue>
    <customValue>
        <fullName>Laying Hens</fullName>
    </customValue>
    <customValue>
        <fullName>Lumpfish</fullName>
    </customValue>
    <customValue>
        <fullName>Meat Chicken Chicks</fullName>
    </customValue>
    <customValue>
        <fullName>Pigs</fullName>
    </customValue>
    <customValue>
        <fullName>Pullets</fullName>
    </customValue>
    <customValue>
        <fullName>Salmon</fullName>
    </customValue>
    <customValue>
        <fullName>Sheep</fullName>
    </customValue>
    <customValue>
        <fullName>Trout</fullName>
    </customValue>
    <customValue>
        <fullName>Turkey Poults</fullName>
    </customValue>
    <customValue>
        <fullName>Turkeys</fullName>
    </customValue>
    <customValue>
        <fullName>Veal Calves</fullName>
    </customValue>
    <customValue>
        <fullName>Wrasse</fullName>
    </customValue>
    <customValue>
        <fullName>List</fullName>
    </customValue>
    <masterLabel>Animals</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Business.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abattoir</fullName>
    </customValue>
    <customValue>
        <fullName>Catching</fullName>
    </customValue>
    <customValue>
        <fullName>Cleaner Fish</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery</fullName>
    </customValue>
    <customValue>
        <fullName>Haulier</fullName>
    </customValue>
    <customValue>
        <fullName>Producer</fullName>
    </customValue>
    <customValue>
        <fullName>Supply Chain</fullName>
    </customValue>
    <masterLabel>Business</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Membership_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ADDITION</fullName>
    </customValue>
    <customValue>
        <fullName>ARCHIVED</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC5R</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC7R</fullName>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
    </customValue>
    <customValue>
        <fullName>CONPASS</fullName>
    </customValue>
    <customValue>
        <fullName>ENQUIRY</fullName>
        <default>true</default>
        <label>ENQUIRY</label>
    </customValue>
    <customValue>
        <fullName>EVIDENCE</fullName>
    </customValue>
    <customValue>
        <fullName>FAILED</fullName>
    </customValue>
    <customValue>
        <fullName>FALLOW</fullName>
    </customValue>
    <customValue>
        <fullName>LAPSED</fullName>
    </customValue>
    <customValue>
        <fullName>MEMBER</fullName>
    </customValue>
    <customValue>
        <fullName>MONREQ</fullName>
    </customValue>
    <customValue>
        <fullName>NEW</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2R</fullName>
    </customValue>
    <customValue>
        <fullName>NEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>NONFR</fullName>
    </customValue>
    <customValue>
        <fullName>NOTINSCHEME</fullName>
    </customValue>
    <customValue>
        <fullName>PASSED</fullName>
    </customValue>
    <customValue>
        <fullName>PREPANEL</fullName>
    </customValue>
    <customValue>
        <fullName>REINSTATE</fullName>
    </customValue>
    <customValue>
        <fullName>RENEW/REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWA</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWALINP</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWR</fullName>
    </customValue>
    <customValue>
        <fullName>REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>SUSPENDED</fullName>
    </customValue>
    <masterLabel>Membership Status</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Production.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abattoir</fullName>
    </customValue>
    <customValue>
        <fullName>Brand/Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Breeding</fullName>
    </customValue>
    <customValue>
        <fullName>Brood</fullName>
    </customValue>
    <customValue>
        <fullName>Calves</fullName>
    </customValue>
    <customValue>
        <fullName>Catching Team</fullName>
    </customValue>
    <customValue>
        <fullName>Cleaner Fish</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Dry Cows</fullName>
    </customValue>
    <customValue>
        <fullName>Finishing</fullName>
    </customValue>
    <customValue>
        <fullName>Flat deck (one-storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Flat deck (two storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Flat deck with Veranda</fullName>
    </customValue>
    <customValue>
        <fullName>Freshwater</fullName>
    </customValue>
    <customValue>
        <fullName>Gilts</fullName>
    </customValue>
    <customValue>
        <fullName>Grazing</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery (On Grower)</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery (Ova)</fullName>
    </customValue>
    <customValue>
        <fullName>Haulier</fullName>
    </customValue>
    <customValue>
        <fullName>Heifers</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-tier (one-storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-tier (two-storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-tier with Veranda</fullName>
    </customValue>
    <customValue>
        <fullName>Packer</fullName>
    </customValue>
    <customValue>
        <fullName>Processor</fullName>
    </customValue>
    <customValue>
        <fullName>Processor/Packer</fullName>
    </customValue>
    <customValue>
        <fullName>Producer</fullName>
    </customValue>
    <customValue>
        <fullName>Rearing</fullName>
    </customValue>
    <customValue>
        <fullName>Retailer</fullName>
    </customValue>
    <masterLabel>Production</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Rearing_System.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Barn</fullName>
    </customValue>
    <customValue>
        <fullName>Free Range</fullName>
    </customValue>
    <customValue>
        <fullName>Indoor</fullName>
    </customValue>
    <customValue>
        <fullName>Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Outdoor Bred</fullName>
    </customValue>
    <customValue>
        <fullName>Outdoor Reared</fullName>
    </customValue>
    <customValue>
        <fullName>n/a</fullName>
    </customValue>
    <customValue>
        <fullName>Pasture</fullName>
    </customValue>
    <masterLabel>Rearing System</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/BulkDownloadSiteCertificatesController.cls
public with sharing class BulkDownloadSiteCertificatesController {
    public Account currentRecord{get;set;}
    public List<SiteCertificate> siteCertificateList{get;set;}
    public Boolean hasSiteCertificates{get;set;}
    public Boolean showSpinner{get;set;}
    public String imageURL{get;set;}
     public String pdfName{get;set;}
    public BulkDownloadSiteCertificatesController(ApexPages.StandardController controller) {
        showSpinner = true;
        currentRecord = [SELECT Id, Name, Membership_Number__c FROM Account WHERE Id = :controller.getRecord().Id];

        List<Account> sites = [SELECT Id, Name, Membership_Number__c FROM Account WHERE ParentId = :currentRecord.Id];
        Map<Id,Map<String,Unit>> supplyChainMap = new Map<Id,Map<String,Unit>>();
        for(Unit__c u : [SELECT Id, Name, Account__c, Business__c, Animals__c, Production__c, Rearing_System__c, Status__c FROM Unit__c WHERE Account__c IN :sites AND Status__c = 'Certified' AND Business__c = 'Supply Chain']){
            Unit unitIns = new Unit();
            unitIns.species = u.Animals__c;
            unitIns.accountId = u.Account__c;
            unitIns.supplyChainCertificateURL = System.URL.getSalesforceBaseUrl().toExternalForm() + '/apex/SupplyChainCertificateSpecies'+'?id='+u.Account__c+'&species=' ;
            if(supplyChainMap.containsKey(u.Account__c)){
                Map<String,Unit> unitmap = supplyChainMap.get(u.Account__c);
                unitmap.put(u.Animals__c,unitIns);
                supplyChainMap.put(u.Account__c, unitmap);
            }else{
                supplyChainMap.put(u.Account__c, new Map<String,Unit> {u.Animals__c=>unitIns});
            }
        }

        // Map list of trout units to site ids
        /*Map<Id,List<Unit__C>> troutMap = new Map<Id,List<Unit__C>>();
        Set<String> businessSetTrout = new Set<String>{
            'Hatchery',
            'Haulier',
            'Abattoir',
            'Producer'
        };
        for(Unit__c u : [SELECT Id, Name, Account__c, Business__c, Animals__c, Production__c, Rearing_System__c, Status__c FROM Unit__c WHERE Account__c IN :siteids AND Status__c = 'Certified' AND Business__c IN:businessSetTrout AND Animals__c = 'Trout']){
            if(troutMap.containsKey(u.Account__c)){
                List<Unit__c> unitList = troutMap.get(u.Account__c);
                unitlist.add(u);
                troutMap.put(u.Account__c, unitList);
            }else{
                troutMap.put(u.Account__c, new List<Unit__c> {u});
            }
        }*/

        // Map list of nsf ukas units to site ids
        Map<Id,Map<String,Unit>> nsfUKASMap = new Map<Id,Map<String,Unit>>();
        Set<String> businessSetNSFUKAS = new Set<String>{
            'Hatchery',
            'Haulier',
            'Abattoir',
            'Producer',
            'Cleaner Fish',
            'Catching'
        };
        for(Unit__c u : [SELECT Id, Name, Account__c, Business__c, Animals__c, Production__c, Rearing_System__c, Status__c FROM Unit__c WHERE Account__c IN :sites AND Status__c = 'Certified' AND Business__c IN:businessSetNSFUKAS]){
            Unit unitIns = new Unit();
            unitIns.species = u.Animals__c;
            unitIns.accountId = u.Account__c;
            unitIns.nsfUkasCertificateUrl = System.URL.getSalesforceBaseUrl().toExternalForm() + '/apex/SCICertificateSpecies'+'?id='+u.Account__c+'&species='+u.Animals__c ;

            if(nsfUKASMap.containsKey(u.Account__c)){
                Map<String,Unit> unitmap = nsfUKASMap.get(u.Account__c);
                unitmap.put(u.Animals__c,unitIns);
                nsfUKASMap.put(u.Account__c, unitmap);
            }else{
                nsfUKASMap.put(u.Account__c, new Map<String,Unit> {u.Animals__c=>unitIns});
            }
        }

        siteCertificateList = new List<SiteCertificate>();
        for(Account a : sites){
            SiteCertificate sc = new SiteCertificate();
            sc.siteRecordId = a.Id;
            sc.siteName = a.Name;
            sc.membershipNumber = a.Membership_Number__c;
            sc.supplyChainCertificateURL = System.URL.getSalesforceBaseUrl().toExternalForm() + '/apex/SupplyChainCertificate'+'?id='+a.Id;
            sc.troutCertificateURL = System.URL.getSalesforceBaseUrl().toExternalForm() + '/apex/TroutCertificate'+'?id='+a.Id;
            sc.nsfUkasCertificate = System.URL.getSalesforceBaseUrl().toExternalForm() + '/apex/SCICertificate_V2'+'?id='+a.Id;
            sc.hasSupplyChainCertificate = false; // false by default
            sc.hasTroutCertificate = false; // false by default
            sc.hasNSFUKASCertificate = false; // false by default
            
            Map<String,Unit> unitCertificateMap = new Map<String,Unit>();

            if(supplyChainMap.containsKey(a.Id)){
                List<Unit> supplyChainList = supplyChainMap.get(a.Id).values();
                if(supplyChainList != null && supplyChainList.size() > 0){
                    sc.hasSupplyChainCertificate = true;
                    for(Unit u:supplyChainList){
                        u.hasSupplyChainCertificate = true;
                        u.hasNSFUKASCertificate = false;
                        u.species = 'Supply Chain';
                        unitCertificateMap.put(u.species,u);
                    }
                }
                
            }
            
            if(nsfUKASMap.containsKey(a.Id)){
                List<Unit> nsfUKASList = nsfUKASMap.get(a.Id).values();
                if(nsfUKASList != null && nsfUKASList.size() > 0){
                    sc.hasNSFUKASCertificate = true;
                    for(Unit u:nsfUKASList){
                        if(unitCertificateMap.containsKey(u.species)){
                            Unit unitIns = unitCertificateMap.get(u.species);
                            unitIns.hasSupplyChainCertificate = false;
                            unitIns.nsfUkasCertificateUrl = u.nsfUkasCertificateUrl;
                            unitCertificateMap.put(u.species,unitIns);
                        }else{
                            u.hasNSFUKASCertificate = true;
                            unitCertificateMap.put(u.species,u);
                        }
                    }
                }
            }
            if(unitCertificateMap != null && unitCertificateMap.size()>0){
                sc.hasUnitCertificates = true;
                sc.unitCertificates = unitCertificateMap.values();
            }else{
                sc.hasUnitCertificates = false;
                sc.unitCertificates = New List<Unit>();
            }
            
            siteCertificateList.add(sc);
            
        }

        if(siteCertificateList.size() > 0){
            hasSiteCertificates = true;
        }else{
            hasSiteCertificates = false;
        }
        showSpinner = false;
    }
    public PageReference attachPDF(){
        if(imageURL != null){
         	PageReference reportPage = new PageReference(imageURL);
            Blob reportPdf;
            try {
                reportPdf = reportPage.getContentAsPDF();
            }
            catch (Exception e) {
                reportPdf = Blob.valueOf(e.getMessage());
            }
            ContentVersion cv = new ContentVersion();
            cv.VersionData = reportPdf;
            cv.Title = pdfName;
            cv.PathOnClient = pdfName;
            cv.Description = pdfName;
            cv.isMajorVersion = true;
            insert cv;
            ContentDocumentLink cdl = new ContentDocumentLink();
            cdl.ContentDocumentId = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =: cv.Id].ContentDocumentId;
            cdl.LinkedEntityId = currentRecord.Id;
            cdl.ShareType = 'V';
            insert cdl;   
        }
        return null;
    }
    public class SiteCertificate{
        public String siteRecordId{get;set;} // Site Id
        public String siteName{get;set;} 
        public String membershipNumber{get;set;} 
        public String supplyChainCertificateURL{get;set;} 
        public String troutCertificateURL{get;set;} 
        public String nsfUkasCertificate{get;set;} 
        public Boolean hasSupplyChainCertificate{get;set;} 
        public Boolean hasTroutCertificate{get;set;} 
        public Boolean hasNSFUKASCertificate{get;set;} 
        public Boolean hasUnitCertificates{get;set;}
        public List<Unit> unitCertificates{get;set;}
    }
    public class Unit{
        public String species{get;set;}
        public String accountId{get;set;}
        public Unit__c unit{get;set;}
        public String supplyChainCertificateURL{get;set;}
        public String nsfUkasCertificateUrl{get;set;}
        public Boolean hasSupplyChainCertificate{get;set;} 
        public Boolean hasNSFUKASCertificate{get;set;} 
    }
}