unpackaged/main/default/objects/Account/fields/Membership_Number__c.field-meta.xml
<CustomField>
    <fullName>Membership_Number__c</fullName>
    <formula>Parent.Head_Office_Number__c  &amp; &quot;.&quot;  &amp;  Site_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Membership_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Unit__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Animals__c.field-meta.xml
<CustomField>
    <fullName>Animals__c</fullName>
    <label>Animals</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Animals</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Production__c.field-meta.xml
<CustomField>
    <fullName>Production__c</fullName>
    <label>Production</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Production</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Rearing_System__c.field-meta.xml
<CustomField>
    <fullName>Rearing_System__c</fullName>
    <label>Rearing System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rearing_System</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applying</fullName>
                <default>true</default>
                <label>Applying</label>
            </value>
            <value>
                <fullName>Certified</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Animals.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Beef Cattle</fullName>
    </customValue>
    <customValue>
        <fullName>Chickens</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy Cattle</fullName>
    </customValue>
    <customValue>
        <fullName>Ducklings</fullName>
    </customValue>
    <customValue>
        <fullName>Ducks</fullName>
    </customValue>
    <customValue>
        <fullName>Laying Hen Chicks</fullName>
    </customValue>
    <customValue>
        <fullName>Laying Hens</fullName>
    </customValue>
    <customValue>
        <fullName>Lumpfish</fullName>
    </customValue>
    <customValue>
        <fullName>Meat Chicken Chicks</fullName>
    </customValue>
    <customValue>
        <fullName>Pigs</fullName>
    </customValue>
    <customValue>
        <fullName>Pullets</fullName>
    </customValue>
    <customValue>
        <fullName>Salmon</fullName>
    </customValue>
    <customValue>
        <fullName>Sheep</fullName>
    </customValue>
    <customValue>
        <fullName>Trout</fullName>
    </customValue>
    <customValue>
        <fullName>Turkey Poults</fullName>
    </customValue>
    <customValue>
        <fullName>Turkeys</fullName>
    </customValue>
    <customValue>
        <fullName>Veal Calves</fullName>
    </customValue>
    <customValue>
        <fullName>Wrasse</fullName>
    </customValue>
    <customValue>
        <fullName>List</fullName>
    </customValue>
    <masterLabel>Animals</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Business.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abattoir</fullName>
    </customValue>
    <customValue>
        <fullName>Catching</fullName>
    </customValue>
    <customValue>
        <fullName>Cleaner Fish</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery</fullName>
    </customValue>
    <customValue>
        <fullName>Haulier</fullName>
    </customValue>
    <customValue>
        <fullName>Producer</fullName>
    </customValue>
    <customValue>
        <fullName>Supply Chain</fullName>
    </customValue>
    <masterLabel>Business</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Membership_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ADDITION</fullName>
    </customValue>
    <customValue>
        <fullName>ARCHIVED</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC5R</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC7R</fullName>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
    </customValue>
    <customValue>
        <fullName>CONPASS</fullName>
    </customValue>
    <customValue>
        <fullName>ENQUIRY</fullName>
        <default>true</default>
        <label>ENQUIRY</label>
    </customValue>
    <customValue>
        <fullName>EVIDENCE</fullName>
    </customValue>
    <customValue>
        <fullName>FAILED</fullName>
    </customValue>
    <customValue>
        <fullName>FALLOW</fullName>
    </customValue>
    <customValue>
        <fullName>LAPSED</fullName>
    </customValue>
    <customValue>
        <fullName>MEMBER</fullName>
    </customValue>
    <customValue>
        <fullName>MONREQ</fullName>
    </customValue>
    <customValue>
        <fullName>NEW</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2R</fullName>
    </customValue>
    <customValue>
        <fullName>NEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>NONFR</fullName>
    </customValue>
    <customValue>
        <fullName>NOTINSCHEME</fullName>
    </customValue>
    <customValue>
        <fullName>PASSED</fullName>
    </customValue>
    <customValue>
        <fullName>PREPANEL</fullName>
    </customValue>
    <customValue>
        <fullName>REINSTATE</fullName>
    </customValue>
    <customValue>
        <fullName>RENEW/REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWA</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWALINP</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWR</fullName>
    </customValue>
    <customValue>
        <fullName>REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>SUSPENDED</fullName>
    </customValue>
    <masterLabel>Membership Status</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Production.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abattoir</fullName>
    </customValue>
    <customValue>
        <fullName>Brand/Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Breeding</fullName>
    </customValue>
    <customValue>
        <fullName>Brood</fullName>
    </customValue>
    <customValue>
        <fullName>Calves</fullName>
    </customValue>
    <customValue>
        <fullName>Catching Team</fullName>
    </customValue>
    <customValue>
        <fullName>Cleaner Fish</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Dry Cows</fullName>
    </customValue>
    <customValue>
        <fullName>Finishing</fullName>
    </customValue>
    <customValue>
        <fullName>Flat deck (one-storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Flat deck (two storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Flat deck with Veranda</fullName>
    </customValue>
    <customValue>
        <fullName>Freshwater</fullName>
    </customValue>
    <customValue>
        <fullName>Gilts</fullName>
    </customValue>
    <customValue>
        <fullName>Grazing</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery (On Grower)</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery (Ova)</fullName>
    </customValue>
    <customValue>
        <fullName>Haulier</fullName>
    </customValue>
    <customValue>
        <fullName>Heifers</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-tier (one-storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-tier (two-storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-tier with Veranda</fullName>
    </customValue>
    <customValue>
        <fullName>Packer</fullName>
    </customValue>
    <customValue>
        <fullName>Processor</fullName>
    </customValue>
    <customValue>
        <fullName>Processor/Packer</fullName>
    </customValue>
    <customValue>
        <fullName>Producer</fullName>
    </customValue>
    <customValue>
        <fullName>Rearing</fullName>
    </customValue>
    <customValue>
        <fullName>Retailer</fullName>
    </customValue>
    <masterLabel>Production</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Rearing_System.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Barn</fullName>
    </customValue>
    <customValue>
        <fullName>Free Range</fullName>
    </customValue>
    <customValue>
        <fullName>Indoor</fullName>
    </customValue>
    <customValue>
        <fullName>Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Outdoor Bred</fullName>
    </customValue>
    <customValue>
        <fullName>Outdoor Reared</fullName>
    </customValue>
    <customValue>
        <fullName>n/a</fullName>
    </customValue>
    <customValue>
        <fullName>Pasture</fullName>
    </customValue>
    <masterLabel>Rearing System</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/DownloadCertificatesController.cls
public with sharing class DownloadCertificatesController {
    
    // current record of from the current page
    public Account currentRecord{get;set;}
    
    // Certificate URL's with currentRecord.Id passed to it
    public String supplyChainCertificateURL{get;set;}
    public String troutCertificateURL{get;set;}
    public String sciCertificate{get;set;}

    // Checking whether the account has the relevant units for certificates
    public Boolean hasSupplyChainCertificate{get;set;}
    public Boolean hasTroutCertificate{get;set;}
    public Boolean hasSCICertificate{get;set;}




    public DownloadCertificatesController(ApexPages.StandardController controller) {
        currentRecord = [SELECT Id, Name, Membership_Number__c FROM Account WHERE Id = :controller.getRecord().Id];

        // Generating the URL's for the certificates
        supplyChainCertificateURL = System.URL.getSalesforceBaseUrl().toExternalForm() + '/apex/SupplyChainCertificate'+'?id='+currentRecord.Id ;
        troutCertificateURL = System.URL.getSalesforceBaseUrl().toExternalForm() + '/apex/TroutCertificate'+'?id='+currentRecord.Id ;
        sciCertificate = System.URL.getSalesforceBaseUrl().toExternalForm() + '/apex/SCICertificate'+'?id='+currentRecord.Id ;


        // Checking if member has Supply Chain certificate
        List<Unit__c> supplyChainList = [SELECT Id, Name, Account__c, Business__c, Animals__c, Production__c, Rearing_System__c, Status__c FROM Unit__c WHERE Account__c =:currentRecord.Id AND Status__c = 'Certified' AND Business__c = 'Supply Chain'];
        if(supplyChainList.size() > 0){
            hasSupplyChainCertificate = true;
        }else{
            hasSupplyChainCertificate = false;
        }


        // Checking if member has trout certificate
        Set<String> businessSetTrout = new Set<String>{
            'Hatchery',
            'Haulier',
            'Abattoir',
            'Producer'
        };
        List<Unit__c> troutList = [SELECT Id, Name, Account__c, Business__c, Animals__c, Production__c, Rearing_System__c, Status__c FROM Unit__c WHERE Account__c =:currentRecord.Id AND Status__c = 'Certified' AND Business__c IN:businessSetTrout AND Animals__c = 'Trout'];
        if(troutList.size() > 0){
            hasTroutCertificate = true;
        }else{
            hasTroutCertificate = false;
        }

        // Checking if member has NSF UKAS certificate
        Set<String> businessSetNSFUKAS = new Set<String>{
            'Hatchery',
            'Haulier',
            'Abattoir',
            'Producer',
            'Cleaner Fish',
            'Catching'
        };

        //List<Unit__c> sciList = [SELECT Id, Name, Account__c, Business__c, Animals__c, Production__c, Rearing_System__c, Status__c FROM Unit__c WHERE Account__c =:currentRecord.Id AND Status__c = 'Certified' AND Business__c IN:businessSetNSFUKAS AND Animals__c != 'Trout'];
        List<Unit__c> sciList = [SELECT Id, Name, Account__c, Business__c, Animals__c, Production__c, Rearing_System__c, Status__c FROM Unit__c WHERE Account__c =:currentRecord.Id AND Status__c = 'Certified' AND Business__c IN:businessSetNSFUKAS];
        if(sciList.size() > 0){
            hasSCICertificate = true;
        }else{
            hasSCICertificate = false;
        }
    }
    
}