unpackaged/main/default/objects/Account/fields/Membership_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Membership_Expiry_Date__c</fullName>
    <inlineHelpText>Membership Expiry Date is 1 year after the Certificate Issue Date by Default. However if common renewal date is used, then Membership Expiry Date reflects when the sites will need to renew by from a group level.</inlineHelpText>
    <label>Membership Expiry Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Primary Account(DoNotUse)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <description>An Account representing a site.</description>
    <label>Site</label>
</RecordType>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Application_Type__c</fullName>
    <label>Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Existing_Member__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Revisit</fullName>
            </value>
            <value>
                <fullName>Levy</fullName>
            </value>
            <value>
                <fullName>Merchandise</fullName>
            </value>
            <value>
                <fullName>Promotion/Partnership</fullName>
            </value>
            <value>
                <fullName>Consultancy</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Existing_Member__c.field-meta.xml
<CustomField>
    <fullName>Existing_Member__c</fullName>
    <label>Existing Member?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Membership_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Membership_Expiry_Date__c</fullName>
    <formula>Site__r.Membership_Expiry_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership Expiry Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Application__c/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <description>For renewal applications</description>
    <label>Renewal</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <formula>IF(Id = Account.Primary_Contact__r.Id , true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates that this contact is the primary contact for the account that it is affiliated with.</inlineHelpText>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Roles__c.field-meta.xml
<CustomField>
    <fullName>Roles__c</fullName>
    <label>Roles</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administration Contact</fullName>
            </value>
            <value>
                <fullName>Agricultural/Technical Contact</fullName>
            </value>
            <value>
                <fullName>Artwork Contact</fullName>
            </value>
            <value>
                <fullName>Assessments Contact</fullName>
            </value>
            <value>
                <fullName>Certification Contact</fullName>
            </value>
            <value>
                <fullName>Compliance Contact</fullName>
            </value>
            <value>
                <fullName>Membership Fee Contact</fullName>
            </value>
            <value>
                <fullName>Licence Fee Contact</fullName>
            </value>
            <value>
                <fullName>Traceability Contact</fullName>
            </value>
            <value>
                <fullName>Payments Contact</fullName>
            </value>
            <value>
                <fullName>Partnerships Commercial Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/InvoicePDFControllerTest.cls
@isTest
public class InvoicePDFControllerTest { 
	@testSetup
    static void loadData(){
        Account act = TestDataFactory.createHeadOfficeAccount();
        act.Membership_Expiry_Date__c = system.today();
        update act;
        Contact cnt = TestDataFactory.createContact(act.Id);
        cnt.Roles__c = 'Invoice Contact';
        update cnt;
        act.Primary_Contact__c = cnt.Id;
        update act;
        Account site = TestDataFactory.createSiteAccount(act.Id);
        Id recordTypeId = Schema.SObjectType.Application__c.getRecordTypeInfosByName().get('Renewal').getRecordTypeId();
        Application__c app = TestDataFactory.createApplication(recordTypeId, act.Id, act.Id, cnt.Id, false); 
        app.Application_Type__c = 'Renewal';
        app.Existing_Member__c = 'Yes';
        insert app;
        Product2 product = TestDataFactory.createProduct(true);
        TestDataFactory.createPriceBookEntry(product.Id,Test.getStandardPricebookId(),true);
        TestDataFactory.createApplicationLineItem(product.Id,app.Id,true);
    }
    @isTest
    static void testMethod1(){
        Application__c app = [SELECT Id FROM Application__c limit 1];
        ApexPages.currentPage().getParameters().put('id',app.Id);
        ApexPages.StandardController controller = new ApexPages.StandardController(app);
        InvoicePDFController brCntrlStnd = new InvoicePDFController(controller);
        system.Assert(brCntrlStnd.startDate == system.today());
        system.Assert(brCntrlStnd.endDate == brCntrlStnd.startDate.addMonths(12));
    }
}