unpackaged/main/default/objects/Account/fields/Membership_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Membership_Expiry_Date__c</fullName>
    <inlineHelpText>Membership Expiry Date is 1 year after the Certificate Issue Date by Default. However if common renewal date is used, then Membership Expiry Date reflects when the sites will need to renew by from a group level.</inlineHelpText>
    <label>Membership Expiry Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Membership_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Unit__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Ingredients__c.field-meta.xml
<CustomField>
    <fullName>Ingredients__c</fullName>
    <label>Ingredients</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Ingredients</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Order_Sizes__c.field-meta.xml
<CustomField>
    <fullName>Order_Sizes__c</fullName>
    <label>Order Sizes</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Small</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Production__c.field-meta.xml
<CustomField>
    <fullName>Production__c</fullName>
    <label>Production</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Production</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applying</fullName>
                <default>true</default>
                <label>Applying</label>
            </value>
            <value>
                <fullName>Certified</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Business.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abattoir</fullName>
    </customValue>
    <customValue>
        <fullName>Catching</fullName>
    </customValue>
    <customValue>
        <fullName>Cleaner Fish</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery</fullName>
    </customValue>
    <customValue>
        <fullName>Haulier</fullName>
    </customValue>
    <customValue>
        <fullName>Producer</fullName>
    </customValue>
    <customValue>
        <fullName>Supply Chain</fullName>
    </customValue>
    <masterLabel>Business</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Ingredients.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Beef</fullName>
    </customValue>
    <customValue>
        <fullName>Chicken</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Duck</fullName>
    </customValue>
    <customValue>
        <fullName>Eggs</fullName>
    </customValue>
    <customValue>
        <fullName>Lamb</fullName>
    </customValue>
    <customValue>
        <fullName>Pork</fullName>
    </customValue>
    <customValue>
        <fullName>Salmon</fullName>
    </customValue>
    <customValue>
        <fullName>Trout</fullName>
    </customValue>
    <customValue>
        <fullName>Turkey</fullName>
    </customValue>
    <customValue>
        <fullName>Veal</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Ingredients</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Membership_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ADDITION</fullName>
    </customValue>
    <customValue>
        <fullName>ARCHIVED</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC5R</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC7R</fullName>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
    </customValue>
    <customValue>
        <fullName>CONPASS</fullName>
    </customValue>
    <customValue>
        <fullName>ENQUIRY</fullName>
        <default>true</default>
        <label>ENQUIRY</label>
    </customValue>
    <customValue>
        <fullName>EVIDENCE</fullName>
    </customValue>
    <customValue>
        <fullName>FAILED</fullName>
    </customValue>
    <customValue>
        <fullName>FALLOW</fullName>
    </customValue>
    <customValue>
        <fullName>LAPSED</fullName>
    </customValue>
    <customValue>
        <fullName>MEMBER</fullName>
    </customValue>
    <customValue>
        <fullName>MONREQ</fullName>
    </customValue>
    <customValue>
        <fullName>NEW</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2R</fullName>
    </customValue>
    <customValue>
        <fullName>NEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>NONFR</fullName>
    </customValue>
    <customValue>
        <fullName>NOTINSCHEME</fullName>
    </customValue>
    <customValue>
        <fullName>PASSED</fullName>
    </customValue>
    <customValue>
        <fullName>PREPANEL</fullName>
    </customValue>
    <customValue>
        <fullName>REINSTATE</fullName>
    </customValue>
    <customValue>
        <fullName>RENEW/REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWA</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWALINP</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWR</fullName>
    </customValue>
    <customValue>
        <fullName>REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>SUSPENDED</fullName>
    </customValue>
    <masterLabel>Membership Status</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Production.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abattoir</fullName>
    </customValue>
    <customValue>
        <fullName>Brand/Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Breeding</fullName>
    </customValue>
    <customValue>
        <fullName>Brood</fullName>
    </customValue>
    <customValue>
        <fullName>Calves</fullName>
    </customValue>
    <customValue>
        <fullName>Catching Team</fullName>
    </customValue>
    <customValue>
        <fullName>Cleaner Fish</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Dry Cows</fullName>
    </customValue>
    <customValue>
        <fullName>Finishing</fullName>
    </customValue>
    <customValue>
        <fullName>Flat deck (one-storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Flat deck (two storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Flat deck with Veranda</fullName>
    </customValue>
    <customValue>
        <fullName>Freshwater</fullName>
    </customValue>
    <customValue>
        <fullName>Gilts</fullName>
    </customValue>
    <customValue>
        <fullName>Grazing</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery (On Grower)</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery (Ova)</fullName>
    </customValue>
    <customValue>
        <fullName>Haulier</fullName>
    </customValue>
    <customValue>
        <fullName>Heifers</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-tier (one-storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-tier (two-storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-tier with Veranda</fullName>
    </customValue>
    <customValue>
        <fullName>Packer</fullName>
    </customValue>
    <customValue>
        <fullName>Processor</fullName>
    </customValue>
    <customValue>
        <fullName>Processor/Packer</fullName>
    </customValue>
    <customValue>
        <fullName>Producer</fullName>
    </customValue>
    <customValue>
        <fullName>Rearing</fullName>
    </customValue>
    <customValue>
        <fullName>Retailer</fullName>
    </customValue>
    <masterLabel>Production</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/SiteUnitsControllerTest.cls
@isTest
public class SiteUnitsControllerTest {
    @isTest
    public static void SiteUnitsControllerTest() {
        //Create Account
        FObject siteObj = DataFactory.getDefSiteAccounts();
        siteObj.insertRecords(true);
        List<Account> insertedAccounts = FObject.getInsertedRecords('Account');
        System.assertEquals(1, insertedAccounts.size());
        insertedAccounts[0].Membership_Expiry_Date__c = Date.today() + 365;
        update insertedAccounts;

        // Create certified units
        Unit__c unit1 = new Unit__c();
        unit1.Account__c = insertedAccounts[0].Id;
        unit1.Name = '01';
        unit1.Business__c = 'Supply Chain';
        unit1.Ingredients__c = 'Beef';
        unit1.Production__c = 'Processor';
        unit1.Order_Sizes__C = 'Single';
        unit1.Status__c = 'Certified';
        insert unit1;

        SiteUnitsController.getUnits(insertedAccounts[0].Id);
    }
}