unpackaged/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Primary Account(DoNotUse)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <description>An Account representing a site.</description>
    <label>Site</label>
</RecordType>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Bulk_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Renewal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bulk Renewal</label>
    <referenceTo>Bulk_Renewal__c</referenceTo>
    <relationshipLabel>Renewal Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Head_Office__c.field-meta.xml
<CustomField>
    <fullName>Head_Office__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Head Office</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Head Office</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/recordTypes/Applications.recordType-meta.xml
<RecordType>
    <fullName>Applications</fullName>
    <active>true</active>
    <description>For new applications.</description>
    <label>Applications</label>
</RecordType>

unpackaged/main/default/objects/Bulk_Renewal__c/Bulk_Renewal__c.object-meta.xml
<CustomObject>
    <description>Object to record the renewal applications created from bulk renewing.</description>
    <label>Bulk Renewal</label>
    <nameField>
        <displayFormat>BR{000000}</displayFormat>
        <label>Bulk Renewal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bulk Renewals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bulk_Renewal__c/fields/Head_Office__c.field-meta.xml
<CustomField>
    <fullName>Head_Office__c</fullName>
    <label>Head Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bulk Renewals</relationshipLabel>
    <relationshipName>Bulk_Renewals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <formula>IF(Id = Account.Primary_Contact__r.Id , true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates that this contact is the primary contact for the account that it is affiliated with.</inlineHelpText>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/BulkRenewalInvoiceControllerTest.cls
@isTest
public class BulkRenewalInvoiceControllerTest {
    @testSetup
    static void loadData(){
        Account act = TestDataFactory.createHeadOfficeAccount();
        Contact cnt = TestDataFactory.createContact(act.Id);
        act.Primary_Contact__c = cnt.Id;
        update act;
        Account site = TestDataFactory.createSiteAccount(act.Id);
        Id recordTypeId = Schema.SObjectType.Application__c.getRecordTypeInfosByName().get('Applications').getRecordTypeId();
        Application__c app = TestDataFactory.createApplication(recordTypeId, act.Id, act.Id, cnt.Id, true); 
        Bulk_Renewal__c  bulk_renewal = TestDataFactory.createBulkRenewal(cnt.Id,act.Id,true);
        TestDataFactory.createDocument('RSPCA_Assured_Headers_Assess_Con_png');
        TestDataFactory.createDocument('RSPCA_Assured_Headers_Comm_In_png');
        TestDataFactory.createDocument('RSPCA_Assured_Headers_Renewal_Invite_png');
        TestDataFactory.createDocument('RSPCA_Assured_Headers_FRReminder_png');
        TestDataFactory.createDocument('EvidenceReminder');
        TestDataFactory.createDocument('RSPCA_Assured_Headers_Final_Payment_Reminder_png');
        TestDataFactory.createDocument('RSPCA_Assured_Headers_Payment_Reminder_png');
        TestDataFactory.createDocument('RSPCA_Assured_Headers_Your_Certificates_png');
        TestDataFactory.createDocument('RSPCA_Assured_Headers_Invoice_png');
        TestDataFactory.createDocument('RSPCA_Assured_Headers_Lapsed_png');
        TestDataFactory.createDocument('RSPCA_Assured_Headers_Cancelled_Not_png');
        TestDataFactory.createDocument('RSPCA_Assured_Headers_Payment_Confirmation_png');
        TestDataFactory.createDocument('RSPCA_Assured_Email_Header_EG_png');
        TestDataFactory.createDocument('FinalEvidenceReminder');
    }
    @isTest
    static void testMethod1(){
        Bulk_Renewal__c  bulk_renewal = [SELECT Id,Head_Office__c FROM Bulk_Renewal__c limit 1];
        Application__c app = [SELECT Id FROM Application__c limit 1];
        ApexPages.currentPage().getParameters().put('id',bulk_renewal.Id);
        ApexPages.StandardController controller = new ApexPages.StandardController(bulk_renewal);
        BulkRenewalInvoiceController brCntrlStnd = new BulkRenewalInvoiceController(controller);
        brCntrlStnd.bulkRenewalId = bulk_renewal.Id;
        brCntrlStnd.userId = userinfo.getUserId();
        brCntrlStnd.applicationId = app.Id;
        brCntrlStnd.accountId = bulk_renewal.Head_Office__c;
        brCntrlStnd.getApplication();
        brCntrlStnd.getAssessmentCompleteUrl();
        brCntrlStnd.getBulkRenewal();
        brCntrlStnd.getCommunityInviteUrl();
        brCntrlStnd.getCommunityName();
        brCntrlStnd.getCommunityUser();
        brCntrlStnd.getEvidenceReminderApplication();
        brCntrlStnd.getEvidenceReminderUrl();
        brCntrlStnd.getExtensionApplication();
        brCntrlStnd.getFinalSiteApplications();
        brCntrlStnd.getMembershipCancelledSites();
        brCntrlStnd.getMembershipCancelledUrl();
        brCntrlStnd.getPymntCnfmUrl();
        brCntrlStnd.getPymntCnfrmApplications();
        brCntrlStnd.getRenewalApplications();
        brCntrlStnd.getRenewalReminderSites();
        brCntrlStnd.getRenewLapsedSites();
        brCntrlStnd.getSiteApplications();
        brCntrlStnd.getSiteCertificates();
        brCntrlStnd.getSixWeekUrl();
        brCntrlStnd.getStrCertUrl();
        brCntrlStnd.getStrInvoiceUrl();
        brCntrlStnd.getStrPymRemUrl();
        brCntrlStnd.getStrPymUrl();
        brCntrlStnd.getTwoWeekRenewalReminderSites();
        brCntrlStnd.getTwoWeekUrl();
        brCntrlStnd.getRenewLapsedUrl();
        brCntrlStnd.getExtensionGrantedUrl();
        brCntrlStnd.getFinalEvidenceReminderUrl();
        brCntrlStnd.getCommunityUrl();
        Account headOffice = brCntrlStnd.getHeadOffice();
        system.assert(headOffice.Name == 'Test Head Office');
    }
}