unpackaged/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Primary Account(DoNotUse)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <description>An Account representing a site.</description>
    <label>Site</label>
</RecordType>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Bulk_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Renewal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bulk Renewal</label>
    <referenceTo>Bulk_Renewal__c</referenceTo>
    <relationshipLabel>Renewal Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Head_Office__c.field-meta.xml
<CustomField>
    <fullName>Head_Office__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Head Office</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Head Office</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Application__c/recordTypes/Applications.recordType-meta.xml
<RecordType>
    <fullName>Applications</fullName>
    <active>true</active>
    <description>For new applications.</description>
    <label>Applications</label>
</RecordType>

unpackaged/main/default/objects/Bulk_Renewal__c/Bulk_Renewal__c.object-meta.xml
<CustomObject>
    <description>Object to record the renewal applications created from bulk renewing.</description>
    <label>Bulk Renewal</label>
    <nameField>
        <displayFormat>BR{000000}</displayFormat>
        <label>Bulk Renewal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bulk Renewals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bulk_Renewal__c/fields/Head_Office__c.field-meta.xml
<CustomField>
    <fullName>Head_Office__c</fullName>
    <label>Head Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bulk Renewals</relationshipLabel>
    <relationshipName>Bulk_Renewals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <formula>IF(Id = Account.Primary_Contact__r.Id , true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates that this contact is the primary contact for the account that it is affiliated with.</inlineHelpText>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/PaymentReminderControllerTest.cls
@isTest
public class PaymentReminderControllerTest {
	@testSetup
    static void loadData(){
        Account act = TestDataFactory.createHeadOfficeAccount();
        Contact cnt = TestDataFactory.createContact(act.Id);
        act.Primary_Contact__c = cnt.Id;
        update act;
        Account site = TestDataFactory.createSiteAccount(act.Id);
        Id recordTypeId = Schema.SObjectType.Application__c.getRecordTypeInfosByName().get('Applications').getRecordTypeId();
		Application__c app = TestDataFactory.createApplication(recordTypeId, act.Id, act.Id, cnt.Id, true); 
        Bulk_Renewal__c  bulk_renewal = TestDataFactory.createBulkRenewal(cnt.Id,act.Id,true);
		TestDataFactory.createDocument('RSPCA_Assured_Headers_Assess_Con_png');
        TestDataFactory.createDocument('RSPCA_Assured_Headers_Comm_In_png');
        TestDataFactory.createDocument('RSPCA_Assured_Headers_Renewal_Invite_png');
        TestDataFactory.createDocument('RSPCA_Assured_Headers_FRReminder_png');
        TestDataFactory.createDocument('EvidenceReminder');
        TestDataFactory.createDocument('RSPCA_Assured_Headers_Final_Payment_Reminder_png');
        TestDataFactory.createDocument('RSPCA_Assured_Headers_Payment_Reminder_png');
        TestDataFactory.createDocument('RSPCA_Assured_Headers_Your_Certificates_png');
        TestDataFactory.createDocument('RSPCA_Assured_Headers_Invoice_png');
        TestDataFactory.createDocument('RSPCA_Assured_Headers_Lapsed_png');
        TestDataFactory.createDocument('RSPCA_Assured_Headers_Cancelled_Not_png');
        TestDataFactory.createDocument('RSPCA_Assured_Headers_Payment_Confirmation_png');
        TestDataFactory.createDocument('RSPCA_Assured_Email_Header_EG_png');
        TestDataFactory.createDocument('FinalEvidenceReminder');
    }
    @isTest
    static void testMethod1(){
        Bulk_Renewal__c  bulk_renewal = [SELECT Id,Head_Office__c FROM Bulk_Renewal__c limit 1];
        Application__c app = [SELECT Id FROM Application__c limit 1];
        ApexPages.currentPage().getParameters().put('id',bulk_renewal.Id);
        ApexPages.StandardController controller = new ApexPages.StandardController(bulk_renewal);
        PaymentReminderController paymentCntrlStnd = new PaymentReminderController(controller);
        PaymentReminderController paymentCntrl = new PaymentReminderController();
        paymentCntrl.accountId = bulk_renewal.Head_Office__c;
        paymentCntrl.applicationId = app.Id;
        paymentCntrl.userId = userInfo.getUserId();
        Account headOffice = paymentCntrl.getHeadOffice();
        system.assert(headOffice.Name == 'Test Head Office');
        app = paymentCntrl.getApplication();
        system.assert(app != null);
        String AssessmentCompleteUrl = paymentCntrl.getAssessmentCompleteUrl();
        system.assert(String.isNotBlank(AssessmentCompleteUrl));
        paymentCntrl.getBulkRenewal();
        String CommunityInviteUrl = paymentCntrl.getCommunityInviteUrl();
        system.assert(String.isNotBlank(CommunityInviteUrl));
        paymentCntrl.getCommunityName();
        String CommunityUrl = paymentCntrl.getCommunityUrl();
        system.assert(String.isNotBlank(CommunityUrl));
        paymentCntrl.getCommunityUser();
        paymentCntrl.getEvidenceReminderApplication();
        String EvidenceReminderUrl = paymentCntrl.getEvidenceReminderUrl();
        paymentCntrl.getFinalSiteApplications();
        paymentCntrl.getMembershipCancelledSites();
        String TwoWeekUrl = paymentCntrl.getTwoWeekUrl();
        paymentCntrl.getTwoWeekRenewalReminderSites();
        String StrPymUrl = paymentCntrl.getStrPymUrl();
        String StrInvoiceUrl = paymentCntrl.getStrInvoiceUrl();
        String StrCertUrl = paymentCntrl.getStrCertUrl();
        String SixWeekUrl = paymentCntrl.getSixWeekUrl();
        paymentCntrl.getSiteCertificates();
        paymentCntrl.getSiteApplications();
        paymentCntrl.getRenewLapsedUrl();
        paymentCntrl.getMembershipCancelledUrl();
        paymentCntrl.getPymntCnfmUrl();
        paymentCntrl.getExtensionGrantedUrl();
        paymentCntrl.getFinalEvidenceReminderUrl();
        paymentCntrl.getCommunityName();
        paymentCntrl.getExtensionApplication();
        paymentCntrl.getRenewLapsedSites();
        paymentCntrl.getRenewalReminderSites();
        List<Application__c> PymntCnfrmApplications = paymentCntrl.getPymntCnfrmApplications();
        system.assert(PymntCnfrmApplications.size() == 0);
        String StrPymRemUrl = paymentCntrl.getStrPymRemUrl();
        system.assert(String.isNotBlank(StrPymRemUrl));
        List<Application__c> RenewalApplications = paymentCntrl.getRenewalApplications();
        system.assert(RenewalApplications.size() == 0);
    }
}