unpackaged/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Primary Account(DoNotUse)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Membership_Status</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Site.recordType-meta.xml
<RecordType>
    <fullName>Site</fullName>
    <active>true</active>
    <description>An Account representing a site.</description>
    <label>Site</label>
</RecordType>

unpackaged/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>AP{000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Application__c/fields/Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Application_Type__c</fullName>
    <label>Application Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Existing_Member__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Revisit</fullName>
            </value>
            <value>
                <fullName>Levy</fullName>
            </value>
            <value>
                <fullName>Merchandise</fullName>
            </value>
            <value>
                <fullName>Promotion/Partnership</fullName>
            </value>
            <value>
                <fullName>Consultancy</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Existing_Member__c.field-meta.xml
<CustomField>
    <fullName>Existing_Member__c</fullName>
    <label>Existing Member?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BACS</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
                <isActive>false</isActive>
                <label>Card</label>
            </value>
            <value>
                <fullName>Cheque</fullName>
                <isActive>false</isActive>
                <label>Cheque</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>ApplicationSite</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Site__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Application__c/fields/Update_Type__c.field-meta.xml
<CustomField>
    <fullName>Update_Type__c</fullName>
    <inlineHelpText>An application for a new unit or extension to flock size mid certificate</inlineHelpText>
    <label>Update Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Application_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Unit</fullName>
            </value>
            <value>
                <fullName>Update to flock size</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <formula>IF(Id = Account.Primary_Contact__r.Id , true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indicates that this contact is the primary contact for the account that it is affiliated with.</inlineHelpText>
    <label>Primary Contact</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Production__c.field-meta.xml
<CustomField>
    <fullName>Production__c</fullName>
    <label>Production</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Production</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Species_Discount_Extra__c.field-meta.xml
<CustomField>
    <fullName>Species_Discount_Extra__c</fullName>
    <label>Species Discount Extra</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Standard_Price__c.field-meta.xml
<CustomField>
    <fullName>Standard_Price__c</fullName>
    <label>Standard Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Unit__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Animals__c.field-meta.xml
<CustomField>
    <fullName>Animals__c</fullName>
    <label>Animals</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Animals</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Ingredients__c.field-meta.xml
<CustomField>
    <fullName>Ingredients__c</fullName>
    <label>Ingredients</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Ingredients</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Number_of_Animals__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Animals__c</fullName>
    <label>Number of Animals</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Order_Sizes__c.field-meta.xml
<CustomField>
    <fullName>Order_Sizes__c</fullName>
    <label>Order Sizes</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Small</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Production__c.field-meta.xml
<CustomField>
    <fullName>Production__c</fullName>
    <label>Production</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Production</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applying</fullName>
                <default>true</default>
                <label>Applying</label>
            </value>
            <value>
                <fullName>Certified</fullName>
            </value>
            <value>
                <fullName>Lapsed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Animals.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Beef Cattle</fullName>
    </customValue>
    <customValue>
        <fullName>Chickens</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy Cattle</fullName>
    </customValue>
    <customValue>
        <fullName>Ducklings</fullName>
    </customValue>
    <customValue>
        <fullName>Ducks</fullName>
    </customValue>
    <customValue>
        <fullName>Laying Hen Chicks</fullName>
    </customValue>
    <customValue>
        <fullName>Laying Hens</fullName>
    </customValue>
    <customValue>
        <fullName>Lumpfish</fullName>
    </customValue>
    <customValue>
        <fullName>Meat Chicken Chicks</fullName>
    </customValue>
    <customValue>
        <fullName>Pigs</fullName>
    </customValue>
    <customValue>
        <fullName>Pullets</fullName>
    </customValue>
    <customValue>
        <fullName>Salmon</fullName>
    </customValue>
    <customValue>
        <fullName>Sheep</fullName>
    </customValue>
    <customValue>
        <fullName>Trout</fullName>
    </customValue>
    <customValue>
        <fullName>Turkey Poults</fullName>
    </customValue>
    <customValue>
        <fullName>Turkeys</fullName>
    </customValue>
    <customValue>
        <fullName>Veal Calves</fullName>
    </customValue>
    <customValue>
        <fullName>Wrasse</fullName>
    </customValue>
    <customValue>
        <fullName>List</fullName>
    </customValue>
    <masterLabel>Animals</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Business.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abattoir</fullName>
    </customValue>
    <customValue>
        <fullName>Catching</fullName>
    </customValue>
    <customValue>
        <fullName>Cleaner Fish</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery</fullName>
    </customValue>
    <customValue>
        <fullName>Haulier</fullName>
    </customValue>
    <customValue>
        <fullName>Producer</fullName>
    </customValue>
    <customValue>
        <fullName>Supply Chain</fullName>
    </customValue>
    <masterLabel>Business</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Ingredients.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Beef</fullName>
    </customValue>
    <customValue>
        <fullName>Chicken</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Duck</fullName>
    </customValue>
    <customValue>
        <fullName>Eggs</fullName>
    </customValue>
    <customValue>
        <fullName>Lamb</fullName>
    </customValue>
    <customValue>
        <fullName>Pork</fullName>
    </customValue>
    <customValue>
        <fullName>Salmon</fullName>
    </customValue>
    <customValue>
        <fullName>Trout</fullName>
    </customValue>
    <customValue>
        <fullName>Turkey</fullName>
    </customValue>
    <customValue>
        <fullName>Veal</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Ingredients</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Membership_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ADDITION</fullName>
    </customValue>
    <customValue>
        <fullName>ARCHIVED</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC5R</fullName>
    </customValue>
    <customValue>
        <fullName>ASSREC7R</fullName>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
    </customValue>
    <customValue>
        <fullName>CONPASS</fullName>
    </customValue>
    <customValue>
        <fullName>ENQUIRY</fullName>
        <default>true</default>
        <label>ENQUIRY</label>
    </customValue>
    <customValue>
        <fullName>EVIDENCE</fullName>
    </customValue>
    <customValue>
        <fullName>FAILED</fullName>
    </customValue>
    <customValue>
        <fullName>FALLOW</fullName>
    </customValue>
    <customValue>
        <fullName>LAPSED</fullName>
    </customValue>
    <customValue>
        <fullName>MEMBER</fullName>
    </customValue>
    <customValue>
        <fullName>MONREQ</fullName>
    </customValue>
    <customValue>
        <fullName>NEW</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2</fullName>
    </customValue>
    <customValue>
        <fullName>NEWAPP2R</fullName>
    </customValue>
    <customValue>
        <fullName>NEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>NONFR</fullName>
    </customValue>
    <customValue>
        <fullName>NOTINSCHEME</fullName>
    </customValue>
    <customValue>
        <fullName>PASSED</fullName>
    </customValue>
    <customValue>
        <fullName>PREPANEL</fullName>
    </customValue>
    <customValue>
        <fullName>REINSTATE</fullName>
    </customValue>
    <customValue>
        <fullName>RENEW/REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWA</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWALINP</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWASS</fullName>
    </customValue>
    <customValue>
        <fullName>RENEWR</fullName>
    </customValue>
    <customValue>
        <fullName>REVISIT</fullName>
    </customValue>
    <customValue>
        <fullName>SUSPENDED</fullName>
    </customValue>
    <masterLabel>Membership Status</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Production.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abattoir</fullName>
    </customValue>
    <customValue>
        <fullName>Brand/Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Breeding</fullName>
    </customValue>
    <customValue>
        <fullName>Brood</fullName>
    </customValue>
    <customValue>
        <fullName>Calves</fullName>
    </customValue>
    <customValue>
        <fullName>Catching Team</fullName>
    </customValue>
    <customValue>
        <fullName>Cleaner Fish</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Dry Cows</fullName>
    </customValue>
    <customValue>
        <fullName>Finishing</fullName>
    </customValue>
    <customValue>
        <fullName>Flat deck (one-storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Flat deck (two storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Flat deck with Veranda</fullName>
    </customValue>
    <customValue>
        <fullName>Freshwater</fullName>
    </customValue>
    <customValue>
        <fullName>Gilts</fullName>
    </customValue>
    <customValue>
        <fullName>Grazing</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery (On Grower)</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery (Ova)</fullName>
    </customValue>
    <customValue>
        <fullName>Haulier</fullName>
    </customValue>
    <customValue>
        <fullName>Heifers</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-tier (one-storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-tier (two-storey)</fullName>
    </customValue>
    <customValue>
        <fullName>Multi-tier with Veranda</fullName>
    </customValue>
    <customValue>
        <fullName>Packer</fullName>
    </customValue>
    <customValue>
        <fullName>Processor</fullName>
    </customValue>
    <customValue>
        <fullName>Processor/Packer</fullName>
    </customValue>
    <customValue>
        <fullName>Producer</fullName>
    </customValue>
    <customValue>
        <fullName>Rearing</fullName>
    </customValue>
    <customValue>
        <fullName>Retailer</fullName>
    </customValue>
    <masterLabel>Production</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/AdditionalApplicationControllerTest.cls
@isTest
public class AdditionalApplicationControllerTest {
    @isTest
    static void fetchCustomerContactWithUserTest() {
        // Create System Admin User with Role to create the account
        FObject adminUser = new FObject('User', 1);
        adminUser.setDefinition('ProfileId', 'static lookup(Profile) field(Name) value(System Administrator) source(salesforce)');
        adminUser.setDefinition('Alias','static value(testadm)');
        adminUser.setDefinition('LastName','static value(testadmin)');
        adminUser.setDefinition('UserName','static value(testadmin543434234324@test.com)');
        adminUser.setDefinition('Email','static value(testadmin@test.com)');
        adminUser.setDefinition('UserRoleId', 'random lookup(UserRole) source(forceea)');
        adminUser.insertRecords(true);
        List<User> insertedUsers = FObject.getInsertedRecords('User');
        User insertedAdminUser = new User();
        for(User u : insertedUsers){
            if(u.Alias == 'testadm'){
                insertedAdminUser = u;
            }
        }

        System.runAs(insertedAdminUser){
            // Account
            FObject acc = DataFactory.getDefSiteAccounts();
            acc.setDefinition('Primary_Contact__c', 'random lookup(Contact) source(forceaa)');
            acc.insertRecords(true);
            
            // Contact
            FObject con = DataFactory.getDefContact();
            con.setDefinition('AccountId', 'random lookup(Account) source(forceea)');
            con.insertRecords(true);
        }
        

        // Create customer user to run the tests with
        FObject customerUser = new FObject('User', 1);
        customerUser.setDefinition('ProfileId', 'static lookup(Profile) field(Name) value(RSPCA Assured Community User Site) source(salesforce)');
        customerUser.setDefinition('ContactId', 'random lookup(Contact) source(forceea)');
        customerUser.setDefinition('Alias','static value(test)');
        customerUser.setDefinition('LastName','static value(Last)');
        customerUser.setDefinition('UserName','static value(tester@test.com)');
        customerUser.setDefinition('Email','static value(tester@test.com)');
        customerUser.insertRecords(true);
        List<User> users = FObject.getInsertedRecords('User');
        List<Account> accounts = FObject.getInsertedRecords('Account');
        User insertedCustomerUser = new User();
        for(User u : users){
            if(u.Alias == 'test'){
                insertedCustomerUser = u;
            }
        }
        Test.startTest();
        System.runAs(insertedCustomerUser){
            AdditionalApplicationController.fetchCustomerContact(accounts[0].Id);
            
        }
        Test.stopTest();

    }

    @isTest
    static void fetchCustomerContactWithoutUserTest() {

        // Account
        FObject acc = DataFactory.getDefSiteAccounts();
        acc.insertRecords(true);
        
        // Contact
        FObject con = DataFactory.getDefContact();
        con.setDefinition('FirstName', 'static value(test)');
        con.setDefinition('AccountId', 'random lookup(Account) source(forceea)');
        con.insertRecords(true);
        List<Contact> contacts = FObject.getInsertedRecords('Contact');
        List<Account> accounts = FObject.getInsertedRecords('Account');
        Account accRecord = accounts[0];
        accRecord.Primary_Contact__c = contacts[0].Id;
        update accRecord;
        AdditionalApplicationController.fetchCustomerContact(accounts[0].Id);

    }
    
    @isTest
    static void createAppWithUnitsTest(){
        // Create joinFee product
        FObject joinFee = new FObject('Product2', 1);
        joinFee.setDefinition('Name','static value(Joining Fee)');
        joinFee.setDefinition('ProductCode','static value(JOINFEE)');
        joinFee.setDefinition('IsActive','static value(true)');
        joinFee.setDefinition('Standard_Price__c','static value(28.80)');
        joinFee.insertRecords(true);
        
        // Create revisitFee product
        FObject revisitFee = new FObject('Product2', 1);
        revisitFee.setDefinition('Name','static value(Revisit)');
        revisitFee.setDefinition('ProductCode','static value(REVISIT)');
        revisitFee.setDefinition('IsActive','static value(true)');
        revisitFee.setDefinition('Standard_Price__c','static value(114.24)');
        revisitFee.insertRecords(true);

        // Create species discount product
        FObject speciesDiscount = new FObject('Product2', 1);
        speciesDiscount.setDefinition('Name','static value(Species Discount)');
        speciesDiscount.setDefinition('ProductCode','static value(SPECIESDISCOUNT)');
        speciesDiscount.setDefinition('IsActive','static value(true)');
        speciesDiscount.setDefinition('Standard_Price__c','static value(-59.50)');
        speciesDiscount.setDefinition('Species_Discount_Extra__c','static value(-88.00)');
        speciesDiscount.insertRecords(true);

        // Create Application 1 with update type = New Unit
        FObject application1 = DataFactory.getDefNewApplications();
        application1.setDefinition('Existing_Member__c', 'static value(Yes)');
        application1.setDefinition('Application_Type__c', 'static value(Update)');
        application1.setDefinition('Update_Type__c', 'static value(New Unit)');
        application1.setDefinition('Payment_Method__c', 'static value(Card)');
        application1.insertRecords(true);
        
        List<Application__c> insertedApps = FObject.getInsertedRecords('Application__c');
        Application__c appNewUnits = new Application__c();
        for(Application__c app : insertedApps){
            app.Id = null;
            if(app.Update_Type__c == 'New Unit'){
                appNewUnits = app;
            }
            
        }
        

        // Create Units
        List<Unit__c> unitList = new List<Unit__c>();
        Unit__c unit1 = new Unit__c();
        unit1.Account__c = appNewUnits.Site__c;
        unit1.Name = '01';
        unit1.Business__c = 'Supply Chain';
        unit1.Ingredients__c = 'Beef';
        unit1.Production__c = 'Processor';
        unit1.Order_Sizes__C = 'Single';
        unitList.add(unit1);
        
        Unit__c unit2 = new Unit__c();
        unit2.Account__c = appNewUnits.Site__c;
        unit2.Name = '02';
        unit2.Business__c = 'Abattoir';
        unit2.Animals__c = 'Beef Cattle';
        unit2.Production__c = 'Abattoir';
        unitList.add(unit2);

        Unit__c unit3 = new Unit__c();
        unit3.Account__c = appNewUnits.Site__c;
        unit3.Name = '03';
        unit3.Business__c = 'Catching';
        unit3.Animals__c = 'Chickens';
        unit3.Production__c = 'Catching Team';
        unitList.add(unit3);

        Unit__c unit4 = new Unit__c();
        unit4.Account__c = appNewUnits.Site__c;
        unit4.Name = '04';
        unit4.Business__c = 'Cleaner Fish';
        unit4.Animals__c = 'Wrasse';
        unit4.Production__c = 'Cleaner Fish';
        unitList.add(unit4);

        Unit__c unit5 = new Unit__c();
        unit5.Account__c = appNewUnits.Site__c;
        unit5.Name = '05';
        unit5.Business__c = 'Hatchery';
        unit5.Animals__c = 'Meat Chicken Chicks';
        unit5.Production__c = 'Hatchery';
        unitList.add(unit5);

        Unit__c unit6 = new Unit__c();
        unit6.Account__c = appNewUnits.Site__c;
        unit6.Name = '06';
        unit6.Business__c = 'Haulier';
        unit6.Animals__c = 'Chickens';
        unit6.Production__c = 'Haulier';
        unitList.add(unit6);

        Unit__c unit7 = new Unit__c();
        unit7.Account__c = appNewUnits.Site__c;
        unit7.Name = '02';
        unit7.Business__c = 'Producer';
        unit7.Production__c = 'Freshwater';
        unit7.Animals__c = 'Trout';
        unit7.Number_Of_Animals__c = 100;
        unitList.add(unit7);

        System.debug(unitList.size());
        System.assertEquals(7, unitList.size());

        // Call the method to add new units
        AdditionalApplicationController.createAppWithUnits(appNewUnits, unitList,true,false);

        
        
        // call the method with the app size 0
        AdditionalApplicationController.createAppWithUnits(appNewUnits.clone(false,false,false,false), new List<Unit__c>(),false,true);
		AdditionalApplicationController.createRevisitFee(insertedApps[0]);

    }
    
    /*
    @isTest
    static void createAppWithUnitsTest1(){
        // Create joinFee product
        FObject joinFee = new FObject('Product2', 1);
        joinFee.setDefinition('Name','static value(Joining Fee)');
        joinFee.setDefinition('ProductCode','static value(JOINFEE)');
        joinFee.setDefinition('IsActive','static value(true)');
        joinFee.setDefinition('Standard_Price__c','static value(28.80)');
        joinFee.insertRecords(true);
        
        // Create revisitFee product
        FObject revisitFee = new FObject('Product2', 1);
        revisitFee.setDefinition('Name','static value(Revisit)');
        revisitFee.setDefinition('ProductCode','static value(REVISIT)');
        revisitFee.setDefinition('IsActive','static value(true)');
        revisitFee.setDefinition('Standard_Price__c','static value(114.24)');
        revisitFee.insertRecords(true);

        // Create species discount product
        FObject speciesDiscount = new FObject('Product2', 1);
        speciesDiscount.setDefinition('Name','static value(Species Discount)');
        speciesDiscount.setDefinition('ProductCode','static value(SPECIESDISCOUNT)');
        speciesDiscount.setDefinition('IsActive','static value(true)');
        speciesDiscount.setDefinition('Standard_Price__c','static value(-59.50)');
        speciesDiscount.setDefinition('Species_Discount_Extra__c','static value(-88.00)');
        speciesDiscount.insertRecords(true);


        // Create Application 2 with update type = update to flock size
        FObject application2 = DataFactory.getDefNewApplications();
        application2.setDefinition('Existing_Member__c', 'static value(Yes)');
        application2.setDefinition('Application_Type__c', 'static value(Update)');
        application2.setDefinition('Update_Type__c', 'static value(Update to flock size)');
        application2.setDefinition('Payment_Method__c', 'static value(BACS)');
        application2.insertRecords(true);
        
        List<Application__c> insertedApps = FObject.getInsertedRecords('Application__c');
        Application__c appUpdateFlock = new Application__c();
        for(Application__c app : insertedApps){
            app.Id = null;
            if(app.Update_Type__c == 'Update to flock size'){
                appUpdateFlock = app;
                // below has been commented out as card payment has not been enabled
                //app.Payment_Method__c = 'Card';
            }
            
        }
        // Create Units
        List<Unit__c> unitList = new List<Unit__c>();
        Unit__c unit1 = new Unit__c();
        unit1.Account__c = appUpdateFlock.Site__c;
        unit1.Name = '01';
        unit1.Business__c = 'Supply Chain';
        unit1.Ingredients__c = 'Beef';
        unit1.Production__c = 'Processor';
        unit1.Order_Sizes__C = 'Single';
        unitList.add(unit1);
        insert unitList;


        // Call the method to update flock size
        AdditionalApplicationController.createAppWithUnits(appUpdateFlock, unitList);

        // call the method with unit size 0
        AdditionalApplicationController.createAppWithUnits(null, new List<Unit__c>());
    }
*/
    @isTest
    static void getPoultryUnitsTest() {
        // Create account
        FObject accObj = DataFactory.getDefSiteAccounts();
        accObj.insertRecords(true);
        List<Account> accounts = FObject.getInsertedRecords('Account');

        // Create Units
        Unit__c unit = new Unit__c();
        unit.Account__c = accounts[0].Id;
        unit.Name = '01';
        unit.Business__c = 'Producer';
        unit.Animals__c = 'Chickens';
        unit.Production__c = 'Producer';
        unit.Status__c = 'Certified';
        insert unit;

        // Check records created
        List<Unit__c> units = [SELECT Id FROM Unit__C];
        System.assertEquals(1, accounts.size());
        System.assertEquals(1, units.size());

        // Call method to get poultry units
        AdditionalApplicationController.getPoultryUnits(accounts[0].Id);

        // call method to get poultry units with site id = null
        AdditionalApplicationController.getPoultryUnits(null);

    }

    @isTest
    static void getNewUnitNumberTest() {
        // Create account
        FObject accObj = DataFactory.getDefSiteAccounts();
        accObj.insertRecords(true);
        List<Account> accounts = FObject.getInsertedRecords('Account');

        // Create Units
        Unit__c unit = new Unit__c();
        unit.Account__c = accounts[0].Id;
        unit.Name = '01';
        unit.Business__c = 'Producer';
        unit.Animals__c = 'Chickens';
        unit.Production__c = 'Producer';
        unit.Status__c = 'Certified';
        insert unit;

        // Check records created
        List<Unit__c> units = [SELECT Id FROM Unit__C];
        System.assertEquals(1, accounts.size());
        System.assertEquals(1, units.size());

        // Call method to get new unit number
        AdditionalApplicationController.getNewUnitNumber(accounts[0].Id);


    }
}