unpackaged/main/default/objects/Contact/fields/ConvertedLeadID__c.field-meta.xml
<CustomField>
    <fullName>ConvertedLeadID__c</fullName>
    <label>ConvertedLeadID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Enquiry_Standard__c/Enquiry_Standard__c.object-meta.xml
<CustomObject>
    <label>Enquiry Standard</label>
    <nameField>
        <displayFormat>ESID-{00}</displayFormat>
        <label>Enquiry Standards ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enquiry Standards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Enquiry_Standard__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Standards</relationshipLabel>
    <relationshipName>Enquiry_Standards</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Enquiry_Standard__c/fields/Standard__c.field-meta.xml
<CustomField>
    <fullName>Standard__c</fullName>
    <label>Standard</label>
    <referenceTo>Standard__c</referenceTo>
    <relationshipLabel>Enquiry Standards</relationshipLabel>
    <relationshipName>Enquiry_Standards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/LogEnquiryConfirmation__c.field-meta.xml
<CustomField>
    <fullName>LogEnquiryConfirmation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LogEnquiryConfirmation</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Standard__c/Standard__c.object-meta.xml
<CustomObject>
    <label>Standard</label>
    <nameField>
        <label>Standards Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Standard__c/fields/Standard_Link__c.field-meta.xml
<CustomField>
    <fullName>Standard_Link__c</fullName>
    <label>Standard Link</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/classes/ContactTriggerTest.cls
@isTest
public class ContactTriggerTest {
    @isTest
    public static void leadConvertTest() {
        Lead l = new Lead();
        l.FirstName = 'first';
        l.LastName = 'last';
        l.Email = 'test@test.com';
        l.Company = 'TEST';

        insert l;

        l.LogEnquiryConfirmation__c = true;

        update l;

        Standard__c s = new Standard__c(Name = 'Test', Standard_Link__c = 'test.com');
        insert s;

        Enquiry_Standard__c es = new Enquiry_Standard__c(Standard__c = s.Id, Lead__c = l.Id);
        insert es;

        Contact c = new Contact();
        c.FirstName = 'first';
        c.LastName = 'last';
        c.Email = 'test@test.com';
        c.ConvertedLeadID__c = l.Id;

        insert c;
    }
}