unpackaged/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Unit__c/fields/Animals__c.field-meta.xml
<CustomField>
    <fullName>Animals__c</fullName>
    <label>Animals</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Animals</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Animals_List__c.field-meta.xml
<CustomField>
    <fullName>Animals_List__c</fullName>
    <label>List of Animals</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Animals</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Unit__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <label>Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Animals.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Beef Cattle</fullName>
    </customValue>
    <customValue>
        <fullName>Chickens</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy Cattle</fullName>
    </customValue>
    <customValue>
        <fullName>Ducklings</fullName>
    </customValue>
    <customValue>
        <fullName>Ducks</fullName>
    </customValue>
    <customValue>
        <fullName>Laying Hen Chicks</fullName>
    </customValue>
    <customValue>
        <fullName>Laying Hens</fullName>
    </customValue>
    <customValue>
        <fullName>Lumpfish</fullName>
    </customValue>
    <customValue>
        <fullName>Meat Chicken Chicks</fullName>
    </customValue>
    <customValue>
        <fullName>Pigs</fullName>
    </customValue>
    <customValue>
        <fullName>Pullets</fullName>
    </customValue>
    <customValue>
        <fullName>Salmon</fullName>
    </customValue>
    <customValue>
        <fullName>Sheep</fullName>
    </customValue>
    <customValue>
        <fullName>Trout</fullName>
    </customValue>
    <customValue>
        <fullName>Turkey Poults</fullName>
    </customValue>
    <customValue>
        <fullName>Turkeys</fullName>
    </customValue>
    <customValue>
        <fullName>Veal Calves</fullName>
    </customValue>
    <customValue>
        <fullName>Wrasse</fullName>
    </customValue>
    <customValue>
        <fullName>List</fullName>
    </customValue>
    <masterLabel>Animals</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Business.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abattoir</fullName>
    </customValue>
    <customValue>
        <fullName>Catching</fullName>
    </customValue>
    <customValue>
        <fullName>Cleaner Fish</fullName>
    </customValue>
    <customValue>
        <fullName>Hatchery</fullName>
    </customValue>
    <customValue>
        <fullName>Haulier</fullName>
    </customValue>
    <customValue>
        <fullName>Producer</fullName>
    </customValue>
    <customValue>
        <fullName>Supply Chain</fullName>
    </customValue>
    <masterLabel>Business</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

unpackaged/main/default/classes/BatchToUpdateMultipleAnimals.cls
public with sharing class BatchToUpdateMultipleAnimals implements Database.Batchable<sObject>{
    public Database.QueryLocator start(Database.BatchableContext BC){
        List<String> businessList = new List<String>{
            'Hatchery','Abattoir','Haulier','Catching'
        };
        String query = 'SELECT ID,Animals__c,Animals_List__c,Business__c,Description__c FROM Unit__c where Business__c IN :businessList';
        return Database.getQueryLocator(query);
     }
  
    public void execute(Database.BatchableContext BC, List<Unit__c> scope){
        Map<String,String> animalsMap = new Map<String,String>{
            'Beef'=>'Beef Cattle','Cattle'=>'Beef Cattle','Calves'=>'Veal Calves','Chickens'=>'Chickens','Chicks'=>'Meat Chicken Chicks',
            'Pigs'=>'Pigs','Poults'=>'Turkey Poults','Sheep'=>'Sheep','Spent Hens'=>'Laying Hens','Turkeys'=>'Turkeys'
        };
       for(Unit__c unit : scope){
           system.debug('unit.Animals_List__c'+unit.Animals_List__c);
           if(unit.Animals_List__c != null && unit.Animals_List__c.contains('List')){
               unit.Animals_List__c = unit.Animals_List__c.replace('List','');
           }
           if((unit.Business__c == 'Catching' || unit.Business__c == 'Hatchery') || unit.Description__c == null){
               if(unit.Animals__c != 'List'){
                   if(unit.Animals_List__c == NULL){
                       unit.Animals_List__c = unit.Animals__c;
                   }else if(!unit.Animals_List__c.contains(unit.Animals__c)){
                       unit.Animals_List__c = unit.Animals_List__c +';'+unit.Animals__c;
                   }  
               }
                
               unit.Animals__c = 'List';
           }else if(unit.Description__c != null){               
               String description = unit.Description__c;
               system.debug('description:::'+description);
               //String animals = description.substringBetween('(',')');
               Integer firstIndex = description.indexOf('(');
               Integer lastIndex = description.lastIndexOf(')');
               system.debug('first index'+firstIndex);
               system.debug('last index'+lastIndex);
               if(description.contains('(') && description.contains(')')){
                   String animals = description.substring(firstIndex-1,lastIndex);
                   animals = animals.replace(')',',');
                   animals = animals.replace('(','');
                   system.debug('animals:::'+animals);
                   if(String.isNotBlank(animals)){
                       List<String> animalsList = animals.split(',');
                       List<String> newAnimalsList = new List<String>();
                       system.debug('animalsList:::'+animalsList);
                       for(String animal:animalsList){
                           animal = animal.trim();
                           if(animalsMap.containsKey(animal) && newAnimalsList.indexOf(animal) == -1){
                               newAnimalsList.add(animalsMap.get(animal));
                           }/*else if(animal != 'Cattle'){
                            newAnimalsList.add(animal);
                            }*/
                       }
                       system.debug('newAnimalsList:::'+newAnimalsList);
                       unit.Animals_List__c = String.join(newAnimalsList,';');
                       if(!unit.Animals_List__c.contains(unit.Animals__c) && unit.Animals__c != 'List'){
                           unit.Animals_List__c += ';'+unit.Animals__c;
                       }  
                       unit.Animals__c ='List';
                       unit.Description__c = description.substringBefore('(');    
                   }
                   
               }else if(unit.Animals__c != null && unit.Animals__c != 'List'){
                   if(unit.Animals_List__c == NULL){
                       unit.Animals_List__c = unit.Animals__c;
                   }else if(!unit.Animals_List__c.contains(unit.Animals__c)){
                       unit.Animals_List__c = unit.Animals_List__c +';'+unit.Animals__c;
                   }   
                   unit.Animals__c = 'List';
               }
           }
       }
       system.debug('scope::::'+scope);
       update scope;
    }
  
    public void finish(Database.BatchableContext BC){
        
    }
}